export const arq1 = "Aries es el primer Signo del zodíaco. Es el que acaba de llegar y no sabe cómo funciona el mundo. Se mueve por impulsos cortos y muy enérgicos. Busca la novedad, pero se cansa muy rápido de ella. Es independiente y no escucha los consejos de otros. Puede enfadarse muy rápido y tener impulsos emocionales intensos, pero que se apagan enseguida. Necesita estar activo continuamente y es muy competitivo.";

export const arq2 = "Tauro es el labrador. Es el que da forma y disfruta de la energía convertida en materia. Está muy conectado con los sentidos y cree necesitar seguridad material, como dinero u objetos. Le gusta la comodidad, pero no necesariamente el lujo. Necesita desapegarse y no ser celoso. Está conectado con los ciclos de la naturaleza, lo que puede hacer que sea confiado y se vuelva un poco perezoso. Necesita entender que es mucho más de lo que tiene y que su valía personal no se mide en dinero.";

export const arq3 = "Géminis es un Signo dual, pero no porque tenga una parte malvada, sino porque su propósito es ser consciente de que todo es uno. Es muy mental y rápido, tal vez demasiado, perdiéndose detalles y no profundizando. Su alta frecuencia es cuando es capaz de bajar del ruido mental y entrar en su cuerpo, conectándose con su emocional y con la empatía hacia los demás. A pesar de sus grandes, distintos y diversos intereses, tiene que aprender a profundizar.";

export const arq4 = "El arquetipo de Cáncer nos habla de una fuerte conexión con el hogar y con la familia. En baja frecuencia es manipulador y dramático, además de ser capaz de absorber las emociones de otros y confundirlas con las suyas propias. En su alta frecuencia ha encontrado cómo nutrirse a él mismo y solo así es capaz de ayudar a otros. Puede ser tan sensible que se crea una coraza para protegerse.";

export const arq5 = "El arquetipo de Leo nos habla de una necesidad de ser admirado y reconocido por lo que es. Puede hacer daño solo para demostrar su supremacía, pero es el Rey, es el corazón y quiere ser reconocido como tal. Eso es romántico y brillante. Para llegar a su alta frecuencia debe reconocerse y valorarse a sí mismo. Debe de no necesitar esto de fuera, porque si lo recibe de fuera, corre el riesgo de nunca estar satisfecho, porque en verdad la validación propia es la única que vale.";

export const arq6 = "El arquetipo de Virgo nos habla de un gran juzgador, crítico y analítico, sobre todo con él mismo. Busca servir a otro y clasificar todo en su mente para hacer el uso más útil. Es un gran científico. No quiere ver su caos ni enfrentarse a qué es lo que le hace daño. Somatiza todo lo que niega. Es extremadamente ordenado o desordenado. Le da miedo la muerte, envejecer, y confía en remedios naturales y holísticos.";

export const arq7 = "El arquetipo de Libra busca la armonía, el equilibrio, la belleza, la amabilidad y la diplomacia. Es dependiente de otros porque les necesita para descubrirse a sí mismo. No es muy trabajador porque está centrado en la belleza estética. Es elegante y buen compañero, pero puede no darle importancia al amor, centrándose en ser aceptado socialmente. Es muy influenciable por otros. No tolera las agresiones ni las malas formas.";

export const arq8 = "Escorpio es el que rompe la estructura que Leo había creado para estar seguro y lo transforma para renacer. Es muy profundo y busca el lado escondido u oscuro de todo lo que encuentra. Es magnético y poderoso, con una fuerte atracción sexual. Es capaz de ver el lado oscuro de otros, pero tiene que aprender a no usarlos a su favor.";

export const arq9 = "Sagitario es el buscador de la Verdad. El filósofo, el que busca propósito y necesita independencia. Es el maestro y comunica con pasión aquello que le gusta. Puede huir al futuro engañándose con un falso optimismo. Necesita aventuras, viajes y experiencias. Es directo, honesto, abierto y tal vez impulsivo, pudiendo dañar con sus palabras.";

export const arq10 = "Capricornio es el arquetipo de la autoridad, la responsabilidad y el estatus social. Siempre tiene un plan diseñado meticulosamente para que sea lo más práctico y eficiente posible. Desea que lo que construye perdure a futuras generaciones y repercuta en ellas positivamente. Sigue las normas y prioriza el deber antes que sus deseos. Es serio. Puede ser pesimista y ver la vida gris. Quiere acabar con la estupidez en la sociedad. Es el arquetipo de matar al padre para convertirse en su propio padre.";

export const arq11 = "Acuario ama a la humanidad, pero odia a los humanos. Su propósito es encontrar su esencia dentro de un grupo y del universo. Tiene que recordar que es único, pero a la vez parte de todo. Es el rebelde futurista, muy mental y desconectado de las emociones para no crear vinculaciones. Puede sentirse muy incomprendido. Rige las electricidades, la ciencia ficción, las asociaciones y los amigos.";

export const arq12 = "Piscis tiene un gran y dulce corazón, que hace que otros se aprovechen. Se siente responsable del sufrimiento del mundo. Es muy influenciado por otros porque puede absorber energías que no son suyas. Puede estar tan triste que se hunda en la depresión. Es capaz de traer a lo tangible lo intangible, y lo suele hacer a través del arte. Rige los sueños, las adicciones, los sacrificios y lo abstracto.";
