export const astrologia1 = "La astrología surgió hace unos 4.000 años en Mesopotamia, donde se usaba para entender los arquetipos que formaban a una persona. \n\n En la Edad Media y en el Renacimiento era parte del conocimiento aceptado, y muchos reyes cristianos tenían astrólogo en su corte, incluido el rey católico de España y sus descendientes. \n\n A partir del siglo 17, con la revolución científica, con Galileo y Descartes, esta herramienta perdió credibilidad, pasando a ser pseudociencia. Pero la astrología era y sigue siendo una herramienta de autoconocimiento, una herramienta que permite entender los arquetipos que su alma ha elegido para vivir esta experiencia llamada Vida.";

export const astrologia2 = "El Ascendente es la energía del camino que tiene que recorrer para manifestar su sol. Debe aprender a colocarlo en sí para poder usarlo a su favor. El sol es la energía que su alma se ha comprometido a manifestar en su más alta frecuencia. Es donde brilla cuando se deja ser, aunque este brillo suele estar retenido tras una muralla de miedo. La luna es de dónde parte. Es lo que su madre le dio en los primeros años de vida, por lo que es a lo que está acostumbrado e inconscientemente busca.";

export const asc1 = "Un ascendente Aries es fuerte y sin pedir ayuda, sigue un camino lleno de objetivos que rara vez son alcanzados debido a que se aburre muy rápido. Igualmente, si alguien se interpone, se frustra mucho y muy rápido.";

export const asc2 = "Un ascendente Tauro es lento pero constante, es labrador de proyectos. Necesita estructura y es muy práctico. No es violento, pero puede apegarse o ser demasiado celoso. Suele tener un cuerpo grande que se siente pesado.";

export const asc3 = "Un ascendente Géminis es indeciso, nervioso, y necesita aprender debido a su insaciable curiosidad. Tiene un don natural para la comunicación y vive demasiado en su cabeza. Debe aprender a profundizar, a silenciar su ruido mental y a no tener demasiados proyectos en marcha, dado que suele abrumarse y al final no hace nada.";

export const asc4 = "Un ascendente Cáncer es sensible y percibe lo que otros sienten, normalmente confundiéndolo con lo que él mismo siente. Es muy vulnerable y para evitar ser abrumado crea una coraza en la que refugiarse. Necesita aprender a perdonar el pasado.";

export const asc5 = "Un ascendente Leo posee confianza en sí mismo, aunque esto puede manifestarse como demasiado ego. Es encantador, creativo y romántico. Necesita ser querido y admirado, pero debe aprender a darse esto a sí mismo, en vez de buscarlo fuera.";

export const asc6 = "Un ascendente Virgo suele sentirse inadecuado y crea una Vidade austeridad, es decir, se apaña con lo mínimo. Guarda resentimiento de sus experiencias pasadas, por eso debe aprender a soltar y a distinguir lo que es bueno o lo que no. Suele ser muy crítico, autoexigente y juzga a los demás proporcionalmente a cómo se juzga a sí mismo. Es buen analizador y busca poner al servicio lo que sabe.";

export const asc7 = "Un ascendente Libra es dulce y diplomático. Necesita una pareja para descubrirse a sí mismo. Por ello, suele ser dependiente y releva en los demás sus decisiones. Debe aprender a ser autosuficiente y a tomar decisiones haciéndose responsable de las consecuencias.";

export const asc8 = "Un ascendente Escorpio es misterioso, enigmático y magnético. Suele ser silencioso y parecer calmado, pero está continuamente observando. Puede ser resentido, pero cuando madura se convierte en gran transformador de infiernos y es capaz de beneficiarse de ellos.";

export const asc9 = "Un ascendente Sagitario es generoso y filosófico. Puede estar en busca de la verdad de la Vida o haberse cerrado a ella por completo y vivir con miedo, sin creerse que la Vidapuede ser bonita. Igualmente, es comunicador apasionado.";

export const asc10 = "Un ascendente Capricornio es metódico y está orientado hacia el futuro. Es disciplinado con tendencia a procrastinar, pero se siente responsable cuando hace lo que se ha prometido hacer.";

export const asc11 = "Un ascendente Acuario debe encontrar su individualidad aún formando parte de un grupo más grande. Suele ser muy futurista, con creencias fuertes respecto a la igualdad.";

export const asc12 = "Un ascendente Piscis es hipersensible y tiene una gran compasión debido a un corazón amable. Debe aprender a no sacrificarse por otros. Suele ser romántico, pero puede dejarse llevar por la confusión de sus emociones.";

export const sol1 = "Una persona que tiene el Sol en Aries cuando está en sombra es violenta, combativa, siente que no tiene capacidad para cambiar lo que desea. Puede ser impulsiva y se aburre muy rápido de la novedad. Cuando está en luz, esta persona tiene confianza en sí misma, independencia, ambición y valentía. Su naturaleza es ser líder, necesita libertad, iniciativa y movimiento, tanto físico como en sus rutinas. Es capaz de dejar atrás los prejuicios sociales y va a por lo que quiere teniendo en cuenta las consecuencias de sus actos.";

export const sol2 = "Una persona que tiene el Sol en Tauro, cuando está en sombra, piensa que vale lo que tiene. Es muy posesiva, cabezota y está atrapada en patrones tóxicos. Puede comer demasiado como un intento de disfrutar de un cuerpo que no siente como suyo. Pero cuando está en luz, es paciente, tranquila, laboriosa, leal y práctica. Está enraizada en su cuerpo y es capaz de disfrutarlo más allá de la comida. Es capaz de valorarse independientemente de sus posesiones y más allá del dinero que atesora.";

export const sol3 = "Una persona que tiene el Sol en Géminis cuando está en sombra puede ser superficial, irresponsable, nerviosa y puede empezar mucho sin comprometerse a acabarlo o a interiorizarlo. Acumula información sin integrarla, tiene un ruido mental excesivo y compulsivo, a la vez que una gran desconexión con su corazón. Pero todo cambia cuando está en luz, porque entonces es capaz de profundizar e integrar. Va rápido pero sin estrés, reconoce su inteligencia y valora su curiosidad, a pesar de saber que por mucho que aprenda nunca podrá entenderlo todo, porque no está hecha para entender el orden universal sino para alinearse y desde su corazón disfrutarlo.";

export const sol4 = "Una persona con el Sol en Cáncer, cuando está en sombra, siente un apego tóxico a su familia que le impide crecer. Se siente sola porque nadie le entiende. Es fácilmente herida debido a su sensibilidad y puede confundir las emociones de otros con las suyas y hacerse más daño. Cuando está en luz, es capaz de diferenciar lo que es suyo y de lo que no, sin dramatizar ni sufrir, ni culparse. Es gran nutridora, capaz de apoyar a otros sin manipularles, a la vez que se hace cargo de sí misma y de sus necesidades, las cuales no fueron legitimadas.";

export const sol5 = "Una persona con Sol en Leo, cuando está en sombra, se siente mediocre y va mendigando atención. Es orgullosa, cruel y egocéntrica, con miedo a hacer el ridículo. Pero cuando está en luz, es brillante, es capaz de darse el reconocimiento a sí misma sin buscarlo externamente. Es noble, creativa, digna y siempre está dispuesta a dar apoyo. Está conectada a su amor y a su corazón, por lo que es gran creadora.";

export const sol6 = "Una persona con Sol en Virgo, cuando está en sombra, niega y no quiere ver su caos interno. Necesita controlarlo todo, porque le da miedo darse cuenta de que la Vidaes impredecible. Juzga muy duramente, en especial a sí misma, y trata de servir a otros para sentirse útil. Trata de clasificar todas sus experiencias. Cuando está en luz, es porque ha comprendido sin sufrimiento que el universo y la Vidatienen un orden más allá del que puede entender. Su propósito final es poner sus dones analíticos y científicos al servicio de algo más grande que ella.";

export const sol7 = "Una persona con Sol en Libra, cuando está en sombra, es muy insegura y dependiente de la aprobación de otros. Suele necesitar un empujón externo para poner en marcha sus ideas. Intenta tener información de todos para mantener la armonía. Cuando está en luz, encuentra su individualidad y suficiencia sin necesidad de apoyo externo. Es diplomática y social, capaz de mantener su armonía interna a pesar de que el ambiente o la situación no lo sea.";

export const sol8 = "Una persona con Sol en Escorpio, cuando está en sombra, se siente abandonada, traicionada y humillada. Puede querer tener control y poder porque piensa que así no volverá a ser dañada ni humillada. Pero cuando está en luz, es capaz de transformar los peores infiernos en oportunidades para crecer. Es consciente y está interesada en temas no convencionales, como la muerte. Tiene una gran determinación y fuerza de voluntad.";

export const sol9 = "Una persona con Sol en Sagitario, cuando está en sombra, puede aferrarse a lo que considera una verdad y desde ahí crear su realidad aunque le haga infeliz. Esto es una forma de protegerse de lo incomprensible que es la vida. Puede hablar demasiado, ser impulsiva y perderse el presente por estar demasiado en el futuro o por tener un optimismo tóxico de que todo, de alguna forma, se arreglará. Cuando está en luz, es entusiasta, extrovertida, con curiosidad y siempre en movimiento, en busca de la verdad y de una filosofía universal. Se siente grande y completa, consciente de la grandeza de su pequeñez.";

export const sol10 = "Una persona con Sol en Capricornio, cuando está en sombra, construye barreras para proteger su vulnerabilidad e inseguridad, quiere el control para asegurarse de que estas barreras son respetadas. Puede ser negativa y ver la Vidade color gris. Deja de estar en sombra cuando reconoce su valía y se convierte en su propio padre/madre. Cuando está en luz, es muy responsable y haga lo que haga, quiere que repercuta positivamente en futuras generaciones. Es digna, estable, seria y respeta las normas.";

export const sol11 = "Una persona con Sol en Acuario, cuando está en sombra, es muy mental y puede ver las emociones como algo peligroso, ya que no quiere dependencias. Odia a los humanos por amar a la humanidad. Cuando está en luz, es capaz de reconocer su valía y su individualidad dentro de un grupo; este grupo puede ser una empresa, sus amistades o el universo en sí. Para ella es más fácil conectar con varias personas que establecer un vínculo con solo una.";

export const sol12 = "Una persona con Sol en Piscis, cuando está en sombra, puede tratar de escapar a la mente y al análisis debido a que se siente abrumada y confusa por su gran sensibilidad y percepción. Se siente como una esponja de las energías de otros. Puede hablar mucho y, al ser tan compasiva, otros pueden aprovecharse de ella. Es fácilmente incomprendida, porque a veces ni ella se entiende a sí misma. Cuando está en luz, es trascendental, amable, dulce y artista. En muy alta frecuencia es capaz de conectarse con el infinito sin interferencias egoicas.";