export const arq1 = "Es el primer signo del zodiaco, es el que acaba de llegar y no sabe cómo funciona el mundo. Se mueve por impulsos cortos y muy enérgicos, busca la novedad pero se cansa muy rápido de ella. Suelen ser independientes y no escuchan los consejos de otros. Pueden enfadarse muy rápido y tener impulsos emocionales intensos pero que se apagan enseguida. Necesita estar activo continuamente y es muy competitivo.";

export const arq2 = "Es el labrador, el que da forma y disfruta de la energía convertida en materia. Está muy conectado a los sentidos y necesita seguridad material, como dinero u objetos. Les gusta la comodidad, no necesariamente el lujo. Necesita desapegarse y no ser celoso. Está conectado con los ciclos de la naturaleza, lo que puede hacer que sea confiado porque entiende que cada cosa tiene su tiempo y se vuelva un poco perezoso. Necesita entender que no es lo que tiene.";

export const arq3 = "Es un signo dual porque su propósito es ser consciente de que todo es uno. Son muy mentales y rápidos, tal vez demasiado, perdiéndose detalles y no profundizando. Su alta frecuencia es cuando es capaz de bajar del ruido mental y entrar en su cuerpo, conectándose con su emocional y con la empatía hacia los demás. A pesar de sus grandes, diversos y distintos intereses, tiene que aprender a profundizar.";

export const arq4 = "El arquetipo de Cáncer nos habla de una fuerte conexión al hogar y a la familia. En baja frecuencia es manipulador y dramático, además de ser capaz de absorber las energías de otros y confundirlas con las suyas propias. En su alta frecuencia, ha encontrado cómo nutrirse a él mismo y es capaz de nutrir a otros y ayudarles a encontrar su individualidad. Tiene necesidad de pertenecer a algo mayor. Es tan sensible que se protege detrás de una coraza. Por ello, tiene que ser consciente de su vulnerabilidad y aprender del dolor.";

export const arq5 = "El arquetipo de Leo nos habla de una necesidad de ser admirado y reconocido por lo que es. Puede hacer daño solo para demostrar su supremacía. Es el Rey, es el corazón y quiere ser reconocido como tal. Es romántico, brillante. Para llegar a su alta frecuencia, debe reconocerse y valorarse a sí mismo, debe de no necesitar esto de fuera. Porque si lo recibe de fuera, corre el riesgo de nunca estar satisfecho por no encontrarlo suficiente.";

export const arq6 = "El arquetipo de Virgo nos habla de un gran juzgador, crítico y analítico, sobretodo con él mismo. Busca servir a otro y clasificar todo en su mente para hacer el uso más útil de ello. Es un buen científico. No quiere ver su caos ni enfrentarse a qué es lo que le hace daño o a sus traumas pasados y congelados, por lo que estos son expresados en forma de somatización. Extremadamente ordenados o desordenados. Le da miedo la muerte, envejecer y confía en remedios naturales y tratos holísticos.";

export const arq7 = "El arquetipo de Libra busca la armonía, el equilibrio, la belleza, la amabilidad y la diplomacia. Es dependiente de otros porque les necesita como espejo para descubrirse a sí mismo. No es muy trabajador, porque está más centrado en la belleza estética y en el orden bonito. Es elegante y buen compañero, pero puede no darle importancia al amor, centrándose más en el matrimonio, en la complacencia y en ser aceptado socialmente. Es muy influenciable por otros y no tolera las agresiones ni las malas formas.";

export const arq8 = "Es el que rompe la estructura que el ego había creado para estar seguro y lo transforma para renacer. Es muy profundo y busca el lado oscuro o escondido de todo lo que se encuentra. La unión es el éxtasis y la separación la agonía, por eso deben de entender que uno no existe sin el otro. Magnético y poderoso, es capaz de ver el lado oscuro de otros y usarlos a su favor.";

export const arq9 = "El buscador de la verdad, el filósofo, el que busca su propósito y necesita independencia. Suele ser el maestro y comunica con pasión aquello que le gusta. Puede ser muy orientado al futuro causando un falso optimismo, necesitan aventuras, viajes y experiencias. Son directos, honestos, animados, abiertos y tal vez impulsivos, pudiendo dañar con sus palabras al ser tan directos.";

export const arq10 = "El arquetipo de la responsabilidad, de la autoridad y del estatus social. Siempre tiene un plan, diseñado meticulosamente para que sea lo más práctico y eficiente posible. Desea que lo que construya perdure a futuras generaciones y repercuta en ellas positivamente. Siguen las normas y priorizan el deber antes que sus deseos. Serio y puede ver la vida gris. Quiere acabar con la estupidez de la sociedad. Es el arquetipo de matar al padre para convertirse en su propio padre.";

export const arq11 = "El arquetipo de Acuario es el estar conectado profundamente con la humanidad, y a pesar de ello, odiar a los humanos. Su propósito es encontrar su individualidad dentro de un grupo y del universo, de recordar que tienen una esencia única pero que a la vez es parte de todo. Es el arquetipo del rebelde futurista, muy mental y desconectado de sus emociones para no crear vinculaciones. Por ello puede sentirse muy incomprendido. Rige las electricidades, la ciencia ficción, las asociaciones y los amigos.";

export const arq12 = "El arquetipo del abandono del mundo material para la unión con Dios, del sacrificio de uno mismo por algo mayor. Se siente responsable del sufrimiento del mundo. Tiene un gran y dulce corazón, que hace que otros se aprovechen. Es influenciado por otros y puede absorber emociones que no son suyas. Puede sentir mucha autocompasión y hundirse en la depresión. Rige el arte, los sueños, las adicciones y lo abstracto.";
