import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { astrologiaBg, astrologiaTxt, AstrologiaIcon, AscendenteIcon, SunIcon, astrologiaNom, MoonIcon, RecursosIconAstrologia, PlanetIcon } from "../../../GlobalVariables";
import {
  asc1, asc2, asc3, asc4, asc5, asc6, asc7, asc8, asc9, asc10, asc11, asc12,
  astrologia1, astrologia2,
  sol1, sol2, sol3, sol4, sol5, sol6, sol7, sol8, sol9, sol10, sol11, sol12,
  luna1, luna2, luna3, luna4, luna5, luna6, luna7, luna8, luna9, luna10, luna11, luna12,
  astro1, astro2, astro3, astro4, astro5, astro6, astro7, astro8, astro9, astro10, astro11, astro12
} from "./LetraAstrologia";
import { arq1, arq2, arq3, arq4, arq5, arq6, arq7, arq8, arq9, arq10, arq11, arq12 } from "./LetraArquetipos";

const detalles: Detalles = { color: astrologiaTxt, icon: AstrologiaIcon, bgColor: astrologiaBg };

const basePath = "/aprendizaje/videoLessonPage/" + astrologiaNom;

const serviciosAstrologicos: FloatingButtonConfig = {
  label: "Servicios Astrológicos",
  action: "astrologia-services",
};

export const modulosAstrologia: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: RecursosIconAstrologia,
    floatingButton: serviciosAstrologicos,
    submodules: [
      {
        id: "astro0",
        nom: "Recursos a tu disposición",
        link: `/recursos/${astrologiaNom}`,
        linkAnterior: "",
        linkNext: "",
        descripcion: "Recursos esenciales para acompañar tu aprendizaje y profundizar en Astrología.",
        video: "",
        letra: null,
        cursoId: "astro-curso-1",
        detalles: detalles,
        icon: null,
        floatingButton: serviciosAstrologicos,
      },
    ],
  },
  {
    title: "1. Introducción",
    icon: AstrologiaIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      {
        id: "astro1",
        nom: "1.1 La historia de la Astrología",
        link: `${basePath}/astro1`,
        linkAnterior: "",
        linkNext: `${basePath}/astro2`,
        descripcion: "La Astrología nos revela los arquetipos que nuestra Alma ha elegido.",
        video: "J2tQEea8vpM",
        letra: astrologia1,
        cursoId: "astro-curso-1",
        detalles: detalles,
        icon: AstrologiaIcon,
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "astro2",
        nom: "1.2 El Sol, el Ascendente y la Luna",
        link: `${basePath}/astro2`,
        linkAnterior: `${basePath}/astro1`,
        linkNext: `${basePath}/asc1`,
        descripcion: "El Ascendente es el camino, el Sol nuestra esencia y Luna las raíces tempranas.",
        video: "aBav2XmgGpE",
        letra: astrologia2,
        cursoId: "astro-curso-1",
        detalles: detalles,
        icon: AstrologiaIcon,
        floatingButton: serviciosAstrologicos,
      },
    ],
  },
  {
    title: "2. El Ascendente",
    icon: AscendenteIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      { id: "asc1",  nom: "Ascendente ♈︎ Aries",       link: `${basePath}/asc1`,  linkAnterior: `${basePath}/astro2`, linkNext: `${basePath}/asc2`,  descripcion: "Un Ascendente Aries avanza con fuerza pero se frustra con facilidad.",                                            video: "_3WF7lxVAz4", letra: asc1,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc2",  nom: "Ascendente ♉︎ Tauro",       link: `${basePath}/asc2`,  linkAnterior: `${basePath}/asc1`,  linkNext: `${basePath}/asc3`,  descripcion: "Un Ascendente Tauro progresa lento y constante, aferrado a lo seguro.",                                           video: "AlWk6ZVFhA4", letra: asc2,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc3",  nom: "Ascendente ♊︎ Géminis",     link: `${basePath}/asc3`,  linkAnterior: `${basePath}/asc2`,  linkNext: `${basePath}/asc4`,  descripcion: "Un Ascendente Géminis es curioso y comunicativo, pero disperso y nervioso.",                                      video: "zD_oRgpl9_A", letra: asc3,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc4",  nom: "Ascendente ♋︎ Cáncer",      link: `${basePath}/asc4`,  linkAnterior: `${basePath}/asc3`,  linkNext: `${basePath}/asc5`,  descripcion: "Un Ascendente Cáncer es sensible y protector, debe de aprender a perdonar el pasado.",                            video: "w7ESpg_dwx4", letra: asc4,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc5",  nom: "Ascendente ♌︎ Leo",         link: `${basePath}/asc5`,  linkAnterior: `${basePath}/asc4`,  linkNext: `${basePath}/asc6`,  descripcion: "Un Ascendente Leo es creativo y seguro, y debe aprender a reconocerse y a validarse.",                             video: "NRDrA91MqHE", letra: asc5,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc6",  nom: "Ascendente ♍︎ Virgo",       link: `${basePath}/asc6`,  linkAnterior: `${basePath}/asc5`,  linkNext: `${basePath}/asc7`,  descripcion: "Un Ascendente Virgo es crítico y analítico, debe de aprender a soltar y poner sus dones al servicio.",             video: "8XGSOZE3vaA", letra: asc6,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc7",  nom: "Ascendente ♎︎ Libra",       link: `${basePath}/asc7`,  linkAnterior: `${basePath}/asc6`,  linkNext: `${basePath}/asc8`,  descripcion: "Un Ascendente Libra es dulce y dependiente, y debe aprender a decidir y sostenerse a él mismo.",                   video: "WnzBfpvXqgA", letra: asc7,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc8",  nom: "Ascendente ♏︎ Escorpio",    link: `${basePath}/asc8`,  linkAnterior: `${basePath}/asc7`,  linkNext: `${basePath}/asc9`,  descripcion: "Un Ascendente Escorpio es misterioso y observador, transformando resentimientos en fortaleza.",                    video: "7Ng-go2w-S0", letra: asc8,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc9",  nom: "Ascendente ♐︎ Sagitario",   link: `${basePath}/asc9`,  linkAnterior: `${basePath}/asc8`,  linkNext: `${basePath}/asc10`, descripcion: "Un Ascendente Sagitario es generoso y filosófico, busca la verdad universal.",                                    video: "a5zmxZbPk6A", letra: asc9,  detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc10", nom: "Ascendente ♑︎ Capricornio", link: `${basePath}/asc10`, linkAnterior: `${basePath}/asc9`,  linkNext: `${basePath}/asc11`, descripcion: "Un Ascendente Capricornio es disciplinado y responsable, orientado a sus metas y al futuro.",                      video: "vThhLbA_VL8", letra: asc10, detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc11", nom: "Ascendente ♒︎ Acuario",     link: `${basePath}/asc11`, linkAnterior: `${basePath}/asc10`, linkNext: `${basePath}/asc12`, descripcion: "Un Ascendente Acuario busca su individualidad mientras conecta con un grupo.",                                    video: "pgH9o-lP5Y0", letra: asc11, detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "asc12", nom: "Ascendente ♓︎ Piscis",      link: `${basePath}/asc12`, linkAnterior: `${basePath}/asc11`, linkNext: `${basePath}/sol1`,  descripcion: "Un Ascendente Piscis es compasivo y sensible, debe de aprender a cuidarse sin sacrificarse.",                      video: "hJZflzNjxYo", letra: asc12, detalles: detalles, icon: AscendenteIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
    ],
  },
  {
    title: "3. El Sol",
    icon: SunIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      { id: "sol1",  nom: "Sol en ♈︎ Aries",       link: `${basePath}/sol1`,  linkAnterior: `${basePath}/asc12`, linkNext: `${basePath}/sol2`,  descripcion: "Un Sol en Aries es valiente e independiente, guiado por su iniciativa y la libertad.",                              video: "zbyC_x43Qx0", letra: sol1,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol2",  nom: "Sol en ♉︎ Tauro",       link: `${basePath}/sol2`,  linkAnterior: `${basePath}/sol1`,  linkNext: `${basePath}/sol3`,  descripcion: "Un Sol en Tauro es paciente y leal, debe de valorar la Vida más allá de las posesiones.",                            video: "Zd0gtDOfFBU", letra: sol2,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol3",  nom: "Sol en ♊︎ Géminis",     link: `${basePath}/sol3`,  linkAnterior: `${basePath}/sol2`,  linkNext: `${basePath}/sol4`,  descripcion: "Un Sol en Géminis es curioso e inteligente, debe de integrar el conocimiento con el corazón.",                        video: "P-y8MOFR2wI", letra: sol3,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol4",  nom: "Sol en ♋︎ Cáncer",      link: `${basePath}/sol4`,  linkAnterior: `${basePath}/sol3`,  linkNext: `${basePath}/sol5`,  descripcion: "Un Sol en Cáncer es nutridor y sensible, debe diferenciar lo propio de lo ajeno.",                                   video: "",            letra: sol4,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol5",  nom: "Sol en ♌︎ Leo",         link: `${basePath}/sol5`,  linkAnterior: `${basePath}/sol4`,  linkNext: `${basePath}/sol6`,  descripcion: "Un Sol en Leo es creativo y brillante, debe de reconocerse y dar Amor sin depender de otros.",                       video: "",            letra: sol5,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol6",  nom: "Sol en ♍︎ Virgo",       link: `${basePath}/sol6`,  linkAnterior: `${basePath}/sol5`,  linkNext: `${basePath}/sol7`,  descripcion: "Un Sol en Virgo es analítico y servicial, debe de poner sus dones meticulosos al servicio de algo mayor.",           video: "2na3Wq4wGiY", letra: sol6,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol7",  nom: "Sol en ♎︎ Libra",       link: `${basePath}/sol7`,  linkAnterior: `${basePath}/sol6`,  linkNext: `${basePath}/sol8`,  descripcion: "Un Sol en Libra es diplomático y social, debe de encontrar la armonía en sí mismo.",                                video: "jjkhJwSbaxU", letra: sol7,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol8",  nom: "Sol en ♏︎ Escorpio",    link: `${basePath}/sol8`,  linkAnterior: `${basePath}/sol7`,  linkNext: `${basePath}/sol9`,  descripcion: "Un Sol en Escorpio es intenso y transformador, capaz de convertir su sufrimiento en crecimiento.",                  video: "Q_zzeWeWwKk", letra: sol8,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol9",  nom: "Sol en ♐︎ Sagitario",   link: `${basePath}/sol9`,  linkAnterior: `${basePath}/sol8`,  linkNext: `${basePath}/sol10`, descripcion: "Un Sol en Sagitario es entusiasta y buscador de verdad, expandiendo su conciencia con optimismo.",                  video: "M3gTOQr_UAY", letra: sol9,  detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol10", nom: "Sol en ♑︎ Capricornio", link: `${basePath}/sol10`, linkAnterior: `${basePath}/sol9`,  linkNext: `${basePath}/sol11`, descripcion: "Un Sol en Capricornio es responsable y estable, orientado al legado y a la disciplina.",                             video: "pT7crWfsF3I", letra: sol10, detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol11", nom: "Sol en ♒︎ Acuario",     link: `${basePath}/sol11`, linkAnterior: `${basePath}/sol10`, linkNext: `${basePath}/sol12`, descripcion: "Un Sol en Acuario es individualista y visionario, debe de integrar su valía dentro de un grupo.",                   video: "oMuiKav8CKM", letra: sol11, detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "sol12", nom: "Sol en ♓︎ Piscis",      link: `${basePath}/sol12`, linkAnterior: `${basePath}/sol11`, linkNext: `${basePath}/luna1`, descripcion: "Un Sol en Piscis es sensible y trascendental, debe de aprender a no sacrificarse y a no hacerse pequeño.",          video: "QiP6zlkeWLg", letra: sol12, detalles: detalles, icon: SunIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
    ],
  },
  {
    title: "4. La Luna",
    icon: MoonIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      { id: "luna1",  nom: "Luna en ♈︎ Aries",       link: `${basePath}/luna1`,  linkAnterior: `${basePath}/sol12`,  linkNext: `${basePath}/luna2`,  descripcion: "La Luna en Aries siente que debe defenderse sola, reaccionando con independencia e impulsividad emocional.",              video: "5u_eDK03nxw", letra: luna1,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna2",  nom: "Luna en ♉︎ Tauro",       link: `${basePath}/luna2`,  linkAnterior: `${basePath}/luna1`,  linkNext: `${basePath}/luna3`,  descripcion: "La Luna en Tauro busca seguridad emocional en lo material, desarrollando apego a la estabilidad y a los recursos.",     video: "yzj1MoluTiE", letra: luna2,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna3",  nom: "Luna en ♊︎ Géminis",     link: `${basePath}/luna3`,  linkAnterior: `${basePath}/luna2`,  linkNext: `${basePath}/luna4`,  descripcion: "La Luna en Géminis intelectualiza las emociones porque no aprendió a expresarlas afectivamente.",                          video: "-nKmbn68i0k", letra: luna3,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna4",  nom: "Luna en ♋︎ Cáncer",      link: `${basePath}/luna4`,  linkAnterior: `${basePath}/luna3`,  linkNext: `${basePath}/luna5`,  descripcion: "La Luna en Cáncer vive un fuerte apego materno que puede generar dependencia emocional y necesidad de refugio.",          video: "WunkXx2KAxM", letra: luna4,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna5",  nom: "Luna en ♌︎ Leo",         link: `${basePath}/luna5`,  linkAnterior: `${basePath}/luna4`,  linkNext: `${basePath}/luna6`,  descripcion: "La Luna en Leo necesita sentirse admirada para sentirse amada y aprender a desarrollar su propia autoestima.",            video: "rE8ufNQMzmg", letra: luna5,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna6",  nom: "Luna en ♍︎ Virgo",       link: `${basePath}/luna6`,  linkAnterior: `${basePath}/luna5`,  linkNext: `${basePath}/luna7`,  descripcion: "La Luna en Virgo cree que solo merece Amor si es útil, desarrollando perfeccionismo y autoexigencia.",                   video: "qjG1k3_94xg", letra: luna6,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna7",  nom: "Luna en ♎︎ Libra",       link: `${basePath}/luna7`,  linkAnterior: `${basePath}/luna6`,  linkNext: `${basePath}/luna8`,  descripcion: "La Luna en Libra busca armonía emocional en las relaciones, evitando el conflicto y priorizando la diplomacia.",         video: "tJa4nHwHYcI", letra: luna7,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna8",  nom: "Luna en ♏︎ Escorpio",    link: `${basePath}/luna8`,  linkAnterior: `${basePath}/luna7`,  linkNext: `${basePath}/luna9`,  descripcion: "La Luna en Escorpio vive emociones intensas y complejas, donde el Amor puede confundirse con control o pérdida.",        video: "oJ4w1IcZ6XM", letra: luna8,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna9",  nom: "Luna en ♐︎ Sagitario",   link: `${basePath}/luna9`,  linkAnterior: `${basePath}/luna8`,  linkNext: `${basePath}/luna10`, descripcion: "La Luna en Sagitario busca libertad emocional y sentido, pero puede evitar profundizar en sus sentimientos.",             video: "uno3h94XJ2o", letra: luna9,  detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna10", nom: "Luna en ♑︎ Capricornio", link: `${basePath}/luna10`, linkAnterior: `${basePath}/luna9`,  linkNext: `${basePath}/luna11`, descripcion: "La Luna en Capricornio aprende a reprimir sus emociones y a buscar valor a través del esfuerzo y la responsabilidad.",  video: "vSqpdFimvV0", letra: luna10, detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna11", nom: "Luna en ♒︎ Acuario",     link: `${basePath}/luna11`, linkAnterior: `${basePath}/luna10`, linkNext: `${basePath}/luna12`, descripcion: "La Luna en Acuario desarrolla distancia emocional y apego evitativo para proteger su libertad.",                         video: "N2t3zsuQXNw", letra: luna11, detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
      { id: "luna12", nom: "Luna en ♓︎ Piscis",      link: `${basePath}/luna12`, linkAnterior: `${basePath}/luna11`, linkNext: "",                  descripcion: "La Luna en Piscis es profundamente sensible y empática, pero necesita aprender a poner límites emocionales.",             video: "Tca57If-0NI", letra: luna12, detalles: detalles, icon: MoonIcon, cursoId: "astro-curso-1", floatingButton: serviciosAstrologicos },
    ],
  },
];

export const modulosArquetipos: ModuloContenido[] = [
  {
    title: "Los Arquetipos",
    icon: AstrologiaIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      { id: "arq1",  nom: "Arquetipo ♈︎ Aries",       link: `${basePath}/arq1`,  linkAnterior: "",               linkNext: `${basePath}/arq2`,  descripcion: "El primer arquetipo: impulso, independencia y la energía que acaba de llegar al mundo.",                          video: "3SRMdBSQBs8", letra: arq1,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq2",  nom: "Arquetipo ♉︎ Tauro",       link: `${basePath}/arq2`,  linkAnterior: `${basePath}/arq1`,  linkNext: `${basePath}/arq3`,  descripcion: "El arquetipo de la materia: conectado a los sentidos, la seguridad y los ciclos naturales.",                    video: "S-4pup6qN8k", letra: arq2,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq3",  nom: "Arquetipo ♊︎ Géminis",     link: `${basePath}/arq3`,  linkAnterior: `${basePath}/arq2`,  linkNext: `${basePath}/arq4`,  descripcion: "El signo dual que busca ser consciente de que todo es uno y aprender a profundizar.",                             video: "5qgXlEJxtMY", letra: arq3,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq4",  nom: "Arquetipo ♋︎ Cáncer",      link: `${basePath}/arq4`,  linkAnterior: `${basePath}/arq3`,  linkNext: `${basePath}/arq5`,  descripcion: "Conectado al hogar y a la familia, debe aprender a nutrirse a sí mismo para poder nutrir a otros.",                    video: "Ab0COSmQ3D0", letra: arq4,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq5",  nom: "Arquetipo ♌︎ Leo",         link: `${basePath}/arq5`,  linkAnterior: `${basePath}/arq4`,  linkNext: `${basePath}/arq6`,  descripcion: "El Rey del zodiaco que debe aprender a reconocerse sin validación externa.",                            video: "5KvJ-d7nNrA", letra: arq5,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq6",  nom: "Arquetipo ♍︎ Virgo",       link: `${basePath}/arq6`,  linkAnterior: `${basePath}/arq5`,  linkNext: `${basePath}/arq7`,  descripcion: "El gran analítico del zodiaco, debe aprender a soltar el control y poner sus dones al servicio de algo mayor.",    video: "gcg9pUrM4dA", letra: arq6,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq7",  nom: "Arquetipo ♎︎ Libra",       link: `${basePath}/arq7`,  linkAnterior: `${basePath}/arq6`,  linkNext: `${basePath}/arq8`,  descripcion: "Busca la armonía y la belleza, pero necesita aprender a sostenerse a sí mismo y a encontrar la armonía interna.",                                  video: "MM9ZHNLlSp8", letra: arq7,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq8",  nom: "Arquetipo ♏︎ Escorpio",    link: `${basePath}/arq8`,  linkAnterior: `${basePath}/arq7`,  linkNext: `${basePath}/arq9`,  descripcion: "El transformador profundo que muere y renace, capaz de ver lo que otros no ven.",                                 video: "sZeORCA1IpQ", letra: arq8,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq9",  nom: "Arquetipo ♐︎ Sagitario",   link: `${basePath}/arq9`,  linkAnterior: `${basePath}/arq8`,  linkNext: `${basePath}/arq10`, descripcion: "El buscador de la Verdad que necesita independencia, aventura y propósito.",                              video: "jDzYEcKgejc", letra: arq9,  detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq10", nom: "Arquetipo ♑︎ Capricornio", link: `${basePath}/arq10`, linkAnterior: `${basePath}/arq9`,  linkNext: `${basePath}/arq11`, descripcion: "El arquetipo de la responsabilidad que construye para que repercuta positívamente en las futuras generaciones.",                    video: "A27P5g_wxv8", letra: arq10, detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq11", nom: "Arquetipo ♒︎ Acuario",     link: `${basePath}/arq11`, linkAnterior: `${basePath}/arq10`, linkNext: `${basePath}/arq12`, descripcion: "El rebelde futurista que busca su individualidad dentro de la humanidad.",                                          video: "moNzwpf4QRk", letra: arq11, detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
      { id: "arq12", nom: "Arquetipo ♓︎ Piscis",      link: `${basePath}/arq12`, linkAnterior: `${basePath}/arq11`, linkNext: "",                  descripcion: "El arquetipo del sacrificio y la trascendencia, con un corazón dulce pero que siente el sufrimiento del mundo.",              video: "KlKo0YVvkss", letra: arq12, detalles: detalles, icon: AstrologiaIcon, cursoId: "astro-curso-2", floatingButton: serviciosAstrologicos },
    ],
  },
];

export const modulosAstrologiaCurso0: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: RecursosIconAstrologia,
    floatingButton: serviciosAstrologicos,
    submodules: [
      {
        id: "c0-recursos",
        nom: "Recursos a tu disposición",
        link: `/recursos/CartaAstral`,
        linkAnterior: "",
        linkNext: "",
        descripcion: "Recursos esenciales para acompañar tu aprendizaje y profundizar en Astrología.",
        video: "",
        letra: null,
        cursoId: "astro-curso-0",
        detalles: detalles,
        icon: null,
        floatingButton: serviciosAstrologicos,
      },
    ],
  },
  {
    title: "1. Introducción",
    icon: AstrologiaIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      {
        id: "c0-intro1",
        nom: "1.1 La historia de la Astrología",
        link: `${basePath}/c0-intro1`,
        linkAnterior: "",
        linkNext: `${basePath}/c0-intro2`,
        descripcion: "La Astrología nos revela los arquetipos que nuestra Alma ha elegido.",
        video: "J2tQEea8vpM",
        letra: astrologia1,
        cursoId: "astro-curso-0",
        detalles: detalles,
        icon: AstrologiaIcon,
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-intro2",
        nom: "1.2 La Carta Astral",
        link: `${basePath}/c0-intro2`,
        linkAnterior: `${basePath}/c0-intro1`,
        linkNext: `${basePath}/c0-asc`,
        descripcion: "La carta astral desvela los arquetipos que tu alma eligió para desarrollar e integrar en esta Vida.",
        video: "k8-MJOaBZk8",
        letra: astro1,
        cursoId: "astro-curso-0",
        detalles: detalles,
        icon: AstrologiaIcon,
        floatingButton: serviciosAstrologicos,
      },
    ],
  },
  {
    title: "2. Los planetas personales",
    icon: PlanetIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      {
        id: "c0-asc",
        nom: "2.1 El Ascendente",
        link: `${basePath}/c0-asc`,
        linkAnterior: `${basePath}/c0-intro2`,
        linkNext: `${basePath}/c0-sol`,
        descripcion: "El Ascendente es lo que pareces y tu camino hacia el Sol; define cómo te enfrentas a la Vida.",
        video: "wCTFnw0fiog",
        letra: astro2,
        detalles: detalles,
        icon: AscendenteIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-sol",
        nom: "2.2 El Sol",
        link: `${basePath}/c0-sol`,
        linkAnterior: `${basePath}/c0-asc`,
        linkNext: `${basePath}/c0-luna`,
        descripcion: "El Sol no es lo que eres, sino la energía que debes incorporar en su más alta frecuencia.",
        video: "Fo7sDdHjlSc",
        letra: astro3,
        detalles: detalles,
        icon: SunIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-luna",
        nom: "2.3 La Luna",
        link: `${basePath}/c0-luna`,
        linkAnterior: `${basePath}/c0-sol`,
        linkNext: `${basePath}/c0-mercurio`,
        descripcion: "La Luna es lo que recibiste de tu madre y cómo te conectas con tu mundo interior.",
        video: "A_2VrpFEo-g",
        letra: astro4,
        detalles: detalles,
        icon: MoonIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-mercurio",
        nom: "2.4 Mercurio",
        link: `${basePath}/c0-mercurio`,
        linkAnterior: `${basePath}/c0-luna`,
        linkNext: `${basePath}/c0-venus`,
        descripcion: "Mercurio habla de cómo opera tu mente, cómo te comunicas y dónde tienes más curiosidad.",
        video: "6hYtw96mym0",
        letra: astro5,
        detalles: detalles,
        icon: PlanetIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-venus",
        nom: "2.5 Venus",
        link: `${basePath}/c0-venus`,
        linkAnterior: `${basePath}/c0-mercurio`,
        linkNext: `${basePath}/c0-marte`,
        descripcion: "Venus habla de si crees merecer disfrutar la Vida, dónde quieres ser amado y cómo atraes.",
        video: "pjV9VBk3FoI",
        letra: astro6,
        detalles: detalles,
        icon: PlanetIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-marte",
        nom: "2.6 Marte",
        link: `${basePath}/c0-marte`,
        linkAnterior: `${basePath}/c0-venus`,
        linkNext: `${basePath}/c0-jupiter`,
        descripcion: "Marte transforma el deseo en movimiento y define cómo actúas, persigues y defiendes tus límites.",
        video: "djNyv14sGI0",
        letra: astro7,
        detalles: detalles,
        icon: PlanetIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
    ],
  },
    {
    title: "3. Los planetas sociales",
    icon: PlanetIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      {
        id: "c0-jupiter",
        nom: "3.1 Júpiter",
        link: `${basePath}/c0-jupiter`,
        linkAnterior: `${basePath}/c0-marte`,
        linkNext: `${basePath}/c0-saturno`,
        descripcion: "Júpiter es la expansión y la abundancia; el área donde buscas sentido y deseas ir más allá.",
        video: "lSHaqpNAyNA",
        letra: astro8,
        detalles: detalles,
        icon: PlanetIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-saturno",
        nom: "3.2 Saturno",
        link: `${basePath}/c0-saturno`,
        linkAnterior: `${basePath}/c0-jupiter`,
        linkNext: `${basePath}/c0-urano`,
        descripcion: "Saturno es la estructura y el karma; donde enfrentas limitaciones, maduras y te conviertes en adulto.",
        video: "6sDsZnya0UI",
        letra: astro9,
        detalles: detalles,
        icon: PlanetIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
    ],
  },
  {
    title: "4. Los planetas transpersonales",
    icon: PlanetIcon,
    floatingButton: serviciosAstrologicos,
    submodules: [
      {
        id: "c0-urano",
        nom: "4.1 Urano",
        link: `${basePath}/c0-urano`,
        linkAnterior: `${basePath}/c0-saturno`,
        linkNext: `${basePath}/c0-neptuno`,
        descripcion: "Urano es la creación sin límites; donde eres más innovador, original y necesitas libertad.",
        video: "fw6aSgUemQU",
        letra: astro10,
        detalles: detalles,
        icon: PlanetIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-neptuno",
        nom: "4.2 Neptuno",
        link: `${basePath}/c0-neptuno`,
        linkAnterior: `${basePath}/c0-urano`,
        linkNext: `${basePath}/c0-pluton`,
        descripcion: "Neptuno habla de dónde tienes más confusión y cómo buscas trascendencia y fusión con lo divino.",
        video: "gaI2OSHdnFg",
        letra: astro11,
        detalles: detalles,
        icon: PlanetIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
      {
        id: "c0-pluton",
        nom: "4.3 Plutón",
        link: `${basePath}/c0-pluton`,
        linkAnterior: `${basePath}/c0-neptuno`,
        linkNext: "",
        descripcion: "Plutón destruye cíclicamente lo inútil; es tu miedo más profundo y tu deseo más honesto.",
        video: "IxZpyzhz3Qc",
        letra: astro12,
        detalles: detalles,
        icon: PlanetIcon,
        cursoId: "astro-curso-0",
        floatingButton: serviciosAstrologicos,
      },
    ],
  },
];