import type { DoshaKey } from "./doshaIntro";
import type { DoshaCuidarte } from "./doshaCuidarte";

/**
 * «Tu alimentación y tu estilo de Vida», en INGLÉS.
 *
 * Emparejado por la clave del doṣha, que no se traduce. El doṣha que no esté
 * aquí se lee entero en español (ver `useDoshaCuidarte`).
 *
 * Vocabulario:
 *  · Los seis sabores van con el nombre de siempre en inglés: Sweet · Sour ·
 *    Salty · Pungent · Bitter · Astringent («picante» es *pungent*, no *spicy*).
 *  · Las cinco comidas españolas se traducen por lo que son (ver GLOSARIO):
 *    Breakfast · Mid-morning · Lunch · Afternoon snack · Dinner.
 *  · Los términos sánscritos (Abhyanga, ghee, dhal, chai) no se traducen.
 *
 * OJO: `rutina` alimenta el borrador del constructor «Crea tu día» y
 * `equilibran.opciones` la lista de alimentos de ese mismo constructor; van en
 * el MISMO orden que el español.
 */
export const DOSHA_CUIDARTE_EN: Partial<Record<DoshaKey, DoshaCuidarte>> = {
  vata: {
    alimTitulo: "The way of eating that suits you",
    alimIntro: [
      "By now you know that Vata needs stability.",
      "Food is one of the simplest ways to give it that.",
      "This isn't about following a perfect diet.",
      "It's about choosing food that brings warmth, nourishment and regularity.",
    ],
    sabores: {
      titulo: "The tastes that balance you most",
      intro: [
        "Vata is **cold, dry and light**, which is why it loves food with those same qualities.",
        "But it finds its balance in the tastes that bring the opposite.",
      ],
      favorables: ["Sweet.", "Sour.", "Salty."],
      moderarIntro: "The tastes to go easier on are:",
      moderar: ["Pungent.", "Bitter.", "Astringent."],
    },
    alimentosBuenos: {
      titulo: "The food that usually agrees with you",
      items: [
        "Warm grains like basmati rice, oats or quinoa.",
        "Eating a vegetarian diet.",
        "Cooked vegetables: squash, sweet potato, carrot, zucchini, beet…",
        "Healthy fats like ghee, olive oil or avocado.",
        "Nuts and seeds (soaked, especially).",
        "Ripe, sweet fruit.",
        "Warm dairy, if you tolerate it.",
        "Soups, purées and vegetable stews.",
        "Warm infusions of mild ginger, cinnamon, fennel or chamomile.",
      ],
    },
    alimentosAumentan: {
      titulo: "What usually increases Vata",
      items: [
        "Very cold drinks.",
        "Too much salad and raw food.",
        "Dry, gritty or heavily processed food.",
        "Too much coffee and stimulants.",
        "Eating fast, or while doing other things.",
        "Skipping meals.",
      ],
    },
    comoComes: {
      titulo: "More important than what you eat is how you eat",
      intro: ["For Vata, routine feeds you too.", "Try to:"],
      items: [
        "Eat sitting down.",
        "Eat without rushing.",
        "Keep to similar hours every day.",
        "Chew slowly.",
        "Keep your phone and the TV away while you eat.",
      ],
      cierre: "Your digestive system works better when it feels safe and steady.",
    },
    diaEjemplo: {
      titulo: "A sample day",
      comidas: [
        { momento: "Breakfast", texto: ["Oat porridge with cinnamon, cooked apple, walnuts and a warm infusion."] },
        { momento: "Mid-morning", texto: ["A handful of almonds or a piece of ripe fruit."] },
        { momento: "Lunch", texto: ["Basmati rice with sautéed vegetables and lentils or dhal.", "Dressed with olive oil or ghee."] },
        { momento: "Afternoon snack", texto: ["A warm infusion and some nut butter with fruit."] },
        { momento: "Dinner", texto: ["Squash or vegetable purée with quinoa and a little ghee.", "A light dinner, warm and easy to digest."] },
      ],
    },
    alimCierre: ["*Don't look for perfection, look for consistency.*"],
    desequilibran: {
      titulo: "Which foods do you love that throw you off balance?",
      intro: "Check what you usually eat. It's not to make you feel guilty, it's to notice: this food — cold, dry or very stimulating — tends to increase Vata.",
      opciones: [
        "A big salad or a lot of raw vegetables.",
        "Cold fruit straight from the fridge.",
        "Coffee.",
        "Energy drinks.",
        "Fizzy drinks or very cold drinks.",
        "Ice cream.",
        "Popcorn, rice cakes or dry, crunchy snacks.",
        "Toast, cookies or crackers.",
        "Nuts that haven't been soaked.",
        "Undercooked dried legumes (chickpeas, beans).",
        "Too much black or green tea.",
        "Alcohol.",
        "Very dry or heavily processed food.",
        "Too much bitter or very pungent spice.",
        "Iced or very bitter infusions (horsetail, dandelion).",
        "I've eaten in a rush, standing up, or while doing something else.",
      ],
    },
    equilibran: {
      titulo: "Food that balances you and that you can have today",
      intro: "Check the ones you have on hand or could add today. Warm, nourishing and easy to digest: exactly what Vata needs.",
      opciones: [
        "Warm basmati rice.",
        "Cooked oats with cinnamon.",
        "Warm quinoa.",
        "Warm soups, purées and stews.",
        "Cooked vegetables (squash, sweet potato, carrot, zucchini, beet).",
        "Well-cooked lentils or dhal.",
        "Ghee.",
        "Olive oil.",
        "Avocado.",
        "Soaked almonds or walnuts.",
        "Ripe banana.",
        "Apple compote.",
        "Dates or figs.",
        "Warm spiced milk (if you tolerate it).",
        "Spice: ginger.",
        "Spice: cinnamon.",
        "Spice: cumin.",
        "Spice: cardamom.",
        "Spice: fennel.",
        "Spice: nutmeg.",
        "Ginger infusion.",
        "Cinnamon infusion.",
        "Fennel infusion.",
        "Licorice infusion.",
        "Chamomile infusion.",
      ],
    },
    rutina: [
      { momento: "Waking up", actividad: "Breathe slowly for a few minutes before starting the day." },
      { momento: "Exercise", actividad: "Yoga or strength work." },
      { momento: "Breakfast", actividad: "Generous and warm.", comida: true },
      { momento: "Lunch", actividad: "Your main meal of the day: warm, cooked and nourishing.", comida: true },
      { momento: "Before sleep", actividad: "Oil, an infusion and silence." },
    ],

    estiloTitulo: "The way of living that suits you",
    estiloIntro: [
      "Food helps.",
      "But for a Vata person, **routine is medicine**.",
      "Every small habit that brings stability helps settle the nervous system.",
    ],
    secciones: [
      {
        titulo: "Start the day without rushing",
        parrafos: [
          "Get up with enough time that you don't start the day running.",
          "A few minutes of silence, breathing or stretching can completely change how you feel for the rest of the day.",
        ],
      },
      {
        titulo: "Move, but don't wear yourself out",
        parrafos: [
          "Exercise is very good for Vata.",
          "What matters isn't doing a lot.",
          "It's doing it steadily and consciously.",
          "The best options are usually:",
        ],
        items: ["Strength work.", "Yoga.", "Swimming.", "Conscious dance."],
        cierre: "Stay away from training to exhaustion every day.",
      },
      {
        titulo: "Make rest a priority",
        parrafos: [
          "Your nervous system needs to recover.",
          "Sleeping well isn't a luxury.",
          "It's a need.",
          "Try to go to bed and get up at a similar hour every day. Cut back on screens during the last hour of the day.",
        ],
      },
      {
        titulo: "Give yourself moments of calm",
        parrafos: ["You don't need to be doing something all the time."],
        items: ["Read.", "Meditate.", "Breathe.", "Listen to music.", "Take a walk.", "Be in nature."],
        cierre: "Anything that lowers the outside noise helps the inside noise come down too.",
      },
    ],
    abhyanga: {
      titulo: "A small habit that can change your day",
      parrafos: [
        "In Ayurveda there's a practice called **Abhyanga**, a self-massage with warm oil traditionally done **before your shower**.",
        "The massage helps nourish the skin, relax the nervous system, improve circulation and give the body a feeling of safety and calm. Afterwards, a warm shower takes off the excess oil without washing away its benefits.",
        "For a **Vata** person it's one of the most recommended habits, especially in stretches of stress, cold or dryness.",
        "*You don't have to do it every day. Once or twice a week can already make a difference.*",
      ],
    },
    recuerda: {
      titulo: "What Ayurveda wants you to remember",
      parrafos: [
        "Vata doesn't need a perfect Life.",
        "It needs a predictable one.",
        "The steadier your routine, the more room your creativity has to express itself without turning into anxiety.",
      ],
    },
    reflexion: {
      titulo: "Reflect",
      pregunta: "Which single habit could you start this very week to bring you a little closer to balance?",
      nota: "We'll come back to it at the end of the map.",
      compromisoTitulo: "My commitment",
      compromisoIntro: "Pick only one for this week.",
      compromisos: [
        "Eat at the same hour.",
        "Sleep earlier.",
        "Do 10 minutes of breathing.",
        "Walk every day.",
        "Have a warm breakfast.",
        "Put my phone away while I eat.",
      ],
    },
    cierre: [
      "*Balance isn't born from big changes; it's born from repeating small habits with love and patience.*",
    ],
  },
  pitta: {
    alimTitulo: "The way of eating that suits you",
    alimIntro: [
      "By now you know that Pitta needs balance.",
      "Food is one of the simplest ways to keep its fire in harmony.",
      "This isn't about eating less.",
      "It's about choosing food that cools, nourishes and keeps the heat from building up.",
    ],
    sabores: {
      titulo: "The tastes that balance you most",
      intro: [
        "Pitta is **hot, intense and slightly oily**.",
        "That's why it finds its balance in the tastes that bring coolness and lightness.",
      ],
      favorables: ["Sweet.", "Bitter.", "Astringent."],
      moderarIntro: "The tastes to go easier on are:",
      moderar: ["Pungent.", "Sour.", "Salty."],
    },
    alimentosBuenos: {
      titulo: "The food that usually agrees with you",
      items: [
        "Eating a mostly vegetarian diet.",
        "Fresh vegetables like cucumber, zucchini, asparagus, broccoli or leafy greens.",
        "Sweet fruit like grapes, cherries, melon, apple, pear or mango.",
        "Grains like basmati rice, barley or oats.",
        "Coconut, avocado and small amounts of ghee.",
        "Mild spices like cilantro, fennel, cardamom, cumin or turmeric.",
        "Infusions of mint, chamomile or licorice.",
      ],
    },
    alimentosAumentan: {
      titulo: "What usually increases Pitta",
      items: [
        "Very spicy food.",
        "Too much sour food.",
        "A lot of salt.",
        "Fried and very fatty food.",
        "Alcohol.",
        "Too much coffee and stimulants.",
        "Eating in a rush or under stress.",
        "Skipping meals.",
      ],
    },
    comoComes: {
      titulo: "More important than what you eat is how you eat",
      intro: ["For Pitta, hunger is usually very intense.", "That's why it matters to honor it without going to extremes.", "Try to:"],
      items: [
        "Eat at regular hours.",
        "Sit down to eat calmly.",
        "Keep away from work and your phone while you eat.",
        "Enjoy your food without rushing.",
        "Listen for when you're really full.",
      ],
      cierre: "Your digestion works better when your body doesn't feel under pressure.",
    },
    diaEjemplo: {
      titulo: "A sample day",
      comidas: [
        { momento: "Breakfast", texto: ["Oat porridge with pear, seeds and a mint infusion."] },
        { momento: "Mid-morning", texto: ["Fresh fruit or a handful of seeds."] },
        { momento: "Lunch", texto: ["Basmati rice with steamed vegetables, lentils and fresh cilantro."] },
        { momento: "Afternoon snack", texto: ["Plain yogurt (if you tolerate it) or sweet fruit."] },
        { momento: "Dinner", texto: ["Zucchini purée with quinoa and sautéed vegetables.", "A light dinner, easy to digest."] },
      ],
    },
    alimCierre: ["*Don't feed only your hunger.*", "*Feed your balance too.*"],
    desequilibran: {
      titulo: "Have you eaten anything today that throws you off balance… even if you love it?",
      intro: "Check what you've had today. It's not to make you feel guilty, it's to notice: this food — hot, spicy, sour or very stimulating — tends to increase Pitta.",
      opciones: [
        "Very spicy food (chili peppers).",
        "Fried or very fatty food.",
        "A lot of tomato or sour sauces.",
        "Vinegar or too much citrus.",
        "A lot of salt.",
        "Pickles or fermented food.",
        "Aged cheeses.",
        "Red meat or cured meats.",
        "Too much raw garlic or onion.",
        "Coffee.",
        "Energy drinks.",
        "Alcohol.",
        "Chocolate.",
        "Hot sauces.",
        "Too much very hot spice (black pepper, chili, mustard).",
        "Very stimulating infusions (black tea, strong ginger).",
        "I've eaten in a rush or under stress.",
      ],
    },
    equilibran: {
      titulo: "Food that balances you and that you can have today",
      intro: "Check the ones you have on hand or could add today. Fresh, light and cooling: exactly what settles Pitta's fire.",
      opciones: [
        "Cucumber.",
        "Zucchini.",
        "Asparagus.",
        "Broccoli and leafy greens.",
        "Sweet fruit (melon, pear, grapes, mango).",
        "Coconut or coconut water.",
        "Basmati rice.",
        "Barley or oats.",
        "Avocado.",
        "Ghee (in small amounts).",
        "Fresh cilantro.",
        "Mild yogurt or fresh dairy (if you tolerate it).",
        "Spice: cilantro.",
        "Spice: fennel.",
        "Spice: cardamom.",
        "Spice: cumin.",
        "Spice: turmeric.",
        "Spice: mint.",
        "Mint infusion.",
        "Chamomile infusion.",
        "Licorice infusion.",
        "Rose infusion.",
        "Fennel infusion.",
      ],
    },
    rutina: [
      { momento: "Waking up", actividad: "Meditate, so you don't begin the day in a rush." },
      { momento: "Exercise", actividad: "Swimming or a walk." },
      { momento: "Breakfast", actividad: "Fresh and balanced.", comida: true },
      { momento: "Lunch", actividad: "Your biggest meal, at its hour and without rushing.", comida: true },
      { momento: "Before sleep", actividad: "Reading or meditating." },
    ],

    estiloTitulo: "The way of living that suits you",
    estiloIntro: [
      "Food helps.",
      "But for a Pitta person, **rest is medicine too**.",
      "Your nature has an enormous capacity to do, to create and to reach its goals.",
      "That's why it needs to learn when to stop.",
    ],
    secciones: [
      {
        titulo: "Start the day calmly",
        parrafos: [
          "You don't have to begin the day answering messages or thinking about everything you have to do.",
          "Give a few minutes to breathing, stretching or simply enjoying the silence before you start.",
        ],
      },
      {
        titulo: "Move, but don't compete",
        parrafos: ["Exercise is very good for Pitta.", "What matters isn't training more.", "It's enjoying the movement.", "The best options are usually:"],
        items: ["Strength work.", "Speed (running, cycling, swimming...)", "Yoga.", "Hiking."],
        cierre: "Don't turn every workout into a competition.",
      },
      {
        titulo: "Make rest a priority",
        parrafos: [
          "Sleeping well helps your body and your mind come back to balance.",
          "Try to finish work with enough time for your mind to switch off before you go to bed.",
          "Not everything has to be solved today.",
        ],
      },
      {
        titulo: "Give yourself moments where you don't have to prove anything",
        parrafos: [],
        items: ["Read.", "Take a walk.", "Be in nature.", "Listen to music.", "Meditate.", "Spend time with people who bring you calm."],
        cierre: "Remember that your worth doesn't depend on your productivity.",
      },
    ],
    abhyanga: {
      titulo: "A small habit that can change your day",
      parrafos: [
        "For a **Pitta** person, one of the most beneficial habits is setting aside a few minutes every day to do something with no goal at all.",
        "A quiet walk.",
        "Breathing.",
        "Watching nature.",
        "Sitting in the morning sun.",
        "Not to achieve anything.",
        "Simply to be present.",
        "That small rest helps the fire stop burning energy for nothing.",
      ],
    },
    recuerda: {
      titulo: "What Ayurveda wants you to remember",
      parrafos: [
        "Pitta doesn't need to keep proving what it's capable of.",
        "It needs to remember that even the brightest fire needs moments to burn lower.",
        "When you learn to rest, your energy stops draining you and starts holding you up.",
      ],
    },
    reflexion: {
      titulo: "Reflect",
      pregunta: "Which small habit could you bring in this week to slow down a little without stopping taking care of yourself?",
      nota: "We'll come back to it at the end of the map.",
      compromisoTitulo: "My commitment",
      compromisoIntro: "Pick only one for this week.",
      compromisos: [
        "Take a real break at midday.",
        "Stop working at a set hour.",
        "Eat without screens.",
        "Move without competing or pushing myself.",
        "Give 10 minutes to doing nothing.",
        "Go to bed a little earlier.",
      ],
    },
    cierre: [
      "*Balance isn't about doing less, it's about learning when it's time to stop.*",
    ],
  },
  kapha: {
    alimTitulo: "The way of eating that suits you",
    alimIntro: [
      "By now you know that Kapha needs movement and lightness.",
      "Food is one of the most effective ways to wake up its energy and keep the heaviness away.",
      "This isn't about eating less.",
      "It's about choosing food that wakes up your metabolism and brings vitality.",
    ],
    sabores: {
      titulo: "The tastes that balance you most",
      intro: [
        "Kapha is **cold, heavy, moist and stable**.",
        "That's why it finds its balance in the tastes that bring warmth, lightness and stimulation.",
      ],
      favorables: ["Pungent.", "Bitter.", "Astringent."],
      moderarIntro: "The tastes to go easier on are:",
      moderar: ["Sweet.", "Sour.", "Salty."],
    },
    alimentosBuenos: {
      titulo: "The food that usually agrees with you",
      items: [
        "Eating a mostly vegetarian diet.",
        "Vegetables of all kinds, especially leafy greens, broccoli, cauliflower, asparagus, artichokes or cabbage.",
        "Light fruit like apple, pomegranate, berries or pear.",
        "Light grains like barley, millet or quinoa.",
        "Legumes like lentils, chickpeas or beans.",
        "Stimulating spices like ginger, turmeric, black pepper, mustard, cinnamon or cumin.",
        "Infusions of ginger, cinnamon or spiced tea.",
      ],
    },
    alimentosAumentan: {
      titulo: "What usually increases Kapha",
      items: [
        "Too much sweet food.",
        "Refined flour and pastries.",
        "Too much dairy and cheese.",
        "Very fatty or fried food.",
        "Meat of any kind.",
        "Very sugary drinks.",
        "Ice cream and very cold food.",
        "Eating too much, even when the food is healthy.",
        "Snacking constantly between meals.",
      ],
    },
    comoComes: {
      titulo: "More important than what you eat is how you eat",
      intro: ["For Kapha it matters to eat when there's real hunger.", "Try to:"],
      items: [
        "Eat only when you have an appetite.",
        "Don't go back for seconds out of habit.",
        "Eat slowly and with attention.",
        "Leave several hours between meals, to help your digestion.",
        "Don't eat out of boredom, stress or emotional need.",
      ],
      cierre: "Your digestion works better when your body has time to finish each process.",
    },
    diaEjemplo: {
      titulo: "A sample day",
      comidas: [
        { momento: "Breakfast", texto: ["A ginger and cinnamon infusion with fruit — or, if you're not hungry, simply the infusion."] },
        { momento: "Mid-morning", texto: ["Only if real hunger shows up."] },
        { momento: "Lunch", texto: ["Quinoa with sautéed vegetables, chickpeas and spices."] },
        { momento: "Afternoon snack", texto: ["A piece of fruit or an infusion."] },
        { momento: "Dinner", texto: ["Vegetable purée or steamed vegetables with tofu.", "A light dinner makes resting easier and keeps the heaviness away."] },
      ],
    },
    alimCierre: ["*Don't eat out of habit.*", "*Eat because your body really needs it.*"],
    desequilibran: {
      titulo: "Have you eaten anything today that throws you off balance… even if you love it?",
      intro: "Check what you've had today. It's not to make you feel guilty, it's to notice: this food — heavy, sweet, fatty or very cold — tends to increase Kapha.",
      opciones: [
        "Sweets, pastries or desserts.",
        "Ice cream.",
        "Cheese or too much dairy.",
        "Fried or very fatty food.",
        "Bread and refined flour.",
        "Sugary drinks.",
        "Very cold food, or food straight from the fridge.",
        "Fatty meat.",
        "Too many nuts.",
        "Too much banana or avocado.",
        "I've eaten too much, even if it was healthy.",
        "I've snacked between meals without real hunger.",
        "Too much salt.",
        "Very sweet infusions, or ones with a lot of milk.",
        "I've eaten out of boredom or out of anxiety.",
      ],
    },
    equilibran: {
      titulo: "Food that balances you and that you can have today",
      intro: "Check the ones you have on hand or could add today. Light, warm and stimulating: exactly what sets Kapha in motion.",
      opciones: [
        "Leafy green vegetables.",
        "Broccoli, cauliflower, cabbage or artichoke.",
        "Asparagus.",
        "Legumes (lentils, chickpeas, beans).",
        "Light grains (barley, millet, quinoa).",
        "Light fruit (apple, pear, pomegranate, berries).",
        "Steamed or sautéed vegetables.",
        "Light, spiced soups.",
        "Raw honey (in moderation).",
        "Spice: ginger.",
        "Spice: black pepper.",
        "Spice: turmeric.",
        "Spice: mustard.",
        "Spice: cinnamon.",
        "Spice: cumin.",
        "Spice: clove.",
        "Ginger infusion.",
        "Cinnamon infusion.",
        "Ginger infusion with lemon.",
        "Spiced tea (unsweetened chai).",
      ],
    },
    rutina: [
      { momento: "Waking up", actividad: "Get up right away and wake your body up." },
      { momento: "Exercise", actividad: "Running or HIIT." },
      { momento: "Breakfast", actividad: "Light, or even skipped if there's no hunger.", comida: true },
      { momento: "Lunch", actividad: "Light and spiced; make it the main meal of the day.", comida: true },
      { momento: "Before sleep", actividad: "Stay off the couch and go to bed early." },
    ],

    estiloTitulo: "The way of living that suits you",
    estiloIntro: [
      "Food helps.",
      "But for a Kapha person, **movement is medicine**.",
      "Every small change breaks the inertia and gives energy back to the body.",
    ],
    secciones: [
      {
        titulo: "Start the day with energy",
        parrafos: [
          "Get up as soon as the alarm goes off, and don't stay in bed for long.",
          "Beginning the day with movement helps wake up both body and mind.",
          "Traditional Ayurveda recommends hard exercise before breakfast, but it's fine to do it later as long as it's before 8 in the evening.",
        ],
      },
      {
        titulo: "Move every day",
        parrafos: ["Exercise is one of Kapha's best allies.", "The most recommended activities are usually:"],
        items: ["Running.", "Cycling.", "Hiking.", "Strength training.", "Dancing.", "Fast-moving sports."],
        cierre: "You don't have to train for hours. The key is keeping it up.",
      },
      {
        titulo: "Stay away from too much comfort",
        parrafos: [
          "Kapha finds its well-being in stability, but too much comfort can turn into stagnation.",
          "Look for small changes that keep your energy moving.",
        ],
        items: ["Try a new route.", "Learn something different.", "Meet new people.", "Leave your comfort zone often."],
      },
      {
        titulo: "Surround yourself with things that inspire you",
        parrafos: ["Motivation is something you grow too."],
        items: ["Listen to music.", "Spend time with people whose enthusiasm rubs off on you.", "Make plans you're excited about.", "Let yourself discover new things."],
        cierre: "Every different experience wakes up your energy.",
      },
    ],
    abhyanga: {
      titulo: "A small habit that can change your day",
      parrafos: [
        "For a **Kapha** person, one of the most beneficial habits is beginning the morning with a few minutes of movement.",
        "It can be walking, stretching, doing dynamic yoga or simply dancing to your favorite song.",
        "What matters isn't the intensity.",
        "It's reminding your body that every day begins with action.",
      ],
    },
    recuerda: {
      titulo: "What Ayurveda wants you to remember",
      parrafos: [
        "Kapha doesn't need to become someone different.",
        "It needs to trust that moving doesn't mean losing its stability.",
        "Quite the opposite.",
        "Every small step keeps alive the energy that already exists inside you.",
      ],
    },
    reflexion: {
      titulo: "Reflect",
      pregunta: "Which small habit could you start this week to fill your Life with a little more movement?",
      nota: "We'll come back to it at the end of the map.",
      compromisoTitulo: "My commitment",
      compromisoIntro: "Pick only one for this week.",
      compromisos: [
        "Walk every day.",
        "Get up as soon as the alarm goes off.",
        "Exercise at least three days.",
        "Try something new this week.",
        "Eat a lighter, earlier dinner.",
        "Don't snack between meals.",
      ],
    },
    cierre: [
      "*You don't have to change your whole Life, you only have to take the first step.*",
    ],
  },
};
