export const keter2Letra = "Keter nos invita a mirar en nuestro interior para descubrir el propósito de nuestra vida, hacia qué dirección nuestra alma desea ir, y desde ahí, alinear nuestra mente y acciones con nuestro propósito final. Cuando estamos confundidos, el Ego coge las riendas y nos hace buscar algo por lo que diferenciarnos, por lo que sentirnos especiales. Buscamos destacar por algo externo a nosotros, por un objeto, por una actividad… queriendo demostrar que somos únicos, pero esto no es necesario, porque ya lo somos. Keter nos invita a recordar que somos manifestaciones de lo divino con un plan concreto.";

export const chokmah2Letra = "Chokhmah es la capacidad de ver lo que de verdad está pasando antes de que lo intentemos clasificar o analizar. Puede ser incómodo pero transformador, porque solo cuando habitamos el presente, somos capaces de ver qué es lo que nos duele. Cuando no habitamos el presente, reaccionamos a fantasmas del pasado con patrones previamente establecidos. Por eso, Chokmah nos invita a permanecer en el presente, para así ver qué es lo que la Vida de verdad tiene para nosotros.";

export const binah2Letra = "El propósito de Binah es poder bajar a tierra la sabiduría de Chokmah, gracias a Binah clasificamos y analizamos las situaciones y podemos hacerlas entendibles para aprender de ellas. Es muy común que si llevamos un tiempo sin ampliar nuestros esquemas mentales, tengamos una Binah rígida y repitamos patrones que nos hacen daño. Binah nos invita a que ampliemos nuestra consciencia, no que nos quedemos en los bucles de siempre.";

export const daat2Letra = "Da'at es el puente dinámico entre Binah y Chokmah, es decir, es la conexión que lleva la luz de Chokmah a ser clasificada en Binah. A veces cuando hay traumas, Daat puede bloquearse, haciendo que en verdad sí entiendas lo que está pasando, pero no seas capaz ni quieras ser consciente de ello. Esto en psicología se llama disociación y ocurre cuando la experiencia abruma tanto a la persona que para aguantarla tiene que desconectarse. En baja frecuencia, repetimos patrones que ya sabemos que nos hacen daño, pero al estar tan acostumbrados, preferimos acomodarnos en el sufrimiento. En su alta frecuencia, somos capaces de integrar nuevos patrones en nuestra vida, patrones que sabemos que nos ayudan y que nos hacen avanzar.";

export const chesed2Letra = "Chesed nos invita a compartir, a dar sin esperar nada a cambio. Es decir, podemos dar y eso no nos hace mejor ni peor, damos porque estamos alineados con nuestra esencia y por extensión, con la vida. Cuando no tenemos amor propio, damos para que el otro nos quiera, por lo que siempre nos sentiremos vacíos. Chesed recuerda que tenemos que ser conscientes del para qué damos, que debemos de respetar los límites del otro, y recuerda que el dar es lo natural.";

export const gevurah2Letra = "Gevurah es la energía de los límites, la disciplina y el discernimiento. Gevurah es la restricción consciente que nos devuelve al camino de nuestra esencia. Es el juicio que nos ayuda a discernir si algo es nutritivo o dañino, si útil o si es una distracción. Nos guía para establecer límites claros y coherentes con nuestro camino sin caer en la rigidez ni en la violencia. Cuando Gevurah está equilibrada: podemos decir \"no\" con firmeza y sin culpa, aceptamos que puede incomodar a otros, pero recordamos que no somos responsables de sus emociones.";

export const tiferet2Letra = "Tiferet es el corazón, es el centro que armoniza y equilibra las fuerzas de expansión y restricción. Nos permite comunicar con claridad, sin rencor ni autoprotección. Es la capacidad de ver la verdad sin distorsión emocional, de conectar con nuestra esencia más profunda y con la sabiduría que habita en nosotros. Nos permite actuar desde la armonía y desde la conexión más directa con nuestra esencia.";

export const netzach2Letra = "Netzach es la energía de la persistencia, la determinación y la constancia. Recuerda que conocer nuestra verdad no basta; hay que sostenerla y defenderla. Muchas personas saben lo que es correcto y coherente en ellos, pero cuando la motivación flaquea o la energía baja tienden a renunciar. Netzach nos invita a mantenernos firmes, a persistir con paciencia y disciplina, y a recorrer el camino hasta el final.";

export const hod2Letra = "Hod es la energía de la comunicación. Está profundamente ligada a la humildad, porque cuando conocemos nuestra verdad, recordamos que no somos superiores ni inferiores; y podemos hablar desde la verdad de lo que somos. Nos enseña paciencia y respeto. No nos enfadamos ni nos sentimos heridos si hay malentendidos, porque entendemos que cada persona le da una interpretación distinta a las palabras y a la realidad.";

export const yesod2Letra = "Yesod nos invita a consolidar lo que sabemos y sentimos, a integrar en nuestra identidad nuestra esencia. Pero esto no es fácil, porque en yesod, en el pasado construimos nuestro yo repitiendo las estructuras de la sociedad y de la familia. Por ello, Yesod en alta frecuencia, nos invita a transformar nuestro Yo, y a que nuestra autopercepción sea coherente con nuestra esencia.";

export const malkuth2Letra = "Malkhut es la manifestación tangible del Árbol de la Vida. Es donde toda la energía se canaliza para tomar forma material. Es la encarnación. Aquí ya no hay secretos: la realidad muestra lo que realmente somos en ese momento. Lo que está integrado se manifiesta con orden, verdad y coherencia. Lo que está herido o negado se manifiesta en desorden y enfermedad. Por eso, Malkhut es el gran espejo. No refleja lo que decimos que somos, sino lo que verdaderamente somos en ese momento.";
