export const chokmahLetra = "Chokmah es el continuo flujo de sabiduría y de luz que baña el universo a cada segundo. Es el conocimiento sin límites que, como humanos, si fuésemos capaces de acceder a solo una parte, nos volveríamos locos. Por ello, tenemos la Sephirot de Binah, la que estructura, la que pone límites, la que clasifica y decide qué guardar, olvidar, recordar o comprender. Gracias a Binah, estamos cuerdos y podemos tener una línea de vida coherente. Da'at es la energía que nos permite oscilar entre la luz de Jojmá y la clasificación de Binah. Da'at es la sabiduría y el aprendizaje.";

export const chesedLetra = "Chesed es la sephirot del dar. Aquí no tenemos límites, siempre podemos dar más, porque según la cábala, no debemos atesorar conocimientos ni experiencias como falsos custodios. Debemos compartir para crecer todos. Por eso, en esta dimensión, el problema es cuánto puede tolerar y recibir el otro. Debemos tener amabilidad y misericordia para ponernos en el lugar del otro y dar proporcionalmente a lo que puede recibir. Porque aquel que da y el otro es feliz recibiendo, el dador también es recibidor.";

export const geburahLetra = "Geburah es la dimensión del recibir para crecer. El universo y la vida son generosos y siempre están dando, pero muchas veces nos cerramos a recibir por falta de amor propio y por ello no podemos crecer y nos quedamos estancados. Te aseguro que ninguna entidad, ni Dios, ni el universo quiere que te quedes estancado en el sufrimiento. Lo que quieren es que cojas lo que te ofrece y que con ello te eleves. Por ello, Gevurah recuerda no tener miedo a recibir, sino ser conscientes de cuánto es adecuado que recibamos en cada momento.";

export const tiferetLetra = "Tiferet es la sephirot más bonita, porque es la dimensión de la paz y la armonía, que en nuestro cuerpo se encuentra en nuestro corazón. Gracias a Tiferet podemos oscilar entre las distintas dimensiones desde la amabilidad y el respeto propio. Nos ayuda y acompaña cariñosamente a ver dónde están nuestros desequilibrios.";

export const netzachLetra = "Netzach es la sephirot de las emociones y los sentimientos. Cuando estamos en su alta frecuencia, somos capaces de reconocer y gestionarlas. No nos avergonzamos ni las reprimimos, ni nos enfadamos con ellas. La mejor forma de expresarlas es a través de la sephirot de Hod, la dimensión donde intelectualizamos nuestro interior y, a través de ello, podemos hacer una comunicación correcta. Hod nos recuerda que cada uno tiene su realidad estructurada a través de la interpretación que cada uno le da a las palabras, por eso nos invita a, cuando haya un malentendido, hablarlo tranquilamente.";

export const yesodLetra = "En la sephirot de Yesod se encuentra cómo somos capaces de percibir el mundo. Normalmente se percibe a través de lo inculcado por la sociedad y por nuestra familia. Es la dimensión donde se forma nuestro ego, que es el filtro de cómo vemos al resto de dimensiones del Árbol de la Vida. El ego es el que nos dice, normalmente de muy mala manera y desagradablemente, dónde se encuentran nuestros desequilibrios. Y si conseguimos escucharlo sin estar enfadados, desde la observación, puede ser nuestro aliado para volver a la armonía.";

export const malkhutLetra = "Malkhut es la sephirot donde la energía se manifiesta en materia. El propósito es ser conscientes de que la materia es energía sagrada manifestada, que es una herramienta y que cumple una función más allá de la que se ve a simple vista. Es el recordar que la naturaleza y nosotros somos seres divinos.";

export const cabalaLetra = "La cábala es la recopilación de las filosofías místicas que explican la estructura y el propósito del alma humana. Estas enseñanzas se basan en la interpretación de la Torah, el texto sagrado que forma parte del antiguo testamento y que fue escrito por Moises. La cábala habla de Dios, pero en sentido holístico, es decir, Dios no es un hombre que nos observa y nos juzga, sino una inteligencia infinita que nos rige y estructura, es la materia y su movimiento, es absolutamente todo lo que existe y existirá. En la cábala, no se le llama Dios, sino Ein Sof o Uno, haciendo referencia a que por muchas manifestaciones que existan, todos somos Uno.";

export const tikunOlamLetra = "Como la cábala dice, el Ein Sof está en todos nosotros, pero para poder manifestarlo debemos hacer lo que se conoce como Tikun Olam cuya traducción es la reparación del universo. La cábala dice que la única reparación posible es a través de nuestro amor propio, valía y respeto. Sólo así podremos ser nuestra versión más divina y por extensión, recordarle a los demás con nuestra luz que ellos también son parte del Uno y que sin ellos, Dios no está completo.";

export const orkliLetra = "Al igual que nos encontramos en el taoísmo y en el hinduismo, en la cábala, Dios también se manifiesta en dos energías. A la energía masculina se le llama Or, que es la luz potencialmente creadora e infinita, y a la energía femenina se le llama Kli, que es el receptor, la vasija sagrada, que recibe, transforma y da estructura a la luz divina. \n\n Cuando la luz sagrada Or se integra en el Kli, la vasija divina, se crea una Sephirot, cuyo significado es dimensión. El Árbol de la Vida, está compuesto por 10 sephirot concretas que dan estructura al universo y al alma humana.";

export const ketherLetra = "La sephirot más elevada y cercana al Ein Sof es Kéter, Estamos en Keter cuando volvemos al corazón, y por extensión, volvemos al Uno. Aquí entendemos que somos manifestaciones de lo divino viviendo una experiencia cuyo propósito es el amor propio y la aceptación de que todo tiene unos tiempos y un plan, el cual no estamos hechos para entender. Es la sensación de saber que nunca hemos acabado y aún así disfrutar el camino de nuestra reparación.";