import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { cabalaNom, RecursosIconCabala, cabalaTxt, CabalaIcon, cabalaBg } from "../../../GlobalVariables";
import { cabalaLetra, tikunOlamLetra, orkliLetra, ketherLetra, chokmahLetra, chesedLetra, geburahLetra, tiferetLetra, netzachLetra, yesodLetra, malkhutLetra } from "./LetraCabala";

const detalles: Detalles = { color: cabalaTxt, icon: CabalaIcon, bgColor: cabalaBg };

const basePath = "/aprendizaje/videoLessonPage/" + cabalaNom;

const misDesequilibriosVitales: FloatingButtonConfig = {
  label: "Encontrar mis desequilibrios",
  action: "espacio-auth",
  route: "/espacio/questions/" + cabalaNom,
};

export const modulosCabala: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: RecursosIconCabala,
    floatingButton: misDesequilibriosVitales,
    submodules: [
      {
        id: "cabala0",
        nom: "Recursos a tu disposición",
        link: `/recursos/` + cabalaNom,
        linkAnterior: "",
        linkNext: "",
        descripcion: "Recursos esenciales para acompañar tu aprendizaje.",
        video: "",
        letra: null,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: null,
        floatingButton: misDesequilibriosVitales,
      },
    ],
  },
  {
    title: "1. Los fundamentos",
    icon: CabalaIcon,
    floatingButton: misDesequilibriosVitales,
    submodules: [
      {
        id: "cabala1",
        nom: "1.1 ¿Qué es la Cábala?",
        link: `${basePath}/cabala1`,
        linkAnterior: "",
        linkNext: `${basePath}/cabala2`,
        descripcion: "La Cábala es la sabiduría mística que explica el propósito del alma y la unidad de todo con el Ein Sof.",
        video: "h91IKB8GLh4",
        letra: cabalaLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2",
        nom: "1.2 Tikkun Olam",
        link: `${basePath}/cabala2`,
        linkAnterior: `${basePath}/cabala1`,
        linkNext: `${basePath}/cabala3`,
        descripcion: "Tikkun Olam nos enseña que la reparación del universo comienza con nuestro amor propio y respeto hacia los demás.",
        video: "7QcXrDyqGjI",
        letra: tikunOlamLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala3",
        nom: "1.3 Or & Kli",
        link: `${basePath}/cabala3`,
        linkAnterior: `${basePath}/cabala2`,
        linkNext: `${basePath}/cabala4`,
        descripcion: "Or y Kli representan las energías masculina y femenina que, al unirse, dan forma al Árbol de la Vida y al universo.",
        video: "6ulm1lcYg6c",
        letra: orkliLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
    ],
  },
  {
    title: "2. El Árbol de la Vida",
    icon: CabalaIcon,
    floatingButton: misDesequilibriosVitales,
    submodules: [
      {
        id: "cabala4",
        nom: "2.1 Keter",
        link: `${basePath}/cabala4`,
        linkAnterior: `${basePath}/cabala3`,
        linkNext: `${basePath}/cabala5`,
        descripcion: "Keter representa la conexión con el Uno y la manifestación del amor propio y la aceptación del plan divino.",
        video: "Y3yz43ypGrQ",
        letra: ketherLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala5",
        nom: "2.2 Chokmah, Binah & Da'at",
        link: `${basePath}/cabala5`,
        linkAnterior: `${basePath}/cabala4`,
        linkNext: `${basePath}/cabala6`,
        descripcion: "Chokmah es la sabiduría infinita y Binah la estructura que nos permite vivir coherentemente.",
        video: "IrZ5eZ7QdwA",
        letra: chokmahLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala6",
        nom: "2.3 Chesed",
        link: `${basePath}/cabala6`,
        linkAnterior: `${basePath}/cabala5`,
        linkNext: `${basePath}/cabala7`,
        descripcion: "Chesed es la capacidad de dar con amabilidad y proporcionalidad.",
        video: "yXbpB4AfmRw",
        letra: chesedLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala7",
        nom: "2.4 Gevurah",
        link: `${basePath}/cabala7`,
        linkAnterior: `${basePath}/cabala6`,
        linkNext: `${basePath}/cabala8`,
        descripcion: "Gevurah enseña a recibir de forma consciente para crecer.",
        video: "9gATLqT5qFY",
        letra: geburahLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala8",
        nom: "2.5 Tiferet",
        link: `${basePath}/cabala8`,
        linkAnterior: `${basePath}/cabala7`,
        linkNext: `${basePath}/cabala9`,
        descripcion: "Tiferet es la armonía y la paz interna que nos permite reconocer desequilibrios.",
        video: "a2oykvOoTB0",
        letra: tiferetLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala9",
        nom: "2.6 Netzach & Hod",
        link: `${basePath}/cabala9`,
        linkAnterior: `${basePath}/cabala8`,
        linkNext: `${basePath}/cabala10`,
        descripcion: "Netzach y Hod nos ayudan a gestionar emociones y comunicarlas de manera consciente.",
        video: "PoXe_VzFth8",
        letra: netzachLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala10",
        nom: "2.7 Yesod",
        link: `${basePath}/cabala10`,
        linkAnterior: `${basePath}/cabala9`,
        linkNext: `${basePath}/cabala11`,
        descripcion: "Yesod filtra nuestra percepción del mundo a través del ego, que puede ser un aliado.",
        video: "f1cy0UWBsV8",
        letra: yesodLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala11",
        nom: "2.8 Malkhut",
        link: `${basePath}/cabala11`,
        linkAnterior: `${basePath}/cabala10`,
        linkNext: "",
        descripcion: "Malkhut manifiesta la energía divina en la materia, recordándonos que todo es sagrado.",
        video: "zmBsovd2dKk",
        letra: malkhutLetra,
        cursoId: "cabala-curso-1",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
    ],
  },
];
