import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { cabalaNom, RecursosIconCabala, cabalaTxt, CabalaIcon, cabalaBg } from "../../../GlobalVariables";
import { keter2Letra, chokmah2Letra, binah2Letra, daat2Letra, chesed2Letra, gevurah2Letra, tiferet2Letra, netzach2Letra, hod2Letra, yesod2Letra, malkuth2Letra } from "./LetraCabala2";

const detalles: Detalles = { color: cabalaTxt, icon: CabalaIcon, bgColor: cabalaBg };

const basePath = "/aprendizaje/videoLessonPage/" + cabalaNom;

const misDesequilibriosVitales: FloatingButtonConfig = {
  label: "Encontrar mis desequilibrios",
  action: "espacio-auth",
  route: "/espacio/questions/" + cabalaNom,
};

export const modulosCabala2: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: RecursosIconCabala,
    floatingButton: misDesequilibriosVitales,
    submodules: [
      {
        id: "cabala2-0",
        nom: "Recursos a tu disposición",
        link: `/recursos/` + cabalaNom + "-camino",
        linkAnterior: "",
        linkNext: "",
        descripcion: "Recursos esenciales para acompañar tu aprendizaje.",
        video: "",
        letra: null,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: null,
        floatingButton: misDesequilibriosVitales,
      },
    ],
  },
  {
    title: "1. El árbol de la vida como camino",
    icon: CabalaIcon,
    floatingButton: misDesequilibriosVitales,
    submodules: [
      {
        id: "cabala2-1",
        nom: "1.1 Keter",
        link: `${basePath}/cabala2-1`,
        linkAnterior: "",
        linkNext: `${basePath}/cabala2-2`,
        descripcion: "Keter nos invita a mirar en nuestro interior para descubrir el propósito de nuestra vida y alinear mente y acciones con nuestra esencia divina.",
        video: "4LLo_Gr-NfY",
        letra: keter2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-2",
        nom: "1.2 Chokmah",
        link: `${basePath}/cabala2-2`,
        linkAnterior: `${basePath}/cabala2-1`,
        linkNext: `${basePath}/cabala2-3`,
        descripcion: "Chokmah es la capacidad de ver lo que de verdad está pasando antes de clasificarlo, habitando el presente para recibir lo que la Vida tiene para nosotros.",
        video: "2V4qoHx2sHE",
        letra: chokmah2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-3",
        nom: "1.3 Binah",
        link: `${basePath}/cabala2-3`,
        linkAnterior: `${basePath}/cabala2-2`,
        linkNext: `${basePath}/cabala2-4`,
        descripcion: "Binah baja a tierra la sabiduría de Chokmah, clasificando y analizando las situaciones para aprender de ellas y ampliar nuestra consciencia.",
        video: "AvaSsLLM4oA",
        letra: binah2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-4",
        nom: "1.4 Da'at",
        link: `${basePath}/cabala2-4`,
        linkAnterior: `${basePath}/cabala2-3`,
        linkNext: `${basePath}/cabala2-5`,
        descripcion: "Da'at es el puente dinámico entre Binah y Chokmah que nos permite integrar nuevos patrones y avanzar en nuestra vida.",
        video: "wgeeZgwmwLI",
        letra: daat2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-5",
        nom: "1.5 Chesed",
        link: `${basePath}/cabala2-5`,
        linkAnterior: `${basePath}/cabala2-4`,
        linkNext: `${basePath}/cabala2-6`,
        descripcion: "Chesed nos invita a dar sin esperar nada a cambio, desde la alineación con nuestra esencia y con plena consciencia del para qué damos.",
        video: "vvgEtzlP6BE",
        letra: chesed2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-6",
        nom: "1.6 Gevurah",
        link: `${basePath}/cabala2-6`,
        linkAnterior: `${basePath}/cabala2-5`,
        linkNext: `${basePath}/cabala2-7`,
        descripcion: "Gevurah es la energía de los límites y el discernimiento que nos devuelve al camino de nuestra esencia con firmeza y sin culpa.",
        video: "SnMDLfSpWno",
        letra: gevurah2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-7",
        nom: "1.7 Tiferet",
        link: `${basePath}/cabala2-7`,
        linkAnterior: `${basePath}/cabala2-6`,
        linkNext: `${basePath}/cabala2-8`,
        descripcion: "Tiferet es el corazón que armoniza expansión y restricción, permitiéndonos actuar desde la verdad y la conexión más directa con nuestra esencia.",
        video: "Haq7pykCNaI",
        letra: tiferet2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-8",
        nom: "1.8 Netzach",
        link: `${basePath}/cabala2-8`,
        linkAnterior: `${basePath}/cabala2-7`,
        linkNext: `${basePath}/cabala2-9`,
        descripcion: "Netzach es la energía de la persistencia y la determinación que nos invita a mantenernos firmes en el camino de nuestra verdad.",
        video: "",
        letra: netzach2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-9",
        nom: "1.9 Hod",
        link: `${basePath}/cabala2-9`,
        linkAnterior: `${basePath}/cabala2-8`,
        linkNext: `${basePath}/cabala2-10`,
        descripcion: "Hod es la energía de la comunicación y la humildad, que nos enseña a hablar desde nuestra verdad con paciencia y respeto.",
        video: "eVhc6kTrqFo",
        letra: hod2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-10",
        nom: "1.10 Yesod",
        link: `${basePath}/cabala2-10`,
        linkAnterior: `${basePath}/cabala2-9`,
        linkNext: `${basePath}/cabala2-11`,
        descripcion: "Yesod nos invita a transformar nuestra autopercepción para que sea coherente con nuestra esencia, más allá de los patrones heredados.",
        video: "6yHSKr1G-Eo",
        letra: yesod2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
      {
        id: "cabala2-11",
        nom: "1.11 Malkuth",
        link: `${basePath}/cabala2-11`,
        linkAnterior: `${basePath}/cabala2-10`,
        linkNext: "",
        descripcion: "Malkhut es el gran espejo: la manifestación tangible de lo que verdaderamente somos en cada momento.",
        video: "jqoFXn8rKmE",
        letra: malkuth2Letra,
        cursoId: "cabala-curso-2",
        detalles: detalles,
        icon: CabalaIcon,
        floatingButton: misDesequilibriosVitales,
      },
    ],
  },
];
