import type { Detalles, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { tcmTxt, TCMIcon, tcmBg, tcmNomLink, CincoElementosIcon, RecursosIconTCM, MouthIcon } from "../../../GlobalVariables";
import { letratcm1, letratcm10, letratcm11, letratcm12, letratcm13, letratcm14, letratcm15, letratcm16, letratcm17, letratcm18, letratcm19, letratcm2, letratcm20, letratcm21, letratcm22, letratcm23, letratcm24, letratcm3, letratcm4, letratcm5, letratcm6, letratcm7, letratcm8, letratcm9 } from "./LetraTCM";

const detalles: Detalles = { color: tcmTxt, icon: TCMIcon, bgColor: tcmBg };

const basePath = "/aprendizaje/videoLessonPage/" + tcmNomLink;
const basePathCurso2 = "/aprendizaje/videoLessonPage/" + tcmNomLink;

export const modulostcmFundamentos: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: RecursosIconTCM,
    submodules: [
      { 
        id:"tcm0",
        nom: "Recursos a tu disposición",
        link:`/recursos/` + tcmNomLink,
        linkAnterior:"",
        linkNext:"",
        descripcion:"Recursos esenciales para acompañar tu aprendizaje y profundizar en la Medicina Tradicional China.",
        video:"n0Cqpw_A3VU",
        letra: null,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon:null
      },
    ],
  },

  {
    title: "1. Los fundamentos",
    icon: TCMIcon,
    submodules: [
      { 
        id:"tcm1",
        nom: "1.1 El taoísmo",
        link:`${basePath}/tcm1`,
        linkAnterior:"",
        linkNext:`${basePath}/tcm2`,
        descripcion:"Eres parte del universo.",
        video:"pHbFMoTEftg",
        letra: letratcm1,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: TCMIcon
      },
      { 
        id:"tcm2",
        nom: "1.2 El Yin y el Yang",
        link:`${basePath}/tcm2`,
        linkAnterior:`${basePath}/tcm1`,
        linkNext:`${basePath}/tcm3`,
        descripcion:"El verdadero equilibrio es la armonía entre fuerzas que se complementan.",
        video:"OU5huhK-FxU",
        letra: letratcm2,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: TCMIcon,
      },
    ],
  },
  {
    title: "2. Los Cinco Elementos 五行",
    icon: CincoElementosIcon,
    submodules: [
      { 
        id:"tcm3",
        nom: "2.1 Introducción a los Cinco Elementos 五行",
        link:`${basePath}/tcm3`,
        linkAnterior:`${basePath}/tcm2`,
        linkNext:`${basePath}/tcm4`,
        descripcion:"El ser humano es una extensión de la naturaleza.",
        video:"bL9v3VBJc8I",
        letra: letratcm3,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      { 
        id:"tcm4",
        nom: "2.2 La Madera 木",
        link:`${basePath}/tcm4`,
        linkAnterior:`${basePath}/tcm3`,
        linkNext:`${basePath}/tcm5`,
        descripcion:"Sé como el bambú: firme en tus raíces, flexible en tus tormentas.",
        video:"1gMBVFKMAXY",
        letra: letratcm4,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      { 
        id:"tcm5",
        nom: "2.3 El Fuego 火",
        link:`${basePath}/tcm5`,
        linkAnterior:`${basePath}/tcm4`,
        linkNext:`${basePath}/tcm6`,
        descripcion:"El fuego es la semilla del Amor, que siempre debe de empezar en uno mismo.",
        video:"oqmoovl3Yio",
        letra: letratcm5,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      { 
        id:"tcm6",
        nom: "2.4 La Tierra 土",
        link:`${basePath}/tcm6`,
        linkAnterior:`${basePath}/tcm5`,
        linkNext:`${basePath}/tcm7`,
        descripcion:"Cultivar la tierra interior es aprender a confiar en la Vida.",
        video:"tXqEjnQPgwc",
        letra: letratcm6,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      { 
        id:"tcm7",
        nom: "2.5 El Metal 金",
        link:`${basePath}/tcm7`,
        linkAnterior:`${basePath}/tcm6`,
        linkNext:`${basePath}/tcm8`,
        descripcion:"Saber soltar es la muestra más profunda de Amor.",
        video:"BzgxPMYOqrA",
        letra: letratcm7,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      { 
        id:"tcm8",
        nom: "2.6 El Agua 水",
        link:`${basePath}/tcm8`,
        linkAnterior:`${basePath}/tcm7`,
        linkNext:`${basePath}/tcm9`,
        descripcion:"En el silencio del agua habita nuestra verdadera esencia.",
        video:"o2ot4bFWMoQ",
        letra: letratcm8,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: CincoElementosIcon
      },
    ],
  },
  {
    title: "3. El diagnóstico de la lengua",
    icon: MouthIcon,
    submodules: [
      { 
        id:"tcm9",
        nom: "3.1 La lengua",
        link:`${basePath}/tcm9`,
        linkAnterior:`${basePath}/tcm8`,
        linkNext:`${basePath}/tcm10`,
        descripcion:"La lengua habla en silencio sobre el estado de tu equilibrio.",
        video:"XiG2Ll57It4",
        letra: letratcm21,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: MouthIcon
      },
      { 
        id:"tcm10",
        nom: "3.2 El color de la lengua",
        link:`${basePath}/tcm10`,
        linkAnterior:`${basePath}/tcm9`,
        linkNext:`${basePath}/tcm11`,
        descripcion:"El cuerpo siempre refleja lo que necesita sanar.",
        video:"EC1-aTmn2aE",
        letra: letratcm22,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: MouthIcon
      },
      { 
        id:"tcm11",
        nom: "3.3 La forma de la lengua",
        link:`${basePath}/tcm11`,
        linkAnterior:`${basePath}/tcm10`,
        linkNext:`${basePath}/tcm12`,
        descripcion:"La forma de tu lengua es un mapa sutil de tu energía interna.",
        video:"F8AiR97m0Qk",
        letra: letratcm23,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: MouthIcon
      },
      { 
        id:"tcm12",
        nom: "3.4 La capa de la lengua",
        link:`${basePath}/tcm12`,
        linkAnterior:`${basePath}/tcm11`,
        linkNext:"",
        descripcion:"La capa de la lengua revela tu armonía interior.",
        video:"AhobpjkmH0I",
        letra: letratcm24,
        cursoId: "tcm-curso-1",
        detalles: detalles,
        icon: MouthIcon
      },
    ],
  },
];

export const modulostcmCincoElementos: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: RecursosIconTCM,
    submodules: [
      {
        id: "ce0",
        nom: "Recursos a tu disposición",
        link: `/recursos/` + tcmNomLink + "?curso=cincoelementos",
        linkAnterior: "",
        linkNext: "",
        descripcion: "Recursos esenciales para acompañar tu aprendizaje y profundizar en la Medicina Tradicional China.",
        video: "n0Cqpw_A3VU",
        letra: null,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: null
      },
    ],
  },
  {
    title: "1. Los Cinco Elementos 五行",
    icon: CincoElementosIcon,
    submodules: [
      {
        id: "tcmce1",
        nom: "1.1 Introducción a los Cinco Elementos 五行",
        link: `${basePathCurso2}/tcmce1`,
        linkAnterior: "",
        linkNext: `${basePathCurso2}/tcmce2`,
        descripcion: "El ser humano es una extensión de la naturaleza.",
        video: "bL9v3VBJc8I",
        letra: letratcm3,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce2",
        nom: "1.2 La Madera 木",
        link: `${basePathCurso2}/tcmce2`,
        linkAnterior: `${basePathCurso2}/tcmce1`,
        linkNext: `${basePathCurso2}/tcmce3`,
        descripcion: "Sé como el bambú: firme en tus raíces, flexible en tus tormentas.",
        video: "1gMBVFKMAXY",
        letra: letratcm4,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce3",
        nom: "1.3 El Fuego 火",
        link: `${basePathCurso2}/tcmce3`,
        linkAnterior: `${basePathCurso2}/tcmce2`,
        linkNext: `${basePathCurso2}/tcmce4`,
        descripcion: "El fuego es la semilla del Amor, que siempre debe de empezar en uno mismo.",
        video: "oqmoovl3Yio",
        letra: letratcm5,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce4",
        nom: "1.4 La Tierra 土",
        link: `${basePathCurso2}/tcmce4`,
        linkAnterior: `${basePathCurso2}/tcmce3`,
        linkNext: `${basePathCurso2}/tcmce5`,
        descripcion: "Cultivar la tierra interior es aprender a confiar en la Vida.",
        video: "tXqEjnQPgwc",
        letra: letratcm6,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce5",
        nom: "1.5 El Metal 金",
        link: `${basePathCurso2}/tcmce5`,
        linkAnterior: `${basePathCurso2}/tcmce4`,
        linkNext: `${basePathCurso2}/tcmce6`,
        descripcion: "Saber soltar es la muestra más profunda de Amor.",
        video: "BzgxPMYOqrA",
        letra: letratcm7,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce6",
        nom: "1.6 El Agua 水",
        link: `${basePathCurso2}/tcmce6`,
        linkAnterior: `${basePathCurso2}/tcmce5`,
        linkNext: `${basePathCurso2}/tcmce7`,
        descripcion: "En el silencio del agua habita nuestra verdadera esencia.",
        video: "o2ot4bFWMoQ",
        letra: letratcm8,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
    ],
  },
  {
    title: "2. El Ciclo Generador 相生",
    icon: CincoElementosIcon,
    submodules: [
      {
        id: "tcmce7",
        nom: "2.1 Introducción al Ciclo Generador 相生",
        link: `${basePathCurso2}/tcmce7`,
        linkAnterior: `${basePathCurso2}/tcmce6`,
        linkNext: `${basePathCurso2}/tcmce8`,
        descripcion: "Comprender los ciclos de la naturaleza, es comprender nuestros ciclos.",
        video: "OAYf3uHIJLY",
        letra: letratcm9,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce8",
        nom: "2.2 El Fuego genera la Tierra",
        link: `${basePathCurso2}/tcmce8`,
        linkAnterior: `${basePathCurso2}/tcmce7`,
        linkNext: `${basePathCurso2}/tcmce9`,
        descripcion: "Cuando el corazón está en equilibrio, todo el cuerpo respira en armonía.",
        video: "ufDdxo0Ffxw",
        letra: letratcm10,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce9",
        nom: "2.3 La Tierra genera el Metal",
        link: `${basePathCurso2}/tcmce9`,
        linkAnterior: `${basePathCurso2}/tcmce8`,
        linkNext: `${basePathCurso2}/tcmce10`,
        descripcion: "Nutrirte bien es el primer paso para vivir en armonía y equilibrio.",
        video: "n0Cqpw_A3VU",
        letra: letratcm11,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce10",
        nom: "2.4 El Metal genera el Agua",
        link: `${basePathCurso2}/tcmce10`,
        linkAnterior: `${basePathCurso2}/tcmce9`,
        linkNext: `${basePathCurso2}/tcmce11`,
        descripcion: "La respiración consciente es el puente entre el cuerpo y el universo.",
        video: "AjwK8HIYBpU",
        letra: letratcm12,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce11",
        nom: "2.5 El Agua genera la Madera",
        link: `${basePathCurso2}/tcmce11`,
        linkAnterior: `${basePathCurso2}/tcmce10`,
        linkNext: `${basePathCurso2}/tcmce12`,
        descripcion: "Cuando te escuchas, permites que todo en ti fluya sin resistencia.",
        video: "FD4FYd6utzM",
        letra: letratcm13,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce12",
        nom: "2.6 La Madera genera el Fuego",
        link: `${basePathCurso2}/tcmce12`,
        linkAnterior: `${basePathCurso2}/tcmce11`,
        linkNext: `${basePathCurso2}/tcmce13`,
        descripcion: "Un corazón equilibrado protege tu cuerpo y permite la manifestación de tu verdadero yo.",
        video: "a8220pAxffc",
        letra: letratcm14,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
    ],
  },
  {
    title: "3. El Ciclo Controlador 相克",
    icon: CincoElementosIcon,
    submodules: [
      {
        id: "tcmce13",
        nom: "3.1 Introducción al Ciclo Controlador 相克",
        link: `${basePathCurso2}/tcmce13`,
        linkAnterior: `${basePathCurso2}/tcmce12`,
        linkNext: `${basePathCurso2}/tcmce14`,
        descripcion: "Respetar tus ciclos y tu cuerpo es el camino hacia una Vida llena de Amor.",
        video: "wC2Z3RxbK9E",
        letra: letratcm15,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce14",
        nom: "3.2 La Madera controla la Tierra",
        link: `${basePathCurso2}/tcmce14`,
        linkAnterior: `${basePathCurso2}/tcmce13`,
        linkNext: `${basePathCurso2}/tcmce15`,
        descripcion: "La ira no resuelta se transforma en desequilibrio; la conciencia la transforma en crecimiento.",
        video: "aWJBZDaW8bM",
        letra: letratcm16,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce15",
        nom: "3.3 La Tierra controla el Agua",
        link: `${basePathCurso2}/tcmce15`,
        linkAnterior: `${basePathCurso2}/tcmce14`,
        linkNext: `${basePathCurso2}/tcmce16`,
        descripcion: "La pre-ocupación debilita; la calma y la gestión emocional te hace más fuerte.",
        video: "U8iyzmfOWu0",
        letra: letratcm17,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce16",
        nom: "3.4 El Agua controla el Fuego",
        link: `${basePathCurso2}/tcmce16`,
        linkAnterior: `${basePathCurso2}/tcmce15`,
        linkNext: `${basePathCurso2}/tcmce17`,
        descripcion: "El miedo se disuelve cuando encuentras te encuentras.",
        video: "s-b1j0Snz1w",
        letra: letratcm18,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce17",
        nom: "3.5 El Fuego controla el Metal",
        link: `${basePathCurso2}/tcmce17`,
        linkAnterior: `${basePathCurso2}/tcmce16`,
        linkNext: `${basePathCurso2}/tcmce18`,
        descripcion: "Respirar con calma es regalarle claridad a tu corazón.",
        video: "6XUZromIhBE",
        letra: letratcm19,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
      {
        id: "tcmce18",
        nom: "3.6 El Metal controla la Madera",
        link: `${basePathCurso2}/tcmce18`,
        linkAnterior: `${basePathCurso2}/tcmce17`,
        linkNext: "",
        descripcion: "Cada respiración consciente es un abrazo a nuestro interior y un agradecimiento a la Vida.",
        video: "PNqzu2Y2a9M",
        letra: letratcm20,
        cursoId: "tcm-curso-2",
        detalles: detalles,
        icon: CincoElementosIcon
      },
    ],
  },
];
