import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { NutricionIcon, nutricionBg, nutricionNomLink, nutricionTxt } from "../../../GlobalVariables";
import { MicrobiotaIconMicro, MicrobiotaIconEje } from "./MicrobiotaIcons";

const detalles: Detalles = { color: nutricionTxt, icon: NutricionIcon, bgColor: nutricionBg };

const basePath = "/aprendizaje/videoLessonPage/" + nutricionNomLink;

const respetarme: FloatingButtonConfig = {
  label: "Respetarme",
  action: "espacio-auth",
  route: "/espacio/questions/" + nutricionNomLink,
};

export const modulosNutricion: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-rec",
        nom: "Recursos a tu disposición",
        link: `/recursos/` + nutricionNomLink,
        linkAnterior: "",
        linkNext: "",
        descripcion: "",
        video: "",
        letra: null,
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: null,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "1. Respétate",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-r1",
        nom: "Somos lo que comemos",
        link: `${basePath}/nut-r1`,
        linkAnterior: "",
        linkNext: `${basePath}/nut-m1`,
        descripcion: "Descubre por qué los alimentos que elegimos cada día no solo construyen nuestro cuerpo, sino también nuestra claridad mental y nuestro estado emocional.",
        video: "0QBJyFRGgnI",
        letra: "Aunque estemos tranquilos o descansando, nuestras células están en continua actividad. Lo que comemos es transformado y usado para permitir que podamos seguir con esta experiencia llamada Vida. Teniendo eso en cuenta, ¿por qué no darles lo que es mejor para ellas? Pero, ¿cómo sabemos lo que es mejor para ellas? A través de estos módulos entenderás por qué unos alimentos son mejores que otros y qué efecto tienen en ti.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "2. Macronutrientes",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-m1",
        nom: "Proteínas",
        link: `${basePath}/nut-m1`,
        linkAnterior: `${basePath}/nut-r1`,
        linkNext: `${basePath}/nut-m2`,
        descripcion: "Nuestras células usan los amino ácidos de las proteínas para sus diversas funciones.",
        video: "BU2DpV82oqM",
        letra: "Las proteínas son de vital importancia, cuando nuestra dieta carece de ellas nuestro cuerpo decae y bastante rápido, nos sentimos lentos, pesados y se nos olvidan las cosas. Entendamos por qué ocurre esto. Imaginemos a las proteínas como collares de perlas. Cada perla es distinta y única. Cada célula usa las perlas de la proteína para hacer sus propios collares. Estos collares son las enzimas. Las enzimas son las que mantienen la correcta regulación de la célula. Por eso, para respetar a tu cuerpo y a todas las células que te forman, que trabajan por y para ti, asegúrate de tomar suficiente proteína.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-m2",
        nom: "Carbohidratos",
        link: `${basePath}/nut-m2`,
        linkAnterior: `${basePath}/nut-m1`,
        linkNext: `${basePath}/nut-m3`,
        descripcion: "La fibra cambia nuestra digestión y hace que las células tengan una disponibilidad eficiente de glucosa.",
        video: "n2cRzyINYDE",
        letra: "Las células y por extensión, nosotros, necesitamos glucosa. Por el bien de todos nuestros órganos y de nuestras neuronas, queremos que esa glucosa se incorpore en nosotros poco a poco, para no sobrecargarnos y hacernos daño. Entonces, ¿cómo podemos absorber la glucosa más lentamente? Muy sencillo, eligiendo alimentos con fibra, esta es la razón por la que las verduras, frutas y productos integrales son saludables. Si elegimos bollería o harinas blancas, esto nos sobrecargará, porque no podemos usar toda esa glucosa a la vez. Esto deteriorará a nuestras neuronas y obligará a que la glucosa que no ha podido ser usada se almacene en forma de grasa.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-m3",
        nom: "Grasas",
        link: `${basePath}/nut-m3`,
        linkAnterior: `${basePath}/nut-m2`,
        linkNext: `${basePath}/nut-mi1`,
        descripcion: "Nuestras células se reconstruyen con grasas, por eso elige grasas insaturadas para que sean más flexibles y eficientes.",
        video: "CuoVBfewgiQ",
        letra: "Los tipos de grasas que existen son un arma de doble filo porque pueden protegernos o causar un deterioro temprano. Las células tienen una membrana que las protege y les permite comunicarse. Las células usan las grasas de nuestra dieta para reconstruir esta membrana. Si elegimos grasas insaturadas, como el aguacate, el aceite de oliva, los frutos secos, nuestras células serán más eficientes y estarán mejor protegidas. En cambio, si se reconstruyen con grasas trans o saturadas, serán más lentas, torpes e incluso nuestro cuerpo las puede percibir como enemigos.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "3. Micronutrientes",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-mi1",
        nom: "Vitaminas",
        link: `${basePath}/nut-mi1`,
        linkAnterior: `${basePath}/nut-m3`,
        linkNext: `${basePath}/nut-mi2`,
        descripcion: "Las vitaminas activan a las células. Sin vitaminas no puede haber vida.",
        video: "djMQ-EIifZc",
        letra: "Siempre nos han dicho que las vitaminas son necesarias, pero nadie nos ha explicado por qué. Aquí por fin lo entenderás. Recordemos que las células crean enzimas usando las proteínas de nuestra dieta, pero estas enzimas no están activadas, necesitan vitaminas para activarse, sin vitaminas esas enzimas no pueden hacer su función y por lo tanto, no podemos reconstruirnos ni mejorarnos. Sin vitaminas nos deterioramos, envejecemos y perdemos funciones que creíamos estables.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-mi2",
        nom: "Minerales",
        link: `${basePath}/nut-mi2`,
        linkAnterior: `${basePath}/nut-mi1`,
        linkNext: "",
        descripcion: "Los minerales son las herramientas de tus células. Sin minerales no hay vitalidad.",
        video: "7KN0sqwUO0E",
        letra: "Los minerales son muy importantes también, porque son las herramientas que usan las enzimas. Sin minerales, a pesar de que la enzima esté activa, no puede trabajar, por lo que nos deterioramos y nos sentimos más cansados y lentos. En conclusión, la enzima usa las vitaminas para activarse y los minerales para trabajar.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
];

export const modulosMicrobiota: ModuloContenido[] = [
  {
    title: "1. La microbiota",
    icon: MicrobiotaIconMicro,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-1",
        nom: "¿Qué es la microbiota?",
        link: `${basePath}/mic-1`,
        linkAnterior: "",
        linkNext: `${basePath}/mic-2`,
        descripcion: "Descubre el ecosistema invisible que vive en ti, cómo se distribuye por tu cuerpo y por qué su equilibrio determina tu salud.",
        video: "zZCPgFJzUDo",
        letra: "Tu cuerpo tiene más bacterias que células humanas y a este ecosistema invisible se le llama microbiota. Tenemos distintas microbiotas por todo el cuerpo: en la piel, en el intestino y en la boca. Cada una está formada por diferentes bacterias. Muchas de ellas son beneficiosas y esenciales, pero otras pueden ser perjudiciales si se rompe el equilibrio.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMicro,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "2. Probióticos y prebióticos",
    icon: MicrobiotaIconMicro,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-2",
        nom: "Probióticos y prebióticos",
        link: `${basePath}/mic-2`,
        linkAnterior: `${basePath}/mic-1`,
        linkNext: `${basePath}/mic-3`,
        descripcion: "Entiende la relación entre los probióticos y los prebióticos, y por qué de su digestión nacen las cadenas cortas de ácidos grasos.",
        video: "cmEGCqAqSaE",
        letra: "¿Sabías qué son los probióticos? Son las bacterias vivas de nuestro interior. Estas necesitan alimentarse y lo hacen a través de los prebióticos. Es decir, los probióticos comen prebióticos. Cuando son digeridos, se generan cadenas cortas de ácidos grasos.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMicro,
        floatingButton: respetarme,
      },
      {
        id: "mic-3",
        nom: "Las cadenas cortas de ácidos grasos",
        link: `${basePath}/mic-3`,
        linkAnterior: `${basePath}/mic-2`,
        linkNext: `${basePath}/mic-4`,
        descripcion: "Conoce los AGCC, los metabolitos que produce tu microbiota y su profundo impacto en tu cuerpo y tu cerebro.",
        video: "I43ZhU8TkFE",
        letra: "¿Sabías por qué los probióticos son buenos? Cuando los probióticos comen prebióticos, se crean moléculas que incrementan nuestro bienestar. Son reguladores del hígado, de la glucosa, del colesterol, además de fortalecer a nuestro intestino, previniendo el cáncer de colon. Estos metabolitos, llamados cadenas cortas de ácidos grasos, son capaces de llegar hasta el cerebro, expandiendo así nuestro bienestar.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMicro,
        floatingButton: respetarme,
      },
      {
        id: "mic-4",
        nom: "¿Dónde se encuentran los probióticos?",
        link: `${basePath}/mic-4`,
        linkAnterior: `${basePath}/mic-3`,
        linkNext: `${basePath}/mic-5`,
        descripcion: "Aprende en qué alimentos encontrar probióticos y prebióticos y por qué la fibra es tan importante para tu microbiota.",
        video: "md6jovwm_T4",
        letra: "¿Sabes dónde viven los probióticos? Los probióticos están en alimentos que contienen microorganismos vivos, como los alimentos fermentados: el kimchi, el kéfir, el chucrut y el yogur. En cambio, los prebióticos, la comida de los probióticos, son tipos de fibra que se encuentran en frutas, verduras y legumbres. Por eso tener una dieta rica en fibra es tan importante.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMicro,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "3. Eje intestino-cerebro",
    icon: MicrobiotaIconEje,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-5",
        nom: "El segundo cerebro",
        link: `${basePath}/mic-5`,
        linkAnterior: `${basePath}/mic-4`,
        linkNext: "",
        descripcion: "Descubre cómo las bacterias de tu intestino producen neurotransmisores que cambian tu estado mental y liberan la serotonina de la felicidad.",
        video: "KXc56eqHmpM",
        letra: "¿Por qué dicen que el intestino es nuestro segundo cerebro? Se ha demostrado que las bacterias de nuestra microbiota pueden segregar moléculas que son idénticas a nuestros neurotransmisores, por lo que son capaces de cambiar nuestro estado energético, mental y físico. Además, las bacterias de nuestra microbiota pueden estimular a las células del intestino, haciendo que liberen serotonina, el neurotransmisor de la felicidad.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconEje,
        floatingButton: respetarme,
      },
    ],
  },
];