import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { IntestinoIcon, NutricionIcon, nutricionBg, nutricionNomLink, nutricionTxt } from "../../../GlobalVariables";
import { MicrobiotaIconMicro, MicrobiotaIconEje, MicrobiotaIconMujer, MicrobiotaIconDecisiones } from "./MicrobiotaIcons";

const detalles: Detalles = { color: nutricionTxt, icon: NutricionIcon, bgColor: nutricionBg };

const basePath = "/aprendizaje/videoLessonPage/" + nutricionNomLink;

const respetarme: FloatingButtonConfig = {
  label: "Respetarme",
  action: "espacio-auth",
  route: "/espacio/questions/" + nutricionNomLink,
};

export const modulosNutricion: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-rec",
        nom: "Recursos a tu disposición",
        link: `/recursos/` + nutricionNomLink,
        linkAnterior: "",
        linkNext: "",
        descripcion: "",
        video: "",
        letra: null,
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: null,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "1. Respétate",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-r1",
        nom: "Somos lo que comemos",
        link: `${basePath}/nut-r1`,
        linkAnterior: "",
        linkNext: `${basePath}/nut-m1`,
        descripcion: "Descubre por qué los alimentos que elegimos cada día no solo construyen nuestro cuerpo, sino también nuestra claridad mental y nuestro estado emocional.",
        video: "0QBJyFRGgnI",
        letra: "Aunque estemos tranquilos o descansando, nuestras células están en continua actividad. Lo que comemos es transformado y usado para permitir que podamos seguir con esta experiencia llamada Vida. Teniendo eso en cuenta, ¿por qué no darles lo que es mejor para ellas? Pero, ¿cómo sabemos lo que es mejor para ellas? A través de estos módulos entenderás por qué unos alimentos son mejores que otros y qué efecto tienen en ti.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "2. Macronutrientes",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-m1",
        nom: "Proteínas",
        link: `${basePath}/nut-m1`,
        linkAnterior: `${basePath}/nut-r1`,
        linkNext: `${basePath}/nut-m2`,
        descripcion: "Nuestras células usan los amino ácidos de las proteínas para sus diversas funciones.",
        video: "BU2DpV82oqM",
        letra: "Las proteínas son de vital importancia, cuando nuestra dieta carece de ellas nuestro cuerpo decae y bastante rápido, nos sentimos lentos, pesados y se nos olvidan las cosas. Entendamos por qué ocurre esto. Imaginemos a las proteínas como collares de perlas. Cada perla es distinta y única. Cada célula usa las perlas de la proteína para hacer sus propios collares. Estos collares son las enzimas. Las enzimas son las que mantienen la correcta regulación de la célula. Por eso, para respetar a tu cuerpo y a todas las células que te forman, que trabajan por y para ti, asegúrate de tomar suficiente proteína.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-m2",
        nom: "Carbohidratos",
        link: `${basePath}/nut-m2`,
        linkAnterior: `${basePath}/nut-m1`,
        linkNext: `${basePath}/nut-m3`,
        descripcion: "La fibra cambia nuestra digestión y hace que las células tengan una disponibilidad eficiente de glucosa.",
        video: "n2cRzyINYDE",
        letra: "Las células y por extensión, nosotros, necesitamos glucosa. Por el bien de todos nuestros órganos y de nuestras neuronas, queremos que esa glucosa se incorpore en nosotros poco a poco, para no sobrecargarnos y hacernos daño. Entonces, ¿cómo podemos absorber la glucosa más lentamente? Muy sencillo, eligiendo alimentos con fibra, esta es la razón por la que las verduras, frutas y productos integrales son saludables. Si elegimos bollería o harinas blancas, esto nos sobrecargará, porque no podemos usar toda esa glucosa a la vez. Esto deteriorará a nuestras neuronas y obligará a que la glucosa que no ha podido ser usada se almacene en forma de grasa.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-m3",
        nom: "Grasas",
        link: `${basePath}/nut-m3`,
        linkAnterior: `${basePath}/nut-m2`,
        linkNext: `${basePath}/nut-mi1`,
        descripcion: "Nuestras células se reconstruyen con grasas, por eso elige grasas insaturadas para que sean más flexibles y eficientes.",
        video: "CuoVBfewgiQ",
        letra: "Los tipos de grasas que existen son un arma de doble filo porque pueden protegernos o causar un deterioro temprano. Las células tienen una membrana que las protege y les permite comunicarse. Las células usan las grasas de nuestra dieta para reconstruir esta membrana. Si elegimos grasas insaturadas, como el aguacate, el aceite de oliva, los frutos secos, nuestras células serán más eficientes y estarán mejor protegidas. En cambio, si se reconstruyen con grasas trans o saturadas, serán más lentas, torpes e incluso nuestro cuerpo las puede percibir como enemigos.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "3. Micronutrientes",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-mi1",
        nom: "Vitaminas",
        link: `${basePath}/nut-mi1`,
        linkAnterior: `${basePath}/nut-m3`,
        linkNext: `${basePath}/nut-mi2`,
        descripcion: "Las vitaminas activan a las células. Sin vitaminas no puede haber vida.",
        video: "djMQ-EIifZc",
        letra: "Siempre nos han dicho que las vitaminas son necesarias, pero nadie nos ha explicado por qué. Aquí por fin lo entenderás. Recordemos que las células crean enzimas usando las proteínas de nuestra dieta, pero estas enzimas no están activadas, necesitan vitaminas para activarse, sin vitaminas esas enzimas no pueden hacer su función y por lo tanto, no podemos reconstruirnos ni mejorarnos. Sin vitaminas nos deterioramos, envejecemos y perdemos funciones que creíamos estables.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-mi2",
        nom: "Minerales",
        link: `${basePath}/nut-mi2`,
        linkAnterior: `${basePath}/nut-mi1`,
        linkNext: "",
        descripcion: "Los minerales son las herramientas de tus células. Sin minerales no hay vitalidad.",
        video: "7KN0sqwUO0E",
        letra: "Los minerales son muy importantes también, porque son las herramientas que usan las enzimas. Sin minerales, a pesar de que la enzima esté activa, no puede trabajar, por lo que nos deterioramos y nos sentimos más cansados y lentos. En conclusión, la enzima usa las vitaminas para activarse y los minerales para trabajar.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
];

export const modulosMicrobiota: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-rec",
        nom: "Recursos a tu disposición",
        link: `/recursos/microbiota`,
        linkAnterior: "",
        linkNext: "",
        descripcion: "",
        video: "",
        letra: null,
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: null,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "1. La microbiota",
    icon: MicrobiotaIconMicro,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-1",
        nom: "Qué es la microbiota",
        link: `${basePath}/mic-1`,
        linkAnterior: "",
        linkNext: `${basePath}/mic-2`,
        descripcion: "Descubre el ecosistema invisible que vive en ti y cómo influye en tu salud, tus emociones y tu forma de vivir.",
        video: "l9md_hWKrSc",
        letra: "Tu cuerpo tiene más bacterias que células humanas. A este ecosistema invisible se le llama microbiota. No tenemos solo una: tenemos distintas microbiotas distribuidas por el cuerpo, como en la piel, el intestino y la boca. Cada una está formada por diferentes especies de microorganismos, que a su vez, dependen de nuestros hábitos, de nuestra dieta e incluso de nuestras emociones.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMicro,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "2. Probióticos y prebióticos",
    icon: MicrobiotaIconMicro,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-2",
        nom: "Probióticos y prebióticos",
        link: `${basePath}/mic-2`,
        linkAnterior: `${basePath}/mic-1`,
        linkNext: `${basePath}/mic-3`,
        descripcion: "Entiende la relación entre los probióticos y los prebióticos.",       video: "enkevPOa7Qc",
        letra: "Los probióticos es el nombre que reciben las bacterias vivas de nuestro interior, estas necesitan alimentarse, y lo hacen a través de los prebióticos. Es decir, los probióticos comen prebióticos y cuando estos son digeridos, se generan cadenas cortas de ácidos grasos, o para resumir short chain fatty acids. Estas sustancias son brutalmente buenas para nuestro bienestar y funcionamiento.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMicro,
        floatingButton: respetarme,
      },
      {
        id: "mic-3",
        nom: "Las cadenas cortas de ácidos grasos",
        link: `${basePath}/mic-3`,
        linkAnterior: `${basePath}/mic-2`,
        linkNext: `${basePath}/mic-4`,
        descripcion: "Conoce los AGCC, los metabolitos que produce tu microbiota y su profundo impacto en tu cuerpo y tu cerebro.",
        video: "HSA1FFKDwjc",
        letra: "Cuando los probióticos comen prebióticos, segregan cadenas cortas de ácidos grasos, como el acetato, propionato y butirato. Estos son profundamente transformadores para nuestro cuerpo. Son reguladores del hígado, de la glucosa, del colesterol, además, fortalecen a nuestro intestino, permitiendo que las células tengan un ciclo de vida completo, previniendo así el cáncer de colon. Además, estos metabolitos llegan hasta el cerebro, fortaleciéndolo y expandiendo el bienestar.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMicro,
        floatingButton: respetarme,
      },
      {
        id: "mic-4",
        nom: "¿Dónde se encuentran los probióticos?",
        link: `${basePath}/mic-4`,
        linkAnterior: `${basePath}/mic-3`,
        linkNext: `${basePath}/mic-5`,
        descripcion: "Aprende en qué alimentos encontrar probióticos y prebióticos y por qué la fibra es tan importante para tu microbiota.",
        video: "3p5UY3mE1B8",
        letra: "Los probióticos están en alimentos que contienen microorganismos vivos, como los alimentos fermentados. Por ejemplo: yogur, kéfir, chucrut o kimchi. En cambio, los prebióticos, la comida de los probióticos, son tipos de fibra que se encuentran en alimentos como frutas, verduras, legumbres y cereales integrales. Por esto, tener una dieta rica en fibra es tan importante, sin fibra los probióticos no podrán sobrevivir, porque no tienen lo que necesitan.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMicro,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "3. El intestino",
    icon: IntestinoIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-5",
        nom: "¿Dónde vive la microbiota?",
        link: `${basePath}/mic-5`,
        linkAnterior: `${basePath}/mic-4`,
        linkNext: `${basePath}/mic-6`,
        descripcion: "Explora las tres capas del intestino grueso y cómo protegerlas para mantener tu microbiota fuerte y equilibrada.",
        video: "_wLLcjHDDc4",
        letra: "Nuestra microbiota más importante vive en el intestino grueso que está formado por 3 capas. La primera capa está hecha con mucosa, es muy importante porque sostiene a nuestra microbiota y protege a las células que forman el intestino grueso. La segunda capa está formada por células que se juntan a través de pequeñas conjunciones que solo se abren cuando hay nutrientes, por ejemplo, para permitir el paso de glucosa. El problema está en que dependiendo de los alimentos que comamos, nuestra barrera puede inflamarse, lo que hace que estas conjunciones se separen involuntariamente y permitan el paso al interior de nuestro cuerpo a bacterias que no deberían de salir del intestino. Por suerte, el cuerpo es muy inteligente y tenemos una tercera capa, donde vive una parte del sistema inmunitario, listo para impedir que bacterias malas entren. Pero, este sistema puede fallar, por ello, para hacer a nuestra microbiota y por extensión a nuestro intestino, más fuerte, come mucha fibra.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: IntestinoIcon,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "4. Eje intestino-cerebro",
    icon: MicrobiotaIconEje,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-7",
        nom: "El nervio vago",
        link: `${basePath}/mic-7`,
        linkAnterior: `${basePath}/mic-5`,
        linkNext: `${basePath}/mic-8`,
        descripcion: "Entiende cómo tu intestino y tu cerebro se comunican constantemente y por qué el intestino lidera esa conversación.",
        video: "etDQFi3SPcM",
        letra: "Nada en tu cuerpo funciona de forma independiente, todo está interconectado. En especial, el intestino y el cerebro están en comunicación constante. El nervio vago es la autopista principal. Recoge el nivel de bienestar del intestino y lo envía directamente al cerebro. Pero además, el intestino tiene su propio sistema nervioso: el sistema nervioso entérico, con millones de neuronas que envían señales al cerebro. La conexión de nuestro intestino con nuestro cerebro es más importante que la del cerebro con el intestino, aproximadamente el 85% de las señales del nervio vago van del intestino al cerebro, no al revés.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconEje,
        floatingButton: respetarme,
      },
      {
        id: "mic-8",
        nom: "Nuestra microbiota produce neurotransmisores",
        link: `${basePath}/mic-8`,
        linkAnterior: `${basePath}/mic-7`,
        linkNext: `${basePath}/mic-9`,
        descripcion: "Descubre cómo las bacterias de tu intestino influyen directamente en tu estado de ánimo y en tu felicidad.",
        video: "5mcWlc3_o1k",
        letra: "Las bacterias de nuestra microbiota pueden segregar compuestos idénticos a nuestros neurotransmisores, por lo que transformarán nuestro estado a uno relajado pero activo y feliz. No solo esto, sino que pueden estimular a las células del intestino para que liberen serotonina, el neurotransmisor de la felicidad.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconEje,
        floatingButton: respetarme,
      },
      {
        id: "mic-9",
        nom: "La microbiota y el cortisol",
        link: `${basePath}/mic-9`,
        linkAnterior: `${basePath}/mic-8`,
        linkNext: `${basePath}/mic-10`,
        descripcion: "Aprende cómo el estrés y el cortisol transforman tu microbiota y con ella, todo tu cuerpo.",
        video: "Z5_zwvc9EDA",
        letra: "El cortisol es capaz de cambiar nuestra microbiota. El cortisol puede predisponer a que las células de nuestro intestino se separen, permitiendo el paso a la sangre a bacterias que no deberían de salir del intestino. Además, el cortisol debilita a nuestras bacterias buenas, como a los Lactobacillus y Bifidobacterium. El cortisol cambia nuestra microbiota y con ello, a todo nuestro cuerpo.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconEje,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "5. Las mujeres y la microbiota",
    icon: MicrobiotaIconMujer,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-6",
        nom: "El Estroboloma",
        link: `${basePath}/mic-6`,
        linkAnterior: `${basePath}/mic-9`,
        linkNext: `${basePath}/mic-10`,
        descripcion: "Descubre cómo tu microbiota regula tu equilibrio hormonal y qué puedes hacer para cuidarte desde dentro.",
        video: "s8R9lN_AuJo",
        letra: "Tu equilibrio hormonal empieza en el intestino. Nuestro hígado manda al intestino hormonas que ya han cumplido su función. Pero si en el intestino tenemos una sobrepoblación de bacterias malas, estas pueden reactivar los estrógenos y devolverlos a la circulación. Esta sobrecarga de estrógenos puede causar problemas como síntomas premenstruales, dolores excesivos durante la regla e incluso aumentar el riesgo de cánceres. Esto se remedia con una microbiota equilibrada. Por ello, si tienes alguno de los síntomas nombrados, es muy recomendable tomar más fibra, hacer ejercicio y tomar solo grasas insaturadas, en especial las omega3. Cuídate como te mereces, eres importante.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconMujer,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "6. Tus decisiones",
    icon: MicrobiotaIconDecisiones,
    floatingButton: respetarme,
    submodules: [
      {
        id: "mic-10",
        nom: "Nuestras decisiones cambian nuestra microbiota",
        link: `${basePath}/mic-10`,
        linkAnterior: `${basePath}/mic-6`,
        linkNext: "",
        descripcion: "Toma conciencia del poder que tienes cada día para transformar tu microbiota y con ella, tu bienestar.",
        video: "c7F0iGzRtUc",
        letra: "En nuestra microbiota habitan bacterias que viven de lo que nosotros comemos, por lo que necesitan esos alimentos para sobrevivir. Si comemos mucho azúcar, en nosotros predominarán bacterias perjudiciales que además tratarán de convencernos para que comamos azúcar, porque recuerda, solo están pidiendo lo que necesitan para sobrevivir. Nuestra microbiota es repoblada parcialmente cada vez que comemos, por eso, cambiar una microbiota perjudicial e inflamatoria a una equilibrada es posible. Todo depende de los alimentos que elijas cada día, pero por favor, trátate con respeto y entiende por qué eliges los alimentos que eliges, qué te hacen sentir, de verdad quieres comer eso o es impulso. Conócete para que tu vida no esté bajo el control de heridas no sanadas.",
        cursoId: "nut-curso-2",
        detalles: detalles,
        icon: MicrobiotaIconDecisiones,
        floatingButton: respetarme,
      },
    ],
  },
];