import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { NutricionIcon, nutricionBg, nutricionNomLink, nutricionTxt } from "../../../GlobalVariables";

const detalles: Detalles = { color: nutricionTxt, icon: NutricionIcon, bgColor: nutricionBg };

const basePath = "/aprendizaje/videoLessonPage/" + nutricionNomLink;

const respetarme: FloatingButtonConfig = {
  label: "Respetarme",
  action: "espacio-auth",
  route: "/espacio/questions/" + nutricionNomLink,
};

export const modulosNutricion: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-rec",
        nom: "Recursos a tu disposición",
        link: `/recursos/` + nutricionNomLink,
        linkAnterior: "",
        linkNext: "",
        descripcion: "",
        video: "",
        letra: null,
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: null,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "1. Respétate",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-r1",
        nom: "Somos lo que comemos",
        link: `${basePath}/nut-r1`,
        linkAnterior: "",
        linkNext: `${basePath}/nut-m1`,
        descripcion: "Descubre por qué los alimentos que elegimos cada día no solo construyen nuestro cuerpo, sino también nuestra claridad mental y nuestro estado emocional.",
        video: "0QBJyFRGgnI",
        letra: "Aunque estemos tranquilos o descansando, nuestras células están en continua actividad. Lo que comemos es transformado y usado para permitir que podamos seguir con esta experiencia llamada Vida. Teniendo eso en cuenta, ¿por qué no darles lo que es mejor para ellas? Pero, ¿cómo sabemos lo que es mejor para ellas? A través de estos módulos entenderás por qué unos alimentos son mejores que otros y qué efecto tienen en ti.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "2. Macronutrientes",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-m1",
        nom: "Proteínas",
        link: `${basePath}/nut-m1`,
        linkAnterior: `${basePath}/nut-r1`,
        linkNext: `${basePath}/nut-m2`,
        descripcion: "Entiende qué son las proteínas, para qué las necesita tu cuerpo y cuáles son las mejores fuentes para mantener tu salud y energía.",
        video: "BU2DpV82oqM",
        letra: "Las proteínas son de vital importancia, cuando nuestra dieta carece de ellas nuestro cuerpo decae y bastante rápido, nos sentimos lentos, pesados y se nos olvidan las cosas. Entendamos por qué ocurre esto. Imaginemos a las proteínas como collares de perlas. Cada perla es distinta y única. Cada célula usa las perlas de la proteína para hacer sus propios collares. Estos collares son las enzimas. Las enzimas son las que mantienen la correcta regulación de la célula. Por eso, para respetar a tu cuerpo y a todas las células que te forman, que trabajan por y para ti, asegúrate de tomar suficiente proteína.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-m2",
        nom: "Carbohidratos",
        link: `${basePath}/nut-m2`,
        linkAnterior: `${basePath}/nut-m1`,
        linkNext: `${basePath}/nut-m3`,
        descripcion: "Aprende a distinguir los carbohidratos que te nutren de los que te desgastan, y cómo elegirlos para sostener tu energía a lo largo del día.",
        video: "n2cRzyINYDE",
        letra: "Las células y por extensión, nosotros, necesitamos glucosa. Por el bien de todos nuestros órganos y de nuestras neuronas, queremos que esa glucosa se incorpore en nosotros poco a poco, para no sobrecargarnos y hacernos daño. Entonces, ¿cómo podemos absorber la glucosa más lentamente? Muy sencillo, eligiendo alimentos con fibra, esta es la razón por la que las verduras, frutas y productos integrales son saludables. Si elegimos bollería o harinas blancas, esto nos sobrecargará, porque no podemos usar toda esa glucosa a la vez. Esto deteriorará a nuestras neuronas y obligará a que la glucosa que no ha podido ser usada se almacene en forma de grasa.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-m3",
        nom: "Grasas",
        link: `${basePath}/nut-m3`,
        linkAnterior: `${basePath}/nut-m2`,
        linkNext: `${basePath}/nut-mi1`,
        descripcion: "Rompe con los mitos sobre las grasas y descubre cuáles son esenciales para tu cerebro, tus hormonas y tu bienestar general.",
        video: "CuoVBfewgiQ",
        letra: "Los tipos de grasas que existen son un arma de doble filo porque pueden protegernos o causar un deterioro temprano. Las células tienen una membrana que las protege y les permite comunicarse. Las células usan las grasas de nuestra dieta para reconstruir esta membrana. Si elegimos grasas insaturadas, como el aguacate, el aceite de oliva, los frutos secos, nuestras células serán más eficientes y estarán mejor protegidas. En cambio, si se reconstruyen con grasas trans o saturadas, serán más lentas, torpes e incluso nuestro cuerpo las puede percibir como enemigos.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
  {
    title: "3. Micronutrientes",
    icon: NutricionIcon,
    floatingButton: respetarme,
    submodules: [
      {
        id: "nut-mi1",
        nom: "Vitaminas",
        link: `${basePath}/nut-mi1`,
        linkAnterior: `${basePath}/nut-m3`,
        linkNext: `${basePath}/nut-mi2`,
        descripcion: "Descubre el papel fundamental de las vitaminas en tu salud, cuáles necesitas y cómo obtenerlas de forma natural a través de tu alimentación.",
        video: "djMQ-EIifZc",
        letra: "Siempre nos han dicho que las vitaminas son necesarias, pero nadie nos ha explicado por qué. Aquí por fin lo entenderás. Recordemos que las células crean enzimas usando las proteínas de nuestra dieta, pero estas enzimas no están activadas, necesitan vitaminas para activarse, sin vitaminas esas enzimas no pueden hacer su función y por lo tanto, no podemos reconstruirnos ni mejorarnos. Sin vitaminas nos deterioramos, envejecemos y perdemos funciones que creíamos estables.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
      {
        id: "nut-mi2",
        nom: "Minerales",
        link: `${basePath}/nut-mi2`,
        linkAnterior: `${basePath}/nut-mi1`,
        linkNext: "",
        descripcion: "Comprende qué minerales necesita tu cuerpo para funcionar en equilibrio y cómo una carencia puede afectar tu energía, tu ánimo y tu salud.",
        video: "7KN0sqwUO0E",
        letra: "Los minerales son muy importantes también, porque son las herramientas que usan las enzimas. Sin minerales, a pesar de que la enzima esté activa, no puede trabajar, por lo que nos deterioramos y nos sentimos más cansados y lentos. En conclusión, la enzima usa las vitaminas para activarse y los minerales para trabajar.",
        cursoId: "nut-curso-1",
        detalles: detalles,
        icon: NutricionIcon,
        floatingButton: respetarme,
      },
    ],
  },
];
