export const letraKarma1 = "Hemos reencarnado para sanarnos y recordar que tenemos derecho al disfrute y al amor, que somos seres dignos y preciosos. Cada uno tiene ciertas áreas en las cuales hacer un desarrollo más consciente. Sanar las heridas, arrastradas de vidas anteriores, y recordar que somos y estamos hechos de amor, es el sentido de nuestra vida.";

export const letraKarma2 = "El karma es aquello que se repite. La situación que nos solemos encontrar y que tanto nos molesta y nos duele, eso es nuestro karma. Decidimos que nuestra evolución y desarrollo fuese a través del dolor. Por eso, cuando tienes una situación desagradable, de la cual estás cansado y frustrado, te invito a que trates de observar para qué está. Qué tiene eso para ti. Al servicio de qué herida está esa situación.";

export const letraKarma3 = "Todo tiene una razón, si no, no existiría. Sé que esto es difícil de entender, porque estamos acostumbrados a existir, pero para que algo tenga lugar, miles de reacciones metabólicas, celulares y neuronales tienen que ponerse de acuerdo para causarte la cantidad exacta de dolor para que crezcas. Nada que te ocurre es en tu contra.";

export const letraKarma4 = "Los pactos más duros se dan entre las almas que más se aman. Según la espiritualidad, elegimos a las personas con las que nos vamos a encontrar para que nos muestren algo que habíamos olvidado y hemos elegido recordar. Solemos elegir el cómo van a hacer que lo recordemos, pero ojo, no es necesario que nos lo hagan para que lo recordemos.\n\nPor ejemplo, si yo quedo con Pedro para que me haga recordar que tengo derecho a defenderme y elijo que sea a través de una paliza, en el momento en que veo venir a Pedro, no necesito que llegue a pegarme para que yo recuerde que tengo derecho a defenderme.";

export const letraKarma5 = "Cuando no somos capaces de ver la raíz de nuestras heridas, la vida nos pone a personas que nos van a señalar dónde las tenemos. Esto no es agradable, pero es una ventaja: ahora podemos hacernos cargo porque sabemos exactamente dónde y qué nos duele. Y si seguimos sin querer mirar, la situación se exagerará hasta que asumamos nuestra responsabilidad.";

export const letraKarma6 = "El juego de la vida se basa en que seamos capaces de vernos a nosotros mismos desde varios ángulos, y aún así ser capaces de recordar que somos dignos de ser amados. Cada vez que te pasa algo malo, es tu alma preguntándote: ¿eres capaz de amarte a pesar de esto?";

export const letraKarma7 = "El cristianismo te dice que eres pequeño, que estás sucio y que Dios te ha expulsado a esta tierra para sufrir. Te dice que estás siendo juzgado a cada instante de tu vida y que serás castigado.";
