export const letraCh1 = "Los chakras son puntos de energía que conectan más intensamente a nuestro cuerpo con la energía que nos da Vida. Nuestra alma está conectada con todo nuestro cuerpo, pero en ciertos puntos la podemos sentir más. Esos puntos son los chakras.";

export const letraCh2 = "¿Sientes que el mundo es un lugar peligroso? ¿Piensas que la Vida está en tu contra? El chakra raíz es el punto de energía que nos conecta profundamente con lo tangible y la naturaleza. Es el que recuerda que tenemos raíces y que merecemos caminar por esta tierra, que somos bienvenidos y que no estamos en peligro, porque el mundo no es un lugar peligroso.";

export const letraCh3 = "El segundo chakra es el chakra del gozo. No estamos hablando necesariamente del sexo, sino, por ejemplo, ¿cuánta gente se da el permiso de sentir su respiración? ¿Cuánta gente disfruta de su sonrisa y de que otros le vean sonreír? Nos solemos privar de estos placeres básicos y naturales por creencias y lealtades inconscientes. No está bien visto que sonrías al ver el cielo azul, y a partir de ahí, la gente se bloquea cualquier otro placer a no ser que este le lleve a un extremo exagerado e insano.";

export const letraCh4 = "El vacío interior que sientes a la altura del estómago es el tercer chakra. El chakra del plexo solar es el de la valía personal: no podemos creer que valemos si creemos que el mundo es un lugar peligroso o si no nos dejamos disfrutar de nuestra respiración. La mayoría de la gente tiene este chakra muy malito, el dolor y el vacío suele ser confundido por hambre, llevando a tendencias autodestructivas.";

export const letraCh5 = "Para sanar al tercer chakra, tienes que recordar que eres suficiente simplemente por ser. Ya sé que puedes pensar que no es así y que tienes que hacer más, pero la verdad es que no puedes ganarte a pulso tu suficiencia. La batalla se perdió el día en que pensaste que tu derecho a existir era debatible.";

export const letraCh6 = "¿Cuántas personas son capaces de sentir el latido de su corazón? Solemos enterrar nuestro corazón y nuestros sentimientos bajo capas de dolor, y los congelamos porque creemos que así no nos dolerá. Así es como nos desconectamos plenamente del chakra corazón y, por extensión, de nuestra esencia y nuestra parte más amable y bondadosa. Lo hacemos por supervivencia, para creer que de alguna forma podemos borrar el dolor, pero lo negado acaba controlando nuestra Vida.";

export const letraCh7 = "¿Eres capaz de comunicarte claramente y con confianza? Cuando tenemos alineado el quinto chakra, somos capaces de decir lo que queremos decir sin confusiones. En este estado prefieres ser feliz a tener razón, realmente no quieres discutir, eres consciente de que estar enfadado con el pasado no merece la pena.";

export const letraCh8 = "El chakra del tercer ojo es el más popular pero el peor comprendido. Este chakra se abre cuando somos conscientes de que todos somos uno. No es que seas capaz de ver ángeles u otras dimensiones, pero eres capaz de sentir energías y de confiar en tu intuición. A pesar de esto, es importante tener en cuenta que si estamos encarnados es para algo y no merece la pena tratar de ir a otros mundos si ni siquiera entendemos y valoramos el nuestro.";

export const letraCh9 = "El chakra corona es nuestra conexión más directa con nuestra alma. Cuando está abierto, sientes un cosquilleo en la cabeza, y ya has dejado atrás todos tus enfados con la Vida y con las personas. Eres capaz de entender que tu Vida tiene sentido, que no eres un gasto y que Dios no te ha abandonado ni expulsado.";
