export const letraAyu1 = "La Ayurveda es una medicina ancestral originada en la India hace miles de años. Su traducción es literalmente \"la ciencia de la vida\". No solo es un sistema tradicional de salud, sino que es una filosofía que recuerda que estamos unidos a la naturaleza. Su propósito es que recuperemos nuestro equilibrio, y que vivamos en armonía con nuestra constitución física y mental únicas.";

export const letraAyu2 = "Según la Ayurveda, toda la naturaleza está compuesta por cinco elementos fundamentales: tierra, agua, fuego, aire y éter, cuyo significado es espacio o vacío. La energía vital que da vida a estos elementos y, por extensión, a la materia, es el prana. Los seres humanos también estamos formados por estos cinco elementos, que causan una influencia directa e inevitable en nuestra Vida.";

export const letraAyu3 = "Para crear la naturaleza, los Cinco elementos se combinan en grupos de dos. A cada grupo se le llama dosha. Los doshas son energías biológicas que regulan el funcionamiento del cuerpo y de la mente. En total son tres: Vata, formado por aire y éter; Pitta, por fuego y agua; y Kapha, por agua y tierra.";

export const letraAyu4 = "La constitución de la naturaleza y de los seres humanos se basa en la combinación única de los tres doshas. Aunque suele haber uno o dos predominantes, cada persona tiene los tres en distintas proporciones. Esta combinación crea nuestro metabolismo, nuestro físico, nuestra forma de pensar y nuestras emociones. Conocer tu constitución es importante, porque solemos sentirnos atraídos por alimentos, emociones y actividades que comparten cualidades con nuestro dosha predominante. Por ello es muy fácil estar desequilibrado. La Ayurveda quiere que comprendas tu naturaleza para volver al equilibrio.";

export const letraAyu5 = "Las personas cuyo dosha predominante es Vata suelen ser delgadas, muy activas y con una mente inquieta. Por ello, tienden al estrés, a la dispersión y al agotamiento. Las personas Vata son muy sensibles al frío. A pesar de ello, tienden a elegir alimentos fríos, crudos o secos, como ensaladas o comidas sacadas directamente de la nevera. Esto agrava todavía más su desequilibrio. Las personas Vata deben aprender a nutrirse con comidas calientes y cocinadas, además de encontrar momentos de pausa y respiración.";

export const letraAyu6 = "Las personas con predominancia de Pitta suelen tener una constitución media, una mente clara y una energía intensa. Son personas decididas, resolutivas y con una gran capacidad de concentración. Les gusta avanzar con eficiencia, pero suelen ser demasiado exigentes, con mucha tendencia al enfado. Se alteran extremadamente rápido y es frecuente que padezcan de inflamación o problemas en la piel. Para equilibrarse, es fundamental priorizar alimentos frescos, suaves e hidratantes, así como cultivar calma y menos competitividad.";

export const letraAyu7 = "Las personas con predominancia de Kapha suelen tener una constitución más ancha, una energía constante y tranquila. Tienen una gran capacidad para cuidar, sostener y crear estabilidad. Sin embargo, desequilibrados, pueden sentir pesadez, apego o resistencia al cambio. Kapha es especialmente sensible a la humedad, el exceso de descanso, a las comidas pesadas y la falta de movimiento. A pesar de ello, se sienten atraídos por alimentos pesados, dulces y abundantes, así como por el sedentarismo y la comodidad excesiva. Por eso, Kapha se equilibra con el movimiento, con alimentos ligeros y poco calóricos.";

export const letraAyu8 = "Como hemos visto, tendemos a sentirnos atraídos por aquello con cualidades de nuestro dosha predominante, ya sea en los alimentos, en las actividades o en las emociones. Por eso es tan importante conocer nuestro dosha: para entender, sin juzgarnos, por qué nos atrae aquello que nos hace daño. Recordemos, un Vata necesita más calor, más pausa y menos alimentos crudos; un Pitta refrescarse, bajar la intensidad y soltar el control; y un Kapha más movimiento, más estímulo y una alimentación ligera.";
