import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { AyurvedaIcon, ayurvedaBg, ayurvedaNomLink, ayurvedaTxt } from "../../../GlobalVariables";
import {
  letraCh1, letraCh2, letraCh3, letraCh4, letraCh5,
  letraCh6, letraCh7, letraCh8, letraCh9,
} from "./LetraChakras";

const detalles: Detalles = { color: ayurvedaTxt, icon: AyurvedaIcon, bgColor: ayurvedaBg };

const basePath = "/aprendizaje/videoLessonPage/" + ayurvedaNomLink;

const conocerMiDosha: FloatingButtonConfig = {
  label: "Profundizar en los chakras",
  action: "espacio-auth",
  route: "/espacio/questions/" + ayurvedaNomLink,
};

export const modulosChakras: ModuloContenido[] = [
  {
    title: "1. ¿Qué son los chakras?",
    icon: AyurvedaIcon,
    floatingButton: conocerMiDosha,
    submodules: [
      {
        id: "ayu-ch1",
        nom: "1.1 ¿Qué son los chakras?",
        link: `${basePath}/ayu-ch1`,
        linkAnterior: "",
        linkNext: `${basePath}/ayu-ch2`,
        descripcion: "Descubre qué son los chakras: los puntos donde el cuerpo y el alma se conectan con mayor intensidad.",
        video: "wk2zeX3HPbg",
        letra: letraCh1,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
    ],
  },
  {
    title: "2. Los chakras inferiores",
    icon: AyurvedaIcon,
    floatingButton: conocerMiDosha,
    submodules: [
      {
        id: "ayu-ch2",
        nom: "2.1 El chakra raíz",
        link: `${basePath}/ayu-ch2`,
        linkAnterior: `${basePath}/ayu-ch1`,
        linkNext: `${basePath}/ayu-ch3`,
        descripcion: "El chakra que nos ancla a la tierra y nos recuerda que somos bienvenidos, que tenemos raíces y que el mundo no es un lugar peligroso.",
        video: "fMOx4iUQu4I",
        letra: letraCh2,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch3",
        nom: "2.2 El chakra sacro",
        link: `${basePath}/ayu-ch3`,
        linkAnterior: `${basePath}/ayu-ch2`,
        linkNext: `${basePath}/ayu-ch4`,
        descripcion: "El chakra del gozo: aprende a darte permiso para disfrutar de los placeres simples y naturales sin bloqueos ni culpa.",
        video: "cL90XrMKNgs",
        letra: letraCh3,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch4",
        nom: "2.3 El plexo solar",
        link: `${basePath}/ayu-ch4`,
        linkAnterior: `${basePath}/ayu-ch3`,
        linkNext: `${basePath}/ayu-ch5`,
        descripcion: "El chakra de la valía personal: el vacío interior a la altura del estómago suele confundirse con hambre y lleva a tendencias autodestructivas.",
        video: "1h3L3FAshLg",
        letra: letraCh4,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch5",
        nom: "2.4 Sanar el plexo solar",
        link: `${basePath}/ayu-ch5`,
        linkAnterior: `${basePath}/ayu-ch4`,
        linkNext: `${basePath}/ayu-ch6`,
        descripcion: "Eres suficiente simplemente por ser, sin tener que ganártelo a pulso.",
        video: "DCjcmWwkaoU",
        letra: letraCh5,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
    ],
  },
  {
    title: "3. Los chakras superiores",
    icon: AyurvedaIcon,
    floatingButton: conocerMiDosha,
    submodules: [
      {
        id: "ayu-ch6",
        nom: "3.1 El chakra corazón",
        link: `${basePath}/ayu-ch6`,
        linkAnterior: `${basePath}/ayu-ch5`,
        linkNext: `${basePath}/ayu-ch7`,
        descripcion: "Cerramos nuestro corazón para no sentir dolor y eso nos desconecta de nuestra esencia.",
        video: "b-iylRkRZBI",
        letra: letraCh6,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch7",
        nom: "3.2 El chakra de la garganta",
        link: `${basePath}/ayu-ch7`,
        linkAnterior: `${basePath}/ayu-ch6`,
        linkNext: `${basePath}/ayu-ch8`,
        descripcion: "Habla desde tu Verdad, sin miedo y con claridad.",
        video: "K2w2IrSzG7g",
        letra: letraCh7,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch8",
        nom: "3.3 El tercer ojo",
        link: `${basePath}/ayu-ch8`,
        linkAnterior: `${basePath}/ayu-ch7`,
        linkNext: `${basePath}/ayu-ch9`,
        descripcion: "Confía en tu intuición.",
        video: "CiAZ74rwnhg",
        letra: letraCh8,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch9",
        nom: "3.4 El chakra corona",
        link: `${basePath}/ayu-ch9`,
        linkAnterior: `${basePath}/ayu-ch8`,
        linkNext: "",
        descripcion: "Tu Vida tiene sentido, no eres un gasto.",
        video: "Eq7ySNNiS7o",
        letra: letraCh9,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
    ],
  },
];
