import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { AyurvedaIcon, ayurvedaBg, ayurvedaNomLink, ayurvedaTxt } from "../../../GlobalVariables";
import {
  letraCh1, letraCh2, letraCh3, letraCh4, letraCh5,
  letraCh6, letraCh7, letraCh8, letraCh9,
} from "./LetraChakras";

const detalles: Detalles = { color: ayurvedaTxt, icon: AyurvedaIcon, bgColor: ayurvedaBg };

const basePath = "/aprendizaje/videoLessonPage/" + ayurvedaNomLink;

const conocerMiDosha: FloatingButtonConfig = {
  label: "Conocer mi dosha",
  action: "espacio-auth",
  route: "/espacio/questions/" + ayurvedaNomLink,
};

export const modulosChakras: ModuloContenido[] = [
  {
    title: "1. ¿Qué son los chakras?",
    icon: AyurvedaIcon,
    floatingButton: conocerMiDosha,
    submodules: [
      {
        id: "ayu-ch1",
        nom: "1.1 ¿Qué son los chakras?",
        link: `${basePath}/ayu-ch1`,
        linkAnterior: "",
        linkNext: `${basePath}/ayu-ch2`,
        descripcion: "Descubre qué son los chakras: los puntos donde el cuerpo y el alma se conectan con mayor intensidad.",
        video: "MYKnqq_IsX0",
        letra: letraCh1,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
    ],
  },
  {
    title: "2. Los chakras inferiores",
    icon: AyurvedaIcon,
    floatingButton: conocerMiDosha,
    submodules: [
      {
        id: "ayu-ch2",
        nom: "2.1 El chakra raíz",
        link: `${basePath}/ayu-ch2`,
        linkAnterior: `${basePath}/ayu-ch1`,
        linkNext: `${basePath}/ayu-ch3`,
        descripcion: "El chakra que nos ancla a la tierra y nos recuerda que somos bienvenidos, que tenemos raíces y que el mundo no es un lugar peligroso.",
        video: "5QJX5m3xeiM",
        letra: letraCh2,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch3",
        nom: "2.2 El chakra sacro",
        link: `${basePath}/ayu-ch3`,
        linkAnterior: `${basePath}/ayu-ch2`,
        linkNext: `${basePath}/ayu-ch4`,
        descripcion: "El chakra del gozo: aprende a darte permiso para disfrutar de los placeres simples y naturales sin bloqueos ni culpa.",
        video: "u6RvQM9z-6Q",
        letra: letraCh3,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch4",
        nom: "2.3 El plexo solar",
        link: `${basePath}/ayu-ch4`,
        linkAnterior: `${basePath}/ayu-ch3`,
        linkNext: `${basePath}/ayu-ch5`,
        descripcion: "El chakra de la valía personal: por qué el vacío interior a la altura del estómago suele confundirse con hambre y lleva a tendencias autodestructivas.",
        video: "ABMe6GRb030",
        letra: letraCh4,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch5",
        nom: "2.4 Sanar el plexo solar",
        link: `${basePath}/ayu-ch5`,
        linkAnterior: `${basePath}/ayu-ch4`,
        linkNext: `${basePath}/ayu-ch6`,
        descripcion: "Cómo recuperar la certeza de que eres suficiente simplemente por ser, sin tener que ganártelo a pulso.",
        video: "cp-ZP_RVACg",
        letra: letraCh5,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
    ],
  },
  {
    title: "3. Los chakras superiores",
    icon: AyurvedaIcon,
    floatingButton: conocerMiDosha,
    submodules: [
      {
        id: "ayu-ch6",
        nom: "3.1 El chakra corazón",
        link: `${basePath}/ayu-ch6`,
        linkAnterior: `${basePath}/ayu-ch5`,
        linkNext: `${basePath}/ayu-ch7`,
        descripcion: "Por qué enterramos nuestros sentimientos y cómo eso nos desconecta de nuestra esencia más amable y bondadosa.",
        video: "YaB75vCfubM",
        letra: letraCh6,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch7",
        nom: "3.2 El chakra de la garganta",
        link: `${basePath}/ayu-ch7`,
        linkAnterior: `${basePath}/ayu-ch6`,
        linkNext: `${basePath}/ayu-ch8`,
        descripcion: "Cuando este chakra está alineado, te comunicas con claridad y prefieres ser feliz a tener razón.",
        video: "yqW2TkgSZGI",
        letra: letraCh7,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch8",
        nom: "3.3 El tercer ojo",
        link: `${basePath}/ayu-ch8`,
        linkAnterior: `${basePath}/ayu-ch7`,
        linkNext: `${basePath}/ayu-ch9`,
        descripcion: "El chakra más popular y peor comprendido: la conciencia de que todos somos uno y el despertar de la intuición.",
        video: "LPa1i1hJwjA",
        letra: letraCh8,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
      {
        id: "ayu-ch9",
        nom: "3.4 El chakra corona",
        link: `${basePath}/ayu-ch9`,
        linkAnterior: `${basePath}/ayu-ch8`,
        linkNext: "",
        descripcion: "La conexión más directa con el alma: cuando ya has soltado los enfados y comprendes que tu vida tiene sentido y que no eres un gasto.",
        video: "J7UE_KEs528",
        letra: letraCh9,
        cursoId: "ayu-curso-2",
        detalles: detalles,
        icon: AyurvedaIcon,
        floatingButton: conocerMiDosha,
      },
    ],
  },
];
