import type { Detalles, ModuloContenido } from "../../../dtos/aprendizaje.type";
import {
  AyurvedaIcon, ayurvedaBg, ayurvedaNomLink, ayurvedaTxt,
  VataIconAyu,
  PittaIconAyu,
  KaphaIconAyu,
} from "../../../GlobalVariables";
import {
  letraAyu1, letraAyu2, letraAyu3,
  letraAyu5, letraAyu6, letraAyu7, letraAyu8,
} from "./LetraAyurveda";

const detalles: Detalles = { color: ayurvedaTxt, icon: AyurvedaIcon, bgColor: ayurvedaBg };

const basePath = "/aprendizaje/videoLessonPage/" + ayurvedaNomLink;

export const modulosAyurveda: ModuloContenido[] = [
  {
    title: "Recursos",
    icon: AyurvedaIcon,
    submodules: [
      {
        id: "ayu-rec",
        nom: "Recursos a tu disposición",
        link: `/recursos/` + ayurvedaNomLink,
        linkAnterior: "",
        linkNext: "",
        descripcion: "",
        video: "",
        letra: null,
        cursoId: "ayu-curso-1",
        detalles: detalles,
        icon: null,
      },
    ],
  },
  {
    title: "1. Introducción",
    icon: AyurvedaIcon,
    submodules: [
      {
        id: "ayu-i1",
        nom: "¿Qué es la Ayurveda?",
        link: `${basePath}/ayu-i1`,
        linkAnterior: "",
        linkNext: `${basePath}/ayu-i2`,
        descripcion: "Descubre qué es la Ayurveda, su origen milenario en la India y por qué es mucho más que un sistema de salud.",
        video: "iorzixFaCqU",
        letra: letraAyu1,
        cursoId: "ayu-curso-1",
        detalles: detalles,
        icon: AyurvedaIcon,
      },
      {
        id: "ayu-i2",
        nom: "Los Cinco Elementos",
        link: `${basePath}/ayu-i2`,
        linkAnterior: `${basePath}/ayu-i1`,
        linkNext: `${basePath}/ayu3`,
        descripcion: "Conoce los cinco elementos fundamentales que componen toda la naturaleza y la energía vital que los anima.",
        video: "gdr9WTsvmn8",
        letra: letraAyu2,
        cursoId: "ayu-curso-1",
        detalles: detalles,
        icon: AyurvedaIcon,
      },
    ],
  },
  {
    title: "2. Los Doshas",
    icon: AyurvedaIcon,
    submodules: [
      {
        id: "ayu3",
        nom: "Los Doshas",
        link: `${basePath}/ayu3`,
        linkAnterior: `${basePath}/ayu-i2`,
        linkNext: `${basePath}/ayu4`,
        descripcion: "Entiende qué son los doshas, cómo surgen de los cinco elementos y cuáles son los tres tipos.",
        video: "Ycd1X3AnBPI",
        letra: letraAyu3,
        cursoId: "ayu-curso-1",
        detalles: detalles,
        icon: AyurvedaIcon,
      },
      {
        id: "ayu4",
        nom: "Vata",
        link: `${basePath}/ayu4`,
        linkAnterior: `${basePath}/ayu3`,
        linkNext: `${basePath}/ayu5`,
        descripcion: "Explora las características físicas y mentales de Vata y aprende qué necesita para volver al equilibrio.",
        video: "5WfC9mGUndM",
        letra: letraAyu5,
        cursoId: "ayu-curso-1",
        detalles: detalles,
        icon: VataIconAyu,
      },
      {
        id: "ayu5",
        nom: "Pitta",
        link: `${basePath}/ayu5`,
        linkAnterior: `${basePath}/ayu4`,
        linkNext: `${basePath}/ayu6`,
        descripcion: "Conoce la energía intensa y transformadora de Pitta y cómo cuidarla para evitar el exceso de fuego interno.",
        video: "mWy5tkGplz0",
        letra: letraAyu6,
        cursoId: "ayu-curso-1",
        detalles: detalles,
        icon: PittaIconAyu,
      },
      {
        id: "ayu6",
        nom: "Kapha",
        link: `${basePath}/ayu6`,
        linkAnterior: `${basePath}/ayu5`,
        linkNext: `${basePath}/ayu7`,
        descripcion: "Comprende la estabilidad y la fuerza de Kapha y qué necesita para no caer en el estancamiento.",
        video: "8cPUwuSFnWQ",
        letra: letraAyu7,
        cursoId: "ayu-curso-1",
        detalles: detalles,
        icon: KaphaIconAyu,
      },
      {
        id: "ayu7",
        nom: "Recapitulación de los Doshas",
        link: `${basePath}/ayu7`,
        linkAnterior: `${basePath}/ayu6`,
        linkNext: "",
        descripcion: "Integra lo aprendido sobre los tres doshas y comprende por qué nos atrae aquello que nos desequilibra.",
        video: "siZ5Rn0wSZc",
        letra: letraAyu8,
        cursoId: "ayu-curso-1",
        detalles: detalles,
        icon: AyurvedaIcon,
      },
    ],
  },
];
