// ─────────────────────────────────────────────────────────────────────────
// RESÚMENES de los arquetipos, en INGLÉS.
//
// Mismo mapa que astrologiaResumenes.ts (el español manda: de él salen las
// claves, el orden y los planetas que tienen resumen). Aquí va SOLO la prosa.
//
// Ojo con las claves: los signos se indexan por su nombre ESPAÑOL («Géminis»),
// porque es lo que guarda la carta del usuario. Lo que no esté aquí se muestra
// en español, celda a celda (ver getTextoSigno / resumenDe).
//
// Y ojo con el emparejamiento: el resumen y el texto largo de un arquetipo se
// pintan juntos, así que traducir uno sin el otro deja el popup a medio idioma.
// textoEstatico() lo evita no poniendo resumen si no coinciden, pero lo bueno
// es traducir los dos a la vez.
// ─────────────────────────────────────────────────────────────────────────
import type { CuerpoKey } from "./astrologiaData";

/** Los doce signos en el orden canónico, para mapear «Casa N = Signo N». */
const SIGNOS = [
  "Aries", "Tauro", "Géminis", "Cáncer", "Leo", "Virgo",
  "Libra", "Escorpio", "Sagitario", "Capricornio", "Acuario", "Piscis",
] as const;

/** Convierte un mapa por número (1-12) en un mapa por nombre de signo. */
const porSigno = (m: Record<number, string>): Record<string, string> =>
  Object.fromEntries(SIGNOS.map((s, i) => [s, m[i + 1]!]));

/** Quirón: el mismo resumen vale para el signo y para la casa. */
const QUIRON: Record<number, string> = {
  1: "It hurts to begin, it hurts to be you.\nYour **courage** was born wounded, but it's your greatest gift.\nHeal your self-image and walk however you want, not how you were told.",
  2: "You feel you don't deserve abundance or pleasure.\nYour body and your worth don't depend on what you own.\nLove your lack and you'll discover your own richness.",
  3: "Nobody listened to you, and now you believe you're worthless.\nYour wounded voice hides a gift: putting the different into words.\nSpeak your own way, even if it isn't anyone else's.",
  4: "You never felt a home, and that's why you run from your own inside.\nCaring for others won't heal the emptiness unless you hold your inner child.\nYour gift is giving the shelter you never had.",
  5: "They didn't let you shine as you were.\nYour creativity hurts, but it's your most luminous gift.\nExpress yourself, even while the shame shakes.",
  6: "You feel you never do enough, or well enough.\nGuilt for existing on Earth paralyzes you.\nYour gift is caring; start by forgiving your **imperfection**.",
  7: "Loving hurts because you fear being rejected and abandoned.\nYou project onto the other what you don't dare look at in yourself.\nYour gift is sharing yourself without losing yourself.",
  8: "You absorbed pain and control from childhood.\nYou fear your own power as much as anyone else's.\n**Intimacy**, looked at properly, is your door into transformation.",
  9: "You lost your trust in Life and in any greater meaning.\nYou look for answers outside when the truth is to keep exploring.\nYour gift is the faith that's reborn after pain.",
  10: "You felt small, judged, incapable of achieving anything.\nThe fear of failing stops you before you even try.\nYour gift is helping others find their place in the world.",
  11: "You were different, and the group rejected you for it.\nYou feel alone, as if you didn't belong to humanity.\nYour gift is healing the collective out of your own strangeness.",
  12: "You carry a pain older than your birth — your bloodline's too.\nYou feel you don't deserve to be happy, or to merge with anything.\nYour gift is serving humanity by healing your own wound first.",
};

/** Nodo Norte: mismo resumen para el signo y para la casa. */
const NODO_NORTE: Record<number, string> = {
  1: "You were born to discover who you are, without asking permission.\nStop looking for outside approval: **move forward** even if you're argued with.\nYour path opens when you act for yourself.",
  2: "Build your own stability, without depending on anyone.\nLearn to enjoy your body and the simple Life.\nDrop the drama; abundance starts in you.",
  3: "Learn to speak to each person in their own language.\nYou don't know more than anyone: listen before you teach.\nYour destiny is to be a bridge between different worlds.",
  4: "Build your own inner temple before anything else.\nBe your own family before you take care of another.\nHeal your family tree to find your home.",
  5: "You were born to create and show your essence to the world.\nDon't chase perfection: **make it real** with what you already have.\nFollow your heart, not the group's applause.",
  6: "Your lesson is caring for your body, your mind and other people, in balance.\nService and healing are your path, not your punishment.\nPut your Life in order without stopping being generous.",
  7: "Learn to share your Life without losing your essence in it.\nGiving ground isn't losing yourself: it's the door to your expansion.\nHappiness grows when you learn to truly be in a partnership.",
  8: "Look at yourself head-on: your shadow is your treasure too.\nLearn to merge with someone without losing your center.\nBe reborn, again and again, like the **phoenix**.",
  9: "Look for your own answers, not the inherited ones.\nExperience teaches you more than any information.\nExplore far away, then share what you discovered inside.",
  10: "Go out into the world and find your real calling.\nBecome a responsible authority, not a tyrant.\nYour power only counts if it serves something bigger than you.",
  11: "Share your creative gift with the collective, without fear of judgment.\nBe authentic before you're applauded.\nLearn to listen and to grow through the group.",
  12: "Deepen your spiritual connection beyond the material.\nFeel, even though chaos and the lack of structure scare you.\nHelp from **compassion**, not from fixing or striving.",
};

/** Nodo Sur: mismo resumen para el signo y para la casa. */
const NODO_SUR: Record<number, string> = {
  1: "You come from a life centered only on you.\nOther people were always a means to your ends.\nNow it's time to look beyond yourself.",
  2: "You cling to material security and refuse change.\nYour self-sufficiency kept you from ever depending on anyone.\nIt's time to let go of the attachment and look inward.",
  3: "Your scattered mind jumps from one thing to the next without going deep.\nYou passed on other people's ideas, never your own.\nIt's time to stop repeating and start thinking for yourself.",
  4: "You lived trapped in your family and never went out to live your own Life.\nYou mistook shelter for a house, instead of for yourself.\nFace the world: that's where your **personal power** is.",
  5: "You lived believing you were the center of the world.\nIt's hard for you to see yourself as one person among many.\nYou came to give light to others, not only to shine yourself.",
  6: "You never stop, numbed by work and logic.\nYou don't believe in anything you can't control.\nStop running from your soul by serving only with your hands.",
  7: "You learned to give yourself away so completely that you lost yourself.\nNow you can't decide without checking what other people want.\nIt's time to get your own voice back.",
  8: "You depended on others to bankroll your desires.\nYou doubt your own worth and your independent strength.\nStep out of the drama and trust your own resources.",
  9: "Your free, intuitive mind clings to its own beliefs.\nYou isolate yourself when nobody thinks like you.\nLet go of needing to always be right.",
  10: "You come from having had a lot of power, and you're still chasing it.\nYou numb yourself with work, always looking for recognition.\nDrop the need to prove yourself and your path unblocks.",
  11: "You lived in your mind and in the group, with barely any individuality.\nYou feel different, but you're not always authentic.\nIt's time to stop performing strangeness and actually be you.",
  12: "You were an expert in the spiritual, but a stranger to the earthly.\nYou live in your inner world, far from the ordinary.\nThe real, frightening as it is, is sacred too.",
};

export const RESUMENES_SIGNO_EN: Partial<Record<CuerpoKey, Record<string, string>>> = {
  quiron: porSigno(QUIRON),
  nodoNorte: porSigno(NODO_NORTE),
  nodoSur: porSigno(NODO_SUR),
  ascendente: {
    "Aries": "You move forward straight and strong, but watch out for leaving everything half-done.\nYour creativity needs its own outlet, not applause.\nPhysical **movement** is your best ally for transforming your energy.",
    "Tauro": "You build methodically, but you cling to routines that stopped serving you.\nLet go of the result and keep the path, not the prize.\nYour body speaks before it screams: listen in time.",
    "Géminis": "On the outside you look calm; inside there's mental noise that never stops.\nYour curiosity is huge, but scattered it empties you: choose, and go deep.\nCome down from your head to your heart to really feel.",
    "Cáncer": "Your shyness is a shell that freezes the pain instead of protecting you.\nYou feel other people's feelings as your own: learn to tell them apart and let them go.\nYou can't nourish others if you don't **nourish** yourself first.",
    "Leo": "You shine and you draw people in, but real leadership doesn't need subjects.\nYou look for validation outside, and however much you get, the thirst doesn't ease.\nThe only validation that really counts is the one **you** give yourself.",
    "Virgo": "You never quite feel enough, and that shapes you from the inside.\nEverything you judge out there mirrors what you haven't healed in yourself.\nLife can't be measured or tidied to perfection: let it go.",
    "Libra": "Other people are your mirror, but your voice counts too: don't let them decide for you.\nWatch out for chasing the perfect Life instead of living today's.\nNow is the only real thing; start with what you can do, today.",
    "Escorpio": "You hide your intensity behind a calm that isn't entirely real.\nYou look for power outside when the real power already lives in you.\nYou're blessed to light up the dark: don't hide your own **shadow**.",
    "Sagitario": "It may not look like it, but sometimes you're afraid of Life, and of it being beautiful.\nEvery goal you reach is only a springboard to the next.\nBe honest about your present: don't escape into the future on false optimism.",
    "Capricornio": "You're trying to please a strict figure you may not need to please anymore.\nRigidity isn't strength: it's **fear** in good clothes.\nDeep down, you feel better when you finally let go and allow yourself to bend.",
    "Acuario": "Your place isn't at the center, it's in the observer's gaze.\nYou dream of a better future, but your ideals need to land in the possible.\nDiscipline and patience are your real compass.",
    "Piscis": "Emotions drag you like a tide if you don't learn to handle them.\nYou absorb what isn't yours: telling it apart and letting it go is your essential work.\nDon't sacrifice yourself for others; setting **boundaries** is loving yourself too.",
  },
  sol: {
    "Aries": "Doubting your own power is the worst thing that can happen to you.\nYou're a born starter: brave, fast, and you live in the present.\nYou learn to chase what you want while weighing the consequences, without taking what isn't yours.",
    "Tauro": "You put your security in material things, and letting go is hard when Life asks for change.\nYou're solid ground: steady, reliable, able to build abundance and share it.\nYou need to validate yourself, beyond what you own.",
    "Géminis": "You tense up and lose yourself when things don't go your way, but you always find a way out.\nYour mind flies fast, learns fast and gets bored just as fast.\nLearn with your heart, not only with your head and its noise.",
    "Cáncer": "You give what you don't have, because you need to feel indispensable; that's your attachment.\nYou grow up when you understand nothing is a punishment and you dare to leave your shell.\nYour goal is holding yourself up without needing anyone in order to exist.",
    "Leo": "When you feel insignificant, you can sink into ego or into depression, hunting applause.\nYou light up whoever's near you with your natural confidence.\nLearn to **be**, simply for the pleasure of being, without needing anyone to clap.",
    "Virgo": "When chaos shows up, you take shelter in cleaning, tidying, or fixing other people's Lives.\nYou grow up by accepting, once and for all, that you control absolutely nothing.\nEverything has its own order, even when you don't see it at first glance.",
    "Libra": "You get tangled in your own emotions when your bonds lack objectivity.\nYou need people around you to feel validated, and that makes you dependent.\nGrow harmony in partnership without needing anyone to feel complete.",
    "Escorpio": "You have three levels: the one who worries, the one who hurts to hurt, and the eagle that rises without getting caught.\nThe first step is always accepting your own **vulnerability**.\nYou free yourself when you let go of what's already rotten, unattached to endings.",
    "Sagitario": "You cling to a single truth for fear of finding the lie behind it.\nWhat matters is the journey toward the promised land, not the destination.\nFor you, stopping the search feels almost like dying: keep searching, humbly.",
    "Capricornio": "You build walls to feel safe, and control becomes your obsession.\nYou grow up when you understand the only limits worth anything are the ones you choose.\nYour work is to discover your own worth and become your own **father**.",
    "Acuario": "You see emotions as a threat to the way you understand the world.\nYou grow up when you truly know and accept yourself, without fearing intimacy.\nYou're connected to everything and everyone, without losing your **individuality** for it.",
    "Piscis": "You absorb other people's pain until you drown, swinging between savior, victim and executioner.\nYou grow up when you stop wanting things to be different and learn to flow.\nHealing yourself is already your way of helping heal the world.",
  },
  luna: {
    "Aries": "You experience your mother as a rival, and now you depend only on yourself to feel safe.\nYou blow up fast and let go just as fast: tantrums that burn out on the spot.\nBehind your strength there's a deep **insecurity** you rarely show.",
    "Tauro": "You feel love in your body: food is security, money is affection.\nUnder stress you eat too much or stop eating altogether.\nIn time you discover real security comes from **inside**, not from outside.",
    "Géminis": "You think your emotions instead of feeling them, as if feeling were weakness.\nWhen you don't express yourself, you sabotage yourself with food, especially when you're sad.\nYou prefer variety to depth, even when it costs you the real bond.",
    "Cáncer": "Your mother taught you to depend on her with a love that also confused you.\nYou absorb other people's emotions as if they were yours, and it overwhelms you.\nLearn to set **boundaries** and to hold yourself up without depending on anyone.",
    "Leo": "You confuse affection with admiration: if people don't find you special, you feel unloved.\nYou withdraw into fantasy when the world doesn't clap loudly enough.\nLearn to love and admire yourself: that's where real love is.",
    "Virgo": "You grew up believing you'd only be loved if you were useful, and you lost your carefree childhood.\nYou love by giving concrete help, but you rationalize your own emotions so you don't have to feel them.\nIn time you have to learn to serve yourself, not only everyone else.",
    "Libra": "You learned to love for social appearances, not always for what you actually felt.\nYou over-analyze your emotions instead of just feeling them.\nLearn to say no and to stop depending on other people's recognition.",
    "Escorpio": "Your mother's love felt like losing yourself, and that's why you avoid intimacy.\nYou let yourself be emotionally “devoured” rather than feel abandonment.\nYour path runs through forgiveness, compassion, and learning to let go without fear.",
    "Sagitario": "Your mother taught you to flow and not to worry too much about the future.\nYou're nourished by traveling, exploring and helping others find meaning.\nWatch your optimism: sometimes it keeps you from really processing what you feel.",
    "Capricornio": "You learned love is earned with effort and achievement, never given.\nYou spend a good part of your Life chasing a recognition that may never arrive the way you want it.\nLearn to grow **tenderness** and to enjoy without always waiting for validation.",
    "Acuario": "Your mother was unpredictable, and you learned everyone is replaceable.\nFreedom became your only form of emotional security.\nWork on healthy endings and goodbyes, and dare to trust again.",
    "Piscis": "You grew up emotionally flooded, with nobody asking what you needed.\nYour hypersensitivity and your compassion can turn into self-pity if you don't tend them.\nEssentially, you have to learn to become your own **mother**.",
  },
  mercurio: {
    "Aries": "Your mind races to the future and **improvises** solutions while everything burns.\nYou start a thousand battles, but finishing them is another war.\nTalk, argue, let that sharp tongue out: keeping quiet isn't your thing.",
    "Tauro": "You think with your hands: you need to touch, taste, build in order to understand.\nYour mind is **stubborn** and methodical, and it holds on to the known.\nEverything you say you keep like treasure; your memory doesn't forget.",
    "Géminis": "Your curiosity is a **bottomless well** that hops from topic to topic.\nWithout depth you empty out inside; boredom hits you fast.\nTidy your mind before sleep and that speed becomes your superpower.",
    "Cáncer": "You confuse what you feel with what everyone else feels.\nYour memory keeps the whole **bloodline**: stories, patterns, family.\nWrite down what you're afraid people think of you; your real question is in there.",
    "Leo": "Your mind turns ideas into reality with warmth and **magnetism**.\nYou think with your heart, and one compliment can move all of you.\nYou lead slowly but firmly: your words lift whoever listens.",
    "Virgo": "You analyze, you classify, you look for the pattern behind every detail.\nYour **perfectionism** sharpens you, but it can also freeze you.\nWhatever you don't say out loud, your body ends up saying for you.",
    "Libra": "You try to understand everyone in order to hold the harmony between them.\nYou over-analyze, you hesitate, you avoid deciding because you hate conflict.\nYou need someone to challenge you, or your brilliant mind turns shallow.",
    "Escorpio": "There's always something more under the surface, and you sense it first.\nYou investigate before you speak, but when you speak, you **cut**.\nOnce you've decided what you think, nobody moves you.",
    "Sagitario": "Your mind looks for meaning, not just facts: you're a seeker of **truth**.\nYou speak unfiltered, enthusiastic, sometimes too honest.\nTeach, travel, share: that's where your mind actually lives.",
    "Capricornio": "You plan calmly and execute with **discipline** to the very end.\nYour humor, a little dark, comes from anticipating what could go wrong.\nYou respect rules because in them you find solid ground.",
    "Acuario": "You see trends before they exist: your mind lives ahead of time.\nYou stay objective even about what overwhelms everyone else.\nYou need silence so you don't get lost thinking without acting.",
    "Piscis": "You absorb the world like a sponge; your mind is **psychic**, not only rational.\nYou hide what you really think as a form of intimacy.\nYou blend reality and fantasy effortlessly: that's where your art is born.",
  },
  venus: {
    "Aries": "You love the way you conquer: fast, burning, no half measures.\nYou need **freedom** so your fire never goes out.\nYour love has to be rekindled constantly or it simply isn't love.",
    "Tauro": "You want a love that's built slowly and lasts forever.\nYou're deeply **sensual**, loyal, and you need to know you won't be left.\nWhat grows with time is the only thing you really trust.",
    "Géminis": "You love through words, curiosity and mental play.\nYou get bored fast, and commitment can feel like a cage.\nYour real bond is the living conversation, not the eternal promise.",
    "Cáncer": "You hide your vulnerability behind a steady, dignified front.\nYou need tenderness, care and safety to really open up.\nInsecurity wakes your jealousy; calm wakes your devotion.",
    "Leo": "You love big, with drama, luxury and unfiltered passion.\nYou need to be **admired**: if you're ignored, your ego empties out.\nYour loyalty is fierce with whoever you truly love.",
    "Virgo": "You love by pointing out what could be better, even when that stings.\nYou assess every relationship with your head: “is this working for me?”.\nDeep down you're only looking for approval, not perfection.",
    "Libra": "You look for beauty, harmony and being loved above all else.\nYou please so much that sometimes you lose yourself in the process.\nYour opinion matters: own it before anyone else does.",
    "Escorpio": "You love all or nothing, like a total **merging** with the other.\nYou know nothing lasts forever, and that gives you both fear and depth.\nYou refuse the superficial: you look for the essence or you don't look at all.",
    "Sagitario": "You live love as a journey of growth and shared purpose.\nYou need freedom, ethics and a partner who makes you venture out, not repeat.\nSmall doesn't stop you; petty does.",
    "Capricornio": "You want emotional and financial security before anything else.\nYou protect yourself with distance, but once committed you're **loyal** for Life.\nYou prefer quality, not quantity, in every emotional investment.",
    "Acuario": "You fall in love with ideas, with the different, with whatever fits no mold.\nYou need freedom; without it you dim or you run.\nYour sensuality is quiet, but your independence isn't negotiable.",
    "Piscis": "You long for a total, almost divine union with the other.\nWithout love you feel empty and adrift; with love, you dissolve completely.\nThe wounded attracts you, and sometimes that costs you dearly.",
  },
  marte: {
    "Aries": "You cut your own path and you're always the first to act.\nYour anger explodes fast and dies just as fast: you don't store it.\nLearn to pause and that brute force becomes real **power**.",
    "Tauro": "You act with patience and finish what you start, unhurried but unstopping.\nYou're not aggressive, but touch what's yours and you answer with **firmness**.\nYou don't forget offenses: your memory for grudges is long.",
    "Géminis": "Your energy is mental, quick, a thousand tabs open at once.\nWithout constant stimulation you scatter and lose focus.\nYou argue to release tension; watch out for provoking just to fight.",
    "Cáncer": "Emotional frustration fuels your energy more than anything else.\nYou protect your family **fiercely**, even though your biggest conflicts are born there too.\nThe better you know yourself, the less you need passive aggression.",
    "Leo": "You need to be first, and to conquer feeling you deserve it.\nYour magnetism inspires people, but blocked it frustrates and depresses you.\nLead without always needing the applause: that's where your real greatness is.",
    "Virgo": "You want everything done right, and you believe nobody does it better than you.\nYou work nonstop; letting yourself rest is hard.\nWatch out for the compulsive need to always be right.",
    "Libra": "You persuade and charm, but sometimes you confuse your desire with what others expect.\nYou act on expectations first and assert yourself afterwards.\nTrusting yourself without outside validation is your real challenge.",
    "Escorpio": "You act with strategy, patience and a power that rarely shows itself head-on.\nYou wait for the exact moment; you never strike without knowing it serves your end.\nYour mystery hides intentions only you control.",
    "Sagitario": "You throw yourself into adventure with boldness, optimism and little patience for routine.\nYour enthusiasm is **contagious**, even when it's reckless.\nFreedom isn't negotiable; commitment can feel suffocating.",
    "Capricornio": "You move with discipline and purpose toward higher and higher goals.\nYou're not impulsive; you only stop when the exhaustion is real.\nGrow some humility, or the achievement can turn hollow on you.",
    "Acuario": "You fight for high ideals and for doing what's never been done.\nYou lead better than you follow, and you question every established authority.\nYou swing between intense passion and total detachment.",
    "Piscis": "You're a warrior who acts from feeling, not from force.\nYour power is subtle, almost magical, and you motivate without confronting.\nYou need solitude to recharge that fluid, compassionate energy.",
  },
  jupiter: {
    "Aries": "You trust your Life mission with an enthusiastic, brave faith.\nYou lead naturally, but you need to learn to say no.\nYour optimism is contagious; your impulsiveness is the price to watch.",
    "Tauro": "You have a natural talent for building wealth by sowing patiently.\nYou understand that giving is what actually makes you receive.\nWatch attachment to material things: that's where your abundance jams.",
    "Géminis": "Your mind expands through words and close conversations.\nYou prefer selective depth to a shallow crowd.\nYour world is big, but you explore it close to home.",
    "Cáncer": "You find meaning in emotional security and in your family roots.\nYou're a host who makes everyone feel at home.\nYour abundance can even arrive through the home itself.",
    "Leo": "You're generous and charismatic, though deep down you expect gratitude.\nYou feel your role in the world matters, and you act accordingly.\nWatch the excess: your greatness doesn't always need to shine harder.",
    "Virgo": "Your confidence comes from achievement and accumulated knowledge.\nYou overwork and expect too much, from yourself and from everyone else.\nLearn to delegate: success also arrives in the second half of Life.",
    "Libra": "You need a partner in order to grow; your adventure is always relational.\nYou idealize the bond, looking for something beyond the physical.\nWatch out for promising more than you can hold.",
    "Escorpio": "You live crisis as a way of Life and come out of it wiser.\nThe hidden draws you: death, deep transformation.\nYou can see light where other people only see dark.",
    "Sagitario": "You look for a deep purpose behind every experience you live.\nYou have a strong sense of justice and a thirst for eternal truths.\nTravel, write, laugh loudly: that's your real expansion.",
    "Capricornio": "You're ethical, ambitious, and you want status with honor and responsibility.\nYou can be frugal about small things and generous about big ones.\nYour Life makes sense when you reach what you set out for.",
    "Acuario": "Your personal growth only makes sense if it gives something to humanity.\nYou question what's established and defend reform without fear.\nYou live more in the future than in the present: be careful not to get lost there.",
    "Piscis": "You look for merging with the divine, and you need to withdraw to find yourself again.\nYour compassion, especially toward the weak, makes you deeply loved.\nYou're not ambitious about material things: your search is purely spiritual.",
  },
  saturno: {
    "Aries": "You learned to fend for yourself too early, and that gave you a steel **resilience**.\nObeying is hard: you need to build your own rules before you can respect anyone else's.\nWatch out for hiding fear behind the need to always justify yourself.",
    "Tauro": "You came to build your own material and emotional **security**, brick by brick.\nThe fear of loss makes you cautious, tenacious and sometimes stubborn.\nYour lesson is loosening control enough to let pleasure and abundance in.",
    "Géminis": "Knowledge gives you security, but it doesn't replace the heart.\nYou learn to think with discipline, though doubt sometimes stops you before you speak.\nYour goal is balancing your mind with the emotional Life you tend to postpone.",
    "Cáncer": "You grew up learning to swallow what you felt; now it's your turn to build your own **emotional security**.\nFamily duty weighs, but it can't replace taking care of yourself.\nYou heal when you let yourself ask for help without feeling weak for it.",
    "Leo": "As a child you weren't seen as you were, and that left a huge thirst for **recognition**.\nYou can turn rigid or demanding exactly where you most wanted to shine.\nYour work is enjoying yourself without needing anyone's applause.",
    "Virgo": "Perfectionism makes you brilliant, and also merciless with yourself.\nYou learned everything has to be done “right”, and that weighs more than you let on.\nYou heal when you turn control into kind discipline, with room for humor.",
    "Libra": "You don't commit lightly: first you assess, measure, wait for safety.\nLove reaches you late but serious, with lessons in **fairness** and balance.\nWatch out for seeming cold when you're only being careful.",
    "Escorpio": "You carry an emotional intensity few can take, and even less patience for other people's laziness.\nYou know how to descend into hell — yours or someone else's — without breaking.\nYour challenge is learning **subtlety**, not only willpower.",
    "Sagitario": "You chase truth with a ferocious mental discipline, almost as a Life mission.\nDeep down you're trying to prove something to parents who never quite valued you.\nWatch out for getting so rigid you stop hearing other truths.",
    "Capricornio": "Ambition and status are your north, almost by inheritance from your father.\nYou grew up too early and now you can hardly imagine anyone without your discipline.\nLearn to laugh more and demand a little less of yourself.",
    "Acuario": "You want to change the world, but letting go of your own certainties is hard.\nYou feel the weight of “improving” society, even when it isn't your job.\nYour freedom arrives when you let other people follow their own rules.",
    "Piscis": "You feel the world loads you with a weight you can't trace.\nYou believe peace is only earned through sacrifice, never given.\nWith maturity you turn that wound into deep **spiritual wisdom**.",
  },
  urano: {
    "Aries": "You're one of the people who plant seeds of change, even if you have to start from zero again and again.\nYour independence is fierce, rebellious almost by nature.\nWatch the recklessness when revolution turns into fanaticism.",
    "Tauro": "You transform the material from within, changing the very idea of value.\nYou have a natural **magnetism**, often tied to art or music.\nWithout awareness, that change turns into stubbornness and jealousy.",
    "Géminis": "Your mind is brilliant and restless, always one step ahead.\nYou catch new ideas easily, though you rarely finish them.\nYou can feel disconnected from the people around you, as if you spoke another language.",
    "Cáncer": "You look for **emotional freedom** even inside your own family.\nYou see your parents as equals, not as authority, and you redefine what home means.\nYour intuition is almost psychic, though the ups and downs sometimes flood you.",
    "Leo": "You carry a revolution inside: you need to feel unique and you're not going to ask permission.\nYour confidence can tear down the old to build something freer.\nBe careful that force doesn't turn into ego with no brakes.",
    "Virgo": "You reinvent how to work and how to care for your body, unafraid of the new.\nYour practicality makes you a bridge between the technical and the natural.\nIf you fall out of balance, restlessness settles into your health and your work.",
    "Libra": "You redefine what a relationship is: **equality** matters more than the label.\nYou want to be yourself even inside the bond with another.\nSo much independence sometimes leaves you heartbroken more than once.",
    "Escorpio": "You live radical changes that stir everything up from the root.\nYour emotional intensity and your magnetism are undeniable.\nWithout inner work, that force can swing toward jealousy or revenge.",
    "Sagitario": "You want a freedom that fits in no dogma and no border.\nYou join the spiritual with the scientific without asking anyone's permission.\nYou travel suddenly, almost as a flight toward the truth.",
    "Capricornio": "You want to change the system, though part of you still obeys it.\nYou look to the future with your feet still anchored in tradition.\nWithout balance, that tension turns into pure personal ambition.",
    "Acuario": "Your mind opens doors other people couldn't even see.\nYou're inventive, eccentric, and you enjoy connecting with people who think differently.\nWatch out for staying in the idea and never landing it.",
    "Piscis": "You bring a quiet **revolution** out of the subconscious and the spiritual.\nYou turn the mystical into something tangible other people can understand.\nWithout clear boundaries, your sensitivity floods and looks for unhealthy escapes.",
  },
  neptuno: {
    "Aries": "Your dreams push you to fight for a **mission** bigger than you.\nYou look for souls to save with a limitless imagination.\nYou're warrior and poet at once, moved by compassion.",
    "Tauro": "You dream big, but you land every dream in the everyday.\nYour sense of beauty turns the material into something almost poetic.\nYou want beauty, harmony and stability all at once.",
    "Géminis": "Your imagination reinvents how we speak, travel and connect.\nYou write with an inventive sensitivity that's hard to match.\nCurious to the point of the esoteric, you always argue with passion.",
    "Cáncer": "Your attachment to family and home is almost sacred.\nYou protect and you give yourself, though fantasy sometimes pulls you away from the real.\nThe bond with your mother shapes a large part of your emotional world.",
    "Leo": "You idealize the people you love, and that can work against you.\nAnything with color, drama and intense Life attracts you.\nBe careful about projecting your fantasies onto real people.",
    "Virgo": "You live an inner fight between emotion and reason.\nYou can be absolute about good and evil, looking for purity in everything.\nWatch out for tearing down the old before you have anything new to put in its place.",
    "Libra": "You look for a kind of impossible **redemption** in the other.\nLove can become your drug and your escape route.\nDisappointment arrives when the other doesn't meet your ideal of perfection.",
    "Escorpio": "The dark attracts you, almost as if it were part of your identity.\nYou can feel flooded by collective emotions with no filter.\nYour real path is healing the unconscious, not obsessing over power.",
    "Sagitario": "You look for a mystical knowledge that expands your consciousness.\nYou chase a perfect world that never quite matches the real one.\nWatch out for **self-deception** dressed up as faith.",
    "Capricornio": "You know how to materialize the invisible, to give your visions concrete shape.\nYou feel the suffering of the people the system leaves behind.\nYour discipline turns compassion into real, practical help.",
    "Acuario": "Your mind is a bridge between science and spirit.\nYour intuition sparks genuinely new ideas.\nYou grasp the abstract with an almost detached calm.",
    "Piscis": "Your identity dissolves into something bigger than yourself: the One.\n**Compassion** is your mother tongue, but you need to learn boundaries.\nWithout them, isolation and addiction stalk your sensitivity.",
  },
  pluton: {
    "Cáncer": "Your loyalty to your own can be fierce, almost tribal.\nYou need to mature emotionally so you don't live from pure instinct.\nWatch out for resentment when the family wound doesn't close.",
    "Leo": "You live a peak of **ego**: you shine and you need it noticed.\nYour creativity is your purest form of power.\nLearn to play with that power without letting it own you.",
    "Virgo": "Your power lives in work done well, almost as an obsession.\nYou go deep into detail, even while understanding yourself is hard.\n“You're with me or you're out”: your way of setting boundaries is radical.",
    "Libra": "Your relationships are intense, almost a matter of Life and death.\nYou break with the models of love you inherited from your parents.\n**Power** has to be shared in a couple, never stockpiled by one.",
    "Escorpio": "You hit bottom in order to truly transform.\nTrauma marks you, but it also gives you the strength to break with the past.\nYou don't change the rules: you change the whole game.",
    "Sagitario": "You need freedom like air, and you firmly believe in humanity.\nYou want a better world and you don't give up trying.\nBe careful that faith doesn't turn into fanaticism.",
    "Capricornio": "You have a **leadership** force few can match.\nYou need to unseat your father's authority to set your own rules.\nYou rebel against any limit you didn't choose yourself.",
    "Acuario": "You feel the call to free the collective from old structures.\nYou help close a cycle of power that no longer works.\nWith others, you build a new social order.",
    "Piscis": "You discover the reality you thought was solid is only an **illusion**.\nYour awareness connects with the invisible damage we do to the planet.\nYou see what other people would rather not look at.",
  },
};

export const RESUMENES_CASA_EN: Partial<Record<CuerpoKey, Record<number, string>>> = {
  quiron: QUIRON,
  nodoNorte: NODO_NORTE,
  nodoSur: NODO_SUR,
  sol: {
    1: "You were born to be yourself, copying no one.\nYour **presence** magnetizes, but be careful not to confuse who you are with what you project.\nWithout a direction of your own, that shine turns bitter.",
    2: "Your real challenge is feeling secure from inside, not from what you own.\nYou're called to be your own **provider**, even if you came from little.\nYour worth is not your bank account.",
    3: "You shine when you think, speak and learn for yourself.\n**Knowledge** is your fuel, not an ornament.\nYou need freedom of movement, even inside a commitment.",
    4: "Your path is healing and outgrowing your father or mother inside you.\nFinding your own **home** — physical and symbolic — gives you identity.\nOnly by separating from your family do you finish being born.",
    5: "You need to feel special, seen and celebrated for what makes you unique.\nYour **creativity** — or your children — is how you expand into the world.\nYou'd rather have negative attention than none, so watch that impulse.",
    6: "Your wisdom is built in the everyday, not in the grand.\nBody and mind are **one**: caring for them is your Life discipline.\nWatch that service to others doesn't become self-sacrifice.",
    7: "You discover yourself through the other, and that's also your risk.\nWithout a healthy relationship **with yourself**, hunting other people's applause empties you.\nRemember: your opinion already counts on its own.",
    8: "You came to look your own **shadow** in the face and to transform without resisting.\nDeath, secrets and the hidden weave your path.\nThe deeper you go, the more you become yourself.",
    9: "You're after your own **philosophy of Life**, not one borrowed from anyone.\nTravel, literal or inner, expands and defines you.\nYou were born to inspire and teach while you keep learning.",
    10: "You're called to **rise** beyond the place you were born into.\nYour identity is built in public: you need recognition earned on your own merit.\nWatch out for chasing achievements only to win a parent's approval.",
    11: "Sociable outside, solitary inside: that's how you live your search for belonging.\nYou need a **group** that recognizes you without dissolving you into it.\nYour ambition is to change society, not just fit into it.",
    12: "You live between two worlds, the material and the **spiritual**, never quite choosing.\nYour Sun is called to serve something bigger than your own identity.\nYou shine quietly, even when you feel alone in a crowd.",
  },
  luna: {
    1: "You need to feel, constantly, that you're loved and enough.\nYour emotions shift like tides, and that **sensitivity** is your gift too.\nStop reshaping yourself to fit: be loyal to who you actually are.",
    2: "Food and possessions are your emotional shelter.\nYour security doesn't depend on what you **have**, but on what you are.\nThere will always be enough for you, even when you share.",
    3: "You feel by speaking: your words carry your emotions.\nYou need to learn to really listen, not just memorize.\nConstant **movement** is how you feel alive.",
    4: "You carry a deep family karma tied to your mother.\nWithout an emotional **home** you feel adrift your whole Life.\nLearn to say what you feel instead of waiting for people to guess.",
    5: "You fall in love with love itself, more than with actual people.\nYou need to be seen, applauded and **admired** to feel safe.\nYour children — or your creativity — are an extension of your own heart.",
    6: "Your body says what your emotions keep quiet.\nYou only feel worthy of love when you're **useful**, and that wears you out.\nRoutine and self-care are your anchor.",
    7: "You lose yourself in the other, looking for the security you don't give yourself.\nYou need the **bond** to feel Life makes sense.\nLearn to see yourself objectively, without projecting your mother onto your partner.",
    8: "You carry emotional wounds that aren't only yours: they're inherited.\nYou use **intimacy** as shelter from an insatiable emptiness.\nYour work is learning to nourish yourself, without asking anyone else to do it.",
    9: "Your intuition connects you to truths that go past reason.\nYou build your philosophy of Life out of what you **feel**, not only what you think.\nYou may feel more at home far from your own home.",
    10: "Your mother shaped who you were supposed to be before you could choose it.\nYou find shelter in nourishing and caring for the **public**, not only your own people.\nDon't forget to love yourself as much as you tend your reputation.",
    11: "Your friendships are your real chosen family.\nYou nourish people naturally, without forcing yourself to fit.\nSo much generosity also leaves you open to **betrayal**.",
    12: "You absorb other people's emotions as if they were yours; learn to let them go.\nYou and your mother carry a karmic bond that's asking to be healed.\nIn solitude and in dreams you find your real **intuition**.",
  },
  mercurio: {
    1: "Your mind is quick, curious and hungry for answers.\nLearning constantly is what gives you **security**.\nWhen something out in the world bothers you, look inward first.",
    2: "You need to understand how the material world works in order to feel safe.\nYour mind is a tool for generating **resources**, not only ideas.\nYou rarely go without, even though how you earn it keeps changing.",
    3: "You think fast, you speak even faster, and you almost always have something to say.\nYou need constant movement and new people to feel alive.\nFamily, especially **siblings**, sits at the center of your mind.",
    4: "You grew up somewhere reason weighed more than affection.\nYour roots and your family history feed a lifelong curiosity.\nLearning isn't a stage: it's your constant way of **steadying** yourself.",
    5: "Love, art and ideas take up your mind equally.\nYour creativity becomes your most honest way of **communicating**.\nPraise for your intelligence seduces you more than anything else.",
    6: "You're a born fixer: you see how to improve anything.\nYou need your mind occupied or the details eat you.\nYour health and your mind are deeply **connected**: tend them together.",
    7: "You look for a partner for your mind, not only for your heart.\nFinding someone who fills you completely is hard, though you commit anyway.\nLearn to communicate without falling into constant **over-analysis**.",
    8: "Your mind digs into the hidden, the forbidden, what others don't dare look at.\nYou share knowledge easily, but you keep your **emotions** to yourself.\nBe careful with contracts, inheritances and anything that taxes your nervous system.",
    9: "Your mind looks for the laws holding existence up, not loose facts.\nIf something doesn't strike you as **logical**, you tend to dismiss it as unreal.\nTeaching what you learn is an essential part of your purpose.",
    10: "Your career needs your intelligence recognized, not only your effort.\nYou change direction often, always learning about yourself and your surroundings.\nYou want to be seen as **sharp** and capable, the way you saw one of your parents.",
    11: "Your friendships expand your ideas and your sense of who you are.\nYou try to decide from **logic**, not emotion, for the good of the group.\nWatch out for overthinking everything until your mind loses its quiet.",
    12: "Saying what you think is hard, and inside everything feels foggy.\nWithout exploring your **unconscious**, you can't fully understand yourself.\nNegative thoughts sink you; positive ones save you.",
  },
  venus: {
    1: "You shine naturally, but your light shouldn't depend on anyone confirming it.\nWatch out for hiding your real face behind a mask of **sweetness**.\nYou already have worth, with nobody needing to remind you.",
    2: "You draw **abundance** almost effortlessly, especially through your relationships.\nBut your worth is not your bank account.\nEnjoy the wealth without attachment or fear of losing it.",
    3: "You seduce with words, you charm by talking.\nShort trips and getaways feed your relationships.\nBe careful not to decorate the truth just to win **approval**.",
    4: "Your home is your emotional shelter, and you build belonging inside it.\nYour **mother's** imprint shapes how you understand love and family.\nYour deepest romantic fulfillment usually arrives late, with roots well planted.",
    5: "You live for intense romance, almost as if that were the only way to feel alive.\nYour creativity and your children are a source of joy and also a mirror.\nBe careful not to confuse **drama** with actually being alive.",
    6: "You love by serving: you care with gestures before words.\nYour eye for detail looks for **harmony** even in the everyday.\nIf you don't handle conflict, your body ends up carrying what your heart keeps quiet.",
    7: "You really discover yourself in partnership; without a bond, something feels missing.\nWatch out for idealizing so much that no real human measures up.\nYou love the idea of **love**; learn to love its daily work too.",
    8: "The forbidden attracts you, the intense, what isn't quite available.\nYour **magnetism** is powerful, and so is your ability to heal in the dark.\nFulfillment arrives when you stop looking outside for what you already have inside.",
    9: "You find peace in your own philosophy of Life, not in anyone else's dogma.\nLove reaches you while traveling, crossing borders or cultures.\nYour **honesty** makes you a teacher, even when diplomacy is missing.",
    10: "You shine with charm where other people chase power and recognition.\nYour relationship with your mother shapes your **ambition** more than you think.\nYou look for a partner who adds status, but the real achievement is yours.",
    11: "Your circle admires you, and you grow inside it.\nBut your worth shouldn't depend on how loudly people clap.\nWatch out for losing yourself in social media, or swapping bonds nonstop.",
    12: "You dream of an absolute love, almost impossible to find on Earth.\nThat's why you sometimes love what can't love you back, dodging the disappointment of real love.\nIn **solitude** and quiet service you find your purest way of loving.",
  },
  marte: {
    1: "You have energy for two Lives and the courage to cut the path yourself.\nYour anger explodes fast, but it dies just as fast.\nLearn to channel that **fire**; that's where your real power is.",
    2: "Money is hard for you to earn and quick to slip through your hands.\nYou aren't your possessions: your real power is in your essence.\nEvery bust is really an invitation to **start over**.",
    3: "Your tongue is fast, sharp and sometimes unfiltered.\nSpeaking or writing is your therapy; forced silence piles up inside you.\nWatch your **speed**, behind the wheel and in Life.",
    4: "You grew up among household tensions and the shadow of a domineering father.\nYou look for a home of your own to escape patterns that repeat until they're healed.\nClarity about what you really want arrives later, but it arrives.",
    5: "You feel alive creating, competing, risking.\nIn love you're passionate and intense, sometimes too **impulsive**.\nWith your children, be careful not to confuse your freedom with theirs.",
    6: "Your body is your temple of discipline and endurance.\nYou work better alone than under anyone's orders.\nWatch the **perfectionism**: it can turn into an accident or burnout.",
    7: "You try to assert yourself through the other, and without their validation you get frustrated.\nYou can be a conqueror, but watch out for projecting your **anger** onto whoever you love most.\nWhen you're aware, mutual challenge becomes stimulation, not war.",
    8: "You chase what you want without looking back, even in the most extreme crisis.\nYour sexual **magnetism** and your strength in the abyss are almost supernatural.\nTransform that intensity or you risk it consuming you.",
    9: "You need to live it to believe it; theory alone isn't enough.\nYou challenge mental, physical and spiritual limits without fear.\nYou're a brave **explorer** and a guide for the people around you.",
    10: "Your whole energy pours into ambition and recognition.\nYou learned the world demands a fight, so you fight to stand out.\nBe careful that leadership doesn't become **tyranny**.",
    11: "You lead teams and look for recognition inside the collective.\nYour individuality sometimes clashes with the need to cooperate.\nWatch out for **betrayals** or rivalries among like-minded peers.",
    12: "You keep a silent war that rarely comes to light.\nWithout physical outlets, that energy turns against you.\nWell channeled, it makes you a fierce **protector** of other people.",
  },
  jupiter: {
    1: "You're a born philosopher looking for the meaning of everything you live.\nYour enthusiasm is contagious, though you sometimes lack the steadiness to finish what you start.\nBe careful not to get excessive in your **pleasures** or your certainties.",
    2: "You have the luck of doing a lot with a little.\nYour **generosity** and enthusiasm inspire the people around you.\nJust be careful not to measure your worth by what you own.",
    3: "Your mind is a bottomless well of ideas, always wanting to learn more.\nYou inspire with your words, even when action doesn't follow them.\nWith siblings, watch the silent **rivalry** over who's “the best”.",
    4: "Your home can be a source of fortune and of faith.\nYou inherit more than assets: you inherit a wide view of Life.\nJust be careful not to trap your soul in family **obligations**.",
    5: "Your motto is “more is better than enough”.\nYou feel alive creating and risking big.\nIn love you need **exploration**; routine suffocates you.",
    6: "You find purpose serving, caring, healing other people.\nWatch the extremes: either you neglect yourself or you obsess over control.\n**Illness**, if it comes, is usually a call to return to yourself.",
    7: "You idealize love so much that reality rarely reaches your dream.\nYou live between the wish for freedom and the need for shared security.\nWhatever happens, you never stop believing in **love**.",
    8: "You cross the emotional hells protected by an almost inexhaustible **faith**.\nMoney and other people's support tend to arrive when you least expect them.\nFor you, even suffering hides a promise of renewal.",
    9: "You look for the meaning of everything, almost compulsively.\nYour wisdom, applied to real Life, becomes a guide for other people.\nBe careful not to turn your truth into rigid **dogma**.",
    10: "You need to be seen and recognized for what you achieve.\nProfessional doors open almost on their own for you.\nStay **grounded**: promotions with no solid base collapse fast.",
    11: "Groups seek you out as a source of inspiration and guidance.\nYour optimism holds you up even when reality disappoints.\nWatch out for committing to so much that you **finish** nothing.",
    12: "You're the “guardian angel”: doors open for you even in a crisis.\nYour **faith**, more than religious, is a deep connection with your essence.\nEven your most powerful enemies can turn into allies.",
  },
  saturno: {
    1: "You grew up too fast, carrying responsibilities that weren't yours.\nBehind your **mask** of coldness hides the fear of not being enough.\nYour mastery arrives late: the second half of Life is where you finally bloom.",
    2: "You come from a bloodline marked by scarcity and the fear of never having enough.\nYou confuse your worth with what you own, and that keeps you trapped.\nYour mastery is **abundance** lived without guilt or fear.",
    3: "As a child you felt misunderstood, judged for asking and for being different.\nYou learned to keep quiet and to protect yourself with distance and precision.\nYour mastery is becoming a deep **communicator**, able to truly listen.",
    4: "You grew up without ever feeling a real home, under a cold authority that demanded without holding you.\nYou feel rootless and you doubt your own worth.\nYour work is building an inner **home** that's a sanctuary, not a prison.",
    5: "They didn't let you be a child, so you learned to hide who you are.\nThe fear of looking ridiculous blocks your creativity and the way you love.\nYour mastery is creating and showing yourself without asking permission or applause.",
    6: "You believe you have to be useful to deserve love, and that wears you out.\nPerfectionism gets into your body, into your bones and skin.\nYour mastery is serving from awareness, not from compulsion.",
    7: "You fear intimacy and you sabotage your own bonds without meaning to.\nYou pick partners who are larger than life or far away, so you can feel small and safe.\nYour mastery is born from learning to be alone before loving as an equal.",
    8: "Letting anyone truly know you is hard.\nYou control so you don't have to face your own shadow and your old wounds.\nYour mastery arrives when you release control and accept **transformation**.",
    9: "You grew up with the image of a punishing God and a guilt that isn't yours.\nThe fear of failing makes you avoid risk and adventure.\nYour mastery is building a **spirituality** of your own: kind, and freeing.",
    10: "You're afraid of being seen as a failure, so you chase status and recognition.\nYour self-esteem is born wounded, and the bond with your mother shapes your professional path.\nYour mastery arrives late: a **calling** born from the soul, not the ego.",
    11: "You want to belong and you're also afraid of losing your identity in the group.\nYou're slow to trust, but once you do, you're faithful for Life.\nYour mastery is giving your unique gift without stopping being you.",
    12: "You protect yourself with coldness because your emotions are intense and you're afraid of losing control.\nIsolation and restriction become your greatest teachers.\nYour mastery is the humility of accepting that not everything can be controlled.",
  },
  urano: {
    1: "You define yourself by an absolute need for freedom and independence.\nYou change course all at once when something feels false or confining.\nThere's something electric in you, and your path is discovering your own truth.",
    2: "Money only matters to you because it buys freedom, not security.\nThe harder you try to fit into conventional stability, the more your finances shake.\nYour abundance is mobile, original and tied to your own individuality.",
    3: "You need to build your own way of understanding the world, inheriting nobody's frame.\nYour mind jumps, runs ahead, and sometimes nobody can keep up.\nThe challenge is a mind that's free and also **steady**.",
    4: "You're the black sheep who doesn't repeat the family script.\nHome felt unpredictable, so now you need space and freedom to feel safe.\nYour work is building inner foundations: not rigid, but stable.",
    5: "You're almost obliged to create something that's only yours, with no formula.\nYou're afraid that if people see how different you are, they won't love you.\nYour fulfillment is in what others still call **strange**, or ahead of its time.",
    6: "Your daily Life is a constant mirror of what you haven't resolved inside.\nIf you don't set boundaries in time, your body ends up speaking for you.\nLearn to listen to it before it has to shout.",
    7: "You need living relationships, not cages of habit and not fusion.\nThe fear of abandonment lives right next to your fierce need for freedom.\n**Freedom** has to live inside the relationship, or the relationship breaks.",
    8: "You live abrupt endings that close whole chapters at once.\nYour drives are intense and want to transcend, not only to satisfy.\nYou have the gift of reinventing yourself completely, again and again.",
    9: "You refuse imposed beliefs; you need a truth built your own way.\nYour mind is progressive, ahead of its time, almost prophetic.\nTravel isn't escape: it's a **catalyst** for your own inner revolution.",
    10: "You don't work only for money: your career needs meaning and coherence with your values.\nSudden changes of professional direction are part of your path.\nYou're here to reform the system from inside, your way.",
    11: "You dream of unity: feeling that we're all one.\nYour friends are catalysts of transformation, sometimes more family than your own blood.\nYou're the engine of change inside the groups you belong to.",
    12: "You perceive layers of reality other people can't even imagine.\nYou need periodic solitude to recalibrate, or Life will impose it on you.\nYour gift is building bridges between the conscious and the invisible.",
  },
  neptuno: {
    1: "You dissolve into other people's needs until you lose your own self.\nWatch the leaks: alcohol, fantasy, the role of victim or savior.\nAt your best, you're a **creator** who brings ideas out of nothing.",
    2: "Your relationship with money is tinted with guilt, or with feeling entitled to everything.\nYou undervalue your own gifts, which brings you more insecurity than stability.\nYour real treasure is internal, not material.",
    3: "Your analytical mind scatters, but you perceive what others don't see under the words.\nYou can fool yourself into thinking ideas are yours when you absorbed them from someone else.\nYour gift is captivating with language, emotion and the **abstract**.",
    4: "Feeling rooted is hard; you long for a home that always seems out of reach.\nYou idealize a past that maybe never was the way you remember it.\nLate in Life you'll finally go looking for your soul's lost home.",
    5: "You have an enormous capacity to create and express what others only sense.\nWatch out for idealizing the beloved, or sacrificing your creativity to please.\nPleasure can seduce you too far: careful with gambling and excess.",
    6: "You're the guardian angel who sinks into other people's problems.\nYour nervous system is an extremely sensitive thermometer.\nAt your best, you have genuinely **healing** hands.",
    7: "You idealize your partners so much that you stop seeing who they actually are.\nYou sacrifice yourself chasing a love that's never recognized or repaid.\nWatch out for the eternal **savior** syndrome: it attracts people who don't want saving.",
    8: "You try to transcend your limits through sex, intimacy and death.\nYou're never entirely satisfied: you'd rather fantasize than enjoy what you have.\nYour gift is a deep psychic connection with the invisible.",
    9: "You look for redemption in philosophies and gurus, and you're disappointed again and again.\nThe faith you need is never outside: it's in you.\nYour gift is an open intuition that can touch the poetic and the unreachable.",
    10: "Being visible triggers your deepest vulnerability.\nYou can be idolized or end up at the center of a scandal: your secrets rarely stay hidden.\nYou live your career as **service**, not as plain ambition.",
    11: "You're the group's shaman: you find your union with Life through serving others.\nWatch out for losing yourself in other people's causes until you forget your own.\nYour challenge is defining your own path clearly.",
    12: "You're a sponge that soaks up the invisible, sometimes with no idea what to do with it.\nEscapism and confusion stalk you if you don't learn to clear yourself in solitude.\nYour gift, if you grow it, is touching your own inner **teacher**.",
  },
  pluton: {
    1: "You don't know middle ground: you live intensely, absolutely, obsessively.\nYou destroy before you'll feel vulnerable, or you sacrifice yourself.\nYou have an enormous power of **regeneration**, if you learn not to live in the drama.",
    2: "You have to go past money to discover what really moves you.\nPluto can take everything from you exactly when you think you've reached the top.\nYour real strength is born from dropping attachment and answering a crisis clearly.",
    3: "Your mind goes straight to the core of things, even the taboo ones.\nYour words have real power: they can heal or they can wound.\nWith maturity you learn to listen more and speak less.",
    4: "You carry terror and destruction lived through in your earliest home.\nThe fear of everything blowing up makes you over-control everything, including yourself.\nYour greatest gift is an absolute capacity to **regenerate** and to heal your bloodline.",
    5: "You swing between needing to shine and hiding your creativity for fear of criticism.\nYou try to prove power in order to feel loved, and that can wear you down.\nYour lesson is discovering your singularity without depending on applause.",
    6: "You live demanding perfection and control of yourself, even over what you can't control.\nYou help people, but often expecting gratitude or recognition back.\nYour body warns you when you repress too much: your mastery is serving without dominating.",
    7: "You carry deep wounds of abandonment and betrayal that shape how you love.\nYour relationships are never superficial: they're a trip to the underworld and back.\nYour gift is walking with people through their own **deaths** and rebirths.",
    8: "You live with an inner dissatisfaction that's hard to fully settle.\nYour drives explode if you repress them; they run you if you deny them.\nIn a crisis you become extraordinary: a guide for anyone crossing their own darkness.",
    9: "You perceive in a way nobody else does, but getting the world to understand your vision is hard.\nYou cling to dogma, or chase truth almost fanatically.\nIn time you understand the truth you're after was always inside you.",
    10: "You need to be in charge, and delegating or letting go of control is hard.\nYour self-esteem got tied to achievement, an inheritance from demanding, hard parents.\nReal **leadership** arrives when you stop needing power to feel worth something.",
    11: "You feel you don't fit, and you're deeply afraid of being alone.\nFriendships betrayed in childhood left a wound you're still handling.\nWith maturity you become the leader of groups that do transform reality.",
    12: "You'll live through cyclical destructions that force you to be reborn transformed.\nYour greatest fear is losing control, and that's exactly where your greatest power lives.\nMaturity is learning to trust and to surrender, despite the pain.",
  },
};
