// ─────────────────────────────────────────────────────────────────────────
// RESÚMENES de los arquetipos: 2-3 frases memorables que se muestran ARRIBA
// del texto completo en el popup «saber más» (/metodo/astrologia/cartaAstral).
// El usuario lee el resumen y decide si sigue leyendo el texto entero.
//
// Se combinan con el texto en textoEstatico() (astrologiaTextosApi.ts): si el
// texto no trae ya un separador «---», se antepone el resumen + «---».
//
// AUTO-GENERADO. Para editar a mano, cambia el resumen aquí (o mete tu propio
// «---» dentro del texto en astrologiaTextos.ts / desde el editor de admin).
// ─────────────────────────────────────────────────────────────────────────
import type { CuerpoKey } from "./astrologiaData";

export const RESUMENES_SIGNO: Partial<Record<CuerpoKey, Record<string, string>>> = {
  quiron: {
    "Aries": "Duele empezar, duele ser tú.\nTu **valentía** nació herida, pero es tu mayor don.\nSana tu imagen y camina como quieras, no como te dijeron.",
    "Tauro": "Sientes que no mereces abundancia ni placer.\nTu cuerpo y tu valor no dependen de lo que tienes.\nAma tu carencia y descubrirás tu propia riqueza.",
    "Géminis": "No te escucharon, y ahora crees que no vales.\nTu voz herida esconde un don: comunicar lo diferente.\nHabla a tu manera, aunque sea distinta.",
    "Cáncer": "No sentiste hogar, y por eso huyes de tu propio interior.\nCuidar de otros no cura el vacío si no abrazas a tu niño interior.\nTu don es dar el refugio que nunca tuviste.",
    "Leo": "No te dejaron brillar tal como eras.\nTu creatividad duele, pero es tu don más luminoso.\nExprésate, aunque tiemble la vergüenza.",
    "Virgo": "Sientes que nunca haces suficiente ni lo bastante bien.\nLa culpa por existir en la Tierra te paraliza.\nTu don es cuidar; empieza por perdonar tu **imperfección**.",
    "Libra": "Amar duele porque temes ser rechazado y abandonado.\nProyectas en el otro lo que no te atreves a mirar en ti.\nTu don es compartirte sin perderte.",
    "Escorpio": "Absorbiste el dolor y el control desde niño.\nTemes tu propio poder tanto como el ajeno.\nLa **intimidad**, bien mirada, es tu puerta a la transformación.",
    "Sagitario": "Perdiste la confianza en la Vida y en un sentido mayor.\nBuscas respuestas fuera cuando la verdad está en seguir explorando.\nTu don es la fe que renace después del dolor.",
    "Capricornio": "Te sentiste pequeño, juzgado, incapaz de lograr nada.\nEl miedo a fracasar te frena antes de intentarlo.\nTu don es ayudar a otros a encontrar su lugar en el mundo.",
    "Acuario": "Fuiste diferente, y eso te costó el rechazo del grupo.\nTe sientes solo, como si no pertenecieras a la humanidad.\nTu don es sanar lo colectivo desde tu propia rareza.",
    "Piscis": "Cargas un dolor que viene de antes de nacer, incluso el del linaje.\nSientes que no mereces ser feliz ni fundirte con nada.\nTu don es servir a la humanidad sanando primero tu propia herida.",
  },
  nodoNorte: {
    "Aries": "Naciste para descubrir quién eres, sin pedir permiso.\nDeja de buscar aprobación externa: **avanza** aunque te lo discutan.\nTu camino se abre cuando actúas por ti mismo.",
    "Tauro": "Construye tu propia estabilidad, sin depender de nadie.\nAprende a disfrutar del cuerpo y de la Vida simple.\nSuelta el drama; la abundancia empieza en ti.",
    "Géminis": "Aprende a hablarle a cada uno en su propio idioma.\nNo sabes más que nadie: escucha antes de enseñar.\nTu destino es ser puente entre mundos distintos.",
    "Cáncer": "Construye tu propio templo interior antes que nada.\nSé tu propia familia antes de cuidar de otra.\nSana tu árbol genealógico para encontrar tu hogar.",
    "Leo": "Naciste para crear y mostrar tu esencia al mundo.\nNo busques la perfección: **materializa** con lo que ya tienes.\nSigue a tu corazón, no al aplauso del grupo.",
    "Virgo": "Tu lección es cuidar el cuerpo, la mente y a los demás con equilibrio.\nEl servicio y la sanación son tu camino, no tu castigo.\nOrdena tu Vida sin dejar de ser generoso.",
    "Libra": "Aprende a compartir tu Vida sin perder tu esencia en ello.\nCeder no es perderte: es la puerta a tu expansión.\nLa felicidad crece cuando aprendes a estar en pareja de verdad.",
    "Escorpio": "Mírate de frente: tu sombra también es tu tesoro.\nAprende a fusionarte con otro sin perder tu centro.\nRenace, una y otra vez, como el **ave fénix**.",
    "Sagitario": "Busca tus propias respuestas, no las heredadas.\nLa experiencia te enseña más que cualquier información.\nExplora lejos, luego comparte lo que descubriste dentro.",
    "Capricornio": "Sal al mundo y encuentra tu vocación real.\nConviértete en una autoridad responsable, no en un tirano.\nTu poder solo vale si sirve a algo más grande que tú.",
    "Acuario": "Comparte tu don creativo con el colectivo, sin miedo al juicio.\nSé auténtico antes que aplaudido.\nAprende a escuchar y crecer a través del grupo.",
    "Piscis": "Profundiza tu conexión espiritual más allá de lo material.\nSiente, aunque el caos y la falta de estructura te asusten.\nAyuda desde la **compasión**, no desde el arreglo o el esfuerzo.",
  },
  nodoSur: {
    "Aries": "Vienes de vivir centrado solo en ti.\nEl otro fue siempre un medio para tus fines.\nAhora toca mirar más allá de ti mismo.",
    "Tauro": "Te aferras a la seguridad material y rechazas el cambio.\nTu autosuficiencia te impidió depender de nadie.\nToca soltar el apego y mirar hacia dentro.",
    "Géminis": "Tu mente dispersa salta de una cosa a otra sin profundizar.\nComunicaste ideas ajenas, nunca las propias.\nEs hora de dejar de repetir y empezar a pensar por ti mismo.",
    "Cáncer": "Viviste atrapado en la familia y nunca saliste a vivir tu propia Vida.\nConfundiste el refugio con una casa, no contigo mismo.\nEnfréntate al mundo: ahí está tu **poder personal**.",
    "Leo": "Viviste creyéndote el centro del mundo.\nTe cuesta verte como una persona más entre las demás.\nViniste a dar luz a otros, no solo a brillar tú.",
    "Virgo": "Vives sin parar, anestesiado en el trabajo y la lógica.\nNo crees en nada que no puedas controlar.\nDeja de huir del alma sirviendo solo con las manos.",
    "Libra": "Aprendiste a entregarte tanto que te perdiste a ti mismo.\nAhora te cuesta decidir sin mirar lo que otros quieren.\nToca recuperar tu propia voz.",
    "Escorpio": "Dependiste de otros para sostener tus deseos.\nDudas de tu propio valor y de tu fuerza independiente.\nSal del drama y confía en tus propios recursos.",
    "Sagitario": "Tu mente libre e intuitiva se aferra a sus propias creencias.\nTe aíslas si nadie piensa como tú.\nSuelta el apego a tener siempre la razón.",
    "Capricornio": "Vienes de haber tenido mucho poder y aún lo persigues.\nTe anestesias trabajando, buscando siempre reconocimiento.\nSuelta la necesidad de demostrar y desbloquea tu camino.",
    "Acuario": "Viviste en la mente y en el grupo, casi sin individualidad.\nTe sientes diferente, pero no siempre eres auténtico.\nToca dejar de actuar la rareza y ser tú de verdad.",
    "Piscis": "Fuiste experto en lo espiritual, pero extraño a lo terrenal.\nVives en tu mundo interior, lejos de lo ordinario.\nLo real, aunque asuste, también es sagrado.",
  },
  ascendente: {
    "Aries": "Avanzas directo y con fuerza, pero cuidado con dejarlo todo a medias.\nTu creatividad necesita salida propia, sin depender de aplausos.\nEl **movimiento** físico es tu mejor aliado para transformar tu energía.",
    "Tauro": "Construyes con método, pero te aferras a rutinas que ya no te sirven.\nSueltas el resultado y te quedas con el camino, no con lo conseguido.\nTu cuerpo te habla antes de gritar: escúchalo a tiempo.",
    "Géminis": "Por fuera pareces tranquilo, por dentro hay ruido mental sin parar.\nTu curiosidad es enorme, pero disperso te vacía: elige y profundiza.\nBaja de la cabeza al corazón para sentir de verdad.",
    "Cáncer": "Tu timidez es una coraza que congela el dolor en vez de protegerte.\nSientes lo ajeno como propio: aprende a diferenciarlo y soltarlo.\nNo puedes nutrir a otros si primero no te **nutres** a ti.",
    "Leo": "Brillas y atraes, pero el verdadero liderazgo no necesita súbditos.\nBuscas validación fuera, y por más que la recibas, la sed no se calma.\nLa única validación que de verdad cuenta es la que te das **tú mismo**.",
    "Virgo": "Nunca te sientes del todo suficiente, y eso te condiciona por dentro.\nTodo lo que juzgas fuera es un espejo de lo que aún no sanas en ti.\nLa Vida no se mide ni se ordena a la perfección: suéltalo.",
    "Libra": "Los demás son tu espejo, pero tu voz también cuenta: no dejes que decidan por ti.\nCuidado con perseguir la Vida perfecta en vez de vivir la de hoy.\nEl ahora es lo único real; empieza por hacer lo que puedas, hoy.",
    "Escorpio": "Ocultas tu intensidad tras una calma que no es del todo real.\nBuscas poder fuera cuando el verdadero poder ya vive dentro de ti.\nEstás bendecido para iluminar lo oscuro: no escondas tu propia **sombra**.",
    "Sagitario": "Aunque no lo parezca, a veces le temes a la Vida y a que pueda ser bonita.\nCada meta que alcanzas es solo un trampolín hacia la siguiente.\nSé sincero con tu presente: no escapes al futuro con falso optimismo.",
    "Capricornio": "Buscas complacer a una figura estricta que quizás ya no necesitas complacer.\nLa rigidez no es fortaleza: es **miedo** bien vestido.\nEn el fondo, te sientes mejor cuando por fin sueltas y te permites ser flexible.",
    "Acuario": "Tu lugar no está en el centro, sino en la mirada del observador.\nSueñas con un futuro mejor, pero tus ideales necesitan aterrizar en lo posible.\nLa disciplina y la paciencia son tu verdadera brújula.",
    "Piscis": "Las emociones te arrastran como una marea si no aprendes a gestionarlas.\nAbsorbes lo que no es tuyo: diferenciarlo y soltarlo es tu tarea esencial.\nNo te sacrifiques por otros; poner **límites** también es amarte.",
  },
  sol: {
    "Aries": "Dudar de tu propio poder es lo peor que puede pasarte.\nEres un iniciador nato: valiente, rápido, y vives en el presente.\nAprendes a perseguir tus deseos midiendo las consecuencias, sin tomar lo que no te pertenece.",
    "Tauro": "Pones tu seguridad en lo material, y te cuesta soltar cuando la Vida pide cambio.\nEres tierra firme: estable, fiable, y capaz de construir abundancia para compartirla.\nNecesitas validarte a ti mismo, más allá de lo que posees.",
    "Géminis": "Te tensas y te pierdes cuando las cosas no van como tú quieres, pero siempre encuentras salida.\nTu mente vuela rápido, aprende y se aburre igual de rápido.\nAprende con el corazón, no solo con la cabeza y su ruido mental.",
    "Cáncer": "Das sin tener, porque necesitas sentirte imprescindible; ahí está tu apego.\nMaduras cuando entiendes que nada es un castigo y te atreves a salir de tu caparazón.\nTu meta es sostenerte a ti mismo sin depender de nadie para existir.",
    "Leo": "Cuando te sientes insignificante, puedes hundirte en el ego o en la depresión buscando aplausos.\nIluminas a quien tienes cerca con tu confianza natural.\nAprende a **ser**, simplemente por el placer de ser, sin necesitar que nadie te aplauda.",
    "Virgo": "Cuando el caos aparece, te refugias en limpiar, ordenar o arreglar la Vida de los demás.\nMaduras al aceptar, de una vez, que no controlas absolutamente nada.\nTodo tiene su propio orden, aunque no lo entiendas al primer vistazo.",
    "Libra": "Te enredas en tus propias emociones cuando falta objetividad en tus vínculos.\nNecesitas rodearte de gente para sentirte validado, y eso te hace dependiente.\nCultiva la armonía en pareja sin necesitar a nadie para sentirte completo.",
    "Escorpio": "Tienes tres niveles: el que se preocupa, el que hiere para herir, y el águila que se eleva sin quedar atrapada.\nEl primer paso siempre es aceptar tu propia **vulnerabilidad**.\nTe liberas cuando sueltas lo que ya está podrido, sin apego a los finales.",
    "Sagitario": "Te aferras a una única verdad por miedo a descubrir la mentira detrás.\nLo importante es el viaje hacia la tierra prometida, no el destino.\nPara ti, dejar de buscar se siente casi como morir: sigue buscando, con humildad.",
    "Capricornio": "Construyes muros para sentirte a salvo, y el control se vuelve tu obsesión.\nMaduras cuando entiendes que los únicos límites que valen son los que tú eliges.\nTu tarea es descubrir tu propio valor y convertirte en tu propio **padre**.",
    "Acuario": "Ves las emociones como una amenaza a tu manera de entender el mundo.\nMaduras cuando te conoces y te aceptas de verdad, sin miedo a la intimidad.\nEstás conectado con todo y con todos, sin perder por eso tu **individualidad**.",
    "Piscis": "Absorbes el dolor ajeno hasta ahogarte, oscilando entre salvador, víctima y verdugo.\nMaduras cuando dejas de querer que las cosas sean distintas y aprendes a fluir.\nSanarte a ti mismo ya es tu forma de colaborar en sanar el mundo.",
  },
  luna: {
    "Aries": "Vives a tu madre como una rival, y ahora dependes solo de ti mismo para sentirte a salvo.\nExplotas rápido y sueltas igual de rápido: berrinches que se queman al momento.\nDetrás de tu fuerza hay una **inseguridad** profunda que rara vez muestras.",
    "Tauro": "El amor lo sientes en el cuerpo: comida es seguridad, dinero es afecto.\nBajo estrés, comes de más o dejas de comer del todo.\nCon el tiempo, descubres que la verdadera seguridad viene de **dentro**, no de fuera.",
    "Géminis": "Piensas tus emociones en vez de sentirlas, como si sentir fuera debilidad.\nCuando no te expresas, te saboteas con comida, sobre todo si estás triste.\nPrefieres la variedad a la profundidad, aunque eso te cueste el vínculo real.",
    "Cáncer": "Tu madre te enseñó a depender de ella con un amor que también confundía.\nAbsorbes las emociones ajenas como si fueran tuyas, y eso te desborda.\nAprende a poner **límites** y a sostenerte sin depender de nadie.",
    "Leo": "Confundes afecto con admiración: si no te sienten especial, sientes que no te quieren.\nTe retiras a la fantasía cuando el mundo no te aplaude lo suficiente.\nAprende a amarte y admirarte tú mismo: ahí está el amor verdadero.",
    "Virgo": "Creciste creyendo que solo te querrían si eras útil, y perdiste tu infancia despreocupada.\nAmas dando ayuda concreta, pero racionalizas tus propias emociones para no sentirlas.\nCon el tiempo, tienes que aprender a servirte a ti mismo, no solo a los demás.",
    "Libra": "Aprendiste a querer por apariencia social, no siempre por lo que de verdad sentías.\nSobreanalizas tus emociones en vez de simplemente sentirlas.\nAprende a decir que no y a dejar de depender del reconocimiento ajeno.",
    "Escorpio": "El amor de tu madre se sintió como perderte a ti mismo, y por eso evitas la intimidad.\nTe dejas «devorar» emocionalmente con tal de no sentir el abandono.\nTu camino pasa por el perdón, la compasión, y aprender a soltar sin miedo.",
    "Sagitario": "Tu madre te enseñó a fluir y a no preocuparte demasiado por el futuro.\nTe nutres viajando, explorando y ayudando a otros a encontrar sentido.\nCuidado con tu optimismo: a veces te impide procesar de verdad lo que sientes.",
    "Capricornio": "Aprendiste que el amor se gana con esfuerzo y logros, nunca gratis.\nPasas buena parte de la Vida buscando un reconocimiento que quizá nunca llegue igual.\nAprende a cultivar la **ternura** y a disfrutar sin esperar siempre validación.",
    "Acuario": "Tu madre fue imprevisible, y aprendiste que todo el mundo es reemplazable.\nLa libertad se convirtió en tu única forma de seguridad emocional.\nTrabaja los cierres y las despedidas sanas, y atrévete a confiar de nuevo.",
    "Piscis": "Creciste desbordado emocionalmente, sin que nadie te preguntara qué necesitabas.\nTu hipersensibilidad y tu compasión pueden convertirse en autocompasión si no las cuidas.\nTienes que aprender, esencialmente, a convertirte en tu propia **madre**.",
  },
  mercurio: {
    "Aries": "Tu mente vuela hacia el futuro y **improvisa** soluciones cuando todo arde.\nEmpiezas mil batallas, pero terminarlas es otra guerra.\nHabla, discute, suelta esa lengua afilada: callarte no es lo tuyo.",
    "Tauro": "Piensas con las manos: necesitas tocar, probar, construir para entender.\nTu mente es **terca** y metódica, se aferra a lo ya conocido.\nTodo lo que dices lo guardas como un tesoro; tu memoria no olvida.",
    "Géminis": "Tu curiosidad es un **pozo sin fondo** que salta de tema en tema.\nSin profundidad te vacías por dentro; el aburrimiento te ataca rápido.\nOrganiza tu mente antes de dormir y esa velocidad se vuelve tu superpoder.",
    "Cáncer": "Confundes lo que sientes tú con lo que sienten los demás.\nTu memoria guarda el **linaje** entero: historias, patrones, familia.\nEscribe qué temes que piensen de ti; ahí está tu verdadera pregunta.",
    "Leo": "Tu mente convierte ideas en realidad con calidez y **magnetismo**.\nPiensas con el corazón, y un elogio puede moverte entero.\nLideras despacio pero con firmeza: tus palabras elevan a quien te escucha.",
    "Virgo": "Analizas, clasificas, buscas el patrón detrás de cada detalle.\nTu **perfeccionismo** te afina, pero también puede paralizarte.\nLo que no dices en voz alta, tu cuerpo termina hablándolo.",
    "Libra": "Buscas entender a todos para sostener la armonía entre todos.\nSobreanalizas, dudas, evitas decidir porque odias el conflicto.\nNecesitas quien te rete, si no, tu brillante mente se vuelve superficial.",
    "Escorpio": "Bajo la superficie siempre hay algo más, y tú lo intuyes primero.\nInvestigas antes de hablar, pero cuando hablas, **cortas**.\nUna vez que decides qué piensas, ya nadie te mueve de ahí.",
    "Sagitario": "Tu mente busca sentido, no solo hechos: eres un buscador de **verdad**.\nHablas sin filtro, entusiasta, a veces demasiado honesto.\nEnseña, viaja, comparte: ahí es donde tu mente realmente vive.",
    "Capricornio": "Planificas con calma y ejecutas con **disciplina** hasta el final.\nTu humor, algo oscuro, nace de anticipar lo que puede salir mal.\nRespetas las reglas porque en ellas encuentras terreno firme.",
    "Acuario": "Ves las tendencias antes de que existan: tu mente vive adelantada.\nEres objetivo incluso con lo que a otros les desborda.\nNecesitas silencio para no perderte en pensar sin actuar.",
    "Piscis": "Absorbes el mundo como una esponja; tu mente es **psíquica**, no solo racional.\nEscondes lo que piensas de verdad como forma de intimidad.\nMezclas realidad y fantasía sin esfuerzo: ahí nace tu arte.",
  },
  venus: {
    "Aries": "Amas como conquistas: rápido, ardiente, sin medias tintas.\nNecesitas **libertad** para que tu fuego no se apague nunca.\nTu amor debe reavivarse constantemente o simplemente no es amor.",
    "Tauro": "Buscas un amor que se construya despacio y dure para siempre.\nEres profundamente **sensual**, leal, y necesitas saber que no te van a abandonar.\nLo que crece con el tiempo es lo único en lo que realmente confías.",
    "Géminis": "Amas a través de la palabra, la curiosidad y el juego mental.\nTe aburres rápido, y el compromiso puede sentirse como una jaula.\nTu vínculo real es la conversación viva, no la promesa eterna.",
    "Cáncer": "Escondes tu vulnerabilidad tras una fachada estable y digna.\nNecesitas ternura, cuidado y seguridad para abrirte de verdad.\nLa inseguridad despierta tus celos; la calma despierta tu entrega.",
    "Leo": "Amas a lo grande, con drama, lujo y pasión sin filtro.\nNecesitas ser **admirada**: si te ignoran, tu ego se vacía.\nTu lealtad es feroz con quien de verdad amas.",
    "Virgo": "Amas señalando lo que se puede mejorar, aunque eso duela.\nEvalúas cada relación con la cabeza: «¿esto me funciona?».\nEn el fondo solo buscas aprobación, no perfección.",
    "Libra": "Buscas la belleza, la armonía y ser querida por encima de todo.\nComplaces tanto que a veces te pierdes a ti misma en el proceso.\nTu opinión importa: hazte cargo de ella antes que nadie más.",
    "Escorpio": "Amas todo o nada, como una **fusión** total con el otro.\nSabes que nada dura para siempre, y eso te da miedo y profundidad.\nRechazas lo superficial: buscas la esencia o no buscas nada.",
    "Sagitario": "Vives el amor como un viaje de crecimiento y propósito compartido.\nNecesitas libertad, ética y una pareja que te haga aventurarte, no repetir.\nLo pequeño no te frena; lo mezquino sí.",
    "Capricornio": "Buscas seguridad emocional y financiera antes que nada.\nTe proteges tras la distancia, pero una vez comprometida eres **leal** de por Vida.\nPrefieres calidad, no cantidad, en cada inversión emocional.",
    "Acuario": "Te enamoras de ideas, de lo distinto, de lo que no encaja en ningún molde.\nNecesitas libertad; sin ella, te apagas o huyes.\nTu sensualidad es tranquila, pero tu independencia no se negocia.",
    "Piscis": "Anhelas una unión total, casi divina, con el otro.\nSin amor te sientes vacía y a la deriva; con amor, te fundes entera.\nTe atrae lo herido, y a veces eso te cuesta caro.",
  },
  marte: {
    "Aries": "Trazas tu propio camino y eres la primera en actuar, siempre.\nTu ira estalla rápido y se apaga igual de rápido: no la acumulas.\nAprende a pausar y esa fuerza bruta se vuelve **poder** real.",
    "Tauro": "Actúas con paciencia y terminas lo que empiezas, sin prisa pero sin pausa.\nNo eres agresivo, pero si tocan lo tuyo, respondes con **firmeza**.\nNo olvidas las ofensas: tu memoria del rencor es larga.",
    "Géminis": "Tu energía es mental, rápida, con mil ventanas abiertas a la vez.\nSin estímulo constante te dispersas y pierdes el foco.\nDiscutes para liberar tensión; cuidado con provocar solo para pelear.",
    "Cáncer": "La frustración emocional alimenta tu energía más que ninguna otra cosa.\nProteges a tu familia con **fiereza**, aunque ahí también nazcan tus mayores conflictos.\nCuanto más te conoces, menos necesitas la pasivo-agresividad.",
    "Leo": "Necesitas ser la primera y conquistar sintiendo que te lo mereces.\nTu magnetismo inspira a otros, pero bloqueado te frustra y deprime.\nLidera sin necesitar siempre el aplauso: ahí está tu verdadera grandeza.",
    "Virgo": "Quieres que todo se haga bien, y crees que nadie lo hace mejor que tú.\nTrabajas sin parar; el descanso te cuesta permitírtelo.\nCuidado con la necesidad compulsiva de tener siempre la razón.",
    "Libra": "Persuades y encantas, pero a veces confundes tu deseo con lo que otros esperan.\nActúas primero según expectativas, luego te afirmas a ti misma.\nConfiar en ti sin validación externa es tu verdadero reto.",
    "Escorpio": "Actúas con estrategia, paciencia y un poder que rara vez se muestra de frente.\nEsperas el momento exacto; nunca atacas sin saber que servirá a tu fin.\nTu misterio esconde intenciones que solo tú controlas.",
    "Sagitario": "Te lanzas a la aventura con audacia, optimismo y poca paciencia para la rutina.\nTu entusiasmo **contagia**, aunque a veces sea imprudente.\nLa libertad no se negocia; el compromiso puede sentirse asfixiante.",
    "Capricornio": "Te mueves con disciplina y propósito hacia metas cada vez más altas.\nNo eres impulsiva, solo te detienes cuando el agotamiento es real.\nCultiva la humildad, o el logro se te puede volver vacío.",
    "Acuario": "Luchas por ideales elevados y por hacer lo que nunca se ha hecho.\nLideras mejor de lo que sigues, y cuestionas toda autoridad establecida.\nOscilas entre la pasión intensa y el desapego total.",
    "Piscis": "Eres una guerrera que actúa desde el sentir, no desde la fuerza.\nTu poder es sutil, casi mágico, y motivas sin confrontar.\nNecesitas soledad para recargar esa energía tan fluida y compasiva.",
  },
  jupiter: {
    "Aries": "Confías en tu misión de Vida con una fe entusiasta y valiente.\nLideras de forma natural, pero necesitas aprender a decir que no.\nTu optimismo es contagioso; tu impulsividad, el precio a vigilar.",
    "Tauro": "Tienes talento natural para generar riqueza sembrando con paciencia.\nEntiendes que dar es lo que realmente te hace recibir.\nCuidado con el apego a lo material: ahí se bloquea tu abundancia.",
    "Géminis": "Tu mente se expande a través de las palabras y las conversaciones cercanas.\nPrefieres la profundidad selectiva antes que la multitud superficial.\nTu mundo es grande, pero lo exploras cerca de casa.",
    "Cáncer": "Encuentras sentido en la seguridad emocional y en tus raíces familiares.\nEres una anfitriona que hace sentir a todos en casa.\nTu abundancia puede llegar, incluso, a través del hogar mismo.",
    "Leo": "Eres generosa y carismática, aunque en el fondo esperas gratitud.\nSientes que tu papel en el mundo es importante, y actúas en consecuencia.\nCuida el exceso: tu grandeza no necesita siempre brillar más.",
    "Virgo": "Tu confianza nace del logro y del conocimiento acumulado.\nTrabajas de más y esperas demasiado, tanto de ti como de los demás.\nAprende a delegar: el éxito también llega en la segunda mitad de la Vida.",
    "Libra": "Necesitas una pareja para crecer; tu aventura es siempre relacional.\nIdealizas el vínculo, buscando algo que trascienda lo físico.\nCuidado con prometer más de lo que puedes sostener.",
    "Escorpio": "Vives la crisis como forma de Vida y sales de ella más sabia.\nTe atrae lo oculto, la muerte, la transformación profunda.\nSabes ver luz donde otros solo ven oscuridad.",
    "Sagitario": "Buscas un propósito profundo detrás de cada experiencia vivida.\nTienes un fuerte sentido de justicia y sed de verdades eternas.\nViaja, escribe, ríete fuerte: ahí está tu expansión real.",
    "Capricornio": "Eres ética, ambiciosa y buscas estatus con honor y responsabilidad.\nPuedes ser frugal en lo pequeño y generosa en lo grande.\nTu Vida cobra sentido cuando alcanzas lo que te propones.",
    "Acuario": "Tu crecimiento personal solo tiene sentido si aporta a la humanidad.\nCuestionas lo establecido y defiendes la reforma sin miedo.\nVives más en el futuro que en el presente: cuida no perderte ahí.",
    "Piscis": "Buscas la fusión con lo divino y necesitas retirarte para reencontrarte.\nTu compasión, sobre todo hacia los débiles, te hace muy querida.\nNo eres ambiciosa por lo material: tu búsqueda es puramente espiritual.",
  },
  saturno: {
    "Aries": "Aprendiste a valerte por ti mismo antes de tiempo, y eso te dio una **resiliencia** de acero.\nTe cuesta obedecer: necesitas construir tus propias reglas antes de respetar las ajenas.\nCuidado con esconder el miedo detrás de la necesidad de justificarte siempre.",
    "Tauro": "Vienes a construir tu propia **seguridad** material y emocional, ladrillo a ladrillo.\nEl miedo a la pérdida te vuelve cauto, tenaz y a veces terco.\nTu lección es soltar el control lo suficiente para dejar entrar el placer y la abundancia.",
    "Géminis": "El conocimiento te da seguridad, pero no sustituye al corazón.\nAprendes a pensar con disciplina, aunque a veces la duda te frene antes de hablar.\nTu meta es equilibrar la mente con la Vida emocional que sueles posponer.",
    "Cáncer": "Creciste aprendiendo a callar lo que sentías; ahora te toca construir tu propia **seguridad emocional**.\nEl deber familiar pesa, pero no puede sustituir tu autocuidado.\nSanas cuando te permites pedir ayuda sin sentirlo como debilidad.",
    "Leo": "De niño no te vieron como eras, y eso dejó una sed enorme de **reconocimiento**.\nPuedes volverte rígido o exigente justo donde más querías brillar.\nTu tarea es disfrutar sin necesitar el aplauso de nadie más.",
    "Virgo": "El perfeccionismo te hace brillante, pero también implacable contigo mismo.\nAprendiste que todo debe hacerse «bien», y eso pesa más de lo que aparentas.\nSanas cuando conviertes el control en disciplina amable, con espacio para el humor.",
    "Libra": "No te comprometes a la ligera: primero evalúas, mides, esperas seguridad.\nEl amor te llega tarde pero serio, con lecciones de **justicia** y equilibrio.\nCuidado con parecer frío cuando en realidad solo estás siendo cauto.",
    "Escorpio": "Cargas una intensidad emocional que pocos soportan, y menos paciencia aún con la pereza ajena.\nSabes descender a los infiernos —tuyos o de otros— sin romperte.\nTu reto es aprender la **sutileza**, no solo la fuerza de voluntad.",
    "Sagitario": "Buscas la verdad con una disciplina mental feroz, casi como misión de Vida.\nEn el fondo te esfuerzas por demostrar algo a unos padres que nunca terminaron de valorarte.\nCuidado con volverte tan rígido que dejes de escuchar otras verdades.",
    "Capricornio": "La ambición y el estatus son tu norte, casi por herencia paterna.\nMaduraste antes de tiempo y ahora te cuesta imaginar a otros sin tu misma disciplina.\nAprende a reírte más y a exigirte un poco menos.",
    "Acuario": "Quieres cambiar el mundo, pero te cuesta soltar tus propias certezas.\nSientes el peso de «mejorar» a la sociedad, aunque no sea tarea tuya.\nTu libertad llega cuando dejas que los demás sigan sus propias reglas.",
    "Piscis": "Sientes que el mundo te carga con un peso que no sabes de dónde viene.\nCrees que la paz solo se gana con sacrificio, nunca gratis.\nCon madurez conviertes esa herida en una profunda **sabiduría espiritual**.",
  },
  urano: {
    "Aries": "Eres de los que siembran semillas de cambio, aunque tengas que empezar de cero una y otra vez.\nTu independencia es feroz, casi rebelde por naturaleza.\nCuidado con la imprudencia cuando la revolución se vuelve fanatismo.",
    "Tauro": "Transformas lo material desde dentro, cambiando el propio concepto de valor.\nTienes un **magnetismo** natural, a menudo ligado al arte o la música.\nSin conciencia, ese cambio se convierte en terquedad y celos.",
    "Géminis": "Tu mente es brillante e inquieta, siempre un paso por delante.\nCaptas ideas nuevas con facilidad, aunque rara vez las terminas.\nPuedes sentirte desconectado de quienes te rodean, como hablando otro idioma.",
    "Cáncer": "Buscas **libertad emocional** incluso dentro de tu propia familia.\nVes a tus padres como iguales, no como autoridad, y redefines lo que significa hogar.\nTienes una intuición casi psíquica, aunque a veces te desborden los altibajos.",
    "Leo": "Llevas dentro una revolución: necesitas sentirte único y no vas a pedir permiso.\nTu confianza puede derribar lo viejo para construir algo más libre.\nCuidado con que esa fuerza se vuelva ego sin freno.",
    "Virgo": "Reinventas la forma de trabajar y de cuidar tu cuerpo, sin miedo a lo nuevo.\nTu practicidad te hace puente entre la técnica y lo natural.\nSi te desequilibras, la inquietud se instala en tu salud y en tu trabajo.",
    "Libra": "Redefines lo que es una relación: la **igualdad** importa más que la etiqueta.\nBuscas ser tú mismo incluso dentro del vínculo con otro.\nTanta independencia, a veces, te deja con el corazón roto más de una vez.",
    "Escorpio": "Vives cambios radicales que remueven todo desde la raíz.\nTu intensidad emocional y tu magnetismo son innegables.\nSin trabajo interior, esa fuerza puede virar hacia los celos o la venganza.",
    "Sagitario": "Buscas una libertad que no cabe en dogmas ni fronteras.\nUnes lo espiritual con lo científico sin pedir permiso a nadie.\nViajas de forma repentina, casi como huida hacia la verdad.",
    "Capricornio": "Quieres cambiar el sistema, aunque una parte de ti siga obedeciéndolo.\nMiras al futuro con los pies aún anclados en la tradición.\nSin equilibrio, esa tensión se convierte en pura ambición personal.",
    "Acuario": "Tu mente abre puertas que otros ni siquiera veían.\nEres inventivo, excéntrico, y disfrutas conectando con quienes piensan diferente.\nCuidado con quedarte solo en la idea sin aterrizarla nunca.",
    "Piscis": "Traes una **revolución** silenciosa desde el subconsciente y la espiritualidad.\nConviertes lo místico en algo tangible que otros puedan entender.\nSin límites claros, tu sensibilidad se desborda y busca escapes poco sanos.",
  },
  neptuno: {
    "Aries": "Tus sueños te empujan a luchar por una **misión** más grande que tú.\nBuscas almas que salvar con una imaginación sin límites.\nEres guerrero y poeta a la vez, movido por la compasión.",
    "Tauro": "Sueñas en grande, pero aterrizas cada sueño en lo cotidiano.\nTu sentido estético convierte lo material en algo casi poético.\nBuscas belleza, armonía y estabilidad al mismo tiempo.",
    "Géminis": "Tu imaginación reinventa cómo hablamos, viajamos y nos conectamos.\nEscribes con una sensibilidad inventiva difícil de igualar.\nCurioso hasta lo esotérico, siempre argumentas con pasión.",
    "Cáncer": "Tu apego a la familia y al hogar es casi sagrado.\nProteges y te entregas, aunque a veces la fantasía te aleje de lo real.\nEl vínculo con tu madre marca gran parte de tu mundo emocional.",
    "Leo": "Idealizas a quienes amas, y eso puede jugarte en contra.\nTe atrae todo lo que tiene color, drama y Vida intensa.\nCuídate de proyectar tus fantasías sobre las personas reales.",
    "Virgo": "Vives una lucha interna entre la emoción y la razón.\nPuedes ser tajante con el bien y el mal, buscando pureza en todo.\nCuidado con derribar lo viejo sin tener aún algo nuevo que poner en su lugar.",
    "Libra": "Buscas en el otro una especie de **redención** imposible.\nEl amor puede volverse tu droga y tu vía de escape.\nLa decepción llega cuando el otro no cumple tu ideal de perfección.",
    "Escorpio": "Te atrae lo oscuro, casi como si fuera parte de tu identidad.\nPuedes sentirte inundado por las emociones colectivas sin filtro.\nTu camino real es sanar el inconsciente, no obsesionarte con el poder.",
    "Sagitario": "Buscas un conocimiento místico que expanda tu conciencia.\nPersigues un mundo perfecto que nunca termina de coincidir con el real.\nCuidado con el **autoengaño** disfrazado de fe.",
    "Capricornio": "Sabes materializar lo invisible, dar forma concreta a tus visiones.\nSientes el sufrimiento de quienes el sistema deja atrás.\nTu disciplina convierte la compasión en ayuda real y práctica.",
    "Acuario": "Tu mente es puente entre la ciencia y el espíritu.\nTienes una intuición que inspira ideas verdaderamente nuevas.\nComprendes lo abstracto con una calma casi despegada.",
    "Piscis": "Tu identidad se disuelve en algo más grande que tú mismo: el Uno.\nLa **compasión** es tu lengua materna, pero necesitas aprender límites.\nSin ellos, el aislamiento y las adicciones acechan tu sensibilidad.",
  },
  pluton: {
    "Cáncer": "Tu lealtad a los tuyos puede ser feroz, casi tribal.\nNecesitas madurar emocionalmente para no vivir desde el instinto puro.\nCuidado con el resentimiento cuando la herida familiar no cicatriza.",
    "Leo": "Vives un apogeo del **ego**: brillas y necesitas que se note.\nTu creatividad es tu forma más pura de poder.\nAprende a jugar con ese poder sin dejar que te posea.",
    "Virgo": "Tu poder vive en el trabajo bien hecho, casi como obsesión.\nProfundizas en los detalles, aunque te cueste entenderte a ti mismo.\n«O estás conmigo o estás fuera»: tu manera de poner límites es radical.",
    "Libra": "Tus relaciones son intensas, casi cuestión de Vida o muerte.\nRompes con los modelos de amor heredados de tus padres.\nEl **poder** debe repartirse en la pareja, nunca acumularse en uno solo.",
    "Escorpio": "Tocas fondo para poder transformar de verdad.\nEl trauma te marca, pero también te da la fuerza para romper con el pasado.\nNo cambias las reglas: cambias el juego entero.",
    "Sagitario": "Necesitas libertad como el aire, y crees firmemente en la humanidad.\nQuieres un mundo mejor y no te rindes en el intento.\nCuidado con que esa fe se convierta en fanatismo.",
    "Capricornio": "Tienes una fuerza de **liderazgo** que pocos pueden igualar.\nNecesitas retirar la autoridad paterna para poner tus propias reglas.\nTe rebelas contra cualquier límite que no hayas elegido tú mismo.",
    "Acuario": "Sientes la llamada de liberar al colectivo de viejas estructuras.\nAyudas a cerrar un ciclo de poder que ya no sirve.\nConstruyes, con otros, un nuevo orden social.",
    "Piscis": "Descubres que la realidad que creías sólida es solo una **ilusión**.\nTu conciencia se conecta con el daño invisible que hacemos al planeta.\nVes lo que otros prefieren no mirar.",
  },
};

export const RESUMENES_CASA: Partial<Record<CuerpoKey, Record<number, string>>> = {
  sol: {
    1: "Naciste para ser tú mismo, sin copiar a nadie.\nTu **presencia** magnetiza, pero cuidado con confundir quién eres con lo que proyectas.\nSin rumbo propio, ese brillo se vuelve amargura.",
    2: "Tu verdadero reto es sentirte seguro desde dentro, no desde lo que tienes.\nEstás llamado a ser tu propio **proveedor**, aunque vengas de poco.\nTu valor no es tu cuenta bancaria.",
    3: "Brillas cuando piensas, hablas y aprendes por ti mismo.\nEl **conocimiento** es tu combustible, no un adorno.\nNecesitas libertad de movimiento, incluso dentro del compromiso.",
    4: "Tu camino es sanar y trascender la figura de tu padre o madre dentro de ti.\nEncontrar tu propio **hogar** —físico y simbólico— te da identidad.\nSolo diferenciándote de tu familia terminas de nacer.",
    5: "Necesitas sentirte especial, visto y celebrado por lo que te hace único.\nTu **creatividad** —o tus hijos— son la manera de expandirte al mundo.\nPrefieres el foco negativo antes que la nada, así que cuida ese impulso.",
    6: "Tu sabiduría se construye en lo cotidiano, no en lo grandioso.\nCuerpo y mente son **uno**: cuidarlos es tu disciplina de Vida.\nVigila no convertir el servicio a otros en autosacrificio.",
    7: "Te descubres a través del otro, pero ese es también tu riesgo.\nSin una relación sana **contigo mismo**, buscar aplauso ajeno te vacía.\nRecuerda: tu opinión ya vale por sí sola.",
    8: "Viniste a mirar de frente tu propia **sombra** y a transformarte sin resistirte.\nLa muerte, los secretos y lo oculto tejen tu camino.\nCuanto más profundizas, más te vuelves tú mismo.",
    9: "Buscas tu propia **filosofía de Vida**, no la prestada de otros.\nLos viajes, literales o internos, te expanden y te definen.\nNaciste para inspirar y enseñar mientras sigues aprendiendo.",
    10: "Estás llamado a **ascender** más allá del origen que te vio nacer.\nTu identidad se construye en lo público: necesitas reconocimiento por mérito propio.\nCuidado con perseguir logros solo para ganarte la aprobación parental.",
    11: "Sociable por fuera, solitario por dentro: así vives tu búsqueda de pertenencia.\nNecesitas un **grupo** que te reconozca sin diluirte en él.\nTu ambición es cambiar la sociedad, no solo encajar en ella.",
    12: "Vives entre dos mundos: el material y el **espiritual**, sin terminar de elegir.\nTu Sol está llamado a servir a algo más grande que tu propia identidad.\nBrillas en silencio, incluso cuando te sientes solo entre la gente.",
  },
  luna: {
    1: "Necesitas sentir constantemente que eres querido y suficiente.\nTus emociones cambian como mareas, y esa **sensibilidad** también es tu don.\nDeja de moldearte para encajar: sé leal a quien realmente eres.",
    2: "La comida y las posesiones son tu refugio emocional.\nTu seguridad no depende de lo que **tienes**, sino de lo que eres.\nSiempre habrá suficiente para ti, aunque compartas.",
    3: "Sientes hablando: tus palabras cargan tus emociones.\nNecesitas aprender a escuchar de verdad, no solo memorizar.\nEl **movimiento** constante es tu forma de sentirte vivo.",
    4: "Cargas un karma familiar profundo ligado a tu madre.\nSin un **hogar** emocional te sientes a la deriva toda la Vida.\nAprende a expresar lo que sientes, en vez de esperar que lo adivinen.",
    5: "Te enamoras del amor mismo, más que de personas concretas.\nNecesitas ser visto, aplaudido y **admirado** para sentirte seguro.\nTus hijos —o tu creatividad— son extensión de tu propio corazón.",
    6: "Tu cuerpo habla lo que tus emociones callan.\nSolo te sientes digno de amor cuando eres **útil**, y eso te agota.\nLa rutina y el autocuidado son tu ancla de seguridad.",
    7: "Te pierdes en el otro buscando la seguridad que no te das a ti mismo.\nNecesitas el **vínculo** para sentir que la Vida tiene sentido.\nAprende a verte con objetividad, sin proyectar en la pareja a tu madre.",
    8: "Cargas heridas emocionales que no son solo tuyas, sino heredadas.\nUsas la **intimidad** como refugio frente a un vacío insaciable.\nTu tarea es aprender a nutrirte tú mismo, sin pedírselo a nadie más.",
    9: "Tu intuición te conecta con verdades que van más allá de la razón.\nConstruyes tu filosofía de Vida a partir de lo que **sientes**, no solo de lo que piensas.\nPuede que te sientas más en casa lejos de tu propia casa.",
    10: "Tu madre moldeó quién debías ser antes de que pudieras elegirlo tú.\nEncuentras refugio nutriendo y cuidando al **público**, no solo a los tuyos.\nNo olvides amarte a ti tanto como cuidas tu reputación.",
    11: "Tus amistades son tu verdadera familia elegida.\nNutres a los demás con naturalidad, sin buscar encajar a toda costa.\nTanta generosidad también te expone a la **traición**.",
    12: "Absorbes emociones ajenas como si fueran tuyas; aprende a soltarlas.\nTu madre y tú cargáis un vínculo kármico que pide ser sanado.\nEn la soledad y los sueños encuentras tu verdadera **intuición**.",
  },
  mercurio: {
    1: "Tu mente es rápida, curiosa y hambrienta de respuestas.\nAprender constantemente es lo que te da **seguridad**.\nCuando algo del mundo te moleste, mira primero hacia dentro.",
    2: "Necesitas entender cómo funciona el mundo material para sentirte seguro.\nTu mente es una herramienta para generar **recursos**, no solo ideas.\nRara vez te falta de nada, aunque tu forma de ganarlo cambie.",
    3: "Piensas rápido, hablas más rápido aún, y casi siempre tienes algo que decir.\nNecesitas movimiento constante y gente nueva para sentirte vivo.\nLa familia, sobre todo los **hermanos**, ocupa un lugar central en tu mente.",
    4: "Creciste en un ambiente donde la razón pesaba más que el afecto.\nTus raíces y tu historia familiar alimentan tu curiosidad de por Vida.\nAprender no es una etapa, es tu forma constante de **estabilizarte**.",
    5: "El amor, el arte y las ideas ocupan tu mente por igual.\nTu creatividad se convierte en tu forma más honesta de **comunicarte**.\nTe seducen con elogios a tu inteligencia, más que con cualquier otra cosa.",
    6: "Eres un arreglador nato: ves cómo mejorar cualquier cosa.\nNecesitas estar mentalmente ocupado o los detalles te consumen.\nTu salud y tu mente están profundamente **conectadas**: cuídalas juntas.",
    7: "Buscas pareja para la mente, no solo para el corazón.\nTe cuesta encontrar a alguien que te llene del todo, aunque igual te comprometes.\nAprende a comunicar sin caer en el **sobreanálisis** constante.",
    8: "Tu mente indaga lo oculto, lo prohibido, lo que otros no se atreven a mirar.\nCompartes conocimiento con facilidad, pero guardas tus **emociones** para ti.\nSé cauto con contratos, herencias y todo lo que toque tu sistema nervioso.",
    9: "Tu mente busca las leyes que sostienen la existencia, no solo datos sueltos.\nSi algo no te parece **lógico**, tiendes a descartarlo como irreal.\nEnseñar lo que aprendes es parte esencial de tu propósito.",
    10: "Tu carrera necesita que se reconozca tu inteligencia, no solo tu esfuerzo.\nCambias de rumbo con frecuencia, siempre aprendiendo sobre ti y tu entorno.\nBuscas ser visto como alguien **alerta** y capaz, igual que viste a uno de tus padres.",
    11: "Tus amistades te expanden las ideas y la sensación de quién eres.\nBuscas decidir desde la **lógica**, no desde la emoción, por el bien del grupo.\nCuidado con sobrepensarlo todo hasta perder la quietud mental.",
    12: "Te cuesta expresar lo que piensas, y por dentro todo se siente nebuloso.\nSin explorar tu **inconsciente**, no puedes entenderte del todo.\nLos pensamientos negativos te hunden; los positivos te salvan.",
  },
  venus: {
    1: "Brillas por naturaleza, pero tu luz no debería depender de que otros te la confirmen.\nCuidado con esconder tu verdadera cara tras una máscara de **dulzura**.\nYa vales, sin necesidad de que nadie te lo recuerde.",
    2: "Atraes la **abundancia** casi sin esfuerzo, sobre todo a través de tus vínculos.\nPero tu valor no es tu cuenta bancaria.\nDisfruta la riqueza sin apego ni miedo a perderla.",
    3: "Seduces con palabras, encantas hablando.\nLos viajes cortos y las escapadas alimentan tus vínculos.\nCuida no adornar la verdad solo por ganar **aprobación**.",
    4: "Tu hogar es tu refugio emocional, y en él construyes pertenencia.\nLa huella de tu **madre** marca cómo entiendes el amor y la familia.\nTu plenitud romántica más honda suele llegar tarde, con raíces bien plantadas.",
    5: "Vives para el romance intenso, casi como si solo así te sintieras viva.\nTu creatividad y tus hijos son fuente de alegría y también de espejo.\nCuidado con confundir el **drama** con estar realmente viva.",
    6: "Amas sirviendo: cuidas con gestos antes que con palabras.\nTu ojo para el detalle busca **armonía** hasta en lo cotidiano.\nSi no gestionas los conflictos, el cuerpo termina cargando lo que el corazón calla.",
    7: "Te descubres de verdad en pareja; sin vínculo, sientes que falta algo.\nCuidado con idealizar tanto que ningún humano real esté a la altura.\nAmas la idea del **amor**; aprende a amar también su trabajo diario.",
    8: "Te atrae lo prohibido, lo intenso, lo que no está del todo disponible.\nTu **magnetismo** es poderoso, y también tu capacidad de sanar en la sombra.\nLa plenitud llega cuando dejas de buscar fuera lo que ya tienes dentro.",
    9: "Encuentras paz en tu propia filosofía de Vida, no en dogmas ajenos.\nEl amor te llega viajando, cruzando fronteras o culturas.\nTu **honestidad** te convierte en maestra, aunque a veces te falte diplomacia.",
    10: "Brillas con encanto donde otros buscan poder y reconocimiento.\nTu relación con tu madre marca tu **ambición** más de lo que crees.\nBuscas una pareja que sume estatus, pero el verdadero logro es el tuyo.",
    11: "Tu círculo te admira, y tú creces dentro de él.\nPero tu valor no debería depender de cuánto te aplaudan los demás.\nCuidado con perderte en redes sociales o cambiar de vínculo sin parar.",
    12: "Sueñas con un amor absoluto, casi imposible de encontrar en la Tierra.\nPor eso a veces amas lo que no puede corresponderte, evitando la decepción del amor real.\nEn la **soledad** y el servicio silencioso, hallas tu forma más pura de amar.",
  },
  marte: {
    1: "Tienes energía para dos Vidas y el coraje de abrir camino tú misma.\nTu ira estalla rápido, pero se apaga igual de rápido.\nAprende a canalizar ese **fuego**; ahí está tu verdadero poder.",
    2: "El dinero te cuesta ganarlo y se te escapa rápido de las manos.\nNo eres tus posesiones: tu verdadero poder está en tu esencia.\nCada quiebra es, en realidad, una invitación a **empezar de nuevo**.",
    3: "Tu lengua es rápida, filosa y a veces sin filtro.\nHablar o escribir es tu terapia; el silencio forzado se te acumula por dentro.\nCuidado con la **velocidad**, al volante y en la Vida.",
    4: "Creciste entre tensiones domésticas y la sombra de un padre dominante.\nBuscas tu propio hogar para escapar de patrones que, sin sanar, se repiten.\nTu claridad sobre lo que realmente quieres llega más tarde, pero llega.",
    5: "Te sientes viva creando, compitiendo, arriesgando.\nEn el amor eres apasionada e intensa, a veces demasiado **impulsiva**.\nCon los hijos, cuida no confundir tu libertad con la de ellos.",
    6: "Tu cuerpo es tu templo de disciplina y resistencia.\nTrabajas mejor sola que bajo órdenes ajenas.\nCuidado con el **perfeccionismo**: puede transformarse en accidente o agotamiento.",
    7: "Buscas afirmarte a través del otro, y sin su validación te frustras.\nPuedes ser conquistadora, pero cuidado con proyectar tu **rabia** en quien más amas.\nCuando estás consciente, el desafío mutuo se vuelve estímulo, no guerra.",
    8: "Persigues lo que quieres sin mirar atrás, incluso en la crisis más extrema.\nTu **magnetismo** sexual y tu fuerza en el abismo son casi sobrenaturales.\nTransforma esa intensidad o corres el riesgo de que te consuma.",
    9: "Necesitas vivirlo para creerlo; la teoría sola no te basta.\nDesafías límites mentales, físicos y espirituales sin miedo.\nEres **exploradora** valiente y guía para quienes te rodean.",
    10: "Tu energía se vuelca entera en la ambición y el reconocimiento.\nAprendiste que el mundo exige lucha, y por eso luchas por destacar.\nCuidado con que el liderazgo se convierta en **tiranía**.",
    11: "Lideras equipos y buscas reconocimiento dentro del colectivo.\nTu individualidad a veces choca con la necesidad de cooperar.\nCuidado con las **traiciones** o rivalidades entre pares afines.",
    12: "Guardas una guerra silenciosa que rara vez sale a la luz.\nSin salidas físicas, esa energía se vuelve contra ti misma.\nBien canalizada, te convierte en **protectora** feroz de los demás.",
  },
  jupiter: {
    1: "Eres una filósofa nata que busca el sentido de todo lo que vive.\nTu entusiasmo es contagioso, aunque a veces te falte constancia para terminar lo que empiezas.\nCuida no volverte excesiva en tus **placeres** o tus certezas.",
    2: "Tienes la suerte de hacer mucho con poco.\nTu **generosidad** y entusiasmo inspiran a quienes te rodean.\nSolo cuida no medir tu valor por lo que posees.",
    3: "Tu mente es un pozo sin fondo de ideas, siempre queriendo aprender más.\nInspiras con tus palabras, aunque no siempre las acompañes de acción.\nCon los hermanos, cuidado con la **rivalidad** silenciosa por ser «la mejor».",
    4: "Tu hogar puede ser fuente de fortuna y también de fe.\nHeredas más que bienes: heredas una visión amplia de la Vida.\nSolo cuida no atrapar tu alma en las **obligaciones** familiares.",
    5: "Tu lema es «más es mejor que suficiente».\nTe sientes viva creando y arriesgando a lo grande.\nEn el amor, necesitas **exploración**; la rutina te asfixia.",
    6: "Encuentras propósito sirviendo, cuidando, sanando a otros.\nCuidado con los extremos: o te descuidas o te obsesionas con el control.\nLa **enfermedad**, si llega, suele ser una llamada a volver a ti.",
    7: "Idealizas tanto el amor que la realidad rara vez alcanza tu sueño.\nVives entre el deseo de libertad y la necesidad de seguridad compartida.\nPase lo que pase, nunca dejas de creer en el **amor**.",
    8: "Atraviesas los infiernos emocionales protegida por una **fe** casi inagotable.\nEl dinero y el apoyo de otros suelen llegarte cuando menos lo esperas.\nPara ti, hasta el sufrimiento esconde una promesa de renovación.",
    9: "Buscas el sentido de todo, casi de forma compulsiva.\nTu sabiduría, si se aplica a la Vida real, se vuelve guía para otros.\nCuida no convertir tu verdad en **dogma** rígido.",
    10: "Necesitas ser vista y reconocida por lo que logras.\nLas puertas profesionales se abren casi solas para ti.\nMantente **anclada**: los ascensos sin base sólida se derrumban rápido.",
    11: "Los grupos te buscan como fuente de inspiración y guía.\nTu optimismo te sostiene incluso cuando la realidad decepciona.\nCuidado con comprometerte tanto que termines sin **acabar** nada.",
    12: "Eres el «ángel guardián»: las puertas se abren para ti hasta en la crisis.\nTu **fe**, más que religiosa, es conexión profunda con tu esencia.\nIncluso tus enemigos más poderosos pueden volverse aliados.",
  },
  saturno: {
    1: "Creciste demasiado rápido, cargando responsabilidades que no eran tuyas.\nDetrás de tu **máscara** de frialdad se esconde el miedo a no ser suficiente.\nTu maestría llega tarde: la segunda mitad de la Vida es donde por fin floreces.",
    2: "Vienes de un linaje marcado por la escasez y el miedo a no tener nunca suficiente.\nConfundes tu valor con lo que posees, y eso te mantiene atrapado.\nTu maestría es la **abundancia** vivida sin culpa ni miedo.",
    3: "De niño te sentiste incomprendido, juzgado por preguntar y por ser diferente.\nAprendiste a callar y a protegerte con distancia y precisión.\nTu maestría es convertirte en un **comunicador** profundo, capaz de escuchar de verdad.",
    4: "Creciste sin sentir un verdadero hogar, con una autoridad fría que exigía sin abrazar.\nTe sientes sin raíces y dudas de tu propio valor.\nTu tarea es construir un **hogar** interior que sea santuario, no prisión.",
    5: "No te dejaron ser niño, así que aprendiste a esconder quién eres.\nEl miedo al ridículo bloquea tu creatividad y tu forma de amar.\nTu maestría es crear y mostrarte sin pedir permiso ni aplausos.",
    6: "Crees que debes ser útil para merecer amor, y eso te agota.\nEl perfeccionismo se te mete en el cuerpo, en huesos y piel.\nTu maestría es servir desde la conciencia, no desde la compulsión.",
    7: "Temes la intimidad y saboteas sin querer tus propios vínculos.\nBuscas parejas grandes o lejanas para sentirte pequeño y a salvo.\nTu maestría nace de aprender a estar solo antes de amar en igualdad.",
    8: "Te cuesta dejar que alguien te conozca de verdad.\nControlas para no enfrentar tu propia sombra y tus viejas heridas.\nTu maestría llega al soltar el control y aceptar la **transformación**.",
    9: "Creciste con la imagen de un Dios que castiga y una culpa que no es tuya.\nEl miedo a fallar te hace evitar riesgos y aventuras.\nTu maestría es crear una **espiritualidad** propia, amable y liberadora.",
    10: "Temes ser visto como un fracaso y por eso persigues estatus y reconocimiento.\nTu autoestima nace herida y tu vínculo con la madre marca tu camino profesional.\nTu maestría llega tarde: una **vocación** que nace del alma, no del ego.",
    11: "Quieres pertenecer pero también temes perder tu identidad en el grupo.\nTardas en confiar, pero cuando lo haces, eres fiel de por Vida.\nTu maestría es aportar tu don único sin dejar de ser tú.",
    12: "Te proteges siendo frío porque tus emociones son intensas y temes perder el control.\nEl aislamiento y las restricciones se convierten en tus mayores maestros.\nTu maestría es la humildad de aceptar que no todo puede controlarse.",
  },
  urano: {
    1: "Te defines por tu necesidad absoluta de libertad e independencia.\nCambias de rumbo de golpe cuando algo te resulta falso o limitante.\nHay algo eléctrico en ti, y tu camino es descubrir tu propia verdad.",
    2: "El dinero solo te importa porque compra libertad, no seguridad.\nCuanto más intentas encajar en la estabilidad convencional, más se sacude tu economía.\nTu abundancia es móvil, original y ligada a tu propia individualidad.",
    3: "Necesitas construir tu propia forma de entender el mundo, sin heredar marcos ajenos.\nTu mente salta, se adelanta, y a veces nadie puede seguirte el ritmo.\nEl reto es tener una mente libre pero también **estable**.",
    4: "Eres la oveja negra que no repite el guion de su familia.\nEl hogar se sintió impredecible, así que ahora necesitas espacio y libertad para sentirte a salvo.\nTu tarea es construir cimientos internos, no rígidos sino estables.",
    5: "Estás casi obligado a crear algo que sea únicamente tuyo, sin fórmulas.\nTemes que si muestran lo diferente que eres, no te amarán.\nTu plenitud está en lo que otros aún llaman **extraño** o adelantado.",
    6: "Tu Vida diaria es un espejo constante de lo que aún no resuelves por dentro.\nSi no pones límites a tiempo, tu cuerpo termina hablando por ti.\nAprende a escucharlo antes de que tenga que gritar.",
    7: "Necesitas relaciones vivas, no jaulas de costumbre ni fusión.\nEl miedo al abandono convive con tu necesidad feroz de libertad.\nLa **libertad** debe habitar la relación, o la relación se rompe.",
    8: "Vives finales abruptos que cierran capítulos enteros de golpe.\nTus impulsos son intensos y buscan trascender, no solo satisfacer.\nTienes el don de reinventarte por completo, una y otra vez.",
    9: "Rechazas las creencias impuestas; necesitas una verdad construida a tu manera.\nTu mente es progresista, adelantada, casi profética.\nLos viajes no son escape: son **catalizadores** de tu propia revolución interior.",
    10: "No trabajas solo por dinero: tu carrera necesita significado y coherencia con tus valores.\nLos cambios repentinos de rumbo profesional son parte de tu camino.\nEstás aquí para reformar el sistema desde dentro, a tu manera.",
    11: "Sueñas con la unidad: sentir que todos somos uno.\nTus amigos son catalizadores de transformación, a veces más familia que tu propia sangre.\nEres el motor de cambio dentro de los grupos a los que perteneces.",
    12: "Percibes capas de realidad que otros ni imaginan.\nNecesitas soledad periódica para recalibrarte, o la Vida te la impondrá.\nTu don es tender puentes entre lo consciente y lo invisible.",
  },
  neptuno: {
    1: "Te disuelves en las necesidades de los demás hasta perder tu propio yo.\nCuidado con las fugas: el alcohol, la fantasía, el papel de víctima o salvador.\nEn tu mejor versión, eres un **creador** que trae ideas de la nada.",
    2: "Tu relación con el dinero está teñida de culpa o de sentirte con derecho a todo.\nInfravaloras tus propios dones, lo que te genera más inseguridad que estabilidad.\nTu verdadero tesoro es interno, no material.",
    3: "Tu mente analítica se dispersa, pero percibes lo que otros no ven bajo las palabras.\nPuedes engañarte creyendo tuyas ideas que en realidad absorbiste de otros.\nTu don es cautivar con lenguaje, emoción y lo **abstracto**.",
    4: "Te cuesta sentir raíces; anhelas un hogar que parece siempre fuera de alcance.\nIdealizas un pasado que quizá nunca fue como lo recuerdas.\nAl final de la Vida buscarás, por fin, el hogar perdido de tu alma.",
    5: "Tienes una capacidad enorme para crear y expresar lo que otros solo intuyen.\nCuidado con idealizar al amado o sacrificar tu creatividad por complacer.\nEl placer puede seducirte demasiado: cuidado con el juego y el exceso.",
    6: "Eres el ángel de la guarda que se hunde en los problemas ajenos.\nTu sistema nervioso es un termómetro extremadamente sensible.\nEn tu mejor versión, tienes verdaderas manos **sanadoras**.",
    7: "Idealizas tanto a tus parejas que dejas de ver quiénes son en realidad.\nTe sacrificas buscando un amor que nunca es reconocido ni recompensado.\nCuidado con el síndrome del eterno **salvador**: atrae a quien no quiere ser salvado.",
    8: "Buscas trascender tus límites a través del sexo, la intimidad y la muerte.\nNunca te sientes del todo satisfecho: prefieres fantasear a disfrutar lo que tienes.\nTu don es una conexión psíquica profunda con lo invisible.",
    9: "Buscas la redención en filosofías y gurús, hasta decepcionarte una y otra vez.\nLa fe que necesitas nunca está fuera: está dentro de ti.\nTu don es una intuición abierta capaz de tocar lo poético y lo inalcanzable.",
    10: "Ser visible activa tu vulnerabilidad más profunda.\nPuedes ser idolatrado o protagonizar un escándalo: tus secretos rara vez quedan ocultos.\nVives tu carrera como un **servicio**, no como una simple ambición.",
    11: "Eres el chamán del grupo: encuentras tu unión con la Vida a través del servicio a otros.\nCuidado con perderte en causas ajenas hasta olvidarte de ti mismo.\nTu reto es definir con claridad tu propio camino.",
    12: "Eres una esponja que absorbe lo invisible, a veces sin saber qué hacer con ello.\nEl escapismo y la confusión acechan si no aprendes a purificarte en soledad.\nTu don, si lo cultivas, es tocar a tu propio **maestro** interior.",
  },
  pluton: {
    1: "No conoces los términos medios: vives de forma intensa, absoluta y obsesiva.\nDestruyes antes de sentirte vulnerable, o te sacrificas a ti mismo.\nTienes un enorme poder de **regeneración**, si aprendes a no vivir en el drama.",
    2: "Debes ir más allá del dinero para descubrir qué te mueve de verdad.\nPlutón puede arrebatarte todo justo cuando crees haber llegado a la cima.\nTu fuerza real nace de soltar el apego y responder con claridad a la crisis.",
    3: "Tu mente va directa al núcleo de las cosas, incluso de lo tabú.\nTus palabras tienen un poder real: pueden sanar o pueden herir.\nCon madurez, aprendes a escuchar más y hablar menos.",
    4: "Cargas terror y destrucción vividos en tu hogar más temprano.\nEl miedo a que todo estalle te hace controlar y controlarte en exceso.\nTu mayor don es la capacidad absoluta de **regenerarte** y sanar tu linaje.",
    5: "Oscilas entre necesitar brillar y esconder tu creatividad por miedo a la crítica.\nBuscas demostrar poder para sentirte amado, y eso te puede desgastar.\nTu lección es descubrir tu singularidad sin depender del aplauso.",
    6: "Vives exigiéndote perfección y control, incluso sobre lo que no puedes controlar.\nAyudas a otros, pero a menudo esperando gratitud o reconocimiento a cambio.\nTu cuerpo te avisa cuando reprimes demasiado: tu maestría es servir sin dominar.",
    7: "Cargas heridas profundas de abandono y traición que marcan cómo amas.\nTus relaciones nunca son superficiales: son un viaje al inframundo y de vuelta.\nTu don es acompañar a otros a través de sus propias **muertes** y renacimientos.",
    8: "Vives con una insatisfacción interna difícil de calmar del todo.\nTus impulsos, si se reprimen, explotan; si se niegan, te controlan.\nEn la crisis te vuelves extraordinario: un guía para quien atraviesa su propia oscuridad.",
    9: "Percibes de forma única, pero te cuesta que el mundo comprenda tu visión.\nTe aferras a dogmas o buscas la verdad de forma casi fanática.\nCon el tiempo entiendes que la verdad que buscas siempre estuvo dentro de ti.",
    10: "Necesitas estar al mando, y te cuesta delegar o soltar el control.\nTu autoestima se ligó al logro, herencia de padres exigentes y duros.\nEl verdadero **liderazgo** llega cuando dejas de necesitar el poder para sentirte válido.",
    11: "Sientes que no encajas, pero temes profundamente la soledad.\nAmistades traicionadas de niño dejaron una herida que aún gestionas.\nCon madurez, te conviertes en líder de grupos que sí transforman la realidad.",
    12: "Vivirás destrucciones cíclicas que te obligan a renacer transformado.\nTu mayor miedo es perder el control, pero ahí reside tu mayor poder.\nLa madurez es aprender a confiar y entregarte, a pesar del dolor.",
  },
  quiron: {
    1: "Duele empezar, duele ser tú.\nTu **valentía** nació herida, pero es tu mayor don.\nSana tu imagen y camina como quieras, no como te dijeron.",
    2: "Sientes que no mereces abundancia ni placer.\nTu cuerpo y tu valor no dependen de lo que tienes.\nAma tu carencia y descubrirás tu propia riqueza.",
    3: "No te escucharon, y ahora crees que no vales.\nTu voz herida esconde un don: comunicar lo diferente.\nHabla a tu manera, aunque sea distinta.",
    4: "No sentiste hogar, y por eso huyes de tu propio interior.\nCuidar de otros no cura el vacío si no abrazas a tu niño interior.\nTu don es dar el refugio que nunca tuviste.",
    5: "No te dejaron brillar tal como eras.\nTu creatividad duele, pero es tu don más luminoso.\nExprésate, aunque tiemble la vergüenza.",
    6: "Sientes que nunca haces suficiente ni lo bastante bien.\nLa culpa por existir en la Tierra te paraliza.\nTu don es cuidar; empieza por perdonar tu **imperfección**.",
    7: "Amar duele porque temes ser rechazado y abandonado.\nProyectas en el otro lo que no te atreves a mirar en ti.\nTu don es compartirte sin perderte.",
    8: "Absorbiste el dolor y el control desde niño.\nTemes tu propio poder tanto como el ajeno.\nLa **intimidad**, bien mirada, es tu puerta a la transformación.",
    9: "Perdiste la confianza en la Vida y en un sentido mayor.\nBuscas respuestas fuera cuando la verdad está en seguir explorando.\nTu don es la fe que renace después del dolor.",
    10: "Te sentiste pequeño, juzgado, incapaz de lograr nada.\nEl miedo a fracasar te frena antes de intentarlo.\nTu don es ayudar a otros a encontrar su lugar en el mundo.",
    11: "Fuiste diferente, y eso te costó el rechazo del grupo.\nTe sientes solo, como si no pertenecieras a la humanidad.\nTu don es sanar lo colectivo desde tu propia rareza.",
    12: "Cargas un dolor que viene de antes de nacer, incluso el del linaje.\nSientes que no mereces ser feliz ni fundirte con nada.\nTu don es servir a la humanidad sanando primero tu propia herida.",
  },
  nodoNorte: {
    1: "Naciste para descubrir quién eres, sin pedir permiso.\nDeja de buscar aprobación externa: **avanza** aunque te lo discutan.\nTu camino se abre cuando actúas por ti mismo.",
    2: "Construye tu propia estabilidad, sin depender de nadie.\nAprende a disfrutar del cuerpo y de la Vida simple.\nSuelta el drama; la abundancia empieza en ti.",
    3: "Aprende a hablarle a cada uno en su propio idioma.\nNo sabes más que nadie: escucha antes de enseñar.\nTu destino es ser puente entre mundos distintos.",
    4: "Construye tu propio templo interior antes que nada.\nSé tu propia familia antes de cuidar de otra.\nSana tu árbol genealógico para encontrar tu hogar.",
    5: "Naciste para crear y mostrar tu esencia al mundo.\nNo busques la perfección: **materializa** con lo que ya tienes.\nSigue a tu corazón, no al aplauso del grupo.",
    6: "Tu lección es cuidar el cuerpo, la mente y a los demás con equilibrio.\nEl servicio y la sanación son tu camino, no tu castigo.\nOrdena tu Vida sin dejar de ser generoso.",
    7: "Aprende a compartir tu Vida sin perder tu esencia en ello.\nCeder no es perderte: es la puerta a tu expansión.\nLa felicidad crece cuando aprendes a estar en pareja de verdad.",
    8: "Mírate de frente: tu sombra también es tu tesoro.\nAprende a fusionarte con otro sin perder tu centro.\nRenace, una y otra vez, como el **ave fénix**.",
    9: "Busca tus propias respuestas, no las heredadas.\nLa experiencia te enseña más que cualquier información.\nExplora lejos, luego comparte lo que descubriste dentro.",
    10: "Sal al mundo y encuentra tu vocación real.\nConviértete en una autoridad responsable, no en un tirano.\nTu poder solo vale si sirve a algo más grande que tú.",
    11: "Comparte tu don creativo con el colectivo, sin miedo al juicio.\nSé auténtico antes que aplaudido.\nAprende a escuchar y crecer a través del grupo.",
    12: "Profundiza tu conexión espiritual más allá de lo material.\nSiente, aunque el caos y la falta de estructura te asusten.\nAyuda desde la **compasión**, no desde el arreglo o el esfuerzo.",
  },
  nodoSur: {
    1: "Vienes de vivir centrado solo en ti.\nEl otro fue siempre un medio para tus fines.\nAhora toca mirar más allá de ti mismo.",
    2: "Te aferras a la seguridad material y rechazas el cambio.\nTu autosuficiencia te impidió depender de nadie.\nToca soltar el apego y mirar hacia dentro.",
    3: "Tu mente dispersa salta de una cosa a otra sin profundizar.\nComunicaste ideas ajenas, nunca las propias.\nEs hora de dejar de repetir y empezar a pensar por ti mismo.",
    4: "Viviste atrapado en la familia y nunca saliste a vivir tu propia Vida.\nConfundiste el refugio con una casa, no contigo mismo.\nEnfréntate al mundo: ahí está tu **poder personal**.",
    5: "Viviste creyéndote el centro del mundo.\nTe cuesta verte como una persona más entre las demás.\nViniste a dar luz a otros, no solo a brillar tú.",
    6: "Vives sin parar, anestesiado en el trabajo y la lógica.\nNo crees en nada que no puedas controlar.\nDeja de huir del alma sirviendo solo con las manos.",
    7: "Aprendiste a entregarte tanto que te perdiste a ti mismo.\nAhora te cuesta decidir sin mirar lo que otros quieren.\nToca recuperar tu propia voz.",
    8: "Dependiste de otros para sostener tus deseos.\nDudas de tu propio valor y de tu fuerza independiente.\nSal del drama y confía en tus propios recursos.",
    9: "Tu mente libre e intuitiva se aferra a sus propias creencias.\nTe aíslas si nadie piensa como tú.\nSuelta el apego a tener siempre la razón.",
    10: "Vienes de haber tenido mucho poder y aún lo persigues.\nTe anestesias trabajando, buscando siempre reconocimiento.\nSuelta la necesidad de demostrar y desbloquea tu camino.",
    11: "Viviste en la mente y en el grupo, casi sin individualidad.\nTe sientes diferente, pero no siempre eres auténtico.\nToca dejar de actuar la rareza y ser tú de verdad.",
    12: "Fuiste experto en lo espiritual, pero extraño a lo terrenal.\nVives en tu mundo interior, lejos de lo ordinario.\nLo real, aunque asuste, también es sagrado.",
  },
};
