import type { HitoHistoria, SubHito } from "./culturaHistoriaUniversal";

// ─────────────────────────────────────────────────────────────────────────
// HISTORIA DE LA FILOSOFÍA (Cultura). Tagline: «La búsqueda de la sabiduría —
// cómo la humanidad aprendió a pensar por sí misma».
//
// Mismo modelo que las demás Historias: ETAPAS (con intro) → SUB-HITOS (cada uno
// con su cómic: pregunta-gancho + cuerpo + dato curioso, foto + texto a la
// derecha). Las 13 etapas están COMPLETAS (de «Antes de la filosofía» hasta
// «Pensar el futuro»). Fotos planas en /recorrido/cultura/historiafilosofia/<subKey>.png
// (el nombre del archivo = key del sub-hito). El texto se pinta con `separarFrases`
// (salto de línea tras cada punto).
//
// Momentos sin fecha (eyebrow "") = pasajes de síntesis/transición (p. ej. «Un
// puente entre dos mundos», «La búsqueda no termina»): el ComicViewer oculta el
// antetítulo cuando va vacío.
// ─────────────────────────────────────────────────────────────────────────

// Todas las fotos (círculo + viñeta) van planas en una sola carpeta, con el
// nombre del sub-hito (misma convención que Historia Universal / historiageneral).
const foto = (_era: string, sub: string) =>
  `/recorrido/cultura/historiafilosofia/${sub}.png`;

// Sub-hito con su cómic (una viñeta). `pregunta` opcional (gancho, va primero) y
// `dato` opcional (curiosidad, va al final). El `cuerpo` son los párrafos.
const hito = (
  era: string, key: string, titulo: string, fecha: string,
  pregunta: string, cuerpo: string[], dato?: string,
): SubHito => {
  const paragraphs: string[] = [];
  if (pregunta) paragraphs.push(pregunta);
  paragraphs.push(...cuerpo);
  if (dato) paragraphs.push(dato);
  return {
    key, titulo, foto: foto(era, key),
    vinetas: [{ src: foto(era, key), eyebrow: fecha, titulo, paragraphs }],
  };
};

export const HISTORIA_FILOSOFIA_HITOS: HitoHistoria[] = [
  {
    key: "antes-filosofia",
    titulo: "Antes de la filosofía",
    anio: "Hasta el siglo VI a. C.",
    intro:
      "Antes de la razón estaban los mitos. Mucho antes de que existieran filósofos, los seres humanos ya intentaban comprender el mundo. ¿Por qué llueve? ¿Por qué morimos? ¿Quién creó el universo? Las respuestas no llegaban mediante experimentos o razonamientos, sino a través de relatos transmitidos de generación en generación. En Mesopotamia, Egipto, la India o China surgieron mitos que explicaban el origen del mundo, el paso de las estaciones o el destino de los seres humanos. Aquellas historias no eran simples cuentos: representaban la forma en que las primeras civilizaciones entendían la realidad. Pero poco a poco ocurrió algo inesperado. Algunos pensadores empezaron a sospechar que quizá el universo no funcionaba por capricho de los dioses, sino siguiendo leyes que podían descubrirse mediante la observación y el razonamiento. Ese cambio, conocido como el paso del mito al logos, marcaría el nacimiento de la filosofía.",
    subhitos: [
      hito("antes-filosofia", "mito-logos", "Del mito al logos", "≈Siglo VI a. C.",
        "¿Y si el universo tuviera reglas en lugar de caprichos?",
        [
          "Durante miles de años, casi todas las civilizaciones habían explicado el mundo mediante mitos. Si había una tormenta era porque un dios estaba enfadado. Si el Sol salía cada mañana era porque una divinidad lo guiaba por el cielo. Los fenómenos naturales dependían de la voluntad de los dioses.",
          "Sin embargo, en las ciudades griegas de Asia Menor comenzó a surgir una idea completamente nueva. Algunos pensadores dejaron de preguntarse qué dios provocaba un fenómeno y empezaron a preguntarse qué causa natural lo producía.",
          "Aquello fue una auténtica revolución intelectual.",
          "Por primera vez, alguien intentaba comprender el universo sin recurrir a la religión. En lugar de aceptar las explicaciones tradicionales, observaban la naturaleza, discutían entre ellos y buscaban argumentos racionales.",
          "Había nacido el logos, una palabra griega que puede traducirse como razón, explicación o pensamiento racional.",
          "Muchos historiadores consideran este momento como el nacimiento no solo de la filosofía, sino también de la ciencia.",
        ],
        "Dato curioso: la palabra lógica procede precisamente de logos, porque ambas comparten la idea de razonar siguiendo argumentos en lugar de recurrir únicamente a la tradición o la autoridad."),
      hito("antes-filosofia", "egipto-mesopotamia", "Egipto y Mesopotamia", "Milenios antes de la filosofía",
        "¿Podía existir sabiduría antes de la filosofía?",
        [
          "Mucho antes de que aparecieran los filósofos griegos, las civilizaciones de Egipto y Mesopotamia ya habían desarrollado conocimientos sorprendentes sobre matemáticas, astronomía, medicina y organización política.",
          "Los sacerdotes observaban el cielo para predecir las crecidas del Nilo o elaborar calendarios, mientras escribas y estudiosos recopilaban conocimientos sobre geometría, agricultura y leyes. Sin embargo, estos saberes estaban estrechamente ligados a la religión y a la autoridad de los gobernantes.",
          "La filosofía nacería cuando algunos pensadores decidieran separar el conocimiento de la tradición religiosa y preguntarse si las cosas podían explicarse mediante la razón.",
        ]),
      hito("antes-filosofia", "vedas-upanishads", "Los Vedas y las Upanishads", "≈1500-500 a. C.",
        "¿Quiénes somos realmente?",
        [
          "Mientras en Grecia comenzaba a desarrollarse la filosofía, en la India surgían textos que planteaban preguntas profundamente filosóficas sobre la existencia.",
          "Los Vedas recogían antiguos himnos y enseñanzas religiosas, pero fueron las Upanishads las que introdujeron cuestiones que todavía hoy siguen siendo objeto de reflexión: ¿qué es el alma?, ¿qué relación existe entre el individuo y el universo?, ¿qué significa alcanzar la verdadera libertad?",
          "Muchas de las ideas que más tarde formarían el hinduismo nacieron en estos textos, que mezclan religión y filosofía de una forma difícil de separar.",
        ],
        "Dato curioso: las Upanishads fueron escritas varios siglos antes de Platón y ya discutían cuestiones sobre la conciencia, la identidad y la realidad que siguen debatiéndose en la filosofía contemporánea."),
      hito("antes-filosofia", "sabios-china", "Los primeros sabios de China", "≈Siglo VI a. C.",
        "¿Y si la pregunta más importante no fuera cómo empezó el universo, sino cómo debemos vivir?",
        [
          "Mientras los filósofos griegos trataban de descubrir de qué estaba hecho el cosmos, en China algunos pensadores dirigían su atención hacia la vida cotidiana y las relaciones humanas.",
          "Allí comenzó a desarrollarse una tradición intelectual que buscaba la armonía, el equilibrio y el buen gobierno. Muy pronto aparecerían figuras como Confucio y Lao Tse, cuyas enseñanzas influirían en cientos de millones de personas durante más de dos mil años.",
          "Su forma de pensar era diferente a la griega, pero perseguía el mismo objetivo: comprender mejor al ser humano y su lugar en el mundo.",
        ]),
      hito("antes-filosofia", "por-que-nacio", "¿Por qué nació la filosofía?", "≈Siglo VI a. C.",
        "¿Por qué, después de tantos milenios, alguien empezó de repente a pensar de otra manera?",
        [
          "Durante miles de años los seres humanos se habían conformado con las explicaciones de los mitos. Entonces, ¿por qué hacia el siglo VI a. C. algunas personas empezaron a buscar respuestas mediante la razón?",
          "No fue casualidad que ocurriera en las ciudades griegas. Allí se daban unas condiciones muy especiales. El comercio ponía en contacto a pueblos con dioses y costumbres muy distintos, lo que hacía sospechar que ninguna versión del mundo era la única verdadera.",
          "Además, los griegos no tenían una casta de sacerdotes todopoderosa que impusiera una única explicación. Cualquier ciudadano podía discutir, preguntar y proponer sus propias ideas en la plaza pública.",
          "El alfabeto, sencillo y accesible, permitió escribir y comparar argumentos. Y una parte de la población disponía de tiempo libre para dedicarse a pensar.",
          "Así, poco a poco, la curiosidad dejó de conformarse con «los dioses lo quisieron así» y empezó a preguntar «¿por qué?». Había nacido la filosofía.",
        ],
        "Dato curioso: la palabra filosofía significa literalmente «amor a la sabiduría». Según la tradición, fue Pitágoras quien la usó por primera vez, porque decía no ser un sabio, sino solo alguien que amaba y buscaba la sabiduría."),
    ],
  },
  {
    key: "primeros-sabios",
    titulo: "Los primeros sabios",
    anio: "≈1200-500 a. C.",
    intro: "Antes de Sócrates, algunos pensadores ya se preguntaban cómo debía vivir el ser humano.",
    // Momentos: Zoroastro · Confucio · Confucianismo · Lao Tse · Taoísmo · Buda · El budismo como filosofía
    subhitos: [],
  },
  {
    key: "grecia-razon",
    titulo: "Grecia descubre la razón",
    anio: "Siglos VI-V a. C.",
    intro:
      "Por primera vez, alguien intentó explicar el universo sin recurrir a los dioses. Alrededor del siglo VI a. C., en las ciudades griegas de la costa de Asia Menor, ocurrió algo que cambiaría la historia del pensamiento. Mientras la mayoría de las civilizaciones seguían explicando el mundo mediante mitos y relatos religiosos, un pequeño grupo de pensadores comenzó a buscar respuestas observando la naturaleza. No pretendían negar a los dioses. Lo que buscaban era comprender si el universo seguía unas leyes propias que podían descubrirse mediante la razón. Todos compartían una misma pregunta: ¿de qué está hecho el universo? Hoy esta pregunta puede parecernos sencilla, pero en aquella época era revolucionaria. Por primera vez, la explicación del mundo dejaba de depender únicamente de la tradición y comenzaba a apoyarse en la observación y el razonamiento. Por eso se les conoce como los filósofos presocráticos, ya que vivieron antes de Sócrates y sentaron las bases de toda la filosofía occidental.",
    subhitos: [
      hito("grecia-razon", "tales-mileto", "Tales de Mileto", "≈624-546 a. C.",
        "¿Cuál es el origen de todas las cosas?",
        [
          "Tales suele ser considerado el primer filósofo de Occidente. Su gran mérito no fue acertar en sus respuestas, sino cambiar la forma de hacer las preguntas.",
          "Observando la naturaleza llegó a la conclusión de que el agua era el principio de todo. Había visto que los seres vivos necesitaban agua para vivir, que la lluvia hacía crecer las plantas y que el agua podía transformarse en hielo o vapor. Pensó que quizá toda la realidad procedía de ese elemento.",
          "Hoy sabemos que estaba equivocado, pero eso es casi lo de menos. Lo verdaderamente importante fue que intentó explicar el universo mediante una causa natural y no mediante un mito.",
          "Además de filósofo, Tales fue matemático y astrónomo. La tradición cuenta que llegó incluso a predecir un eclipse solar, algo que impresionó profundamente a sus contemporáneos.",
        ],
        "Dato curioso: Aristóteles decía que con Tales comenzó la filosofía porque fue el primero en buscar un principio racional para explicar el universo."),
      hito("grecia-razon", "anaximandro", "Anaximandro", "≈610-546 a. C.",
        "¿Y si el origen del universo no fuera ningún elemento conocido?",
        [
          "Discípulo de Tales, Anaximandro pensó que el agua no podía explicar todas las cosas. Si el agua era húmeda, ¿cómo podía dar origen al fuego, que es seco?",
          "Propuso entonces una idea mucho más abstracta: el origen de todo era el ápeiron, una sustancia infinita, eterna e indefinida de la que nacían todas las cosas y a la que todas regresaban.",
          "Fue una idea extraordinariamente moderna, porque ya no buscaba una sustancia visible, sino un principio universal.",
          "También elaboró uno de los primeros mapas conocidos del mundo y defendió que la Tierra flotaba libremente en el espacio, sin apoyarse sobre nada.",
        ],
        "Dato curioso: algunos consideran a Anaximandro el primer científico de la historia por intentar explicar fenómenos naturales sin recurrir a causas sobrenaturales."),
      hito("grecia-razon", "anaximenes", "Anaxímenes", "≈586-526 a. C.",
        "¿Puede un solo elemento transformarse en todo lo que existe?",
        [
          "Anaxímenes volvió a buscar un elemento concreto como origen del universo y eligió el aire.",
          "Pensaba que, al condensarse, el aire se convertía en agua y luego en tierra, mientras que al expandirse se transformaba en fuego. Aunque esta explicación hoy resulta incorrecta, mostraba un intento de comprender cómo la materia podía cambiar de una forma a otra.",
          "Lo importante era el método: observar la naturaleza y buscar explicaciones racionales.",
        ]),
      hito("grecia-razon", "pitagoras", "Pitágoras", "≈570-495 a. C.",
        "¿Y si el universo estuviera hecho de números?",
        [
          "Pitágoras es conocido por el famoso teorema que lleva su nombre, pero fue mucho más que un matemático.",
          "Creía que la esencia del universo no eran los elementos materiales, sino las matemáticas. Observó que la música, la geometría y el movimiento de los astros seguían proporciones numéricas y concluyó que el cosmos entero estaba gobernado por los números.",
          "Para él, comprender las matemáticas era acercarse al orden del universo.",
          "Su escuela también defendía la inmortalidad del alma y la reencarnación, mostrando cómo en la Antigüedad la filosofía, las matemáticas y la religión todavía estaban profundamente unidas.",
        ],
        "Dato curioso: los pitagóricos descubrieron que las notas musicales agradables siguen proporciones matemáticas muy precisas."),
      hito("grecia-razon", "heraclito", "Heráclito", "≈540-480 a. C.",
        "¿Existe realmente algo que permanezca igual?",
        [
          "Heráclito observó que todo cambia constantemente. Los ríos fluyen, las estaciones se suceden, las personas envejecen y nada permanece inmóvil.",
          "Por eso afirmaba: «Nadie puede bañarse dos veces en el mismo río».",
          "No porque el río desaparezca, sino porque tanto el agua como la persona ya han cambiado.",
          "Para Heráclito, el cambio era la ley fundamental del universo. La realidad no era algo fijo, sino un flujo continuo.",
        ],
        "Dato curioso: la idea de que todo está en constante cambio sigue influyendo hoy en la física, la biología y muchas corrientes filosóficas modernas."),
      hito("grecia-razon", "parmenides", "Parménides", "≈515-450 a. C.",
        "¿Y si el cambio fuera solo una ilusión?",
        [
          "Parménides defendía exactamente lo contrario que Heráclito.",
          "Si algo cambia, decía, deja de ser lo que era. Pero de la nada no puede surgir nada. Por tanto, el verdadero ser debe ser eterno, único e inmutable.",
          "Según él, nuestros sentidos nos engañan al hacernos creer que el mundo cambia constantemente. Solo la razón puede mostrarnos la auténtica realidad.",
          "Durante siglos, los filósofos intentaron resolver esta enorme contradicción: ¿tiene razón Heráclito al decir que todo cambia? ¿O la tiene Parménides al afirmar que el cambio es una ilusión?",
          "Gran parte de la filosofía posterior intentará responder precisamente a esa pregunta.",
        ]),
      hito("grecia-razon", "empedocles", "Empédocles", "≈494-434 a. C.",
        "¿Y si todos tuvieran un poco de razón?",
        [
          "Empédocles propuso una solución intermedia. El universo no estaba formado por un único elemento, sino por cuatro: tierra, agua, aire y fuego.",
          "Estos elementos nunca desaparecen; simplemente se mezclan y separan gracias a dos fuerzas que llamó Amor y Discordia.",
          "Aunque hoy sabemos que la materia no funciona así, su teoría de los cuatro elementos dominaría la ciencia occidental durante casi dos mil años.",
        ]),
      hito("grecia-razon", "democrito", "Demócrito", "≈460-370 a. C.",
        "¿Y si toda la materia estuviera formada por partículas invisibles?",
        [
          "Demócrito imaginó que, si dividíamos cualquier objeto una y otra vez, acabaríamos llegando a unas partículas tan pequeñas que ya no podrían romperse.",
          "Las llamó átomos, palabra que en griego significa precisamente «indivisible».",
          "No disponía de microscopios ni experimentos para demostrarlo, pero su intuición fue extraordinaria. Más de dos mil años después, la ciencia recuperaría esa idea y desarrollaría la teoría atómica moderna.",
        ],
        "Dato curioso: aunque los átomos actuales sí pueden dividirse, Demócrito fue el primero en imaginar que toda la materia estaba formada por pequeñas partículas."),
    ],
  },
  {
    key: "hombre-centro",
    titulo: "El hombre en el centro",
    anio: "Siglos V-IV a. C.",
    intro:
      "La filosofía deja de preguntarse de qué está hecho el universo y comienza a preguntarse cómo debemos vivir. Los filósofos presocráticos habían dedicado siglos a intentar comprender la naturaleza. ¿Cuál era el origen del universo? ¿Qué elemento componía todas las cosas? ¿Por qué cambia la realidad? Pero en el siglo V a. C. Atenas vivía una época extraordinaria. La democracia comenzaba a desarrollarse, los ciudadanos debatían sobre leyes, justicia y política, y la vida pública cobraba una importancia nunca vista. En ese contexto apareció un grupo de pensadores que cambió completamente el rumbo de la filosofía. En lugar de preguntarse por las estrellas, comenzaron a preguntarse por las personas. ¿Qué significa vivir bien? ¿Qué es la justicia? ¿Existe la verdad? ¿Cómo debemos educar a nuestros hijos? Desde ese momento, la filosofía ya no trataría solo del universo, sino también del propio ser humano.",
    subhitos: [
      hito("hombre-centro", "sofistas", "Los sofistas", "≈Siglo V a. C.",
        "¿Existe una verdad absoluta... o todo depende del punto de vista?",
        [
          "Los sofistas fueron los primeros grandes maestros profesionales de Grecia. Viajaban de ciudad en ciudad enseñando oratoria, política y argumentación a cambio de dinero.",
          "En una democracia como la ateniense, hablar bien era una habilidad fundamental. Un buen discurso podía convencer a una asamblea, ganar un juicio o alcanzar el poder.",
          "Muchos sofistas defendían que la verdad dependía de cada persona y de cada situación. El más famoso de ellos, Protágoras, resumió esta idea con una frase que todavía hoy sigue siendo debatida: «El hombre es la medida de todas las cosas».",
          "Para algunos filósofos, esto significaba que no existía una verdad universal, sino diferentes puntos de vista igualmente válidos.",
          "Otros, como Sócrates, pensaban que esa idea era muy peligrosa.",
        ],
        "Dato curioso: aunque durante siglos los sofistas tuvieron mala fama por las críticas de Platón, hoy muchos historiadores consideran que fueron excelentes educadores y contribuyeron enormemente al desarrollo de la democracia ateniense."),
      hito("hombre-centro", "socrates", "Sócrates", "470-399 a. C.",
        "¿Cómo puede alguien saber que tiene razón?",
        [
          "Sócrates nunca escribió un solo libro. Todo lo que sabemos sobre él procede principalmente de su discípulo Platón.",
          "En lugar de dar respuestas, Sócrates hacía preguntas. Muchas preguntas.",
          "Creía que la mayoría de las personas afirmaban saber cosas que en realidad nunca habían pensado con profundidad. Por eso recorría las calles de Atenas hablando con políticos, artesanos, poetas y jóvenes, haciéndoles preguntas hasta que descubrían las contradicciones de sus propias ideas.",
          "Este método hoy se conoce como método socrático.",
          "Su objetivo no era humillar a nadie, sino enseñar que reconocer la propia ignorancia es el primer paso para alcanzar el conocimiento.",
          "Su frase más famosa resume perfectamente esta actitud: «Solo sé que no sé nada».",
          "Su forma de cuestionar a las autoridades y las creencias tradicionales acabó generándole numerosos enemigos. En el año 399 a. C. fue acusado de corromper a los jóvenes y de no respetar a los dioses de Atenas.",
          "Fue condenado a muerte. Pudo escapar. No quiso hacerlo.",
          "Aceptó la sentencia y murió bebiendo una copa de cicuta porque consideraba que un ciudadano debía respetar las leyes incluso cuando le perjudicaban personalmente.",
        ],
        "Dato curioso: la muerte de Sócrates marcó profundamente a Platón, que dedicaría gran parte de su vida a intentar construir una sociedad donde una injusticia semejante no volviera a repetirse."),
      hito("hombre-centro", "platon", "Platón", "427-347 a. C.",
        "¿Existe una realidad más perfecta que la que vemos?",
        [
          "La ejecución de Sócrates convenció a Platón de que la mayoría podía equivocarse. Si Atenas había condenado al hombre más sabio que conocía, quizá la democracia no era suficiente para garantizar la justicia.",
          "Platón imaginó entonces que el mundo que percibimos con los sentidos es solo una copia imperfecta de una realidad mucho más perfecta: el Mundo de las Ideas.",
          "Según él, cuando vemos un árbol, un caballo o una persona, estamos contemplando versiones imperfectas de una Idea eterna y perfecta.",
          "Para explicar esta teoría escribió uno de los relatos más famosos de toda la historia de la filosofía: el Mito de la Caverna.",
          "En él describe a unos prisioneros que viven encadenados desde su nacimiento mirando únicamente las sombras proyectadas sobre una pared. Como nunca han visto otra cosa, creen que esas sombras son toda la realidad. Solo cuando uno consigue salir de la cueva descubre el mundo verdadero.",
          "Para Platón, los filósofos son precisamente quienes logran abandonar la caverna y comprender la auténtica realidad. Por eso defendía que los gobernantes ideales debían ser filósofos.",
        ],
        "Dato curioso: Platón fundó la Academia de Atenas, considerada la primera gran institución dedicada a la enseñanza filosófica. Permaneció abierta durante casi novecientos años."),
      hito("hombre-centro", "aristoteles", "Aristóteles", "384-322 a. C.",
        "¿Y si el conocimiento comenzara observando el mundo real?",
        [
          "Aristóteles estudió durante veinte años en la Academia de Platón, pero acabó discrepando de su maestro.",
          "Mientras Platón buscaba las Ideas perfectas, Aristóteles pensaba que el conocimiento debía comenzar observando cuidadosamente la naturaleza.",
          "Investigó prácticamente todos los campos imaginables: biología, zoología, lógica, ética, política, física, astronomía, retórica y poesía. Por eso muchos lo consideran el primer gran científico de la historia.",
          "También fue el maestro de un joven príncipe llamado Alejandro Magno, quien años después conquistaría uno de los mayores imperios de la Antigüedad y difundiría la cultura griega por gran parte del mundo conocido.",
          "En ética defendía la famosa teoría del justo medio. La virtud, decía, suele encontrarse entre dos extremos. El valor, por ejemplo, está entre la cobardía y la temeridad. La generosidad se sitúa entre la avaricia y el despilfarro.",
          "Su influencia fue tan enorme que durante casi dos mil años sus obras se estudiaron como la máxima autoridad en filosofía y ciencia.",
        ],
        "Dato curioso: durante la Edad Media muchos europeos conocían a Aristóteles simplemente como «El Filósofo», porque se consideraba que ningún otro pensador había explicado el mundo con tanta profundidad."),
      hito("hombre-centro", "legado-tres-gigantes", "El legado de tres gigantes", "",
        "",
        [
          "Pocas veces en la historia tres personas han influido tanto en la forma de pensar de la humanidad.",
          "Sócrates enseñó a cuestionarlo todo mediante el diálogo.",
          "Platón imaginó un mundo gobernado por las ideas y la razón.",
          "Aristóteles defendió que el conocimiento comienza observando la realidad.",
          "Durante más de dos mil años, prácticamente todos los filósofos han dialogado, discutido o intentado mejorar las ideas de alguno de ellos.",
          "Aún hoy, cuando debatimos sobre la justicia, la educación, la ciencia o la política, seguimos utilizando preguntas que ellos formularon hace casi dos mil quinientos años.",
        ]),
    ],
  },
  {
    key: "buena-vida",
    titulo: "Cómo vivir una buena vida",
    anio: "Helenismo y Roma",
    intro:
      "Cuando el mundo cambió, la filosofía dejó de buscar la ciudad perfecta y empezó a enseñar cómo ser feliz. En el año 323 a. C., Alejandro Magno murió después de haber conquistado uno de los mayores imperios de la historia. Su imperio se fragmentó y las antiguas ciudades griegas, como Atenas, perdieron la independencia que habían disfrutado durante siglos. La política dejó de estar en manos de los ciudadanos y muchas personas comenzaron a sentir que ya no podían controlar el rumbo del mundo. Ante esa nueva realidad, la filosofía cambió de objetivo. En lugar de preguntarse cuál era el mejor gobierno o cómo estaba formado el universo, los filósofos comenzaron a hacerse una pregunta mucho más íntima: ¿cómo puede una persona ser feliz, incluso cuando el mundo a su alrededor es caótico? Así nacieron algunas de las escuelas filosóficas más prácticas de toda la historia.",
    subhitos: [
      hito("buena-vida", "diogenes-cinismo", "Diógenes y el cinismo", "≈412-323 a. C.",
        "¿Y si necesitáramos mucho menos de lo que creemos?",
        [
          "Diógenes de Sinope fue probablemente el filósofo más extravagante de la Antigüedad.",
          "Pensaba que la sociedad hacía infelices a las personas porque las llenaba de deseos innecesarios: riqueza, fama, poder, lujo o reconocimiento. Para demostrarlo decidió vivir con lo mínimo imprescindible.",
          "La tradición cuenta que habitaba en una enorme tinaja de barro —muchas veces llamada «barril»— y que poseía tan pocas cosas que, al ver a un niño beber agua con las manos, tiró su único cuenco diciendo: «Ese niño vive con menos cosas que yo».",
          "Para Diógenes, la verdadera libertad consistía en no depender de nada que pudiera perderse.",
          "Su actitud provocadora incomodaba a los poderosos. La anécdota más famosa cuenta que Alejandro Magno fue a visitarlo y le preguntó si podía concederle cualquier deseo. Diógenes respondió simplemente: «Sí. Apártate, me tapas el Sol».",
          "Con aquella frase quería demostrar que incluso el hombre más poderoso del mundo no podía ofrecerle nada que realmente necesitara.",
        ],
        "Dato curioso: la palabra «cínico» procede del griego kynikos, que significa «como un perro», porque los seguidores de esta escuela defendían una vida sencilla y alejada de las normas sociales."),
      hito("buena-vida", "epicuro-epicureismo", "Epicuro y el epicureísmo", "341-270 a. C.",
        "¿Qué significa realmente disfrutar de la vida?",
        [
          "Hoy muchas personas utilizan la palabra «epicúreo» para describir a alguien que disfruta de los grandes placeres. Sin embargo, Epicuro enseñaba casi exactamente lo contrario.",
          "Para él, la felicidad no consistía en comer mucho, acumular riquezas o buscar lujos constantes. Todo eso generaba nuevos deseos y, con ellos, nuevas preocupaciones.",
          "La auténtica felicidad era vivir con serenidad, rodeado de buenos amigos, disfrutando de las pequeñas cosas y evitando los miedos innecesarios.",
          "También afirmaba que no debíamos temer a la muerte. Su argumento era sorprendentemente sencillo: «Mientras nosotros existimos, la muerte no está. Cuando la muerte llega, nosotros ya no existimos».",
          "Por tanto, preocuparse constantemente por ella carecía de sentido.",
          "Epicuro fundó una escuela conocida como El Jardín, donde hombres y mujeres estudiaban juntos, algo muy poco habitual en aquella época.",
        ],
        "Dato curioso: Epicuro consideraba que la amistad era uno de los mayores placeres que podía experimentar un ser humano."),
      hito("buena-vida", "zenon-estoicismo", "Zenón y el estoicismo", "≈334-262 a. C.",
        "¿Podemos controlar todo lo que nos ocurre?",
        [
          "Zenón de Citio observó que gran parte del sufrimiento humano nace de intentar controlar cosas que dependen del azar: la salud, la riqueza, la opinión de los demás o los acontecimientos del mundo.",
          "Por eso enseñó una idea que sigue siendo increíblemente actual: debemos distinguir entre aquello que depende de nosotros... y aquello que no.",
          "No podemos controlar una enfermedad, una tormenta o la conducta de otras personas. Sí podemos controlar nuestras decisiones, nuestras acciones y nuestra actitud frente a los problemas.",
          "Para los estoicos, la verdadera libertad consiste en gobernarse a uno mismo.",
          "Siglos después, emperadores como Marco Aurelio, esclavos como Epicteto o políticos como Séneca desarrollarían esta filosofía hasta convertirla en una de las más influyentes de la historia.",
          "Hoy el estoicismo vive un enorme renacimiento y muchas de sus ideas se utilizan incluso en psicología moderna.",
        ],
        "Dato curioso: Marco Aurelio escribió uno de los libros más famosos del estoicismo, Meditaciones, mientras dirigía el Imperio romano y luchaba en campañas militares."),
      hito("buena-vida", "pirron-escepticismo", "Pirrón y el escepticismo", "≈360-270 a. C.",
        "¿Y si nunca pudiéramos estar completamente seguros de nada?",
        [
          "Pirrón acompañó a Alejandro Magno en algunos de sus viajes y conoció culturas muy diferentes. Aquello le hizo darse cuenta de que personas igualmente inteligentes defendían ideas completamente opuestas.",
          "Entonces comenzó a preguntarse: ¿cómo sabemos que nuestras creencias son realmente verdaderas?",
          "Su respuesta fue radical. Decía que muchas discusiones nacen porque las personas creen estar completamente seguras de cosas que en realidad no pueden demostrar.",
          "Por eso proponía suspender el juicio cuando no existieran pruebas suficientes y aceptar con humildad los límites del conocimiento.",
          "El objetivo no era vivir dudando de todo por desesperación, sino alcanzar tranquilidad evitando discusiones inútiles.",
        ],
        "Dato curioso: la ciencia moderna comparte parcialmente esta actitud: una teoría nunca se considera absolutamente definitiva, sino la mejor explicación disponible hasta que aparezcan nuevas pruebas."),
    ],
  },
  {
    key: "ideas-a-dios",
    titulo: "Del mundo de las ideas al mundo de Dios",
    anio: "Siglos III-V d. C.",
    intro:
      "La filosofía griega comenzó a mezclarse con la espiritualidad. Durante siglos, los filósofos griegos habían intentado comprender el universo mediante la razón. Sin embargo, con el paso del tiempo surgió una nueva inquietud. La gente ya no solo quería saber cómo era el mundo, sino también qué sentido tenía la existencia, qué ocurría después de la muerte y cómo podía el ser humano acercarse a lo divino. En este periodo, la filosofía empezó a encontrarse con la religión. Las ideas de Platón adquirieron un significado espiritual y aparecieron pensadores que intentaron unir la razón con la experiencia religiosa. El más importante de todos fue Plotino.",
    subhitos: [
      hito("ideas-a-dios", "plotino", "Plotino", "204-270 d. C.",
        "¿Existe una realidad superior a todo lo que podemos imaginar?",
        [
          "Plotino nació en Egipto durante el Imperio romano, pero desarrolló su pensamiento en Roma. Admiraba profundamente a Platón, aunque creía que sus ideas podían ir todavía más lejos.",
          "Según Plotino, por encima del universo, de los dioses e incluso del pensamiento existía una realidad absolutamente perfecta a la que llamó simplemente: el Uno.",
          "El Uno no era un dios con forma humana ni una persona. Era la fuente de toda la existencia. Todo cuanto existe procede de Él, igual que la luz procede del Sol.",
          "Cuanto más cerca está algo del Uno, más perfecto es. Cuanto más se aleja, más imperfecto se vuelve.",
          "El objetivo de la vida consistía en regresar espiritualmente hacia esa unidad mediante la contemplación, la filosofía y el conocimiento interior.",
          "Para Plotino, conocer era también una forma de acercarse a lo divino.",
        ],
        "Dato curioso: Plotino era tan humilde que nunca quiso que le hicieran un retrato. Decía que ya era bastante cargar con un cuerpo como para dejar además una imagen de él."),
      hito("ideas-a-dios", "neoplatonismo", "El neoplatonismo", "Siglos III-VI",
        "¿Puede la filosofía explicar la experiencia religiosa?",
        [
          "Las ideas de Plotino dieron origen al neoplatonismo, una corriente filosófica que retomó las enseñanzas de Platón, pero les dio un profundo significado espiritual.",
          "Los neoplatónicos creían que el mundo material era solo un reflejo imperfecto de una realidad superior. El alma humana procedía de ese mundo perfecto y debía esforzarse por regresar a él mediante la virtud, la contemplación y el conocimiento.",
          "Esta corriente tuvo una enorme influencia porque ofrecía un puente entre la filosofía griega y las nuevas religiones monoteístas que estaban creciendo en el Imperio romano.",
          "Muchos conceptos que hoy asociamos al cristianismo medieval —como la idea de que el alma asciende hacia Dios o que existe una realidad espiritual superior a la material— fueron desarrollados filosóficamente por los neoplatónicos.",
        ],
        "Dato curioso: el neoplatonismo influyó no solo en el cristianismo, sino también en filósofos judíos y musulmanes durante toda la Edad Media."),
      hito("ideas-a-dios", "filosofia-teologia", "La filosofía abre las puertas a la teología", "",
        "",
        [
          "Mientras Plotino desarrollaba sus ideas, el cristianismo comenzaba a extenderse rápidamente por el Imperio romano.",
          "Muchos cristianos desconfiaban de la filosofía griega, considerándola una creación pagana.",
          "Sin embargo, otros pensaban justo lo contrario. Creían que la razón podía ayudar a comprender mejor la fe.",
          "Uno de ellos sería un joven brillante llamado Agustín de Hipona. Antes de convertirse al cristianismo había estudiado a Platón y, sobre todo, a Plotino.",
          "Gracias al neoplatonismo encontró una forma de unir la filosofía griega con el mensaje cristiano. Durante más de mil años, esa unión marcaría el pensamiento europeo.",
        ]),
      hito("ideas-a-dios", "puente-dos-mundos", "Un puente entre dos mundos", "",
        "",
        [
          "El neoplatonismo representa uno de los momentos más importantes de toda la historia de la filosofía.",
          "Sin él sería muy difícil entender por qué la filosofía sobrevivió tras la caída del Imperio romano.",
          "Las preguntas de Platón no desaparecieron. Simplemente cambiaron de escenario.",
          "Ahora ya no se preguntaban únicamente: ¿qué es la verdad? Sino también: ¿puede la razón acercarnos a Dios?",
          "Esa pregunta dominaría prácticamente toda la Edad Media.",
        ]),
    ],
  },
  {
    key: "razon-busca-dios",
    titulo: "Cuando la razón busca a Dios",
    anio: "Edad Media",
    intro:
      "Durante casi mil años, la gran pregunta fue si la filosofía podía demostrar aquello que la religión enseñaba. Con la caída del Imperio romano de Occidente en el año 476, Europa cambió profundamente. Muchas ciudades desaparecieron, el comercio disminuyó y gran parte del conocimiento clásico quedó refugiado en monasterios y bibliotecas. Sin embargo, la filosofía no desapareció. Mientras los monjes copiaban las obras de Platón y Aristóteles, en el mundo islámico grandes sabios las traducían al árabe, las comentaban y desarrollaban nuevas ideas. Al mismo tiempo, filósofos judíos intentaban armonizar la tradición hebrea con el pensamiento griego. Durante casi mil años, filósofos de tres religiones distintas compartieron una misma preocupación: ¿puede la razón ayudarnos a comprender a Dios?",
    subhitos: [
      hito("razon-busca-dios", "san-agustin", "San Agustín", "354-430",
        "¿Qué ocurre cuando un filósofo encuentra la fe?",
        [
          "Antes de convertirse al cristianismo, Agustín buscó respuestas en distintas corrientes filosóficas. Durante años leyó a Platón y, especialmente, a Plotino. Aquellas lecturas le convencieron de que la verdad no debía buscarse únicamente en el mundo exterior, sino también dentro de uno mismo.",
          "Tras su conversión escribió algunas de las obras más importantes de la filosofía cristiana, como Las Confesiones y La ciudad de Dios.",
          "Agustín defendía que la razón era una herramienta valiosa, pero que necesitaba la fe para alcanzar plenamente la verdad.",
          "Su famosa frase resume esta idea: «Comprende para creer; cree para comprender».",
          "También reflexionó sobre el tiempo, preguntándose cómo podía existir el pasado si ya no está, o el futuro si todavía no ha llegado. Sus ideas sobre la conciencia y el tiempo siguen estudiándose hoy.",
        ],
        "Dato curioso: Las Confesiones están consideradas una de las primeras autobiografías de la historia."),
      hito("razon-busca-dios", "avicena", "Avicena", "980-1037",
        "¿Puede la filosofía explicar la existencia de Dios?",
        [
          "Mientras Europa atravesaba la Alta Edad Media, el mundo islámico vivía una auténtica edad de oro del conocimiento.",
          "Uno de sus mayores genios fue Avicena (Ibn Sina), médico, científico y filósofo.",
          "Estudió profundamente a Aristóteles y desarrolló argumentos para demostrar racionalmente la existencia de Dios. Según él, todo lo que existe tiene una causa, pero esa cadena no puede prolongarse hasta el infinito. Debe existir un Ser Necesario, que no dependa de nada para existir y que sea el origen de todo lo demás.",
          "Además de filósofo, Avicena escribió uno de los tratados de medicina más importantes de la Edad Media, utilizado en universidades europeas durante siglos.",
        ],
        "Dato curioso: se dice que Avicena escribió más de doscientas obras antes de cumplir los cuarenta años."),
      hito("razon-busca-dios", "averroes", "Averroes", "1126-1198",
        "¿Y si la filosofía y la religión dijeran cosas diferentes?",
        [
          "Nacido en Córdoba, durante el esplendor de Al-Ándalus, Averroes dedicó gran parte de su vida a estudiar y comentar las obras de Aristóteles.",
          "Creía que la verdad solo podía ser una. Si parecía existir contradicción entre la filosofía y la religión, era porque los seres humanos habían interpretado mal una de las dos.",
          "Defendía que las personas preparadas intelectualmente debían utilizar la razón para comprender las Escrituras, mientras que la mayoría podía acercarse a ellas mediante interpretaciones más sencillas.",
          "Gracias a sus comentarios, gran parte de la obra de Aristóteles volvió a conocerse en Europa occidental, influyendo decisivamente en universidades como París, Bolonia u Oxford.",
        ],
        "Dato curioso: durante siglos, en muchas universidades europeas Averroes fue conocido simplemente como «El Comentador», por la enorme calidad de sus explicaciones sobre Aristóteles."),
      hito("razon-busca-dios", "maimonides", "Maimónides", "1138-1204",
        "¿Puede la filosofía fortalecer la fe?",
        [
          "Contemporáneo de Averroes y también nacido en Córdoba, Maimónides fue uno de los mayores pensadores del judaísmo.",
          "Intentó demostrar que la filosofía griega y la tradición judía no eran enemigas, sino complementarias.",
          "En su obra Guía de los perplejos explicó cómo muchas aparentes contradicciones entre la razón y la Biblia podían resolverse mediante una interpretación más profunda de los textos sagrados.",
          "Su influencia fue enorme tanto en el pensamiento judío como en el cristiano y el islámico.",
        ],
        "Dato curioso: Maimónides fue también un médico muy prestigioso y llegó a atender al sultán Saladino."),
      hito("razon-busca-dios", "santo-tomas-aquino", "Santo Tomás de Aquino", "1225-1274",
        "¿Puede demostrarse racionalmente que Dios existe?",
        [
          "Santo Tomás es probablemente el filósofo más importante de toda la Edad Media.",
          "Gracias a las traducciones procedentes del mundo islámico, pudo estudiar en profundidad las obras de Aristóteles y quedó convencido de que la razón y la fe no eran enemigas.",
          "Su obra más famosa, la Suma Teológica, intenta responder prácticamente todas las grandes cuestiones sobre Dios, el ser humano, la moral y el conocimiento.",
          "Entre sus aportaciones destacan las famosas Cinco Vías, cinco argumentos filosóficos con los que intentó demostrar racionalmente la existencia de Dios. Aunque hoy siguen siendo objeto de debate, marcaron profundamente la historia de la filosofía.",
          "Para Santo Tomás, la razón podía descubrir muchas verdades por sí sola, pero había otras —como la Trinidad o la Encarnación— que solo podían conocerse mediante la revelación.",
        ],
        "Dato curioso: las universidades medievales estudiaron las obras de Santo Tomás durante siglos y todavía hoy siguen siendo fundamentales en la filosofía católica."),
      hito("razon-busca-dios", "escolastica", "La Escolástica", "Siglos XI-XV",
        "¿Puede organizarse todo el conocimiento mediante la razón?",
        [
          "La Escolástica no fue un filósofo, sino una forma de enseñar y debatir que dominó las universidades medievales.",
          "Los profesores planteaban una pregunta, analizaban los argumentos a favor y en contra y, finalmente, proponían una respuesta razonada.",
          "Este método ayudó a desarrollar el pensamiento lógico y el debate racional mucho antes del nacimiento de la ciencia moderna.",
          "Las primeras universidades europeas, como París, Bolonia u Oxford, se convirtieron en auténticos laboratorios de ideas donde miles de estudiantes discutían sobre filosofía, derecho, medicina y teología.",
        ],
        "Dato curioso: muchas de las técnicas de debate utilizadas hoy en las universidades tienen su origen en la Escolástica medieval."),
    ],
  },
  {
    key: "humanistas-alquimistas",
    titulo: "Humanistas, alquimistas y el despertar de la ciencia",
    anio: "Renacimiento",
    intro:
      "La humanidad dejó de aceptar la autoridad como única fuente de verdad. A finales de la Edad Media, Europa comenzó a cambiar a una velocidad desconocida. La caída de Constantinopla llevó a muchos sabios griegos a Italia con antiguos manuscritos olvidados, la imprenta permitió difundir las ideas como nunca antes y los grandes viajes demostraron que el mundo era mucho más amplio de lo que se había imaginado. Al mismo tiempo, científicos como Copérnico y Galileo empezaban a cuestionar la visión tradicional del universo. La filosofía también cambió. Durante siglos, la gran pregunta había sido: «¿Cómo demostrar que Dios existe?». Ahora la cuestión era mucho más atrevida: «¿Cómo sabemos que algo es realmente verdadero?». Comenzaba la filosofía moderna.",
    subhitos: [
      hito("humanistas-alquimistas", "humanismo", "El Humanismo", "Siglos XIV-XVI",
        "¿Y si el ser humano fuera el centro del conocimiento?",
        [
          "Los humanistas admiraban profundamente la cultura clásica de Grecia y Roma. Creían que, para construir un mundo mejor, era necesario volver a leer directamente a Platón, Aristóteles, Cicerón y otros autores antiguos.",
          "Pero no querían copiar el pasado. Querían aprender de él.",
          "El Humanismo puso al ser humano en el centro de la educación, defendiendo que cada persona podía desarrollar sus capacidades mediante el estudio, la lectura y el pensamiento crítico.",
          "Frente a una visión exclusivamente religiosa del mundo, los humanistas recuperaron el interés por la historia, la literatura, las lenguas clásicas y las ciencias.",
          "Fue el espíritu intelectual del Renacimiento.",
        ],
        "Dato curioso: el famoso hombre de Vitruvio de Leonardo da Vinci simboliza precisamente esa nueva confianza en las capacidades del ser humano."),
      hito("humanistas-alquimistas", "nicolas-cusa", "Nicolás de Cusa", "1401-1464",
        "¿Y si reconocer nuestra ignorancia fuera el principio del conocimiento?",
        [
          "Nicolás de Cusa fue uno de los pensadores que marcaron el paso entre la Edad Media y el Renacimiento.",
          "Defendía que Dios era infinito y que la inteligencia humana nunca podría comprenderlo completamente.",
          "Por eso hablaba de la «docta ignorancia».",
          "No significaba renunciar al conocimiento. Significaba reconocer que cuanto más aprendemos, más conscientes somos de todo lo que todavía desconocemos.",
          "Muchos consideran que esta actitud abrió el camino a la ciencia moderna.",
        ],
        "Dato curioso: Nicolás de Cusa llegó a imaginar un universo sin un centro absoluto, adelantándose parcialmente a ideas que aparecerían décadas después con Copérnico."),
      hito("humanistas-alquimistas", "hermetismo-alquimia", "Hermetismo y alquimia", "Siglos XV-XVII",
        "¿Podían descubrirse los secretos ocultos de la naturaleza?",
        [
          "Durante el Renacimiento no todos buscaban el conocimiento mediante experimentos o razonamientos.",
          "Muchos pensadores creían que el universo escondía misterios accesibles únicamente a quienes supieran interpretar sus símbolos.",
          "Así surgió un enorme interés por el Hermetismo, una tradición inspirada en unos antiguos textos atribuidos a Hermes Trismegisto, un personaje legendario que combinaba rasgos del dios egipcio Thot y del dios griego Hermes.",
          "Los alquimistas no solo intentaban transformar el plomo en oro. También buscaban comprender las fuerzas ocultas de la naturaleza y alcanzar una transformación espiritual del propio ser humano.",
          "Aunque muchas de sus teorías eran erróneas, sus experimentos ayudaron a desarrollar técnicas que más tarde resultarían útiles para el nacimiento de la química.",
        ],
        "Dato curioso: la famosa Piedra Filosofal no simbolizaba únicamente fabricar oro. Para muchos alquimistas representaba la perfección espiritual."),
      hito("humanistas-alquimistas", "paracelso", "Paracelso", "1493-1541",
        "¿Puede la experiencia valer más que la tradición?",
        [
          "Paracelso fue médico, alquimista y filósofo.",
          "Criticó duramente a los médicos que repetían las enseñanzas antiguas sin comprobar si realmente funcionaban.",
          "Defendía que el conocimiento debía basarse en la observación directa de la naturaleza y de los pacientes.",
          "Aunque todavía mezclaba ciencia, alquimia y misticismo, ayudó a transformar la medicina hacia un enfoque mucho más experimental.",
          "Por ello muchos lo consideran uno de los precursores de la medicina moderna.",
        ],
        "Dato curioso: Paracelso popularizó una frase que sigue siendo fundamental en farmacología: «La dosis hace el veneno». Es decir, cualquier sustancia puede ser beneficiosa o perjudicial dependiendo de la cantidad."),
      hito("humanistas-alquimistas", "rosacruces", "Los Rosacruces", "Desde el siglo XVII",
        "¿Existe un conocimiento reservado para unos pocos?",
        [
          "A comienzos del siglo XVII aparecieron unos misteriosos manifiestos que hablaban de una supuesta fraternidad secreta llamada Rosacruz.",
          "Según esos textos, sus miembros poseían antiguos conocimientos sobre filosofía, ciencia, religión y alquimia destinados a mejorar la humanidad.",
          "No está claro si la orden existió realmente o si fue una creación literaria.",
          "Sin embargo, su influencia fue enorme y alimentó durante siglos numerosas leyendas sobre sociedades secretas, sabiduría oculta y conocimientos prohibidos.",
        ],
        "Dato curioso: todavía hoy existen organizaciones rosacruces, aunque muy diferentes de las descritas en aquellas primeras leyendas."),
      hito("humanistas-alquimistas", "templarios", "Los templarios y el mito del conocimiento oculto", "Siglos XII-Actualidad",
        "¿Por qué los templarios aparecen en tantas historias de misterios?",
        [
          "Los Caballeros Templarios fueron una orden militar creada durante las Cruzadas para proteger a los peregrinos que viajaban a Tierra Santa.",
          "Con el tiempo acumularon grandes riquezas y poder político, hasta que el rey Felipe IV de Francia ordenó su persecución en 1307.",
          "Siglos después comenzaron a surgir leyendas que afirmaban que los templarios habían descubierto el Santo Grial, antiguos manuscritos secretos o conocimientos alquímicos.",
          "No existen pruebas históricas que confirmen estas historias.",
          "Sin embargo, esas leyendas inspiraron numerosas novelas, películas y sociedades esotéricas, convirtiendo a los templarios en uno de los mayores mitos de la cultura occidental.",
        ],
        "Dato curioso: muchas de las historias que hoy asociamos a los templarios fueron inventadas varios siglos después de su desaparición."),
      hito("humanistas-alquimistas", "maquiavelo", "Nicolás Maquiavelo", "1469-1527",
        "¿Debe un gobernante hacer siempre lo correcto?",
        [
          "Mientras muchos filósofos imaginaban cómo debería ser un gobernante ideal, Maquiavelo decidió estudiar cómo actuaban realmente los gobernantes.",
          "En su obra El príncipe analizó la política tal como es, no como le gustaría que fuera.",
          "Defendía que un gobernante debía hacer todo lo necesario para conservar el Estado, incluso cuando eso implicara tomar decisiones moralmente difíciles.",
          "No estaba diciendo que la crueldad fuera buena. Estaba afirmando que la política funciona con reglas diferentes a las de la moral individual.",
          "Por eso suele considerarse el fundador de la ciencia política moderna.",
        ],
        "Dato curioso: la expresión «el fin justifica los medios» suele atribuirse a Maquiavelo, aunque esa frase nunca aparece escrita literalmente en El príncipe."),
      hito("humanistas-alquimistas", "mundo-empezaba-de-nuevo", "Un mundo que empezaba de nuevo", "",
        "",
        [
          "El Renacimiento cambió profundamente la forma de pensar.",
          "Los filósofos comenzaron a leer directamente a los clásicos. Los científicos empezaron a observar la naturaleza. Los artistas estudiaban el cuerpo humano. Los exploradores descubrían nuevos continentes.",
          "Todo parecía indicar que el conocimiento podía avanzar sin depender únicamente de la autoridad.",
          "La gran revolución estaba a punto de comenzar.",
        ]),
    ],
  },
  {
    key: "revolucion-pensamiento",
    titulo: "La revolución del pensamiento",
    anio: "Siglos XVII-XVIII",
    intro:
      "¿Cómo sabemos que algo es realmente cierto? Durante siglos, los filósofos habían confiado en las enseñanzas de Aristóteles o en la autoridad de la Iglesia. Pero el Renacimiento y la Revolución Científica cambiaron completamente el panorama. Los telescopios mostraban un universo diferente del imaginado por los antiguos. Los experimentos demostraban que incluso las ideas más aceptadas podían estar equivocadas. La filosofía comenzó entonces a hacerse una nueva pregunta: ¿cuál es el mejor camino para alcanzar el conocimiento? Algunos respondieron que la razón era la fuente principal de la verdad. Otros defendieron que todo conocimiento nace de la experiencia. Durante más de un siglo, este debate dominaría la filosofía europea.",
    // Momentos aún por añadir del índice original: Montesquieu · Voltaire · Jean-Jacques Rousseau · Blaise Pascal
    subhitos: [
      hito("revolucion-pensamiento", "francis-bacon", "Francis Bacon", "1561-1626",
        "¿Y si dejáramos de adivinar cómo funciona el mundo y empezáramos a comprobarlo?",
        [
          "Francis Bacon criticaba duramente a quienes construían teorías sin observar la realidad.",
          "Según él, el conocimiento debía basarse en la experiencia, la observación y la experimentación.",
          "Propuso un método que consistía en reunir datos, compararlos y extraer conclusiones generales. Hoy lo conocemos como método inductivo y constituye uno de los pilares de la ciencia moderna.",
          "Bacon también advirtió que nuestra mente está llena de prejuicios que distorsionan la realidad. Los llamó «ídolos», porque actúan como falsas creencias que nos impiden pensar con claridad.",
        ],
        "Dato curioso: Bacon es considerado uno de los padres del método científico moderno, aunque él mismo realizó muy pocos experimentos."),
      hito("revolucion-pensamiento", "galileo-galilei", "Galileo Galilei", "1564-1642",
        "¿Qué ocurre cuando la observación contradice a la autoridad?",
        [
          "Galileo dirigió un telescopio hacia el cielo y descubrió montañas en la Luna, manchas solares y satélites girando alrededor de Júpiter.",
          "Aquellas observaciones demostraban que el universo no era exactamente como lo había descrito Aristóteles. También apoyaban la teoría de Copérnico, según la cual la Tierra gira alrededor del Sol.",
          "La Iglesia consideró peligrosas estas ideas y Galileo fue juzgado por la Inquisición. Aunque terminó bajo arresto domiciliario, su trabajo transformó para siempre la relación entre ciencia y filosofía.",
          "Galileo defendía una idea revolucionaria: la naturaleza debe leerse observándola, no únicamente consultando libros antiguos.",
        ],
        "Dato curioso: la famosa frase «Eppur si muove» («Y, sin embargo, se mueve») probablemente nunca fue pronunciada por Galileo, aunque se convirtió en el símbolo de la libertad científica."),
      hito("revolucion-pensamiento", "rene-descartes", "René Descartes", "1596-1650",
        "¿Existe alguna verdad de la que no podamos dudar?",
        [
          "Descartes decidió hacer algo que ningún filósofo había intentado de forma tan radical: dudar de absolutamente todo.",
          "¿Y si nuestros sentidos nos engañan? ¿Y si todo lo que creemos saber es falso? ¿Y si incluso estamos soñando?",
          "Después de cuestionarlo todo descubrió una única certeza. Mientras dudaba, estaba pensando. Y si pensaba, existía.",
          "Así nació una de las frases más famosas de toda la historia de la filosofía: «Pienso, luego existo» (Cogito, ergo sum).",
          "A partir de esa certeza intentó reconstruir todo el conocimiento mediante la razón. Por ello se le considera el padre del racionalismo moderno.",
        ],
        "Dato curioso: Descartes también fue un brillante matemático y creó el sistema de coordenadas cartesianas que seguimos utilizando hoy."),
      hito("revolucion-pensamiento", "baruch-spinoza", "Baruch Spinoza", "1632-1677",
        "¿Y si Dios no estuviera fuera del universo... sino que fuera el propio universo?",
        [
          "Spinoza fue uno de los filósofos más valientes de su tiempo. Nacido en una comunidad judía de Ámsterdam, sus ideas resultaron tan revolucionarias que fue expulsado de ella mediante una excomunión extremadamente severa.",
          "Mientras la mayoría imaginaba a Dios como un ser separado del mundo, Spinoza defendió algo completamente distinto. Para él, Dios y la Naturaleza son una misma realidad.",
          "Lo expresó con una frase que se hizo célebre: «Deus sive Natura» («Dios, o lo que es lo mismo, la Naturaleza»).",
          "Según Spinoza, todo cuanto existe forma parte de una única realidad infinita. Nada ocurre por casualidad. Todo sigue las leyes de la naturaleza.",
          "Por eso también pensaba que el ser humano posee menos libertad de la que cree. Muchas de nuestras decisiones están condicionadas por causas que desconocemos. Sin embargo, cuanto mejor comprendemos esas causas, más libres nos volvemos.",
          "Además defendió la libertad de pensamiento y la tolerancia religiosa en una época en la que estas ideas podían costar la vida. Albert Einstein confesó siglos después que el Dios en el que creía era precisamente el Dios de Spinoza.",
        ],
        "Dato curioso: Spinoza rechazó un prestigioso puesto como profesor universitario para conservar su independencia intelectual. Prefería vivir modestamente puliendo lentes antes que renunciar a su libertad para pensar."),
      hito("revolucion-pensamiento", "thomas-hobbes", "Thomas Hobbes", "1588-1679",
        "¿Qué ocurriría si no existieran leyes?",
        [
          "Hobbes imaginó una situación extrema: un mundo sin gobiernos, sin jueces, sin policía, sin normas.",
          "Pensaba que, en ese estado natural, las personas acabarían enfrentándose unas a otras para sobrevivir. Lo describió como «la guerra de todos contra todos».",
          "Para evitar ese caos, los seres humanos aceptan entregar parte de su libertad a un Estado fuerte que garantice el orden. Esta idea dio origen a la teoría moderna del contrato social.",
        ],
        "Dato curioso: Hobbes llamó Leviatán al Estado, tomando el nombre de un gigantesco monstruo marino mencionado en la Biblia."),
      hito("revolucion-pensamiento", "john-locke", "John Locke", "1632-1704",
        "¿Y si todos naciéramos iguales?",
        [
          "Locke no estaba de acuerdo con Hobbes. Creía que las personas poseen unos derechos que ningún gobernante puede quitarles. Entre ellos destacaban la vida, la libertad y la propiedad.",
          "Según Locke, los gobiernos existen para proteger esos derechos, no para concederlos. Si un gobernante los viola, el pueblo tiene derecho a sustituirlo. Estas ideas influirían profundamente en la independencia de Estados Unidos y en la Revolución Francesa.",
          "Además, defendía que la mente humana al nacer es una tabla rasa. No venimos al mundo con conocimientos innatos: aprendemos gracias a la experiencia.",
        ],
        "Dato curioso: muchas de las ideas presentes en las democracias actuales proceden directamente de Locke."),
      hito("revolucion-pensamiento", "gottfried-leibniz", "Gottfried Leibniz", "1646-1716",
        "¿Vivimos en el mejor de los mundos posibles?",
        [
          "Leibniz fue matemático, científico, diplomático y filósofo.",
          "Pensaba que Dios, siendo perfecto, había creado el mejor universo que era posible crear. Aunque exista el mal, ese mal forma parte de un equilibrio más amplio que nosotros todavía no alcanzamos a comprender.",
          "También imaginó que toda la realidad está formada por unas entidades espirituales llamadas mónadas, pequeñas unidades de existencia que constituyen todo cuanto existe.",
          "Fue además uno de los inventores del cálculo infinitesimal, al mismo tiempo que Newton.",
        ],
        "Dato curioso: Leibniz soñó con crear un lenguaje universal basado en la lógica que permitiera resolver los desacuerdos mediante cálculos. Muchos consideran que esa idea anticipó la informática moderna."),
      hito("revolucion-pensamiento", "david-hume", "David Hume", "1711-1776",
        "¿Podemos estar completamente seguros de algo?",
        [
          "Hume llevó el empirismo hasta sus últimas consecuencias. Decía que todo conocimiento procede de la experiencia.",
          "Pero planteó un problema enorme. Vemos que el Sol sale cada mañana. ¿Podemos demostrar que saldrá mañana? No. Solo sabemos que siempre ha ocurrido así.",
          "Nuestra confianza en el futuro se basa en la costumbre, no en una certeza absoluta. Este problema, conocido como el problema de la inducción, sigue siendo uno de los grandes debates de la filosofía de la ciencia.",
          "Hume también cuestionó muchas ideas tradicionales sobre la religión, el alma y la causalidad. Su escepticismo sacudiría profundamente a un joven filósofo alemán llamado Immanuel Kant.",
        ],
        "Dato curioso: Kant confesó que fue precisamente la lectura de Hume la que lo despertó de su «sueño dogmático»."),
      hito("revolucion-pensamiento", "dos-caminos-conocimiento", "Dos caminos hacia el conocimiento", "",
        "",
        [
          "Al finalizar el siglo XVIII, la filosofía parecía dividida en dos grandes escuelas.",
          "Los racionalistas, como Descartes, Spinoza y Leibniz, confiaban principalmente en la razón.",
          "Los empiristas, como Bacon, Locke y Hume, defendían que todo conocimiento comienza con la experiencia.",
          "¿Quién tenía razón? Durante décadas nadie consiguió resolver completamente ese debate.",
          "Hasta que apareció un profesor de Königsberg llamado Immanuel Kant.",
        ]),
    ],
  },
  {
    key: "que-conocer",
    titulo: "¿Qué podemos conocer?",
    anio: "Siglo XVIII",
    intro:
      "El filósofo que intentó reconciliar la razón y la experiencia. Después de casi dos siglos de discusión, la filosofía parecía encontrarse en un callejón sin salida. Los racionalistas afirmaban que la razón era la principal fuente del conocimiento. Los empiristas respondían que todo procede de la experiencia. Ambos tenían buenos argumentos. Y ambos parecían tener también importantes problemas. Fue entonces cuando un profesor alemán propuso una idea completamente nueva. No había que elegir entre razón o experiencia. Las dos eran necesarias. Ese profesor se llamaba Immanuel Kant.",
    subhitos: [
      hito("que-conocer", "immanuel-kant", "Immanuel Kant", "1724-1804",
        "¿Cómo sabemos que conocemos realmente el mundo?",
        [
          "Kant vivió toda su vida en la ciudad prusiana de Königsberg y llevó una existencia tan ordenada que se decía que los vecinos podían poner en hora sus relojes cuando salía a pasear.",
          "Sin embargo, detrás de esa rutina se escondía una de las mentes más revolucionarias de la historia.",
          "Kant admiraba a los racionalistas, pero también reconocía la fuerza de las críticas de Hume. Entonces se hizo una pregunta diferente.",
          "Hasta ese momento todos los filósofos preguntaban: ¿cómo es el mundo? Kant cambió la pregunta por otra mucho más profunda: ¿cómo funciona la mente que intenta conocer el mundo?",
          "Su respuesta transformó la filosofía.",
        ]),
      hito("que-conocer", "revolucion-copernicana-kant", "La revolución copernicana de Kant", "",
        "",
        [
          "Kant comparó su teoría con la de Copérnico.",
          "Antes de Copérnico se pensaba que el Sol giraba alrededor de la Tierra. Copérnico cambió completamente el punto de vista.",
          "Kant hizo algo parecido. Hasta entonces se pensaba que nuestra mente debía adaptarse al mundo. Él propuso justo lo contrario.",
          "El mundo, tal y como lo conocemos, también está organizado por la forma en que funciona nuestra mente. No conocemos la realidad exactamente como es. La conocemos tal como nuestro cerebro puede comprenderla.",
          "Por eso llamó a su teoría una auténtica «revolución copernicana» de la filosofía.",
        ],
        "Dato curioso: muchos científicos actuales consideran que esta idea anticipó cuestiones que hoy estudian la psicología y las neurociencias sobre cómo construimos nuestra percepción de la realidad."),
      hito("que-conocer", "razon-y-experiencia", "Razón y experiencia", "",
        "",
        [
          "Kant resumía toda su filosofía con una frase muy famosa: «Todo nuestro conocimiento comienza con la experiencia, pero no todo procede de la experiencia».",
          "Cuando nacemos no conocemos nada. Necesitamos experimentar el mundo. Pero la experiencia, por sí sola, sería un caos.",
          "Nuestra mente organiza automáticamente todo lo que percibimos mediante conceptos como el espacio, el tiempo o la causalidad.",
          "Por eso, según Kant, conocer consiste en una colaboración constante entre nuestros sentidos y nuestra razón.",
        ]),
      hito("que-conocer", "etica-del-deber", "La ética del deber", "",
        "¿Cómo sabemos si una acción es realmente buena?",
        [
          "Kant no solo transformó la teoría del conocimiento. También revolucionó la ética.",
          "Para Kant, una acción no es moral porque produzca buenos resultados. Es moral cuando hacemos lo correcto por deber.",
          "Su principio más famoso recibe el nombre de imperativo categórico. En una de sus formulaciones dice: «Actúa solo según una regla que puedas querer que se convierta en una ley universal».",
          "Es decir, antes de actuar, pregúntate: ¿qué ocurriría si todo el mundo hiciera lo mismo? Si la respuesta destruye la convivencia, probablemente esa acción no sea moral.",
        ]),
      hito("que-conocer", "dignidad-humana", "La dignidad humana", "",
        "",
        [
          "Otra de las grandes aportaciones de Kant fue afirmar que las personas nunca deben ser tratadas únicamente como un medio para conseguir un objetivo.",
          "Cada ser humano posee una dignidad propia.",
          "Esto significa que nadie debería ser utilizado, manipulado o sacrificado simplemente porque resulte útil para otros.",
          "Esta idea ha influido enormemente en los derechos humanos, en la filosofía política y en muchas constituciones modernas.",
        ],
        "Dato curioso: buena parte de la Declaración Universal de los Derechos Humanos refleja principios que recuerdan directamente a la ética de Kant."),
      hito("que-conocer", "kant-reglas-del-juego", "El filósofo que cambió las reglas del juego", "",
        "",
        [
          "Con Kant terminó una etapa de la filosofía.",
          "A partir de él, la pregunta ya no sería únicamente: ¿qué podemos conocer?",
          "También aparecerían otras nuevas: ¿cómo construye la mente la realidad? ¿Somos realmente libres? ¿Tiene la historia un sentido? ¿Qué hace al ser humano diferente?",
          "Prácticamente todos los grandes filósofos de los siglos XIX y XX dialogarán con Kant, ya sea para continuar su pensamiento... o para discutirlo.",
        ]),
    ],
  },
  {
    key: "grandes-ideas",
    titulo: "El siglo de las grandes ideas",
    anio: "Siglo XIX",
    intro:
      "Nunca antes tantos filósofos habían cambiado tanto la forma de entender al ser humano. El siglo XIX fue una época de cambios extraordinarios. La Revolución Industrial llenó Europa de fábricas y ciudades, aparecieron nuevas máquinas, millones de personas abandonaron el campo para trabajar en las industrias y las revoluciones políticas comenzaron a cuestionar el poder de reyes e iglesias. La ciencia avanzaba a un ritmo nunca visto. La economía estaba transformando la sociedad. Y la filosofía volvió a hacerse nuevas preguntas. ¿Tiene la historia un sentido? ¿Somos realmente libres? ¿Por qué existe el sufrimiento? ¿Qué ocurrirá si la religión deja de ser el centro de la sociedad? Las respuestas fueron muy diferentes... y algunas cambiarían el mundo para siempre.",
    subhitos: [
      hito("grandes-ideas", "hegel", "Georg Wilhelm Friedrich Hegel", "1770-1831",
        "¿Avanza la historia hacia algún lugar?",
        [
          "Hasta entonces muchos pensaban que la historia era simplemente una sucesión de guerras, reyes y acontecimientos. Hegel propuso una idea completamente distinta.",
          "Según él, la historia tiene una dirección. La humanidad avanza poco a poco hacia mayores cotas de libertad.",
          "Pero ese avance nunca es sencillo. Cada idea genera otra que la contradice. De ese conflicto nace una nueva forma de pensar. Y ese proceso vuelve a repetirse.",
          "Aunque Hegel nunca utilizó exactamente las palabras tesis, antítesis y síntesis, esa expresión resume bastante bien cómo entendía la evolución de las ideas.",
          "Para él, los conflictos no eran accidentes. Eran el motor del progreso. Su visión influiría enormemente en filósofos posteriores, especialmente en Karl Marx.",
        ],
        "Dato curioso: Hegel llegó a decir que había visto «al espíritu de la historia a caballo» cuando contempló a Napoleón entrar victorioso en una ciudad alemana."),
      hito("grandes-ideas", "schopenhauer", "Arthur Schopenhauer", "1788-1860",
        "¿Y si el sufrimiento fuera inevitable?",
        [
          "Schopenhauer fue uno de los filósofos más pesimistas de la historia.",
          "Mientras Hegel veía un progreso constante, él observaba algo muy distinto. Las personas desean continuamente cosas nuevas. Cuando las consiguen, pronto vuelven a sentirse insatisfechas.",
          "Para Schopenhauer, la vida está impulsada por una fuerza irracional que llamó la voluntad. Esa voluntad nos empuja constantemente a desear más, y precisamente por eso nunca alcanzamos una felicidad completa.",
          "Curiosamente, encontró inspiración en las filosofías de la India, especialmente en el budismo, que también hablaba del deseo como origen del sufrimiento.",
        ],
        "Dato curioso: Schopenhauer fue uno de los primeros filósofos europeos en estudiar seriamente textos hindúes y budistas."),
      hito("grandes-ideas", "kierkegaard", "Søren Kierkegaard", "1813-1855",
        "¿Qué significa elegir tu propia vida?",
        [
          "Kierkegaard pensaba que la filosofía se estaba olvidando de algo muy importante: cada persona.",
          "Mientras otros filósofos hablaban de la humanidad en general, él se preguntaba cómo vive un individuo concreto sus dudas, sus miedos y sus decisiones.",
          "Defendía que nadie puede vivir por nosotros. Cada persona debe elegir quién quiere ser, aunque eso produzca angustia. Porque elegir implica renunciar a otros caminos.",
          "Por eso suele considerarse el padre del existencialismo, una corriente que florecería un siglo después con Sartre y Camus.",
        ],
        "Dato curioso: muchas de sus obras fueron publicadas con seudónimos porque quería que el lector reflexionara sobre las ideas sin centrarse en la figura del autor."),
      hito("grandes-ideas", "mill", "John Stuart Mill", "1806-1873",
        "¿Qué significa realmente ser libre?",
        [
          "Mill defendió que cada persona debería ser libre para vivir como quisiera, siempre que no perjudicara a los demás. Esta idea, conocida como el principio del daño, sigue siendo uno de los fundamentos del liberalismo moderno.",
          "También fue uno de los primeros filósofos en defender públicamente la igualdad entre hombres y mujeres.",
          "En una época en la que casi nadie cuestionaba esa desigualdad, escribió La sujeción de las mujeres. En esa obra denunciaba que impedir a las mujeres estudiar, votar o participar en la política era una enorme injusticia.",
        ],
        "Dato curioso: Mill fue diputado en el Parlamento británico y uno de los primeros en defender el derecho al voto femenino."),
      hito("grandes-ideas", "marx", "Karl Marx", "1818-1883",
        "¿Quién mueve realmente la historia?",
        [
          "Marx admiraba profundamente a Hegel, pero pensaba que se equivocaba en algo fundamental. No son las ideas las que cambian el mundo. Son las condiciones materiales: la economía, el trabajo, la forma en que una sociedad produce riqueza.",
          "Según Marx, toda la historia puede entenderse como una lucha entre grupos sociales con intereses opuestos. En el siglo XIX esos grupos eran principalmente la burguesía, propietaria de las fábricas, y el proletariado, formado por los trabajadores.",
          "Creía que el capitalismo acabaría generando enormes desigualdades y que los trabajadores terminarían organizándose para transformar la sociedad.",
          "Sus ideas inspiraron revoluciones, partidos políticos y gobiernos durante todo el siglo XX.",
        ],
        "Dato curioso: probablemente ningún filósofo ha influido tanto en la política mundial como Karl Marx."),
      hito("grandes-ideas", "darwin", "Charles Darwin", "1809-1882",
        "¿Y si el ser humano fuera una especie más de la naturaleza?",
        [
          "Darwin no era filósofo. Era naturalista. Sin embargo, pocas personas han cambiado tanto la filosofía.",
          "Hasta entonces muchas culturas pensaban que el ser humano había sido creado de forma especial y ocupaba un lugar único en la naturaleza.",
          "En 1859 Darwin publicó El origen de las especies. Su teoría de la evolución mediante selección natural proponía que todas las especies, incluido el ser humano, compartían antepasados comunes y habían evolucionado durante millones de años.",
          "La idea provocó un enorme debate. No solo transformó la biología. También obligó a la filosofía a replantearse preguntas fundamentales: ¿qué nos hace humanos? ¿Seguimos siendo el centro de la creación? ¿Cómo encaja la evolución con las creencias religiosas?",
          "Todavía hoy estas cuestiones siguen siendo objeto de debate.",
        ],
        "Dato curioso: Darwin tardó más de veinte años en publicar su teoría porque era consciente de la enorme polémica que podía provocar."),
      hito("grandes-ideas", "nietzsche", "Friedrich Nietzsche", "1844-1900",
        "¿Qué ocurre cuando una civilización deja de creer en aquello que le daba sentido?",
        [
          "A finales del siglo XIX, Europa estaba cambiando rápidamente. La ciencia avanzaba. La industrialización transformaba la sociedad. Cada vez más personas dejaban de explicar el mundo exclusivamente mediante la religión.",
          "Fue entonces cuando Nietzsche escribió una de las frases más famosas de toda la historia: «Dios ha muerto».",
          "No quería decir que Dios hubiera existido y acabara de morir. Quería decir algo mucho más profundo. Durante siglos, la cultura europea había construido su moral, su política y su forma de entender el mundo alrededor del cristianismo. Ahora ese fundamento comenzaba a desaparecer.",
          "Y Nietzsche lanzaba una advertencia. Si dejamos de creer en los antiguos valores, ¿con qué los sustituiremos?",
          "También criticó duramente la obediencia ciega, el conformismo y la resignación. Defendía que cada persona debía construir sus propios valores y atreverse a vivir plenamente.",
          "A esta idea la representó mediante el concepto del superhombre (Übermensch), una persona capaz de crear su propio sentido de la vida en lugar de limitarse a seguir las normas heredadas.",
          "Aunque sus escritos fueron manipulados décadas después por el nazismo, esa interpretación contradice muchas de las propias ideas de Nietzsche, que murió antes del nacimiento de ese movimiento.",
        ],
        "Dato curioso: la expresión «Dios ha muerto» es probablemente la frase filosófica más conocida del mundo, pero muy pocas personas conocen su verdadero significado."),
    ],
  },
  {
    key: "mente-humana",
    titulo: "Descubriendo la mente humana",
    anio: "Siglo XX",
    intro:
      "Quizá no somos tan racionales como creemos. Durante siglos, la filosofía había confiado en la razón como la mejor herramienta del ser humano. Pero el siglo XX lo puso todo en duda. Dos guerras mundiales, los campos de exterminio y las bombas atómicas demostraron que la civilización más avanzada también podía cometer las mayores atrocidades. Al mismo tiempo, el psicoanálisis revelaba que buena parte de nuestra conducta nace de impulsos inconscientes que ni siquiera comprendemos. La filosofía dejó entonces de preguntarse solo qué podemos conocer y empezó a preguntarse quiénes somos, por qué existimos y cómo debemos vivir en un mundo que parecía haber perdido el sentido.",
    subhitos: [
      hito("mente-humana", "sigmund-freud", "Sigmund Freud", "1856-1939",
        "¿Y si no fuéramos dueños de nuestra propia mente?",
        [
          "Freud no era filósofo, sino médico, pero su influencia en la forma de entender al ser humano fue enorme.",
          "Propuso que bajo la parte consciente de nuestra mente existe algo mucho más grande y oculto: el inconsciente.",
          "Según él, muchos de nuestros deseos, miedos y recuerdos quedan enterrados allí y, sin darnos cuenta, guían nuestra conducta, nuestros sueños e incluso nuestros errores.",
          "La idea era inquietante. Si gran parte de lo que hacemos nace de impulsos que no controlamos, ¿hasta qué punto somos realmente libres y racionales?",
          "Aunque hoy muchas de sus teorías han sido revisadas o superadas, Freud cambió para siempre la manera de mirar la mente humana.",
        ],
        "Dato curioso: Freud llamó psicoanálisis a su método, basado en hablar y en interpretar los sueños, y de él proceden palabras tan habituales hoy como «represión» o «subconsciente»."),
      hito("mente-humana", "edmund-husserl", "Edmund Husserl", "1859-1938",
        "¿Podemos describir la experiencia tal y como realmente la vivimos?",
        [
          "Husserl quería devolver a la filosofía el rigor de una ciencia, pero partiendo de algo muy concreto: la experiencia vivida.",
          "Propuso un método llamado fenomenología, que consistía en describir con la máxima precisión cómo se nos aparecen las cosas en la conciencia, dejando de lado por un momento las teorías y los prejuicios.",
          "En lugar de preguntarse si el mundo exterior existe, se centraba en cómo lo experimentamos: cómo percibimos un color, recordamos un rostro o sentimos el paso del tiempo.",
          "Su método influyó en casi todos los grandes filósofos del siglo XX, empezando por su propio discípulo, Martin Heidegger.",
        ],
        "Dato curioso: la fenomenología no solo transformó la filosofía; también dejó huella en la psicología, la sociología y hasta en el diseño de tecnología pensada «desde la experiencia del usuario»."),
      hito("mente-humana", "martin-heidegger", "Martin Heidegger", "1889-1976",
        "¿Qué significa realmente existir?",
        [
          "Heidegger pensaba que la filosofía había olvidado su pregunta más importante: ¿qué significa ser?",
          "Se dio cuenta de que el ser humano es el único que se pregunta por su propia existencia. A diferencia de una piedra o un animal, nosotros sabemos que vivimos... y que vamos a morir.",
          "Precisamente por eso, decía, vivir con autenticidad consiste en asumir que nuestro tiempo es limitado y decidir qué hacer con él, en lugar de dejarnos arrastrar por la rutina y por lo que «se supone» que hay que hacer.",
          "Su obra, difícil y profunda, influyó enormemente en el existencialismo posterior.",
        ],
        "Dato curioso: Heidegger inventó numerosas palabras nuevas porque creía que el lenguaje habitual no bastaba para expresar sus ideas sobre la existencia."),
      hito("mente-humana", "jean-paul-sartre", "Jean-Paul Sartre", "1905-1980",
        "¿Y si estuviéramos condenados a ser libres?",
        [
          "Sartre fue la gran figura del existencialismo. Su idea central puede resumirse en una frase: «la existencia precede a la esencia».",
          "Quería decir que el ser humano no nace con un propósito ya escrito. Primero existimos y, después, mediante nuestras decisiones, vamos construyendo quiénes somos.",
          "Eso nos hace radicalmente libres, pero también totalmente responsables. No podemos culpar a los dioses, al destino ni a nuestra naturaleza: somos lo que elegimos ser.",
          "Sartre decía que estamos «condenados a ser libres», porque incluso no elegir es ya una elección.",
        ],
        "Dato curioso: Sartre rechazó el Premio Nobel de Literatura en 1964 porque no quería que ninguna institución condicionara su independencia como escritor."),
      hito("mente-humana", "simone-de-beauvoir", "Simone de Beauvoir", "1908-1986",
        "¿Se nace mujer o se llega a serlo?",
        [
          "Compañera intelectual de Sartre, Simone de Beauvoir llevó el existencialismo a un terreno nuevo: la condición de la mujer.",
          "En su obra El segundo sexo analizó cómo, a lo largo de la historia, la sociedad había definido a la mujer siempre en relación con el hombre, como si fuera «lo otro».",
          "Su frase más famosa resume su pensamiento: «No se nace mujer, se llega a serlo». Con ella quería decir que muchos de los papeles considerados «femeninos» no son naturales, sino aprendidos e impuestos por la cultura.",
          "Su trabajo se convirtió en una de las bases del feminismo moderno.",
        ],
        "Dato curioso: El segundo sexo causó tanto escándalo al publicarse en 1949 que llegó a incluirse en listas de libros prohibidos."),
      hito("mente-humana", "albert-camus", "Albert Camus", "1913-1960",
        "¿Tiene sentido la vida... aunque no tenga sentido?",
        [
          "Camus se enfrentó a una pregunta incómoda: si el universo no tiene un sentido evidente, ¿merece la pena vivir?",
          "A esa contradicción entre nuestra necesidad de sentido y un mundo que no lo ofrece la llamó lo absurdo.",
          "Pero su respuesta no fue pesimista. Propuso rebelarse contra el absurdo viviendo con intensidad, disfrutando y creando, precisamente porque la vida no viene con un manual de instrucciones.",
          "Lo explicó con el mito de Sísifo, aquel personaje condenado a empujar eternamente una roca montaña arriba. Camus imaginaba que, pese a todo, podíamos imaginar a Sísifo feliz.",
        ],
        "Dato curioso: Camus recibió el Premio Nobel de Literatura con solo 44 años y murió poco después en un accidente de coche, llevando en el bolsillo un billete de tren que finalmente no llegó a usar."),
      hito("mente-humana", "hannah-arendt", "Hannah Arendt", "1906-1975",
        "¿Cómo pueden personas normales cometer atrocidades?",
        [
          "Arendt vivió en primera persona el horror del siglo XX. Judía alemana, tuvo que huir del nazismo y dedicó su vida a comprender cómo había sido posible tanta crueldad.",
          "Al cubrir el juicio de un alto responsable nazi, esperaba encontrarse con un monstruo. En su lugar vio a un hombre corriente que se limitaba a «cumplir órdenes» sin pararse a pensar.",
          "De ahí nació su idea más célebre: la banalidad del mal. El mal más terrible, decía, no siempre lo cometen seres perversos, sino personas que dejan de pensar y de cuestionar lo que hacen.",
          "Por eso defendió que pensar por uno mismo y participar en la vida pública son formas de proteger la libertad.",
        ],
        "Dato curioso: la expresión «la banalidad del mal» generó un enorme debate y todavía hoy se utiliza para analizar cómo se cometen las grandes injusticias."),
      hito("mente-humana", "ortega-y-gasset", "José Ortega y Gasset", "1883-1955",
        "¿Somos realmente dueños de nuestra vida?",
        [
          "Ortega y Gasset fue el filósofo español más influyente del siglo XX y logró acercar la filosofía al gran público con un lenguaje claro y elegante.",
          "Su idea más conocida se resume en una frase: «Yo soy yo y mi circunstancia».",
          "Con ella quería decir que no podemos entendernos aislados del mundo que nos rodea: nuestra época, nuestra cultura y nuestra situación forman parte de lo que somos. Pero, a la vez, tenemos la tarea de decidir qué hacer con esa circunstancia.",
          "También reflexionó sobre la sociedad de masas y sobre los peligros de dejar de pensar por uno mismo.",
        ],
        "Dato curioso: Ortega defendía que «la vida es lo que hacemos y lo que nos pasa», y que vivir consiste en decidir constantemente qué vamos a ser en el instante siguiente."),
    ],
  },
  {
    key: "pensar-futuro",
    titulo: "Pensar el futuro",
    anio: "Siglo XX-XXI",
    intro:
      "La filosofía sigue viva porque las preguntas nunca terminan. El siglo XX y el comienzo del XXI trajeron un mundo nuevo: la ciencia se volvió capaz de transformar la vida y el planeta, la tecnología conectó a toda la humanidad y aparecieron problemas que ningún filósofo anterior había imaginado. ¿Cómo sabemos que una teoría científica es fiable? ¿Quién decide lo que está bien y lo que está mal en una sociedad diversa? ¿Puede una máquina llegar a pensar? Lejos de haber terminado su trabajo, la filosofía se enfrenta hoy a algunas de las preguntas más importantes de toda su historia.",
    subhitos: [
      hito("pensar-futuro", "karl-popper", "Karl Popper", "1902-1994",
        "¿Cómo distinguir la ciencia de lo que solo parece ciencia?",
        [
          "Popper se hizo una pregunta clave: ¿qué diferencia una teoría científica de una que no lo es?",
          "Su respuesta fue sorprendente. Una teoría es científica no porque pueda demostrarse, sino porque puede refutarse; es decir, porque existe algún experimento capaz de demostrar que es falsa.",
          "A esta idea la llamó falsabilidad. Según Popper, la ciencia avanza proponiendo teorías atrevidas e intentando después echarlas abajo. Las que resisten todos los intentos son las que provisionalmente aceptamos.",
          "Por eso, en ciencia, ninguna teoría es una verdad absoluta y definitiva: siempre está abierta a ser corregida.",
        ],
        "Dato curioso: Popper también fue un firme defensor de la democracia; en La sociedad abierta y sus enemigos criticó a los regímenes totalitarios y a las filosofías que creían poseer la verdad absoluta."),
      hito("pensar-futuro", "thomas-kuhn", "Thomas Kuhn", "1922-1996",
        "¿La ciencia avanza poco a poco o a saltos?",
        [
          "Hasta Kuhn, muchos pensaban que la ciencia progresaba acumulando descubrimientos de manera lenta y constante.",
          "Kuhn propuso algo distinto. Durante largos periodos, los científicos trabajan dentro de un mismo marco de ideas al que llamó paradigma.",
          "Pero cuando ese marco acumula demasiados problemas que no puede resolver, se produce una revolución científica: el viejo paradigma se derrumba y otro nuevo ocupa su lugar, como ocurrió cuando la física de Newton dejó paso a la de Einstein.",
          "Con Kuhn entendimos que la ciencia también tiene su propia historia, con crisis, rupturas y grandes cambios de mentalidad.",
        ],
        "Dato curioso: gracias a Kuhn, la palabra «paradigma» pasó de la filosofía a usarse hoy en casi todos los ámbitos para hablar de un gran cambio de perspectiva."),
      hito("pensar-futuro", "michel-foucault", "Michel Foucault", "1926-1984",
        "¿Quién decide lo que es normal?",
        [
          "Foucault estudió algo que casi nadie se había planteado: cómo el poder no solo prohíbe, sino que también moldea nuestra forma de pensar y de vivir.",
          "Investigó la historia de las prisiones, los hospitales, la locura y la sexualidad, y mostró que muchas ideas que damos por naturales —lo normal y lo anormal, lo sano y lo enfermo— cambian con cada época.",
          "Según él, en cada momento histórico existe una forma de saber que decide qué se considera verdadero y qué queda excluido.",
          "Su obra invita a mirar con ojos críticos las instituciones y las normas que aceptamos sin cuestionar.",
        ],
        "Dato curioso: Foucault es uno de los autores más citados de todas las ciencias sociales en el mundo entero."),
      hito("pensar-futuro", "john-rawls", "John Rawls", "1921-2002",
        "¿Cómo sería una sociedad realmente justa?",
        [
          "Rawls devolvió la filosofía política al centro del debate con una pregunta muy antigua: ¿qué es una sociedad justa?",
          "Para responderla propuso un experimento mental. Imagina que tuvieras que diseñar las reglas de la sociedad sin saber qué lugar ocuparás en ella: si serás rico o pobre, sano o enfermo, hombre o mujer.",
          "A esa situación la llamó el velo de la ignorancia. Si no sabemos qué nos va a tocar, tenderemos a crear reglas justas para todos, y no solo para unos pocos privilegiados.",
          "Con esta idea defendió que las desigualdades solo son aceptables si benefician también a los más desfavorecidos.",
        ],
        "Dato curioso: su libro Teoría de la justicia, publicado en 1971, reavivó el interés por la filosofía política en todo el mundo."),
      hito("pensar-futuro", "peter-singer", "Peter Singer", "n. 1946",
        "¿Debería importarnos el sufrimiento de todos los seres vivos?",
        [
          "Singer es uno de los filósofos vivos más influyentes y también más polémicos.",
          "Defiende que, a la hora de decidir qué está bien, lo que importa es la capacidad de sufrir. Y como los animales también sufren, sostiene que tenerlos en cuenta es una cuestión de justicia, no de sentimentalismo.",
          "Sus ideas impulsaron el movimiento por los derechos de los animales y el debate sobre el trato que damos a otras especies.",
          "También sostiene que, si podemos evitar un gran sufrimiento a un coste pequeño para nosotros, tenemos el deber moral de hacerlo, lo que le ha llevado a defender la ayuda a las personas más pobres del planeta.",
        ],
        "Dato curioso: Singer popularizó el «altruismo eficaz», un movimiento que busca ayudar al mayor número posible de personas utilizando la razón y las pruebas."),
      hito("pensar-futuro", "byung-chul-han", "Byung-Chul Han", "n. 1959",
        "¿Nos está agotando la sociedad en la que vivimos?",
        [
          "Nacido en Corea del Sur y afincado en Alemania, Byung-Chul Han es uno de los filósofos más leídos del siglo XXI.",
          "Sostiene que hemos pasado de una sociedad que nos prohibía cosas a otra que nos exige rendir al máximo constantemente.",
          "Ya nadie nos obliga desde fuera: nos explotamos a nosotros mismos creyendo que somos libres, siempre disponibles, siempre productivos. A eso lo llama la «sociedad del cansancio».",
          "Su filosofía ayuda a entender fenómenos tan actuales como el estrés, la hiperconexión, las redes sociales o el agotamiento emocional.",
        ],
        "Dato curioso: Han reivindica el valor del aburrimiento, la contemplación y el descanso como formas de resistencia frente a un mundo que nunca se detiene."),
      hito("pensar-futuro", "etica-ia", "La ética de la Inteligencia Artificial", "Siglo XXI",
        "¿Quién es responsable de lo que decide una máquina?",
        [
          "Por primera vez en la historia, hemos creado máquinas capaces de aprender, decidir y generar textos, imágenes o diagnósticos.",
          "Esto plantea preguntas filosóficas totalmente nuevas. Si un coche autónomo tiene un accidente, ¿de quién es la culpa? Si un algoritmo decide quién recibe un préstamo o un trabajo, ¿cómo evitamos que sea injusto?",
          "La filosofía ayuda a pensar estos problemas: qué valores queremos que respeten las máquinas, cómo proteger la privacidad y quién debe responsabilizarse de sus errores.",
          "Son cuestiones que ya no pertenecen al futuro, sino al presente.",
        ],
        "Dato curioso: muchas empresas tecnológicas cuentan hoy con filósofos y expertos en ética para decidir cómo deben comportarse sus sistemas de inteligencia artificial."),
      hito("pensar-futuro", "transhumanismo", "El transhumanismo", "Siglo XXI",
        "¿Deberíamos mejorar al ser humano con la tecnología?",
        [
          "El transhumanismo es una corriente que defiende utilizar la ciencia y la tecnología para superar los límites del cuerpo y la mente humanos.",
          "Sus partidarios imaginan un futuro en el que podríamos curar todas las enfermedades, aumentar nuestra inteligencia o incluso alargar enormemente la vida.",
          "Pero estas posibilidades despiertan grandes dudas. ¿Seguiríamos siendo humanos? ¿Estarían esas mejoras al alcance de todos o solo de unos pocos? ¿Quién decide qué significa «mejorar»?",
          "La filosofía se enfrenta así a una de sus preguntas más antiguas —qué es el ser humano— en un contexto completamente nuevo.",
        ],
        "Dato curioso: algunos científicos creen que las primeras personas que vivirán más de 120 años ya han nacido; otros piensan que es solo una ilusión tecnológica."),
      hito("pensar-futuro", "puede-pensar-maquina", "¿Puede pensar una máquina?", "Siglo XX-XXI",
        "¿Podría una máquina llegar a tener conciencia?",
        [
          "Esta pregunta acompaña a la informática desde su nacimiento. El matemático Alan Turing propuso una prueba: si al conversar con una máquina no pudiéramos distinguirla de un ser humano, tendríamos que admitir que «piensa».",
          "Pero muchos filósofos no están de acuerdo. Una cosa es imitar el pensamiento y otra muy distinta comprender de verdad o tener conciencia.",
          "¿Siente algo una máquina cuando responde, o solo repite patrones sin entender nada? Todavía no tenemos una respuesta.",
          "Es, quizá, una de las preguntas más fascinantes que la filosofía y la ciencia comparten hoy.",
        ],
        "Dato curioso: el famoso «test de Turing» fue propuesto en 1950, mucho antes de que existieran los ordenadores actuales."),
      hito("pensar-futuro", "busqueda-no-termina", "La búsqueda no termina", "",
        "",
        [
          "Hemos recorrido más de dos mil quinientos años de preguntas.",
          "Desde los primeros pensadores que miraron la naturaleza buscando explicaciones, hasta quienes hoy se preguntan por la inteligencia artificial, todos han compartido un mismo impulso: comprender el mundo y comprendernos a nosotros mismos.",
          "La filosofía nunca ha pretendido dar respuestas definitivas. Su verdadera fuerza está en enseñarnos a pensar mejor, a dudar, a preguntar y a no conformarnos con lo primero que nos dicen.",
          "Y mientras existan seres humanos capaces de asombrarse y de preguntar «¿por qué?», la búsqueda de la sabiduría seguirá viva.",
        ],
        "Dato curioso: la palabra «filosofía» sigue significando hoy lo mismo que hace 2.500 años: amor a la sabiduría. Quizá por eso nunca pasará de moda."),
    ],
  },
];
