import { useMemo } from "react";
import { useIdioma } from "../../i18n";
import { SISTEMAS, FRASE_ORGANISMO, type Sistema } from "./SistemasFisiologia";

/**
 * Los 12 sistemas del cuerpo, en INGLÉS.
 *
 * Aquí va SOLO el texto, emparejado por el `key` del sistema. El orden, el
 * color, la foto y los propios `key` viven únicamente en el fichero español:
 * si se duplicaran, bastaría cambiar uno en un idioma y no en el otro para que
 * la rejilla o el progreso guardado dejaran de cuadrar.
 *
 * Lo que falte en este mapa se muestra en español, sistema por sistema
 * (ver `useSistemas`).
 */
export type SistemaTexto = Pick<Sistema, "label" | "claves" | "descripcion">;

export const sistemasFisiologiaEn: Record<string, SistemaTexto> = {
  nervioso: {
    label: "Nervous",
    claves: ["Connects the whole body", "Receives, processes and orders", "Lets us move and feel"],
    descripcion: "It reaches from the brain to the last inch of the body. Everything is connected through the spinal cord and the peripheral nerves. Every cascade of neurotransmitters starts with an electrical signal generated by neurons. It controls and coordinates every function of the body: it takes in information from the environment, processes it and sends out orders so we can move, think, feel and react.",
  },
  cardiovascular: {
    label: "Cardiovascular",
    claves: ["Heart and a network of vessels", "Carries oxygen and CO₂", "Delivers nutrients and hormones"],
    descripcion: "It is made up of the heart and a vast network of arteries, veins and capillaries. The hemoglobin in your red blood cells carries oxygen from the lungs to the cells and then picks up part of the carbon dioxide to take it back to the lungs, where it is breathed out. It also carries nutrients, hormones and other essential substances all over the body.",
  },
  respiratorio: {
    label: "Respiratory",
    claves: ["Takes in oxygen, releases CO₂", "Gives the cells energy", "Defends itself with mucus and cilia"],
    descripcion: "It lets you take oxygen from the air and breathe out carbon dioxide. It is essential for your cells to produce the energy your body needs. It also has defenses of its own — mucus, cilia and various immune cells — that help protect you from microorganisms and particles.",
  },
  digestivo: {
    label: "Digestive",
    claves: ["Turns food into nutrients", "Source of energy", "Home of the “second brain”"],
    descripcion: "It turns food into nutrients the body can absorb and use as a source of energy and for everything it does. It also holds the enteric nervous system, a vast network of neurons able to work fairly independently — which is why it is often called the “second brain”.",
  },
  urinario: {
    label: "Urinary",
    claves: ["Filters the blood", "Removes waste and water", "Keeps the inner balance"],
    descripcion: "It filters the blood to remove waste and excess water through urine, helping keep the body's inner balance. Put another way: urine is the result of filtering the blood and of the reabsorption and secretion the kidneys carry out.",
  },
  endocrino: {
    label: "Endocrine",
    claves: ["Makes hormones", "Regulates metabolism and sleep", "Coordinates stress and growth"],
    descripcion: "It produces the hormones that regulate functions such as growth, metabolism, sleep, stress and reproduction.",
  },
  linfatico: {
    label: "Lymphatic / Immune",
    claves: ["An immune network of vessels and nodes", "Carries fats from the gut", "Collects leftover fluid"],
    descripcion: "It is a large network of vessels and nodes carrying immune cells, always ready to act against infection. It is also closely connected to the gut, since it transports absorbed fats before they reach the blood. And it collects the excess fluid from the tissues and returns it to circulation to keep the body in balance.",
  },
  muscular: {
    label: "Muscular",
    claves: ["Makes movement possible", "Holds posture and gives warmth", "Works together with the bones"],
    descripcion: "It is a complex system, regulated very precisely by neurotransmitters such as acetylcholine and by calcium. It moves the body, holds your posture and generates heat. It works together with the bones for every movement you make.",
  },
  oseo: {
    label: "Skeletal",
    claves: ["Gives support and protection", "Rebuilds itself constantly", "Makes blood and stores calcium"],
    descripcion: "It gives the body support and protection. It is made of millions of cells in constant communication. Bone is broken down and rebuilt continuously through a process called bone remodeling, which is why strength training is essential to keep your bones strong and healthy. It also takes part in making blood cells and stores minerals such as calcium.",
  },
  tegumentario: {
    label: "Integumentary (skin)",
    claves: ["A barrier against the outside", "Regulates temperature and touch", "Tied to the emotions"],
    descripcion: "It forms the body's protective barrier against the outside world. It helps regulate body temperature and lets you feel sensations like touch, cold and heat. It is also closely tied to your emotions and to your stress response, since hormones such as cortisol shape how the skin works.",
  },
  reproductor: {
    label: "Reproductive",
    claves: ["Makes reproduction possible", "Produces the sex cells", "Makes the sex hormones"],
    descripcion: "It makes reproduction possible and produces the sex cells and the hormones tied to reproductive development and function.",
  },
  sensorial: {
    label: "Sensory",
    claves: ["Takes in the five senses", "Sends the signal to the brain", "Includes balance and position"],
    descripcion: "It picks up what is happening around you through the senses (sight, hearing, smell, taste and touch) and sends that information to the nervous system to be interpreted. It also includes proprioception, the sense that lets you know where your body is and how it is moving without looking, making balance and coordination possible.",
  },
};

/** La frase «de creador» de cada sistema en la página del organismo, en inglés. */
export const fraseOrganismoEn: Record<string, string> = {
  nervioso: "Let a network connect it all: through it will travel every thought and every order.",
  cardiovascular: "The heart will nourish every single cell.",
  respiratorio: "With every breath, Life will come in and what is spent will go out.",
  digestivo: "It will turn food into the energy that holds everything up.",
  urinario: "It will purify the blood and keep the balance of the water.",
  endocrino: "Invisible messengers will carry the right order to every corner.",
  linfatico: "A silent army will watch over every cell.",
  muscular: "I will give it the strength to move through the world.",
  oseo: "On these pillars it will stand.",
  tegumentario: "A living border will separate it from the world and, at the same time, hold it.",
  reproductor: "In it I will keep the promise of the Life to come.",
  sensorial: "And so it will be able to see, hear and feel all of creation.",
};

/**
 * Los 12 sistemas en el idioma activo. En español devuelve el array tal cual;
 * en inglés funde el texto sobre él, sistema por sistema, dejando intactos
 * `key`, `color`, `foto`, el cómic y el test.
 */
export const useSistemas = (): Sistema[] => {
  const { idioma } = useIdioma();
  return useMemo(
    () =>
      idioma === "es"
        ? SISTEMAS
        : SISTEMAS.map((s) => ({ ...s, ...(sistemasFisiologiaEn[s.key] ?? {}) })),
    [idioma],
  );
};

/** La frase del sistema `key` en la página del organismo, en el idioma activo. */
export const useFraseOrganismo = (): Record<string, string> => {
  const { idioma } = useIdioma();
  return idioma === "es" ? FRASE_ORGANISMO : { ...FRASE_ORGANISMO, ...fraseOrganismoEn };
};
