export type Alimento = {
  id: number;
  nombre: string;
  nombreCientifico: string;
  tipo: "fruta" | "verdura";
  foto: string;
  uso: string;
  beneficios: string[];
  formaDeUso: string;
  datosCuriosos?: string[];
  precauciones?: string[];
};

export const alimentos: Alimento[] = [
  {
    id: 1,
    nombre: "Espinaca",
    nombreCientifico: "Spinacia oleracea",
    tipo: "verdura",
    foto: "/img/alimentos/espinaca.jpg",
    uso: "Verdura de hoja verde con una densidad nutricional excepcional, rica en hierro, calcio y vitaminas del grupo B.",
    beneficios: [
      "Alta en hierro biodisponible",
      "Rica en calcio y magnesio",
      "Fuente de folatos esenciales para el sistema nervioso",
      "Potente antioxidante por su contenido en luteína y zeaxantina",
      "Favorece la salud ocular",
      "Apoya la función muscular y cardiovascular",
      "Antiinflamatoria natural",
    ],
    formaDeUso: "Cruda en ensaladas, al vapor, salteada con ajo o en batidos verdes. Combinarla con vitamina C mejora la absorción del hierro.",
    datosCuriosos: [
      "Popeye popularizó la espinaca como fuente de hierro, aunque por un error tipográfico se sobreestimó su contenido.",
      "La espinaca cocinada concentra más sus nutrientes al reducir su volumen.",
    ],
  },
  {
    id: 2,
    nombre: "Arándanos",
    nombreCientifico: "Vaccinium corymbosum",
    tipo: "fruta",
    foto: "/img/alimentos/arandanos.jpg",
    uso: "Superfruta antioxidante por excelencia, protege el cerebro, el corazón y las células del envejecimiento prematuro.",
    beneficios: [
      "Altísima concentración de antioxidantes (antocianinas)",
      "Protege la salud neurológica y la memoria",
      "Reduce el riesgo cardiovascular",
      "Antiinflamatorio potente",
      "Favorece la salud urinaria",
      "Mejora la sensibilidad a la insulina",
      "Protege el ADN celular",
    ],
    formaDeUso: "Frescos solos, en batidos, yogures o avena. También en forma de extracto o liofilizado para mayor concentración.",
    datosCuriosos: [
      "Los arándanos silvestres tienen hasta el doble de antioxidantes que los cultivados.",
      "Su pigmento azul-morado es el indicador de su potencia antioxidante.",
    ],
  },
  {
    id: 3,
    nombre: "Brócoli",
    nombreCientifico: "Brassica oleracea var. italica",
    tipo: "verdura",
    foto: "/img/alimentos/brocoli.jpg",
    uso: "Una de las verduras más estudiadas por sus propiedades anticancerígenas y depurativas, gracias al sulforafano.",
    beneficios: [
      "Contiene sulforafano, compuesto con efecto anticancerígeno estudiado",
      "Estimula las enzimas de detoxificación hepática",
      "Rico en vitamina C, K y folatos",
      "Apoya la salud ósea",
      "Antiinflamatorio y antioxidante",
      "Favorece el equilibrio hormonal",
      "Protege la mucosa gástrica",
    ],
    formaDeUso: "Ligeramente al vapor (3-5 min) para preservar el sulforafano. También crudo en ensaladas o en sopas.",
    datosCuriosos: [
      "Masticar el brócoli crudo activa la enzima mirosinasa, necesaria para producir sulforafano.",
      "El brócoli tiene más vitamina C que la naranja por cada 100 g.",
    ],
  },
  {
    id: 4,
    nombre: "Aguacate",
    nombreCientifico: "Persea americana",
    tipo: "fruta",
    foto: "/img/alimentos/aguacate.jpg",
    uso: "Fruta rica en grasas saludables monoinsaturadas, potasio y vitamina E que nutre la piel, el cerebro y el corazón.",
    beneficios: [
      "Fuente de ácido oleico (grasa monoinsaturada antiinflamatoria)",
      "Alto contenido en potasio, más que el plátano",
      "Rica en vitamina E y K",
      "Mejora la absorción de carotenoides de otras verduras",
      "Apoya la salud cardiovascular",
      "Nutre la piel desde dentro",
      "Saciante y estabilizador del azúcar en sangre",
    ],
    formaDeUso: "Solo con sal y limón, en guacamole, en tostadas o incorporado en batidos para cremosidad. El limón previene su oxidación.",
    datosCuriosos: [
      "El aguacate es técnicamente una fruta con semilla grande, llamada baya.",
      "Combinar aguacate con tomate multiplica la absorción de licopeno del tomate.",
    ],
  },
  {
    id: 5,
    nombre: "Zanahoria",
    nombreCientifico: "Daucus carota",
    tipo: "verdura",
    foto: "/img/alimentos/zanahoria.jpg",
    uso: "Verdura rica en betacaroteno, precursor de la vitamina A, esencial para la visión, la piel y el sistema inmunitario.",
    beneficios: [
      "Altísimo contenido en betacaroteno (provitamina A)",
      "Protege la salud ocular y previene la degeneración macular",
      "Fortalece el sistema inmunitario",
      "Mejora la salud de la piel y las mucosas",
      "Antiinflamatoria y antioxidante",
      "Favorece la microbiota intestinal",
      "Apoya la salud hepática",
    ],
    formaDeUso: "Cruda como snack, cocida en sopas o al horno. Con un poco de grasa saludable (aceite de oliva) aumenta la absorción del betacaroteno.",
    datosCuriosos: [
      "La zanahoria cocinada tiene más betacaroteno biodisponible que cruda.",
      "Originalmente las zanahorias eran moradas o blancas; el naranja fue desarrollado en Países Bajos.",
    ],
  },
  {
    id: 6,
    nombre: "Limón",
    nombreCientifico: "Citrus limon",
    tipo: "fruta",
    foto: "/img/alimentos/limon.jpg",
    uso: "Fruta alcalinizante y depurativa que estimula el hígado, favorece la digestión y protege el sistema inmunitario.",
    beneficios: [
      "Muy rico en vitamina C",
      "Alcaliniza el organismo a pesar de su acidez",
      "Estimula la producción de bilis y la función hepática",
      "Favorece la absorción del hierro no hemo",
      "Antibacteriano y antivírico natural",
      "Apoya la salud de la piel y el colágeno",
      "Digestivo y carminativo",
    ],
    formaDeUso: "Agua tibia con limón en ayunas, zumo fresco en ensaladas o como condimento. Evitar el calentamiento excesivo para preservar la vitamina C.",
    datosCuriosos: [
      "El agua con limón en ayunas activa el sistema digestivo y el hígado suavemente.",
      "La cáscara de limón contiene el doble de vitamina C que el zumo.",
    ],
  },
  {
    id: 7,
    nombre: "Remolacha",
    nombreCientifico: "Beta vulgaris",
    tipo: "verdura",
    foto: "/img/alimentos/remolacha.jpg",
    uso: "Verdura rica en nitratos naturales que mejoran el rendimiento físico, la circulación y la oxigenación celular.",
    beneficios: [
      "Mejora la oxigenación y el rendimiento deportivo",
      "Vasodilatadora natural gracias a sus nitratos",
      "Rica en folatos y betaína",
      "Protege el hígado y favorece su detoxificación",
      "Antiinflamatoria y antioxidante",
      "Apoya la salud cardiovascular",
      "Mejora la función cognitiva por mayor flujo sanguíneo cerebral",
    ],
    formaDeUso: "Cruda rallada en ensaladas, en zumo fresco o asada al horno. El zumo de remolacha antes del ejercicio mejora el rendimiento.",
    datosCuriosos: [
      "Los nitratos de la remolacha se convierten en óxido nítrico, un potente vasodilatador.",
      "La orina y las heces pueden teñirse de rosa-rojo tras consumirla; es completamente normal.",
    ],
  },
  {
    id: 8,
    nombre: "Papaya",
    nombreCientifico: "Carica papaya",
    tipo: "fruta",
    foto: "/img/alimentos/papaya.jpg",
    uso: "Fruta tropical con la enzima papaína, potente digestiva que descompone proteínas y calma la inflamación intestinal.",
    beneficios: [
      "Contiene papaína, enzima digestiva proteolítica",
      "Alivia la pesadez y mejora la digestión de proteínas",
      "Rica en vitamina C y betacaroteno",
      "Antiinflamatoria intestinal",
      "Favorece el tránsito intestinal",
      "Apoya la salud de la piel",
      "Refuerza el sistema inmunitario",
    ],
    formaDeUso: "Fresca sola o con unas gotas de limón. También en batidos digestivos o como postre después de comidas con proteína animal.",
    datosCuriosos: [
      "La papaína se usa en la industria alimentaria para ablandar la carne.",
      "Las semillas de papaya son comestibles y tienen propiedades antiparasitarias.",
    ],
  },
  {
    id: 9,
    nombre: "Ajo",
    nombreCientifico: "Allium sativum",
    tipo: "verdura",
    foto: "/img/alimentos/ajo.jpg",
    uso: "Uno de los alimentos medicinales más poderosos, con acción antibacteriana, antivírica, cardiovascular e inmunoestimulante.",
    beneficios: [
      "Contiene alicina, compuesto antibacteriano y antivírico",
      "Reduce el colesterol LDL y los triglicéridos",
      "Anticoagulante natural, apoya la circulación",
      "Potente inmunoestimulante",
      "Antifúngico eficaz",
      "Antiinflamatorio sistémico",
      "Apoya la salud cardiovascular y reduce la presión arterial",
    ],
    formaDeUso: "Machacado o picado en crudo y dejado reposar 10 minutos antes de consumir activa la alicina. En cocina, sopas y aliños.",
    datosCuriosos: [
      "Dejar reposar el ajo tras cortarlo o machacarlo activa la enzima que produce alicina.",
      "El ajo negro fermentado duplica su contenido en antioxidantes.",
    ],
    precauciones: [
      "En exceso puede irritar el estómago en personas con gastritis.",
      "Puede potenciar anticoagulantes; consultar con el médico si se toma medicación.",
    ],
  },
  {
    id: 10,
    nombre: "Granada",
    nombreCientifico: "Punica granatum",
    tipo: "fruta",
    foto: "/img/alimentos/granada.jpg",
    uso: "Fruta con uno de los perfiles antioxidantes más potentes conocidos, especialmente cardiprotectora y antiinflamatoria.",
    beneficios: [
      "Altísimo contenido en punicalaginas y ácido elágico (antioxidantes únicos)",
      "Cardioprotectora y reduce la presión arterial",
      "Antiinflamatoria de alto espectro",
      "Apoya la salud articular",
      "Antimicrobiana frente a bacterias orales",
      "Favorece la memoria y la función cognitiva",
      "Mejora el perfil lipídico",
    ],
    formaDeUso: "Granos frescos solos, en ensaladas o en zumo natural. El zumo de granada concentra sus antioxidantes.",
    datosCuriosos: [
      "La granada tiene hasta tres veces más antioxidantes que el vino tinto o el té verde.",
      "Era símbolo de fertilidad y abundancia en antiguas civilizaciones mediterráneas.",
    ],
  },
  {
    id: 11,
    nombre: "Acelga",
    nombreCientifico: "Beta vulgaris var. cicla",
    tipo: "verdura",
    foto: "/img/alimentos/acelga.jpg",
    uso: "Verdura de hoja rica en magnesio, potasio y vitaminas K y C, esencial para huesos, músculos y sistema nervioso.",
    beneficios: [
      "Excelente fuente de magnesio (mineral más deficitario en la dieta moderna)",
      "Rica en vitamina K para la salud ósea",
      "Potasio para el equilibrio electrolítico y la presión arterial",
      "Vitamina C y betacaroteno antioxidantes",
      "Apoya el sistema nervioso y reduce la fatiga",
      "Favorece la regulación del azúcar en sangre",
      "Depurativa y diurética suave",
    ],
    formaDeUso: "Al vapor con aceite de oliva y ajo, salteada o en sopas. Las pencas también son comestibles y muy ricas en fibra.",
    datosCuriosos: [
      "La acelga y la remolacha son la misma especie vegetal, cultivadas de forma diferente.",
      "Su contenido en magnesio la convierte en un alimento clave para el descanso y la recuperación muscular.",
    ],
  },
  {
    id: 12,
    nombre: "Kiwi",
    nombreCientifico: "Actinidia deliciosa",
    tipo: "fruta",
    foto: "/img/alimentos/kiwi.jpg",
    uso: "Fruta con más vitamina C que la naranja, enzimas digestivas y serotonina, ideal para el tránsito y el descanso.",
    beneficios: [
      "Doble de vitamina C que la naranja por cada 100 g",
      "Contiene actinidina, enzima que mejora la digestión de proteínas",
      "Favorece el tránsito intestinal por su fibra soluble",
      "Rico en vitamina K y folatos",
      "Contiene serotonina natural, mejora el sueño",
      "Anticoagulante suave y cardioprotector",
      "Refuerza el sistema inmunitario",
    ],
    formaDeUso: "Fresco solo, en ensaladas de fruta o batidos. Dos kiwis antes de dormir se han asociado con mejor calidad del sueño en estudios.",
    datosCuriosos: [
      "El kiwi es originario de China, donde se llamaba 'grosella china'.",
      "Comer kiwi con su piel (bien lavada) aporta aún más fibra y antioxidantes.",
    ],
  },
];
