export const letranp1 = "Se dice que el vínculo entre la madre y un hijo es irrompible, pero no es verdad, solo que es muy dificil, porque es nuestra madre la que literalmente forma nuestro cuerpo y por extensión, a las bases de nuestro cerebro.  El niño no solo es formado con la mitad del ADN celular de la madre, sino que también hereda todo su ADN mitocondrial.  Está demostrado que el tono de voz de la madre, los sabores que toma, los olores que huele, los tratos que recibe… el niño cuando nace, los reconoce y los prefiere a otras opciones, lo que nos desvela que funciones cerebrales están ocurriendo, y que el niño está consolidando aquello a lo que la madre se expone.  Recordemos que la madre durante el embarazo recuerda con más presencia su infancia, y por extensión todos sus traumas enterrados. Esto es de brutal importancia, no ya por el hecho de que el niño guardará como familiar los malos hábitos de la madre, sino por el hecho de que todo lo que recuerde, vea, viva, piense y sienta la madre, formará el cerebro del niño, que es casi una copia del sistema nervioso de la madre y por extensión, de su tolerancia a la frustración y de sus traumas no sanados.  En conclusión, todo lo que la madre no se haya trabajado, forman parte del niño.";
 
 export const letranp2 = "La triste realidad es que los seres humanos tendemos a sentirnos insuficientes, e intentamos compensar de alguna forma.  Esto es por influencia inconsciente de las madres.  Pongámonos en contexto. Los padres tienen hijos como narcisificación personal. Cuando el bebé se está gestando, los padres están como locos conscientes o inconscientemente pensando en cómo va a ser ese bebé, qué van a hacer con él, lo bien que se llevarán, que por fin serán felices... es decir, ponen todas las esperanzas de su propia felicidad y estabilidad, fuera de ellos.  Esto deja una tremendísima carga al chiquitín, que obviamente es incapaz de remediar la infelicidad de sus padres.  Cuando este nace, la madre espera que el niño la salve de la falta de amor que tiene hacia sí misma, de su infelicidad y de su propia insuficiencia, pero como no ha sido así, le transmite al bebé que \"no es suficiente, que es un inútil\"  Esta es la razón por la que los hijos suelen sentirse responsables de arreglar la infelicidad de sus padres, es la razón por la que no se permiten ser más felices de lo que ellos fueron, es la razón por la que nos sentimos insuficientes.  Pero que este sea el origen, no significa que sea responsabilidad de tus padres tu propio vacío interior, ahora es momento de que te hagas responsable de tu propia Viday recuerdes que eres suficiente y que siempre lo has sido.";
 
 export const letranp3 = "Los primeros años de un chiquitín están profundamente marcados por si sus padres son capaces de reconocer, diferenciar y legitimar sus necesidades. Parece sencillo, pero no lo es: en estos años el cerebro del niño se está formando, creando conexiones neuronales que lo acompañarán toda la vida.  Estas primeras interacciones dan lugar a vínculos seguros o, en la gran mayoría de los casos, inseguros y evitativos.  Cuando los padres no diferencian o incluso niegan lo que el niño necesita, este aprende que sus necesidades no son legítimas, o peor aún, que no puede confiar en lo que siente.  Imagina algo tristemente común, un ejemplo como cualquier otro… una mamá dando de comer a su hijo con la televisión encendida. El niño, al estar distraído y al tener a su mamá contenta, ignorará sus señales de saciedad, aprendiendo a no escuchar a su propio cuerpo y a que “los niños buenos se acaban todo lo que hay en el plato”. Este ejemplo de falta de escucha propia, no solo tiene que ver con patrones físicos, sino con necesidades más profundas que son calladas por miedo a incomodar, estos patrones se trasladan a la adultez, creando adultos inseguros, atrapados en comportamientos autodestructivos, que se critican, se desprecian y se sienten insuficientes.  No pueden romper estos ciclos porque no se creen capacitados para ello, no validan sus necesidades y, para no “molestar”, aprenden a reprimir lo que sienten. Desde la neurobiología, se sabe que: la falta de respuesta consistente afecta cómo se desarrolla el sistema límbico y los circuitos prefrontales, haciendo que regular emociones y manejar la frustración sea más difícil.  Pero no todo está perdido. Aunque estas huellas son profundas, el cerebro se puede moldear durante toda la vida: con autocompasión, terapia y consciencia, se pueden reconstruir patrones, validar necesidades y aprender a confiar en uno mismo. La clave está en legitimar lo que no se validó en el pasado, porque todo lo que sentimos, pensamos y hacemos hoy puede reescribir nuestro mapa neuronal.  El niño que fuimos sigue vivo dentro, y podemos aprender a sostenerlo, escucharlo y amarlo.";
 
 export const letranp4 = "Los niños no pueden pensar mal de sus figuras de apego, todo lo contrario, necesitan glorificarlas porque las necesitan para sobrevivir.  Por lo que, cuando una figura de apego se enfada o se disgusta o desvalora al niño, este piensa “no es que mis padres no puedan valorarme porque están angustiados con esta situación, es que yo no soy valorable, yo no soy querible”… y un niño maltratado no deja de querer a sus padres pero sí a sí mismo.  De esta forma mientras pasan los días, más nos abandonamos y más nos apegamos a aquellos que no son capaces de amarnos. Porque es lo que hemos tenido, es a lo que estamos acostumbrados.";
 
 export const letranp5 = "En la adolescencia, el pequeñín empieza a individualizarse, es aquí en este periodo de rebeldía cuando se manifiestan las conexiones neuronales aprendidas durante estos años de vida.  Si el niño ha “sido conectado” para la decadencia, se vivirá a sí mismo como alguien insuficiente, como un fracaso. Si está conectado para la desconexión con su cuerpo se vivirá también como un ser con tendencias autodestructivas compensando sus sentimientos de insuficiencia a través de sus conductas alimenticias…  No es que el niño “antes era bueno y de repente se convirtió en eso”, es que los padres mismos han programado al niño a través de su propio sufrimiento e insuficiencia.  por eso cuando al niño le llega la hora de “encontrar su sitio”, está pérdido, lo único que tiene son sus propias necesidades insatisfechas y encima, como nadie más necesitaba lo que él, se etiqueta a sí mismo como exagerado, como loco, como “yo no debería de estar sintiendo esto” y compensando con tendencias autodestructivas.  Es por esto, que los supuestos trastornos de la adolescencia, son SÍNTOMAS de un problema mucho más profundo y enraizado en el ser.";
 
 export const letranp6 = "Todos tenemos al menos una falta básica debido a que nuestros padres no la han sabido legitimar ni corresponder. Esto se manifiesta en la búsqueda de pareja. Literalmente, la búsqueda de pareja es buscar a una persona que creemos que nos cubrirá aquello que las figuras de apego no han podido.  La finalidad de la pareja - a parte del viaje juntos, de las experiencias y el cariño- es ver qué es lo que estamos intentando que esa persona cubra, porque si lo estamos intentando, es porque nosotros mismos no podemos cubrirla y esto es lo que destroza a las parejas: la incesante insistencia con que la otra persona satisfaga nuestra seguridad emocional, alguien que nos diga que merecemos la pena, y encima, tienen que adivinar cómo y cuándo lo necesitamos.  Es por esto que las rupturas duelen tanto, no porque la otra persona sea un desgraciado o te haya hecho una desgracia, sino porque le estamos pidiendo algo que no es capaz de darnos, algo que no sabemos darnos, algo que necesitamos y nunca hemos tenido pero a la vez le culpamos por no poder dárnoslo.  Y todo esto teniendo en cuenta que el otro hace lo mismo con nosotros, la otra persona busca que le demos lo que necesita y tampoco podemos.";
 
 export const letranp7 = "Atraemos y nos atraen aquellos con los que compartimos necesidades no legitimadas. Esto es que cuando alguien nos “cae bien” es que hay una resonancia del cómo nos tratamos a nosotros mismos.  Es por esto que las personas inteligentes se juntan con las inteligentes, y personas quejicas con los quejicas.  Si te mejoras a ti mismo, es inevitable que las personas que antes estaban contigo que ya no corresponden a esa nueva vibración tuya desaparezcan y aparezcan nuevas, más acorde con la manifestación que estás haciendo.  Tenemos que ser conscientes y ver sin juzgar aquello que proyectamos en el otro, porque lo que decimos y vemos habla más de nosotros que de aquel al que estamos calificando.  Lo que nos molesta del otro es lo que nos molesta de nosotros mismos.  Es por eso que ocurre esa “resonancia”, para que puedas ver amplificado dónde no te estás aceptando. Con aceptarse no quiero decir no trabajarse, sino darle un espacio a todo lo que nos forma para integrar la función que cumple en nosotros, en vez de ser la marioneta de esa emoción o herida no sanada.";
 
 export const letranp8 = "La gran mayoría de las personas llegan a la adultez sin darse cuenta de todo el daño que se han estado haciendo, pensando que todos sus problemas son causados por un otro, cuando en verdad se debe a repetir las conductas programadas para el sufrimiento que heredaron de sus padres y solidificaron en su infancia.  Durante la adultez, la gran mayoría se vive a sí mismos como seres cansados, incapaces de mejorar, que ya “no son lo que eran”, sin valorar toda la experiencia y sabiduría que tienen, y al no saberla valorar, se va desintegrando a través de sus quejas a medida que pasan los días en trabajos que detestan, no porque lo aborrezcan, sino porque se aborrecen a sí mismos.  Viven la Vidacomo algo repetitivo, que ya no puede ser placentero debido a que “hacerse viejo es una mierda”, despreciando así todo lo que ha hecho y hace su cuerpo, sin entender que son sus propias acciones y pensamientos lo que lo condenan a esa decadencia día tras día.  Se puede salir de esto, de verdad que sí, pero para ello, tienes que entrar en ti, ver qué patrones se repiten cada día. Únicamente uno logra esa objetividad y conseguir salir de sus pensamientos a través de la meditación.";
 
 export const letranp9 = "El alzheimer se debe a que la persona no es capaz de sostener todo el daño que se ha hecho, no quiere ver la Vidaque ha vivido, y por ello, deciden olvidarla.  Imagínate la angustia de esta persona para preferir literalmente destrozarse las conexiones entre las neuronas, esto es la materia blanca del cerebro, la encargada de las conexiones neuronales.  Se ha demostrado que durante esta enfermedad, las neuronas quedan intactas, lo que se degrada son las conexiones entre ellas.  Da igual la edad que tengas ahora mismo, si eres hombre o mujer, si estás escuchando esto, aún tienes tiempo para sanarte, aún tienes tiempo de mirarte y sentirte, no te abandones al paso del tiempo, el tiempo no sana, los traumas viven en tu cuerpo, porque a veces el pasado ni siquiera ha pasado.";
 
 export const letranp10 = "La espiritualidad no es para olvidarnos del mundo de la materia, es para entender que toda materia es una herramienta que cumple con una función más elevada que ella misma, que sirve para que nos demos cuenta de qué es lo que no nos permitimos, qué puerta nos hemos cerrado, qué nos estamos robando.  Aquello que le damos a otro que no nos damos a nosotros mismos, no es generosidad, es falta de merecimiento.  Todas las interacciones, todos los daños que nos han dado como herencia nuestros padres, todas las rupturas de corazón… solo tiene un objetivo final, y es que tú seas capaz de ver dónde estás y desde ahí, puedas conectar con tu dolor crónico normalizado, y como con una cebolla, puedas empezar a quitar capas de ese dolor para así sostenerte y acogerte por entero.";
 
 export const letranp11 = "Desde el principio quiero dejar claro que no existen esquizofrénicos, existen personas que para sobrevivir a un mundo que percibieron como hostil, tuvieron que desarrollar una estrategia que les permitió no sucumbir a la desesperación.  No están rotos, han hecho lo que han podido.  El entorno y las personas con las que estaban no se han dado cuenta del sufrimiento, no han querido verlo, hasta que fue inevitable e innegable.  Cuando el entorno actúa, lo hacen poniendo etiquetas, les llaman esquizofrénicos. Niegan que son personas, les hacen creer que su dolor no es legítimo, les dicen que están locos y que ahora su único remedio son pastillas.";
 
 export const letranp12 = "Estas personas vienen de ambientes hostiles, en los que se han visto obligados a estar solos o, por lo menos, emocionalmente aislados.  Las familias ignoran el sufrimiento hasta que ya no puede ser evitado.  Una esquizofrenia no se desarrolla de la noche a la mañana, son años de sufrimiento silenciado.  Es más, lo más probable es que las madres se hayan dañado a sí mismas durante el embarazo, dejando al cerebro del niño más vulnerable y con menos resiliencia.  En cualquier caso, el entorno de estas personas ha estado marcado por un abandono insostenible y la persona, para tolerar esta circunstancia, ha tenido que crear un refugio en el cual no estuviesen solos.";
 
 export const letranp13 = "La esquizofrenia no se hereda tal cual. No existe un único gen, una enzima o una proteína que por sí sola la cause.  Lo que sí se hereda es una genética predispuesta al sufrimiento.  Si los padres no han sanado sus heridas, transmiten un ADN teñido por dolor, vacío y humillación. Cuando una persona se cría en ese ambiente de sufrimiento, sin herramientas ni apoyo, la mente puede buscar cualquier refugio.  La psicosis no aparece como un sinsentido, sino como una forma extrema de escapar de una realidad insoportable. La locura es una respuesta racional a un mundo insano.";
 
 export const letranp14 = "El desarrollo de una esquizofrenia es el último recurso que estas personas tienen.  Antes han intentado huir de su realidad de varias formas: a través de las drogas, fumar, la bebida, los videojuegos…  Todo lo que se te ocurra, ya lo han intentado.  Las adicciones nunca son el problema, sino la solución.  El problema es lo que tienen en casa, el dolor que les acompaña a dónde van, el problema es la herida no sanada que les abruma y les impulsa a buscar una solución desesperada.";
 
 export const letranp15 = "Todos construimos nuestra realidad segundo a segundo.  El cerebro recibe una enorme cantidad de información, pero solo una parte ínfima llega a la conciencia.  La atención filtra y descarta casi todo.  Y lo poco que consigue atravesar ese filtro todavía tiene que imponerse al ruido mental constante para que podamos, simplemente, saber que existe.  Por lo que todos creamos nuestra realidad como buenamente podemos.  Si a esto se le suma que la persona se ha visto obligada a la isolación, es absolutamente normal que haya tenido que inventar una realidad para poder sostener todo ese dolor.";
 
 export const letranp16 = "En cualquier estado en el que estemos, tanto contentos, tristes o enfadados, hay cambios en nuestro cuerpo.  Es decir, hay cambios neurológicos y hormonales, por lo que si haces una adaptación a un medio doloroso, es completamente normal que haya cambios en el cerebro.  Por lo que el desequilibrio neuronal no es la causa de la esquizofrenia.  Primero te pones contento, luego la serotonina inunda tu cuerpo, primero te enamoras, y luego la oxitocina llega a todas tus células.  Primero aparecen las voces; después, se producen cambios en la dopamina.";
 
 export const letranp17 = "Todos tenemos voces en nuestra cabeza, es inevitable.  Lo que nos diferencia de que nos pongan o no una etiqueta es si somos capaces de controlar esas voces.  Tenemos que entender que la esquizofrenia es una respuesta adaptativa a un entorno intolerable.  Entonces, ¿cómo estas voces les ayudaron a crear una realidad tolerable?  ¿Para qué necesitan esas voces? ¿Al servicio de qué están? ¿De qué les protegen? ¿De qué les defienden? ¿Cómo les acogen? ¿Qué les prometen?";
 
 export const letranp18 = "La relación que las personas tienen con sus voces es importante.  Lo que dicen las voces es importante, cuándo, cómo, dónde también lo es.  Las personas deben posicionarse como el observador, y cuando las voces digan algo, deben mirar la situación que tienen entre manos, qué sienten y qué les invita a ignorar esa voz.  La esquizofrenia es una respuesta adaptativa que se forma durante años, por lo que no se trata de eliminar esas voces, sino de darles su lugar correspondiente, sin ser sus marionetas.  Se trata de escuchar, observar y racionalizar lo que dicen y desde ahí poder conocerse un poco más.  Esas voces representan las necesidades, deseos profundos y enfados negados que siguen pulsando desde dentro.  Las personas con esquizofrenia deben dejar de despreciarse, de pensar que están rotas, y deben convertir las voces en su herramienta, en su superpoder para conocerse a sí mismos.";
 
 export const letranp19 = "Por ejemplo, si los padres de esta persona le han abandonado emocionalmente pero a la vez estaban presentes, esto deja una huella profunda de incomprensión en la persona.  La persona, para explicar por qué se siente inadecuado, ha dado rienda suelta inconscientemente a las voces que le hacen daño para poder justificar ese estado.  Los niños, desde muy pequeños, aprenden que los padres siempre tienen razón, porque necesitan glorificar a estas figuras y apegarse a ellas para sobrevivir.  Aprenden que los malos son ellos mismos, que el que lo hace mal, lo entiende mal y es egoísta son ellos mismos.  Desde esta percepción internalizada, hacen lo que pueden para soportar ese dolor a lo largo de su vida.";
 
 export const letranp20 = "A muchas personas con psicosis no se las acompaña: se las somete. No se les ayuda a entender de dónde viene su dolor. Se les asusta. Se les etiqueta. Se les hace creer que están rotas.  Y muchas veces se les transmite que la única salida es medicarse, que no hay nada más que hacer.  El medicamento tiene que ser una ayuda puntual, no una forma de vida.  Porque el medicamento apaga a la persona, hace que esté cansada, que apenas pueda moverse, y esto solo incrementa la profunda sensación de inutilidad que estas personas llevan años cargando.";

export const letranp21 = "La anorexia no es una enfermedad mental, es una manifestación más del sufrimiento humano. Las personas con anorexia lo que en verdad buscan es sentirse valoradas, respetadas y que ellas importan. Desean ser queridas por unos padres que no las han sabido querer. Lo que anhelan es sentirse suficientes, es que los demás las perciban como seres capaces, competentes, con valía propia y queribles.";

export const letranp22 = "La familia de las anoréxicas suele ser de clase media alta con un progenitor visto como competente e inteligente, el cual no les ha dado una validación real, por lo que crecen con un vacío interior y además con una ausencia de expresar ese malestar y sus sentimientos. Sus familias suelen darles comodidades y lujos que las hacen sentir abrumadas. No entienden por qué los tienen y no saben si son merecedoras de estos.";

export const letranp23 = "Las anoréxicas viven pensando que no son suficientemente agradecidas. Esto hace que se castiguen a ellas mismas como un intento de compensación, creyendo que nunca serán capaces de devolverle a sus padres todo lo que les han dado. Se sienten responsables de sus familias, en especial del bienestar emocional de sus padres. Reprimen y esconden sus necesidades. Viven con mucho miedo al castigo. Viven preocupadas, no saben qué es lo que sus padres realmente quieren o esperan de ellas. La solución a esto es tratar de ser más perfecta que cualquier otro.";

export const letranp24 = "Las anoréxicas interiorizan que no son suficientes. Se convencen de que no pueden vivir como un humano más, por lo que van más allá de su deber, trabajando hasta a veces literalmente el desmayo. Piensan que si les queda energía es que no han cumplido con lo que tenían que hacer.";

export const letranp26 = "Las anoréxicas se sienten bien por estar enfermas. Creen que adelgazar las hace más valorables y especiales. Tienen que eliminar estas creencias y darse cuenta de que estar delgada no es sinónimo de que todo va a estar bien y de que todo está bajo control.";

export const letranp27 = "A las anoréxicas no se les ha enseñado a que se vean como las personas valiosas que son. Al carecer esa seguridad han encontrado seguridad reprimiendo las necesidades de su cuerpo. Es decir, si son capaces de aguantar el hambre, significa que son fuertes, resistentes y poderosas, que son capaces.";

export const letranp28 = "Las anoréxicas no viven su cuerpo como algo que cuidar, sino como algo que controlar. El cuerpo es un campo de batalla, el hambre contra su merecimiento. Engordar es sinónimo de fracaso, no por la grasa en sí, sino porque eso significa que no han sido capaces de controlarse, que no han sido lo suficientemente fuertes, por lo tanto, piensan que son inútiles.";

export const letranp29 = "Para las anoréxicas, adelgazar es sinónimo de estar haciendo las cosas bien. Cuanto más delgadas, más fuertes, capaces, inteligentes y merecedoras se sienten. Convierten la delgadez en la demostración de que pueden conseguir objetivos difíciles, objetivos que pocos son capaces.";

export const letranp30 = "Las anoréxicas están convencidas de que su personalidad es defectuosa, de que no son suficientemente brillantes, no entienden por qué otros las querrían. La continua evaluación de sí mismas es la enfermedad. Solo podrán empezar a sanarse cuando se acepten a sí mismas. Por muy inmaduras, incapaces, tontas o asustadas que se sientan en ese momento, solo cuando aceptan su yo pueden empezar a sanarse.";

export const letrad1 = "La depresión es el trastorno mental más diagnosticado del mundo. La depresión no es una enfermedad, es la medicalización y etiquetación de dolor que no ha podido ser expresado ni gestionado. La persona normalmente carga con estos traumas congelados hasta que ocurre algo que hace que no pueda más, es ahí cuando va al psiquiatra y este le prescribe los famosos antidepresivos. Los antidepresivos nunca han curado ni curarán a nadie, lo único que hacen es desconectarte de tu dolor dejándote en un estado zombie para que sigas siendo productivo en la sociedad enferma en la que estamos.";

export const letrad2 = "Los depresivos tienen que entender que tienen un duelo congelado. A lo largo de su vida no han encontrado un espacio seguro en el cual poder expresar y así gestionar su dolor, que de tanto guardarlo, se ha convertido en un sufrimiento que les acompaña allá a dónde van. La tristeza es un sentimiento que te invita a cambiar lo que te está pesando en la vida, lo que debe de ser liberado. Pero si tienes tristeza crónica, eso es que no tienes las herramientas ni el permiso para poder llevar a cabo esos cambios en tu vida.";

export const letrad3 = "A veces, la depresión se aprende en casa. No existe un gen que te haga depresivo, más que genética es lo que uno ha aprendido en su infancia. Es decir, una persona cuyos padres son depresivos, no le han podido demostrar que la felicidad existe, por ello es más probable que acabe depresiva porque aprende que esa es la manera en la que hay que funcionar.";

export const letrad4 = "Los depresivos no han tenido, ni tienen permiso para enfadarse. En caso de que pudiesen expresar su enfado, todo el sistema en el que viven se pondrían en su contra. Por lo que han tenido que reprimirla y ese enfado se ha convertido en tristeza, en un sentimiento que les quema por dentro pero que no pueden expresar ni gestionar. Por alguna razón, el sistema en el cual viven saca provecho de esa represión del enfado.";

export const letrad5 = "Por si no fuese suficiente, los depresivos encima tienen que cargar con el resto de personas diciéndoles que deberían de estar alegres, que deberían de motivarse y ponerse en marcha. Su entorno no entiende por qué está triste y eso les frustra y en vez de dejar que el depresivo hable, lo que hacen es decirle que debería de estar feliz. El resultado de esto es que la persona depresiva se siente triste por estar triste y avergonzado de estar avergonzado.";

