import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { neuropsicologiaBg, NeuropsicologiaIcon, neuropsicologiaTxt, MadreIcon, AdultIcon, ChildIcon, FamilyIcon, neuropsicologiaNom, EsqComprenderIcon, EsqOrigenIcon, EsqBiologiaIcon, EsqVocesIcon, AnxEntornoIcon, AnxComidaIcon, AnxSanacionIcon } from "../../../GlobalVariables";
import { letranp1, letranp2, letranp3, letranp4, letranp5, letranp6, letranp7, letranp8, letranp9, letranp10, letranp11, letranp12, letranp13, letranp14, letranp15, letranp16, letranp17, letranp18, letranp19, letranp20, letranp21, letranp22, letranp23, letranp24, letranp26, letranp27, letranp28, letranp29, letranp30, letrad1, letrad2, letrad3, letrad4, letrad5, letres1, letres2, letres3, letres4, letres5 } from "./LetraNeuroPsicologia";

const detalles: Detalles = { color: neuropsicologiaTxt, icon: NeuropsicologiaIcon, bgColor: neuropsicologiaBg };

const basePath = "/aprendizaje/videoLessonPage/" + neuropsicologiaNom;
const basePathEsq = "/aprendizaje/videoLessonPage/" + neuropsicologiaNom + "cursoEsq";
const basePathAnx = "/aprendizaje/videoLessonPage/" + neuropsicologiaNom + "cursoAnx";
const basePathDep = "/aprendizaje/videoLessonPage/" + neuropsicologiaNom + "cursoDep";
const basePathEs = "/aprendizaje/videoLessonPage/" + neuropsicologiaNom + "cursoEs";



const quieroEntenderme: FloatingButtonConfig = {
  label: "Quiero entenderme",
  action: "espacio-auth",
  route: "/espacio/questions/" + neuropsicologiaNom,
};

export const modulosNeuroPsicologia: ModuloContenido[] = [
  {
    title: "1. La madre y el niño",
    icon: MadreIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"np1",
        nom: "1.1 El vínculo entre la madre y el hijo",
        link:`${basePath}/np1`,
        linkAnterior:"",
        linkNext:`${basePath}/np2`,
        descripcion:"El estado de la madre influye a su hijo desde antes del embarazo.",
        video:"-w67yUcj_SM",
        letra: letranp1,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: MadreIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np2",
        nom: "1.2 El nacimiento y la insuficiencia",
        link:`${basePath}/np2`,
        linkAnterior:`${basePath}/np1`,
        linkNext:`${basePath}/np3`,
        descripcion:"Los padres tienen que ser seres completos antes del nacimiento o cargarán al hijo con su infelicidad y frustración.",
        video:"apYqTnx9kiM",
        letra: letranp2,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: MadreIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "2. La Infancia",
    icon: FamilyIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"np3",
        nom: "2.1 Los primeros años de Vida",
        link:`${basePath}/np3`,
        linkAnterior:`${basePath}/np2`,
        linkNext:`${basePath}/np4`,
        descripcion:"La seguridad y el Amor no deberían ser un objetivo a alcanzar dentro de la familia, sino la base desde la que cada hijo comienza su Vida.",
        video:"JqnJlu6L6mc",
        letra: letranp3,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: FamilyIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np4",
        nom: "2.2 Las figuras de apego y el autoabandono",
        link:`${basePath}/np4`,
        linkAnterior:`${basePath}/np3`,
        linkNext:`${basePath}/np5`,
        descripcion:"Los niños se desvalidan a sí mismos antes que desvalidar a sus padres.",
        video:"wRO7-7Z0zsM",
        letra: letranp4,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: FamilyIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "3. El adulto joven",
    icon: ChildIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"np5",
        nom: "3.1 Los trastornos y la adolescencia",
        link:`${basePath}/np5`,
        linkAnterior:`${basePath}/np4`,
        linkNext:`${basePath}/np6`,
        descripcion:"En la individualización, la falta de Amor propio de los niños aflora, y la sociedad trata de tacharles de rotos asignándoles enfermedades mentales.",
        video:"MK9lQqogmbY",
        letra: letranp5,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: ChildIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np6",
        nom: "3.2 El corazón ya estaba roto",
        link:`${basePath}/np6`,
        linkAnterior:`${basePath}/np5`,
        linkNext:`${basePath}/np7`,
        descripcion:"Usamos a los demás para darnos cuenta de lo rotos que ya estamos. Nadie nos rompe el corazón, solo nos muestra dónde lo estaba.",
        video:"CEE_gCwAdDM",
        letra: letranp6,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: ChildIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np7",
        nom: "3.3 Amigos y proyecciones",
        link:`${basePath}/np7`,
        linkAnterior:`${basePath}/np6`,
        linkNext:`${basePath}/np8`,
        descripcion:"Atraemos a personas para que nos muestren dónde no nos aceptamos.",
        video:"jmLKf9E-X6A",
        letra: letranp7,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: ChildIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "4. El adulto",
    icon: AdultIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"np8",
        nom: "4.1 La adultez, la decadencia y el bucle del sinsentido",
        link:`${basePath}/np8`,
        linkAnterior:`${basePath}/np7`,
        linkNext:`${basePath}/np9`,
        descripcion:"La gran mayoría de los adultos se menosprecian y desvaloran, hundiéndose en la pereza, pensando que por cumplir años están condenados a la decadencia.",
        video:"YezjA0ZSK2Y",
        letra: letranp8,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: AdultIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np9",
        nom: "4.2 La vejez y el olvido",
        link:`${basePath}/np9`,
        linkAnterior:`${basePath}/np8`,
        linkNext:`${basePath}/np10`,
        descripcion:"Si te maltratas todos los días, cuando llegues a tu vejez, preferirás olvidar lo que te has hecho a tener que asumir que te has arruinado la Vida.",
        video:"xWWqi6GDH8A",
        letra: letranp9,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: AdultIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np10",
        nom: "4.3 Mirada desde la espiritualidad práctica",
        link:`${basePath}/np10`,
        linkAnterior:`${basePath}/np9`,
        linkNext:"",
        descripcion:"Todo tiene un sentido. La Vida nos habla en cada instante. Escúchala y no te abandones. Eres mucho más que un cuerpo físico.",
        video:"TjFVYfroda4",
        letra: letranp10,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: AdultIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
];

export const modulosEsquizofrenia: ModuloContenido[] = [
  {
    title: "1. Comprendiendo la esquizofrenia",
    icon: EsqComprenderIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"esq1",
        nom: "1.1 Esquizofrénicos",
        link:`${basePathEsq}/esq1`,
        linkAnterior:"",
        linkNext:`${basePathEsq}/esq2`,
        descripcion:"Etiquetaron a personas que solo intentaban sobrevivir a un entorno que nadie quiso ver.",
        video:"ZGWhXbc0u7A",
        letra: letranp11,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqComprenderIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"esq2",
        nom: "1.2 La realidad construida",
        link:`${basePathEsq}/esq2`,
        linkAnterior:`${basePathEsq}/esq1`,
        linkNext:`${basePathEsq}/esq3`,
        descripcion:"Obligado al aislamiento, el cerebro construye su propia realidad para poder sostener el dolor.",
        video:"IEMVkUzib94",
        letra: letranp15,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqComprenderIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "2. El origen del sufrimiento",
    icon: EsqOrigenIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"esq3",
        nom: "2.1 La genética",
        link:`${basePathEsq}/esq3`,
        linkAnterior:`${basePathEsq}/esq2`,
        linkNext:`${basePathEsq}/esq4`,
        descripcion:"No se hereda la enfermedad, se hereda una predisposición al sufrimiento no sanado.",
        video:"Rn69mSslMKk",
        letra: letranp13,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqOrigenIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"esq4",
        nom: "2.2 El entorno familiar",
        link:`${basePathEsq}/esq4`,
        linkAnterior:`${basePathEsq}/esq3`,
        linkNext:`${basePathEsq}/esq5`,
        descripcion:"La esquizofrenia no aparece de repente: son años de dolor silenciado por un entorno que prefirió no mirar.",
        video:"xk2MR2UxhNE",
        letra: letranp12,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqOrigenIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"esq5",
        nom: "2.3 Autodaño y lealtad a los padres",
        link:`${basePathEsq}/esq5`,
        linkAnterior:`${basePathEsq}/esq4`,
        linkNext:`${basePathEsq}/esq6`,
        descripcion:"El niño aprende que el malo es él mismo, y carga con esa percepción toda su vida.",
        video:"R2ZYkMlKD9Y",
        letra: letranp19,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqOrigenIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "3. La biología",
    icon: EsqBiologiaIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"esq6",
        nom: "3.1 Las sustancias como refugio",
        link:`${basePathEsq}/esq6`,
        linkAnterior:`${basePathEsq}/esq5`,
        linkNext:`${basePathEsq}/esq7`,
        descripcion:"Las adicciones son la solución, no el problema. El problema es el dolor insoportable que les acompaña a donde van.",
        video:"qfz2UWPNzyw",
        letra: letranp14,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqBiologiaIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"esq7",
        nom: "3.2 El cerebro",
        link:`${basePathEsq}/esq7`,
        linkAnterior:`${basePathEsq}/esq6`,
        linkNext:`${basePathEsq}/esq8`,
        descripcion:"Los cambios en el cerebro son la consecuencia del dolor, no su causa.",
        video:"Cmabt9J5Kes",
        letra: letranp16,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqBiologiaIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"esq8",
        nom: "3.3 Las pastillas",
        link:`${basePathEsq}/esq8`,
        linkAnterior:`${basePathEsq}/esq7`,
        linkNext:`${basePathEsq}/esq9`,
        descripcion:"A estas personas no se las acompaña: se las somete, se las etiqueta y se las apaga con medicación.",
        video:"fVVlxG1gaIw",
        letra: letranp20,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqBiologiaIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "4. Las Voces",
    icon: EsqVocesIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"esq9",
        nom: "4.1 Las Voces",
        link:`${basePathEsq}/esq9`,
        linkAnterior:`${basePathEsq}/esq8`,
        linkNext:`${basePathEsq}/esq10`,
        descripcion:"Todos tenemos voces internas. La diferencia está en si somos capaces de controlarlas.",
        video:"rkN0YWEfy_A",
        letra: letranp17,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqVocesIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"esq10",
        nom: "4.2 La relación con las voces",
        link:`${basePathEsq}/esq10`,
        linkAnterior:`${basePathEsq}/esq9`,
        linkNext:"",
        descripcion:"Las voces no se eliminan: se escuchan, se observan y se convierten en una herramienta de autoconocimiento.",
        video:"Z_gPrmpwKw4",
        letra: letranp18,
        cursoId: "esquizofrenia",
        detalles: detalles,
        icon: EsqVocesIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
];

export const modulosEsenciales: ModuloContenido[] = [
  {
    title: "1. El corazón herido",
    icon: EsqComprenderIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id: "es1",
        nom: "1.1 Nadie te rompe el corazón",
        link: `${basePathEs}/es1`,
        linkAnterior: "",
        linkNext: `${basePathEs}/es2`,
        descripcion:
          "Las parejas no rompen el corazón: rompen la coraza con la que escondíamos nuestras heridas.",
        video: "ElCSVyx_3OI",
        letra: letres1,
        cursoId: "esenciales",
        detalles: detalles,
        icon: EsqComprenderIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id: "es2",
        nom: "1.2 Las personas como tirita",
        link: `${basePathEs}/es2`,
        linkAnterior: `${basePathEs}/es1`,
        linkNext: `${basePathEs}/es3`,
        descripcion:
          "Cuando alguien vive en tu cabeza, lo estás usando para no sentir tu propio dolor.",
        video: "DkkYekK0l_4",
        letra: letres2,
        cursoId: "esenciales",
        detalles: detalles,
        icon: EsqComprenderIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "2. Las emociones que negamos",
    icon: EsqVocesIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id: "es3",
        nom: "2.1 Los dos tipos de enfado",
        link: `${basePathEs}/es3`,
        linkAnterior: `${basePathEs}/es2`,
        linkNext: `${basePathEs}/es4`,
        descripcion:
          "Hay un enfado que defiende, y otro que te pide cambiar algo de tu Vida.",
        video: "ckq1T6GHBMk",
        letra: letres3,
        cursoId: "esenciales",
        detalles: detalles,
        icon: EsqVocesIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id: "es4",
        nom: "2.2 La ansiedad no existe",
        link: `${basePathEs}/es4`,
        linkAnterior: `${basePathEs}/es3`,
        linkNext: `${basePathEs}/es5`,
        descripcion:
          "La ansiedad es la bola de nieve de las emociones que llevas años negando.",
        video: "gZdcd-LqASU",
        letra: letres4,
        cursoId: "esenciales",
        detalles: detalles,
        icon: EsqVocesIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "3. Sigue luchando por ti",
    icon: AnxSanacionIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id: "es5",
        nom: "3.1 Estar vivo es un acto de valentía",
        link: `${basePathEs}/es5`,
        linkAnterior: `${basePathEs}/es4`,
        linkNext: "",
        descripcion:
          "Mereces el Amor y el apoyo que llevas tanto tiempo anhelando. Deja de abandonarte.",
        video: "0Lpk6bIHeRY",
        letra: letres5,
        cursoId: "esenciales",
        detalles: detalles,
        icon: AnxSanacionIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
];

export const modulosDepresion: ModuloContenido[] = [
  {
    title: "1. Comprende la depresión",
    icon: EsqComprenderIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id: "dep1",
        nom: "1.1 La depresión es un dolor congelado",
        link: `${basePathDep}/dep1`,
        linkAnterior: "",
        linkNext: `${basePathDep}/dep2`,
        descripcion:
          "Detrás de la tristeza crónica hay un duelo que nunca encontró un espacio seguro para ser expresado.",
        video: "aMIUtZTRprg",
        letra: letrad2,
        cursoId: "depresion",
        detalles: detalles,
        icon: EsqComprenderIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id: "dep2",
        nom: "1.2 La depresión es etiquetar el sufrimiento",
        link: `${basePathDep}/dep2`,
        linkAnterior: `${basePathDep}/dep1`,
        linkNext: `${basePathDep}/dep3`,
        descripcion:
          "La depresión no es una enfermedad: es la medicalización del dolor que no se ha podido expresar.",
        video: "wWoYQEk8zBk",
        letra: letrad1,
        cursoId: "depresion",
        detalles: detalles,
        icon: EsqComprenderIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "2. El origen",
    icon: EsqOrigenIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id: "dep3",
        nom: "2.1 La depresión puede ser un mandato familiar",
        link: `${basePathDep}/dep3`,
        linkAnterior: `${basePathDep}/dep2`,
        linkNext: `${basePathDep}/dep4`,
        descripcion:
          "La depresión no se hereda en los genes: se aprende en casa, viendo a unos padres que tampoco supieron ser felices.",
        video: "NSRxhlmPHEw",
        letra: letrad3,
        cursoId: "depresion",
        detalles: detalles,
        icon: EsqOrigenIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id: "dep4",
        nom: "2.2 Los deprimidos no tienen permiso para enfadarse",
        link: `${basePathDep}/dep4`,
        linkAnterior: `${basePathDep}/dep3`,
        linkNext: `${basePathDep}/dep5`,
        descripcion:
          "El enfado no expresado se convierte en tristeza. El sistema saca provecho de esa represión.",
        video: "34zn9ECzCAo",
        letra: letrad4,
        cursoId: "depresion",
        detalles: detalles,
        icon: EsqOrigenIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "3. El entorno",
    icon: AnxEntornoIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id: "dep5",
        nom: "3.1 La depresión no es una elección",
        link: `${basePathDep}/dep5`,
        linkAnterior: `${basePathDep}/dep4`,
        linkNext: "",
        descripcion:
          "El entorno presiona al depresivo para que esté feliz, y acaba sintiéndose triste por estar triste y avergonzado de estar avergonzado.",
        video: "R3_L3pXQIEM",
        letra: letrad5,
        cursoId: "depresion",
        detalles: detalles,
        icon: AnxEntornoIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
];

export const modulosAnorexia: ModuloContenido[] = [
  {
    title: "1. Comprende la anorexia",
    icon: EsqComprenderIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"anx1",
        nom: "1.1 El objetivo de la anorexia",
        link:`${basePathAnx}/anx1`,
        linkAnterior:"",
        linkNext:`${basePathAnx}/anx2`,
        descripcion:"La anorexia es la búsqueda del reconocimiento que sus padres no supieron darles.",
        video:"rGvfLg7KoTo",
        letra: letranp21,
        cursoId: "anorexia",
        detalles: detalles,
        icon: EsqComprenderIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"anx2",
        nom: "1.2 La insuficiencia en la anorexia",
        link:`${basePathAnx}/anx2`,
        linkAnterior:`${basePathAnx}/anx1`,
        linkNext:`${basePathAnx}/anx4`,
        descripcion:"Nunca es suficiente porque ellas mismas no se sienten suficientes.",
        video:"kgDWFW6UhTM",
        letra: letranp24,
        cursoId: "anorexia",
        detalles: detalles,
        icon: EsqComprenderIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "2. El entorno familiar",
    icon: AnxEntornoIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"anx4",
        nom: "2.1 La familia de las anoréxicas",
        link:`${basePathAnx}/anx4`,
        linkAnterior:`${basePathAnx}/anx2`,
        linkNext:`${basePathAnx}/anx5`,
        descripcion:"Sus familias les dan lujos, pero ellas piensan que no son suficientes, por lo que no entienden por qué los tienen.",
        video:"CkxrBYCeYCE",
        letra: letranp22,
        cursoId: "anorexia",
        detalles: detalles,
        icon: AnxEntornoIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"anx5",
        nom: "2.2 El agradecimiento y la culpa",
        link:`${basePathAnx}/anx5`,
        linkAnterior:`${basePathAnx}/anx4`,
        linkNext:`${basePathAnx}/anx6`,
        descripcion:"Al sentirse insuficientes, piensan que no son agradecidas y tratan de castigarse para compensar el por qué reciben tanto.",
        video:"LyikSZDV0AI",
        letra: letranp23,
        cursoId: "anorexia",
        detalles: detalles,
        icon: AnxEntornoIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "3. El cuerpo y el hambre",
    icon: AnxComidaIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"anx6",
        nom: "3.1 La enfermedad como merecimiento",
        link:`${basePathAnx}/anx6`,
        linkAnterior:`${basePathAnx}/anx5`,
        linkNext:`${basePathAnx}/anx7`,
        descripcion:"La enfermedad y su decadencia las hace sentir merecedoras.",
        video:"ei2V3J76EuY",
        letra: letranp26,
        cursoId: "anorexia",
        detalles: detalles,
        icon: AnxComidaIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"anx7",
        nom: "3.2 La falta de valía en la anorexia",
        link:`${basePathAnx}/anx7`,
        linkAnterior:`${basePathAnx}/anx6`,
        linkNext:`${basePathAnx}/anx8`,
        descripcion:"Aguantar el hambre es visto como fortaleza.",
        video:"UqTnM5LZyjU",
        letra: letranp27,
        cursoId: "anorexia",
        detalles: detalles,
        icon: AnxComidaIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"anx8",
        nom: "3.3 El cuerpo como algo que controlar",
        link:`${basePathAnx}/anx8`,
        linkAnterior:`${basePathAnx}/anx7`,
        linkNext:`${basePathAnx}/anx9`,
        descripcion:"El cuerpo es un campo de batalla, el cual tienen que controlar para sentirse capaces.",
        video:"RvPrP2LKD3Y",
        letra: letranp28,
        cursoId: "anorexia",
        detalles: detalles,
        icon: AnxComidaIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"anx9",
        nom: "3.4 Adelgazar en la anorexia",
        link:`${basePathAnx}/anx9`,
        linkAnterior:`${basePathAnx}/anx8`,
        linkNext:`${basePathAnx}/anx10`,
        descripcion:"Convierten la delgadez en la demostración de que pueden conseguir objetivos difíciles.",
        video:"5n5tklXlwvc",
        letra: letranp29,
        cursoId: "anorexia",
        detalles: detalles,
        icon: AnxComidaIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "4. La sanación",
    icon: AnxSanacionIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"anx10",
        nom: "4.1 Sanar una anorexia",
        link:`${basePathAnx}/anx10`,
        linkAnterior:`${basePathAnx}/anx9`,
        linkNext:"",
        descripcion:"El continuo juicio hacia sí mismas es la enfermedad.",
        video:"5Md7Wf9JCEA",
        letra: letranp30,
        cursoId: "anorexia",
        detalles: detalles,
        icon: AnxSanacionIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
];