import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { neuropsicologiaBg, NeuropsicologiaIcon, neuropsicologiaTxt, MadreIcon, AdultIcon, ChildIcon, FamilyIcon, SistemaNerviosoIcon, neuropsicologiaNom } from "../../../GlobalVariables";
import { letranp1, letranp10, letranp11, letranp12, letranp13, letranp14, letranp15, letranp16, letranp17, letranp18, letranp19, letranp20, letranp2, letranp3, letranp4, letranp5, letranp6, letranp7, letranp8, letranp9 } from "./LetraNeuroPsicologia";

const detalles: Detalles = { color: neuropsicologiaTxt, icon: NeuropsicologiaIcon, bgColor: neuropsicologiaBg };

const basePath = "/aprendizaje/videoLessonPage/" + neuropsicologiaNom;

const quieroEntenderme: FloatingButtonConfig = {
  label: "Quiero entenderme",
  action: "espacio-auth",
  route: "/espacio/questions/" + neuropsicologiaNom,
};

export const modulosNeuroPsicologia: ModuloContenido[] = [
  {
    title: "1. La madre y el niño",
    icon: MadreIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"np1",
        nom: "1.1 El vínculo entre la madre y el hijo",
        link:`${basePath}/np1`,
        linkAnterior:"",
        linkNext:`${basePath}/np2`,
        descripcion:"El estado de la madre influye a su hijo desde antes del embarazo.",
        video:"-w67yUcj_SM",
        letra: letranp1,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: MadreIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np2",
        nom: "1.2 El nacimiento y la insuficiencia",
        link:`${basePath}/np2`,
        linkAnterior:`${basePath}/np1`,
        linkNext:`${basePath}/np3`,
        descripcion:"Los padres tienen que ser seres completos antes del nacimiento o cargarán al hijo con su infelicidad y sueños rotos.",
        video:"apYqTnx9kiM",
        letra: letranp2,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: MadreIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "2. La Infancia",
    icon: FamilyIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"np3",
        nom: "2.1 Los primeros años de Vida",
        link:`${basePath}/np3`,
        linkAnterior:`${basePath}/np2`,
        linkNext:`${basePath}/np4`,
        descripcion:"La seguridad y el Amor no deberían ser un objetivo a alcanzar dentro de la familia, sino la base desde la que cada hijo comienza su Vida.",
        video:"JqnJlu6L6mc",
        letra: letranp3,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: FamilyIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np4",
        nom: "2.2 Las figuras de apego y el autoabandono",
        link:`${basePath}/np4`,
        linkAnterior:`${basePath}/np3`,
        linkNext:`${basePath}/np5`,
        descripcion:"Los niños se desvalidan a sí mismos antes que desvalidar a sus padres.",
        video:"wRO7-7Z0zsM",
        letra: letranp4,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: FamilyIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "3. El adulto joven",
    icon: ChildIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"np5",
        nom: "3.1 Los trastornos y la adolescencia",
        link:`${basePath}/np5`,
        linkAnterior:`${basePath}/np4`,
        linkNext:`${basePath}/np6`,
        descripcion:"En la individualización, la falta de Amor propio de los niños aflora, y la sociedad trata de tacharles de rotos asignándoles enfermedades mentales.",
        video:"MK9lQqogmbY",
        letra: letranp5,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: ChildIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np6",
        nom: "3.2 El corazón ya estaba roto",
        link:`${basePath}/np6`,
        linkAnterior:`${basePath}/np5`,
        linkNext:`${basePath}/np7`,
        descripcion:"Usamos a los demás para darnos cuenta de lo rotos que ya estamos. Nadie nos rompe el corazón, solo nos muestra dónde lo estaba.",
        video:"CEE_gCwAdDM",
        letra: letranp6,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: ChildIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np7",
        nom: "3.3 Amigos y proyecciones",
        link:`${basePath}/np7`,
        linkAnterior:`${basePath}/np6`,
        linkNext:`${basePath}/np8`,
        descripcion:"Atraemos a personas para que nos muestren dónde no nos aceptamos.",
        video:"jmLKf9E-X6A",
        letra: letranp7,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: ChildIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
  {
    title: "4. El adulto",
    icon: AdultIcon,
    floatingButton: quieroEntenderme,
    submodules: [
      {
        id:"np8",
        nom: "4.1 La adultez, la decadencia y el bucle del sinsentido",
        link:`${basePath}/np8`,
        linkAnterior:`${basePath}/np7`,
        linkNext:`${basePath}/np9`,
        descripcion:"La gran mayoría de los adultos se menosprecian y desvaloran, hundiéndose en la pereza, pensando que por cumplir años condenados a la decadencia.",
        video:"YezjA0ZSK2Y",
        letra: letranp8,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: AdultIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np9",
        nom: "4.2 La vejez y el olvido",
        link:`${basePath}/np9`,
        linkAnterior:`${basePath}/np8`,
        linkNext:`${basePath}/np10`,
        descripcion:"Si te maltratas todos los días, cuando llegues a tu vejez, preferirás olvidar lo que te has hecho a tener que asumir que te has arruinado la Vida.",
        video:"xWWqi6GDH8A",
        letra: letranp9,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: AdultIcon,
        floatingButton: quieroEntenderme,
      },
      {
        id:"np10",
        nom: "4.3 Mirada desde la espiritualidad práctica",
        link:`${basePath}/np10`,
        linkAnterior:`${basePath}/np9`,
        linkNext:"",
        descripcion:"Todo tiene un sentido. La Vida nos habla en cada instante. Escúchala y no te abandones. Eres mucho más que un cuerpo físico.",
        video:"TjFVYfroda4",
        letra: letranp10,
        cursoId: "etapasVida",
        detalles: detalles,
        icon: AdultIcon,
        floatingButton: quieroEntenderme,
      },
    ],
  },
];


//  {
//     title: "5. Más allá de la Esquizofrenia",
//     icon: SistemaNerviosoIcon,
//     submodules: [
//       {
//         id:"np11",
//         nom: "5.1 Esquizofrénicos",
//         link:`${basePath}/np11`,
//         linkAnterior:"",
//         linkNext:`${basePath}/np12`,
//         descripcion:"No existen esquizofrénicos, existen personas que desarrollaron una estrategia para sobrevivir a un mundo que percibieron como hostil.",
//         video:"",
//         letra: letranp11,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np12",
//         nom: "5.2 El entorno familiar",
//         link:`${basePath}/np12`,
//         linkAnterior:`${basePath}/np11`,
//         linkNext:`${basePath}/np13`,
//         descripcion:"Una esquizofrenia no se desarrolla de la noche a la mañana. Son años de sufrimiento silenciado en un entorno de abandono insostenible.",
//         video:"",
//         letra: letranp12,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np13",
//         nom: "5.3 La genética",
//         link:`${basePath}/np13`,
//         linkAnterior:`${basePath}/np12`,
//         linkNext:`${basePath}/np14`,
//         descripcion:"La esquizofrenia no se hereda tal cual. Lo que se hereda es una genética predispuesta al sufrimiento.",
//         video:"",
//         letra: letranp13,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np14",
//         nom: "5.4 Las sustancias como refugio",
//         link:`${basePath}/np14`,
//         linkAnterior:`${basePath}/np13`,
//         linkNext:`${basePath}/np15`,
//         descripcion:"Las adicciones nunca son el problema, sino la solución. El problema es la herida no sanada que impulsa a buscar una salida desesperada.",
//         video:"",
//         letra: letranp14,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np15",
//         nom: "5.5 La realidad construida",
//         link:`${basePath}/np15`,
//         linkAnterior:`${basePath}/np14`,
//         linkNext:`${basePath}/np16`,
//         descripcion:"Todos construimos nuestra realidad. Cuando alguien ha vivido en aislamiento, inventar una realidad propia es una respuesta completamente normal.",
//         video:"",
//         letra: letranp15,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np16",
//         nom: "5.6 El cerebro",
//         link:`${basePath}/np16`,
//         linkAnterior:`${basePath}/np15`,
//         linkNext:`${basePath}/np17`,
//         descripcion:"El desequilibrio neuronal no es la causa de la esquizofrenia. Primero aparecen las voces; después, se producen cambios en la dopamina.",
//         video:"",
//         letra: letranp16,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np17",
//         nom: "5.7 Las Voces",
//         link:`${basePath}/np17`,
//         linkAnterior:`${basePath}/np16`,
//         linkNext:`${basePath}/np18`,
//         descripcion:"Todos tenemos voces en la cabeza. La diferencia está en si somos capaces de controlarlas. ¿Para qué necesitan esas voces? ¿De qué les protegen?",
//         video:"",
//         letra: letranp17,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np18",
//         nom: "5.8 La relación con las voces",
//         link:`${basePath}/np18`,
//         linkAnterior:`${basePath}/np17`,
//         linkNext:`${basePath}/np19`,
//         descripcion:"No se trata de eliminar las voces, sino de darles su lugar sin ser su marioneta. Convertirlas en una herramienta para conocerse a uno mismo.",
//         video:"",
//         letra: letranp18,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np19",
//         nom: "5.9 Autodañarse y lealtad a los padres",
//         link:`${basePath}/np19`,
//         linkAnterior:`${basePath}/np18`,
//         linkNext:`${basePath}/np20`,
//         descripcion:"Los niños aprenden que los malos son ellos mismos. Esa percepción internalizada lleva a alimentar voces que justifican el propio dolor.",
//         video:"",
//         letra: letranp19,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//       {
//         id:"np20",
//         nom: "5.10 Las pastillas",
//         link:`${basePath}/np20`,
//         linkAnterior:`${basePath}/np19`,
//         linkNext:"",
//         descripcion:"El medicamento tiene que ser una ayuda puntual, no una forma de vida. Apagar a la persona solo incrementa su profunda sensación de inutilidad.",
//         video:"",
//         letra: letranp20,
//         cursoId: "masAllaEsquizofrenia",
//         detalles: detalles,
//         icon: SistemaNerviosoIcon
//       },
//     ],
//   },
