export const fisio1 = "Cuando una estrella muere, libera átomos. Nuestro cuerpo, la naturaleza y todo lo que ves está hecho con esos átomos. Nosotros estamos hechos con polvo de estrellas. El mundo invierte en nosotros todos los días a través del oxígeno que nos da, del agua que bebemos y de los alimentos que transformamos en energía. El mundo está continuamente velando por nosotros, y su único propósito es que seamos capaces de disfrutar de la creación.";
export const fisio2 = "Nuestras células están formadas por los átomos que las estrellas hicieron. Una célula es un organismo perfecto, diseñado para formar parte de un engranaje, como nuestro cuerpo. El metabolismo de las células humanas usa oxígeno, glucosa, agua y un montón de enzimas. Como producto residual, crea energía para nosotros y dióxido de carbono, para las plantas, ellas serán las que creen oxígeno otra vez para nosotros. Gracias a este baile molecular, que da lugar a la Vida, podemos ver una parte del engranaje perfecto que es nuestro universo, y de cómo de interconectados estamos.";
export const fisio3 = "Las células están regidas por una inteligencia que las coordina. Nuestro cuerpo está formado por órganos, que son asociaciones de células que cooperan para permitir funciones necesarias para la Vida. También tenemos sistemas, como el inmunitario, perfectamente organizado, que nos protege sin que tengamos que pedírselo. Imagínate si tuviéramos que pagar al higado para que detoxificase, o a los pulmones para que respirasen o al corazón para que latiese. Nos olvidamos del milagro que es nuestro cuerpo y vivimos encerrados en la mente, lo que nos lleva a una completa desconexión de ser conscientes de lo afortunados que somos por nuestra existencia.";
export const fisio4 = "El sistema endocrino se encarga de la coordinación entre los órganos mediante hormonas. Una hormona es un mensaje que va de un órgano a otro a través de la sangre. Así es como los órganos se comunican, se coordinan y permiten la Vida en nuestro cuerpo. Tenemos muchas hormonas, cada una al servicio de una función distinta, su presencia depende del momento del día o incluso de la etapa de la Vida. Todas y cada una de ellas son necesarias y beneficiosas, si no, no las tendríamos! :) el problema es cuando hay mucho más de lo natural. Por ejemplo, el cortisol es el que nos despierta y prepara para el día, pero si nos estresamos, provocamos una segregación innecesaria y no natural que nos desequilibra. Por eso, si conocemos nuestras hormonas, su función y sus tiempos, podemos tener una Vida más equilibrada, entendiendo cuándo no estamos siguiendo nuestro ciclo circadiano, es decir, cuando estamos yendo en contra de cómo la naturaleza nos ha diseñado.";
export const fisio5 = "El cerebro está conectado con todo el cuerpo a través del sistema nervioso. Este sistema se encarga de recibir información, procesarla y enviar respuestas al organismo. El sistema nervioso nos permite sentir, controlar, movernos y además, regula muchas funciones automáticas, como la respiración, el ritmo cardíaco y la digestión, sin necesidad de tener que encargarnos personalmente de ello. Además, el sistema nervioso coordina la comunicación entre nuestra actividad cerebral y el resto de los órganos, permitiendo que el cuerpo responda en menos de 1 segundo, a los cambios internos y externos. Como podemos ver, tenemos mucho poder para regular al resto de nuestro cuerpo, por lo que un cerebro desarrollado, consciente y claro, da lugar a un cuerpo capaz de reconocer los síntomas de la enfermedad antes de que se produzca. Al contrario, una mente sobreestimulada, es un cuerpo mal gestionado.";
export const fisio6 = "Cada órgano está ahí por una razón, pero lo que tienen en común es que todos velan por nosotros. Su buen o mal funcionamiento nos sirve de espejo para saber si nos estamos tratando con el respeto que merecemos. Los pulmones cogen oxígeno del aire y devuelven el dióxido de carbono. Este oxígeno es entregado a los glóbulos rojos, que, gracias al impulso del corazón, viajarán por todo el cuerpo, entregando el oxígeno a las células. Estas células son las que forman a los órganos. El estómago disuelve los alimentos en sus formas más simples para que sean absorbidos en nuestros intestinos, los nutrientes pasan directamente a la sangre. El hígado detoxifica todo aquello en nuestra sangre y crea enzimas que nos protegen, además de gestionar los nutrientes que comemos. El bazo también se asegura de que en nuestra sangre no haya nada peligroso. Los riñones filtran continuamente, vigilando que haya una correcta regulación de electrolitos y separa lo que ya no nos sirve. Esto es solo una pequeña introducción a todo lo que hace nuestro cuerpo por nosotros, cada minuto! Imaginate todo lo que aun queda por descubrir.";
export const fisio7 = "Nosotros, como seres humanos, somos el milagro más asombroso y complejo de la naturaleza, y no nos creemos dignos ni merecedores de la existencia. Es más, solemos creer que merecemos extinguirnos. Lo que merece extinguirse es la creencia de que somos indignos, porque si nos reconociésemos como el milagro que somos, seríamos capaces de apreciar a la naturaleza como el milagro que es y no la destruiríamos. Si destruimos al mundo es porque tenemos tendencias autodestructivas.";

export const inflam1 = "La inflamación es una respuesta del cuerpo que permite que las células del sistema inmunitario viajen a una zona concreta. La inflamación le dice a las células que nos defienden dónde deben actuar. Estas células pueden atacar bacterias que han entrado a través de una herida. Pero la inflamación no solo ocurre cuando hay infecciones. También puede activarse sin que haya un problema real, causando lo que se conoce como inflamación crónica.";
export const inflam2 = "La inflamación crónica ocurre cuando el sistema inmunitario permanece activado durante mucho tiempo sin que haya una amenaza real. En lugar de activarse y apagarse, como ocurre con una herida, el cuerpo se queda en un estado de alerta constante. La fatiga, el cansancio y la ansiedad hacen que esto ocurra porque mantienen al cortisol en niveles elevados, lo que provoca una sobreactivación del sistema inmunitario, inflamando al cuerpo a la mínima.";
export const inflam3 = "Cuando hay mucho cortisol en la sangre, nuestro cuerpo cree estar en peligro, por lo que pide lo que más fácilmente le permitirá correr: el azúcar. No solo esto, sino que desea obtenerlo lo más rápido posible, por lo que no busca fibra, sino harinas blancas o ultraprocesados. Al recibir tanta glucosa de golpe, nuestro cuerpo se estresa porque nuestras células no necesitan más glucosa, pero ahora hay mucha en la sangre, por lo que el hígado tiene que almacenarla en forma de grasa.";
export const inflam4 = "Dormir mal causa inflamación crónica. Mientras dormimos, nuestro cuerpo se limpia; es cuando nuestro sistema inmunitario está más activo. Se limpia todo: el cerebro, el sistema linfático, el digestivo, ¡todo! Por eso, cuando no dormimos lo suficiente, nuestro cuerpo no está limpio, lo que provoca mayor reactividad de las células inmunitarias. Es decir, a la mínima actuarán, causando así una inflamación crónica de bajo grado que deteriora nuestra Vida y a nuestra persona.";
export const inflam5 = "Tu microbiota puede ser la causa de tu inflamación crónica. Nuestro intestino está formado por células unidas entre sí mediante pequeñas uniones. Cuando comemos alimentos ultraprocesados, grasas trans, saturadas o gluten, estas uniones pueden abrirse, permitiendo pasar bacterias que no deberían salir del intestino. Esto hace que nuestro sistema inmunitario se active, causando más inflamación, lo que hace que se abran aún más las uniones entre las células, creando así un círculo vicioso.";
export const inflam6 = "La inflamación crónica puede manifestarse con pesadez o hinchazón después de comer, lo que nos indica que hay inflamación en el intestino. También pueden aparecer dolores articulares, porque la inflamación crónica crea moléculas que degradan el cartílago. El acné y las irritaciones en la piel son también un síntoma, porque las citoquinas interfieren con el ciclo de Vida de los queratinocitos, las células de nuestra piel.";
export const inflam7 = "El cerebro también puede inflamarse. Cuando te levantas sin energía, incluso después de haber dormido, puede significar cansancio crónico. Esto significa que tu sistema inmunitario está produciendo demasiadas citoquinas, los mensajes que se intercambian las células, y esto está influyendo en el metabolismo de tus células, lo que hace que estés cansado y sin energía. La niebla mental es otra señal importante, porque las citoquinas son capaces de pasar al cerebro y sobreactivar a la microglía, el sistema inmunitario del cerebro, alterando así el ecosistema tan delicado que es nuestro cerebro.";
export const inflam8 = "Reducir la inflamación está en tu mano todos los días. Cambia tu dieta a una alimentación antiinflamatoria: incluye frutas, verduras y grasas saludables. Haz deporte todos los días; no necesitas entrenar como un atleta, con caminar y estirar es suficiente. Prueba la respiración profunda, la meditación o el yoga; tu cuerpo tiene que recordar que no está en peligro. Duerme bien para asegurarte una limpieza completa. Pasa tiempo al aire libre; esto regula el reloj biológico y contribuye a un sistema inmunitario equilibrado. Quince minutos al día pueden marcar la diferencia.";

// Fisiología del cáncer
export const cancer1 = "Tus células saben cuándo van a morir. La célula es un organismo vivo e inteligente. Es capaz de usar el ADN como manual y, por ello, regularse a sí misma, adaptarse a las situaciones y desarrollarse para dividirse y morir. Tenemos millones de células y todas tienen un ciclo parecido. A veces pasan años, pero antes o después se mueren para permitir la Vida de otras células.";
export const cancer2 = "La muerte no existe, existe la transformación. Cuando una célula es consciente de que va a morir, avisa y se prepara porque sabe que no va a desaparecer; lo que va a pasar es que sus átomos van a ser reutilizados por otras células. Es decir, la muerte no existe, existe la transformación. Deja de ser una célula para convertirse en parte de otras células. Nada en la naturaleza es eliminado.";
export const cancer3 = "El cáncer es el resultado de células mutadas genéticamente. Estas mutaciones apagan el mecanismo que corrige el ADN, el cual puede dañarse cada vez que la célula realiza una acción. Por ello, una célula mutada es una célula peligrosa, porque no solo inhibe su muerte, sino que antes o después se dividirá y, cuando lo haga, esta división será errónea, dando paso a la creación de tumores, que son un conjunto de células incorrectas.";
export const cancer4 = "Cada cigarro es un cambio en tu ADN. Las sustancias tóxicas del tabaco son capaces de cambiar el ADN celular, incrementando el riesgo de clonaciones erróneas y, por extensión, de cáncer. Además, vuelve lento y torpe al sistema inmunitario, impidiéndole cumplir con su función.";
export const cancer5 = "El alcohol no solo daña tu hígado, sino que es capaz de cambiar el ADN, incrementando así el riesgo de clonaciones erróneas y, por extensión, de cáncer. Además, hace que nuestra microbiota empeore, devolviendo los estrógenos a la circulación y promoviendo crecimientos anormales en el hígado, en el colon y en la mama.";
export const cancer6 = "Tomar el sol puede ser la causa de un cáncer. La luz está hecha de fotones que, al impactar con las células, crean radicales libres, cambiando nuestro ADN y causando un enorme desequilibrio en la capa protectora de las células. Esto promueve su clonación errónea y aumenta la posibilidad de cáncer.";
export const cancer7 = "El cáncer sabe esconderse de tu sistema inmune. Cuando una célula es clonada incorrectamente, nuestro sistema inmunitario la encuentra y la mata. Entonces, ¿por qué existe el cáncer? Las células mutadas pueden engañar al sistema inmunitario, aparentando ser células normales e inofensivas. Además, pueden producir sustancias que suprimen la respuesta inmune, debilitando la vigilancia natural de nuestro cuerpo. Las células mutadas hacen lo imposible para no morir.";
export const cancer8 = "El cáncer roba nutrientes a las células sanas. Las células mutadas son capaces de crear nuevas arterias que desvían los nutrientes que normalmente irían a las células sanas. Las células cancerígenas se alimentan sobre todo de glucosa. Por ello, una estrategia para evitar el desarrollo de un cáncer es reducir los carbohidratos simples y aumentar la ingesta de fibra.";
export const cancer9 = "El cáncer puede ser cambiado por tu nutrición. Las células cancerígenas cambian su metabolismo y usan sobre todo glucosa. Por lo que si tú cambias tu dieta a una en la que predominen la fibra, las vitaminas, las proteínas de origen vegetal y las grasas insaturadas, las células cancerígenas tendrán menos energía y morirán. Además, esto activará y hará más efectivo a tu sistema inmunitario, por lo que es más probable que encuentre y acabe con ellas.";

// La neurociencia de la meditación
export const med1 = "La meditación tiene cambios en nuestro cerebro, aunque solo la practiquemos 5 minutos al día. Es una práctica milenaria que se trata de ser capaz de estar plenamente en el presente. La mayor parte de nuestra Vida no somos conscientes de cuándo ni cómo estamos inhalando o exhalando. Por ello, nos sentamos a escuchar nuestra respiración. No se trata de dejar la mente en blanco, sino de observar a dónde se va la atención y ser capaz de retornarla a la respiración.";
export const med2 = "Meditar es un reto intelectual. Mucha gente cree que cuando meditas estás tranquilo, pero al principio no es así. Cuando empiezas a meditar estás en una lucha contra ti mismo: tu ruido mental contra tu deseo de centrarte. Meditar es lo más difícil que uno hace en el día, pero si no lo practicas, cuando necesites llevar tu atención a tus estudios o a una conversación, no vas a poder. Por eso, para poder acceder a todas tus capacidades cuando quieras, aprende a estar en el presente a través de la respiración.";
export const med3 = "Meditar te protege contra enfermedades. Cuando meditamos le estamos mandando señales a todas nuestras células de que estamos a salvo. Por ello, nuestro sistema inmunitario puede trabajar eficientemente y los niveles de cortisol se estabilizan.";
export const med4 = "Meditar crea conexiones neuronales. La neuroplasticidad es la creación de conexiones entre las neuronas. Esto ocurre cada vez que aprendemos algo nuevo, tenemos una conversación o cuando leemos algo que realmente nos interesa. Cuando meditamos, las conexiones neuronales de la atención se refuerzan y nuestro cerebro literalmente se hace más grande.";
export const med5 = "Meditar hace más grande tu cerebro. La corteza prefrontal es la zona del cerebro que nos permite razonar, planificar, controlar impulsos y mantener la atención. Cuando meditamos, las conexiones neuronales que permiten estos fenómenos son reforzadas y se hacen más grandes, transformándonos no solo en nuestra mejor versión, sino en una más eficaz y productiva.";
export const med6 = "Meditar reduce el enfado. La amígdala es la parte del cerebro que se ocupa del procesamiento del miedo y de la ansiedad. Es la que inconscientemente nos hace reaccionar a fantasmas del pasado. Cuando meditamos, nuestra amígdala reduce su tamaño, aumentando así nuestro nivel de tolerancia y disminuyendo la reactividad al estrés. Gracias a esto, cuando meditas estás menos enfadado. Además, eres consciente del gasto de energía innecesario que supone.";
export const med7 = "Meditar mejora nuestra memoria. Meditar incrementa el hipocampo, el cual se encarga de la memoria a largo plazo. Un estudio de Harvard demostró que el crecimiento del hipocampo se ve en tan solo 2 meses de práctica diaria. Pero no te desanimes: cada vez que meditas hay cambios en tu cerebro y en la calidad de tu Vida.";
