import type { Detalles, FloatingButtonConfig, ModuloContenido } from "../../../dtos/aprendizaje.type";
import { fisiologiaBg, FisiologiaIcon, fisiologiaNom, fisiologiaTxt, EstrellaIcon, CelulasOrganosIcon, MilagroIcon, SistemaNerviosoIcon, InflamIcon, FisioComidaIcon, FisioEjercicioIcon, EquilibrioIcon, CardioIcon } from "../../../GlobalVariables";
import { fisio1, fisio2, fisio3, fisio4, fisio5, fisio6, fisio7, inflam1, inflam2, inflam3, inflam4, inflam5, inflam6, inflam7, inflam8, cancer1, cancer2, cancer3, cancer4, cancer5, cancer6, cancer7, cancer8, cancer9, cancer10, cancer11, med1, med2, med3, med4, med5, med6, med7 } from "./LetraFisiologia";
import { ejer1, ejer2, ejer3, ejer4, ejer5, ejer6, ejer7 } from "./LetraEjercicio";

const detalles: Detalles = { color: fisiologiaTxt, icon: FisiologiaIcon, bgColor: fisiologiaBg };

const basePath = "/aprendizaje/videoLessonPage/" + fisiologiaNom;

export const fisioCurso1ID = "fisio-curso-1";
export const fisioCurso2ID = "fisio-curso-2";
export const fisioCurso3ID = "fisio-curso-3";
export const fisioCurso4ID = "fisio-curso-4";
export const fisioCurso5ID = "fisio-curso-5";

const conocerMiCuerpo: FloatingButtonConfig = {
  label: "Conocer mi cuerpo",
  action: "espacio-auth",
  route: "/espacio/fisiologia",
};

export const modulosFisiologia: ModuloContenido[] = [
  {
    title: "1. Hechos de polvo de estrellas",
    icon: EstrellaIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "fisio1",
        nom: "1.1 Hechos de polvo de estrellas",
        link: `${basePath}/fisio1`,
        linkAnterior: "",
        linkNext: `${basePath}/fisio2`,
        descripcion: "Nuestro cuerpo está hecho de los átomos que las estrellas liberaron al morir.",
        video: "sBsLNxY2w40",
        letra: fisio1,
        cursoId: fisioCurso1ID,
        detalles: detalles,
        icon: EstrellaIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "fisio2",
        nom: "1.2 Las células",
        link: `${basePath}/fisio2`,
        linkAnterior: `${basePath}/fisio1`,
        linkNext: `${basePath}/fisio3`,
        descripcion: "Una célula es un organismo perfecto que forma parte de un engranaje mayor.",
        video: "Ikx-VBEAO5c",
        letra: fisio2,
        cursoId: fisioCurso1ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "fisio3",
        nom: "1.3 Los órganos",
        link: `${basePath}/fisio3`,
        linkAnterior: `${basePath}/fisio2`,
        linkNext: `${basePath}/fisio4`,
        descripcion: "Los órganos son asociaciones de células coordinadas por una inteligencia mayor.",
        video: "M5vsl12Duok",
        letra: fisio3,
        cursoId: fisioCurso1ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "2. La Inteligencia del Cuerpo",
    icon: CelulasOrganosIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "fisio4",
        nom: "2.1 Las hormonas",
        link: `${basePath}/fisio4`,
        linkAnterior: `${basePath}/fisio3`,
        linkNext: `${basePath}/fisio5`,
        descripcion: "Las hormonas son mensajes entre órganos que coordinan la vida en nuestro cuerpo.",
        video: "r1O8j3T3dFE",
        letra: fisio4,
        cursoId: fisioCurso1ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "fisio5",
        nom: "2.2 El sistema nervioso",
        link: `${basePath}/fisio5`,
        linkAnterior: `${basePath}/fisio4`,
        linkNext: `${basePath}/fisio6`,
        descripcion: "El sistema nervioso conecta el cerebro con todo el cuerpo y regula funciones.",
        video: "kKQJ8tyx8gY",
        letra: fisio5,
        cursoId: fisioCurso1ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "fisio6",
        nom: "2.3 Resumen de nuestros órganos",
        link: `${basePath}/fisio6`,
        linkAnterior: `${basePath}/fisio5`,
        linkNext: `${basePath}/fisio7`,
        descripcion: "Cada órgano vela por nosotros y su funcionamiento refleja cómo nos tratamos.",
        video: "MDw7ntVuN4w",
        letra: fisio6,
        cursoId: fisioCurso1ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "3. El milagro más complejo",
    icon: MilagroIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "fisio7",
        nom: "3.1 El milagro más complejo de la naturaleza",
        link: `${basePath}/fisio7`,
        linkAnterior: `${basePath}/fisio6`,
        linkNext: "",
        descripcion: "Somos el milagro más asombroso y complejo de la naturaleza.",
        video: "MxEhUFtVowA",
        letra: fisio7,
        cursoId: fisioCurso1ID,
        detalles: detalles,
        icon: MilagroIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
];

export const modulosFisiologiaInflamacion: ModuloContenido[] = [
  {
    title: "1. La Inflamación",
    icon: CelulasOrganosIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "inflam1",
        nom: "1.1 Qué es la inflamación",
        link: `${basePath}/inflam1`,
        linkAnterior: "",
        linkNext: `${basePath}/inflam2`,
        descripcion: "La inflamación es la señal que usa el cuerpo para coordinar su defensa.",
        video: "WS0908UOSWU",
        letra: inflam1,
        cursoId: fisioCurso2ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "inflam2",
        nom: "1.2 La inflamación crónica",
        link: `${basePath}/inflam2`,
        linkAnterior: `${basePath}/inflam1`,
        linkNext: `${basePath}/inflam3`,
        descripcion: "Cuando el sistema inmunitario no se apaga, el cuerpo vive en alerta constante.",
        video: "goeZW-BP90w",
        letra: inflam2,
        cursoId: fisioCurso2ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "2. Las Causas",
    icon: InflamIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "inflam3",
        nom: "2.1 El cortisol y el azúcar",
        link: `${basePath}/inflam3`,
        linkAnterior: `${basePath}/inflam2`,
        linkNext: `${basePath}/inflam4`,
        descripcion: "El cortisol eleva el azúcar en sangre, desencadenando una cadena de estrés metabólico.",
        video: "6CRUMl31iBg",
        letra: inflam3,
        cursoId: fisioCurso2ID,
        detalles: detalles,
        icon: InflamIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "inflam4",
        nom: "2.2 El sueño",
        link: `${basePath}/inflam4`,
        linkAnterior: `${basePath}/inflam3`,
        linkNext: `${basePath}/inflam5`,
        descripcion: "Mientras dormimos el cuerpo se limpia; sin ese descanso, la inflamación aumenta.",
        video: "t_yWGGi94Kw",
        letra: inflam4,
        cursoId: fisioCurso2ID,
        detalles: detalles,
        icon: InflamIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "inflam5",
        nom: "2.3 La microbiota",
        link: `${basePath}/inflam5`,
        linkAnterior: `${basePath}/inflam4`,
        linkNext: `${basePath}/inflam6`,
        descripcion: "Una microbiota dañada puede abrir el intestino a bacterias que activan la inflamación.",
        video: "H9LVchILDtU",
        letra: inflam5,
        cursoId: fisioCurso2ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "3. Los Síntomas y la Solución",
    icon: MilagroIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "inflam6",
        nom: "3.1 Los síntomas",
        link: `${basePath}/inflam6`,
        linkAnterior: `${basePath}/inflam5`,
        linkNext: `${basePath}/inflam7`,
        descripcion: "La hinchazón, el dolor articular y el acné son señales de inflamación crónica.",
        video: "vXO8q8fck3Y",
        letra: inflam6,
        cursoId: fisioCurso2ID,
        detalles: detalles,
        icon: MilagroIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "inflam7",
        nom: "3.2 El cerebro inflamado",
        link: `${basePath}/inflam7`,
        linkAnterior: `${basePath}/inflam6`,
        linkNext: `${basePath}/inflam8`,
        descripcion: "Las citoquinas pueden llegar al cerebro y alterar su equilibrio, causando niebla mental.",
        video: "FzoxTVmRx50",
        letra: inflam7,
        cursoId: fisioCurso2ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "inflam8",
        nom: "3.3 Cómo reducir la inflamación",
        link: `${basePath}/inflam8`,
        linkAnterior: `${basePath}/inflam7`,
        linkNext: "",
        descripcion: "Dieta, ejercicio, sueño y aire libre son tus herramientas antiinflamatorias diarias.",
        video: "_hce0vJ2edY",
        letra: inflam8,
        cursoId: fisioCurso2ID,
        detalles: detalles,
        icon: MilagroIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
];

export const modulosFisiologiaCancer: ModuloContenido[] = [
  {
    title: "1. La célula y su funcionamiento",
    icon: CelulasOrganosIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "cancer1",
        nom: "1.1 La célula y su funcionamiento",
        link: `${basePath}/cancer1`,
        linkAnterior: "",
        linkNext: `${basePath}/cancer2`,
        descripcion: "La célula es un organismo vivo inteligente capaz de regularse, adaptarse y reproducirse siguiendo el manual de instrucciones de su ADN.",
        video: "_gxyponHQ74",
        letra: cancer1,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "cancer2",
        nom: "1.2 Las células no se mueren, se transforman",
        link: `${basePath}/cancer2`,
        linkAnterior: `${basePath}/cancer1`,
        linkNext: `${basePath}/cancer3`,
        descripcion: "Cuando una célula muere, sus átomos son reutilizados por otras. La muerte no existe, existe la transformación.",
        video: "7TtKgLW99X4",
        letra: cancer2,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "2. Mutaciones y cómo nace el cáncer",
    icon: InflamIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "cancer3",
        nom: "2.1 El tabaco y el cáncer",
        link: `${basePath}/cancer3`,
        linkAnterior: `${basePath}/cancer2`,
        linkNext: `${basePath}/cancer4`,
        descripcion: "Las sustancias tóxicas del tabaco alteran el ADN celular, aumentando el riesgo de clonaciones erróneas y cáncer.",
        video: "bhC68UPN6b0",
        letra: cancer3,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: InflamIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "cancer4",
        nom: "2.2 El alcohol y el cáncer",
        link: `${basePath}/cancer4`,
        linkAnterior: `${basePath}/cancer3`,
        linkNext: `${basePath}/cancer5`,
        descripcion: "El alcohol altera el ADN y daña la microbiota, promoviendo crecimientos anormales en el hígado, el colon y la mama.",
        video: "B3ZmAHlHO9o",
        letra: cancer4,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: InflamIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "cancer5",
        nom: "2.3 La luz solar y el cáncer",
        link: `${basePath}/cancer5`,
        linkAnterior: `${basePath}/cancer4`,
        linkNext: `${basePath}/cancer6`,
        descripcion: "Los fotones de la luz solar crean radicales libres que alteran el ADN y promueven la clonación errónea de las células.",
        video: "23bhbcRMzeg",
        letra: cancer5,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: InflamIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "cancer6",
        nom: "2.4 Cómo nace el cáncer",
        link: `${basePath}/cancer6`,
        linkAnterior: `${basePath}/cancer5`,
        linkNext: `${basePath}/cancer7`,
        descripcion: "El cáncer surge cuando las mutaciones genéticas apagan el mecanismo de corrección del ADN, dando paso a divisiones celulares erróneas y tumores.",
        video: "7KmoUw9q2T0",
        letra: cancer6,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: InflamIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "3. La célula cancerígena",
    icon: CelulasOrganosIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "cancer7",
        nom: "3.1 El sistema inmunitario y el cáncer",
        link: `${basePath}/cancer7`,
        linkAnterior: `${basePath}/cancer6`,
        linkNext: `${basePath}/cancer8`,
        descripcion: "El sistema inmunitario es nuestra primera defensa contra el cáncer, pero las células mutadas pueden engañarlo y suprimir su respuesta.",
        video: "6qoYE64zG0w",
        letra: cancer7,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
       {
        id: "cancer8",
        nom: "4.1 Las células cancerígenas usan lo que comes para crecer",
        link: `${basePath}/cancer8`,
        linkAnterior: `${basePath}/cancer7`,
        linkNext: `${basePath}/cancer9`,
        descripcion: "Las células mutadas crean nuevas arterias para desviar los nutrientes y alimentar su crecimiento a base de glucosa.",
        video: "j3zy1_VZCG4",
        letra: cancer8,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
       {
        id: "cancer9",
        nom: "5.1 Las células cancerígenas cambian la respiración celular",
        link: `${basePath}/cancer9`,
        linkAnterior: `${basePath}/cancer8`,
        linkNext: `${basePath}/cancer10`,
        descripcion: "Las células cancerígenas alteran su metabolismo para usar menos oxígeno y más glucosa, creando un ambiente hostil para las células sanas.",
        video: "j9Gaz-3CZ_c",
        letra: cancer9,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: CelulasOrganosIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "4. El estilo de vida",
    icon: FisioComidaIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "cancer10",
        nom: "4.1 Por qué el azúcar incrementa el cáncer",
        link: `${basePath}/cancer10`,
        linkAnterior: `${basePath}/cancer9`,
        linkNext: `${basePath}/cancer11`,
        descripcion: "Las células cancerígenas se alimentan de glucosa: cambiar tu dieta puede privarlas de energía y hacer tu sistema inmunitario más efectivo.",
        video: "_rYnDe-ceIg",
        letra: cancer10,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: FisioComidaIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "cancer11",
        nom: "4.2 Las personas con cáncer tienen que ir al gimnasio",
        link: `${basePath}/cancer11`,
        linkAnterior: `${basePath}/cancer10`,
        linkNext: "",
        descripcion: "El ejercicio físico redirige la glucosa hacia las células sanas, reduciendo el crecimiento de las cancerígenas y potenciando el sistema inmunitario.",
        video: "VNQc4C_PTdc",
        letra: cancer11,
        cursoId: fisioCurso3ID,
        detalles: detalles,
        icon: FisioEjercicioIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
];

export const modulosFisiologiaMeditacion: ModuloContenido[] = [
  {
    title: "1. ¿Qué es la meditación?",
    icon: SistemaNerviosoIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "med1",
        nom: "1.1 ¿Qué es la meditación?",
        link: `${basePath}/med1`,
        linkAnterior: "",
        linkNext: `${basePath}/med2`,
        descripcion: "Descubre qué es la meditación, en qué consiste realmente y por qué 5 minutos al día son suficientes para cambiar tu cerebro.",
        video: "Zy2gURdyTIA",
        letra: med1,
        cursoId: fisioCurso4ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "med2",
        nom: "1.2 Meditar no es relajante",
        link: `${basePath}/med2`,
        linkAnterior: `${basePath}/med1`,
        linkNext: `${basePath}/med3`,
        descripcion: "Meditar es una lucha contra el ruido mental. Entender esto es clave para desarrollar la capacidad de atención cuando más la necesitas.",
        video: "7qQABRK4oYY",
        letra: med2,
        cursoId: fisioCurso4ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "2. Meditación y salud",
    icon: MilagroIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "med3",
        nom: "2.1 Meditar reduce la inflamación crónica",
        link: `${basePath}/med3`,
        linkAnterior: `${basePath}/med2`,
        linkNext: `${basePath}/med4`,
        descripcion: "Cuando meditamos le decimos a nuestras células que estamos a salvo: bajan el cortisol, las citoquinas y la inflamación crónica.",
        video: "Dt7wp9Qf_8s",
        letra: med3,
        cursoId: fisioCurso4ID,
        detalles: detalles,
        icon: MilagroIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "3. Meditación y cerebro",
    icon: SistemaNerviosoIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "med4",
        nom: "3.1 Meditar incrementa la neuroplasticidad",
        link: `${basePath}/med4`,
        linkAnterior: `${basePath}/med3`,
        linkNext: `${basePath}/med5`,
        descripcion: "La neuroplasticidad y el crecimiento del cerebro sigue ocurriendo aunque seas adulto.",
        video: "T49n32EVfRw",
        letra: med4,
        cursoId: fisioCurso4ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "med5",
        nom: "3.2 Meditar te hace más productivo",
        link: `${basePath}/med5`,
        linkAnterior: `${basePath}/med4`,
        linkNext: `${basePath}/med6`,
        descripcion: "La corteza prefrontal crece con la meditación, mejorando tu capacidad de razonar, planificar y controlar impulsos.",
        video: "RoKGDGTb7ls",
        letra: med5,
        cursoId: fisioCurso4ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "med6",
        nom: "3.3 La meditación reduce el enfado",
        link: `${basePath}/med6`,
        linkAnterior: `${basePath}/med5`,
        linkNext: `${basePath}/med7`,
        descripcion: "La meditación reduce la reactividad de la amígdala, aumenta tu tolerancia al estrés y mejora tu resiliencia emocional.",
        video: "9Tn4QXafx_E",
        letra: med6,
        cursoId: fisioCurso4ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "med7",
        nom: "3.4 Meditar mejora tu memoria",
        link: `${basePath}/med7`,
        linkAnterior: `${basePath}/med6`,
        linkNext: "",
        descripcion: "El hipocampo crece con la meditación, mejorando la memoria a largo plazo. Harvard lo demostró en tan solo 2 meses de práctica diaria.",
        video: "2lbqmGfRu24",
        letra: med7,
        cursoId: fisioCurso4ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
];

export const modulosFisiologiaEjercicio: ModuloContenido[] = [
  {
    title: "1. El equilibrio",
    icon: EquilibrioIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "ejer1",
        nom: "1.1 El equilibrio",
        link: `${basePath}/ejer1`,
        linkAnterior: "",
        linkNext: `${basePath}/ejer3`,
        descripcion: "Practicar equilibrio hace más grande tu cerebro, mejora tu propiocepción y afina tus reflejos y concentración.",
        video: "bU-1t1Sk-5U",
        letra: ejer1,
        cursoId: fisioCurso5ID,
        detalles: detalles,
        icon: EquilibrioIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "2. La fuerza",
    icon: FisioEjercicioIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "ejer3",
        nom: "2.1 El músculo",
        link: `${basePath}/ejer3`,
        linkAnterior: `${basePath}/ejer1`,
        linkNext: `${basePath}/ejer4`,
        descripcion: "El músculo es nuestro seguro de vida: al retarlo con peso, fortaleces huesos, cartílagos y músculos a la vez.",
        video: "kx2B3lItOGE",
        letra: ejer3,
        cursoId: fisioCurso5ID,
        detalles: detalles,
        icon: FisioEjercicioIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "ejer4",
        nom: "2.2 El músculo cambia tu metabolismo",
        link: `${basePath}/ejer4`,
        linkAnterior: `${basePath}/ejer3`,
        linkNext: `${basePath}/ejer5`,
        descripcion: "Tener músculo regula la glucosa en tu cuerpo, previniendo derrames cerebrales, paros cardiacos y diabetes.",
        video: "wvWwuJ7M1DM",
        letra: ejer4,
        cursoId: fisioCurso5ID,
        detalles: detalles,
        icon: FisioEjercicioIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "ejer5",
        nom: "2.3 El músculo crea conexiones neuronales",
        link: `${basePath}/ejer5`,
        linkAnterior: `${basePath}/ejer4`,
        linkNext: `${basePath}/ejer6`,
        descripcion: "Entrenar libera enzimas que crean conexiones neuronales y neurotransmisores como la serotonina, la dopamina y las endorfinas.",
        video: "pvGF_E-Teic",
        letra: ejer5,
        cursoId: fisioCurso5ID,
        detalles: detalles,
        icon: SistemaNerviosoIcon,
        floatingButton: conocerMiCuerpo,
      },
      {
        id: "ejer6",
        nom: "2.4 No entrenar",
        link: `${basePath}/ejer6`,
        linkAnterior: `${basePath}/ejer5`,
        linkNext: `${basePath}/ejer7`,
        descripcion: "Cuando no entrenas, la miostatina le dice a tus músculos que desaparezcan porque no hacen falta.",
        video: "UmWrXik1igs",
        letra: ejer6,
        cursoId: fisioCurso5ID,
        detalles: detalles,
        icon: FisioEjercicioIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
  {
    title: "3. El cardio",
    icon: CardioIcon,
    floatingButton: conocerMiCuerpo,
    submodules: [
      {
        id: "ejer7",
        nom: "3.1 El cardio",
        link: `${basePath}/ejer7`,
        linkAnterior: `${basePath}/ejer6`,
        linkNext: "",
        descripcion: "El cardio oxigena órganos y cerebro, crea más conexiones neuronales que la fuerza y sus efectos se comparan con los antidepresivos.",
        video: "SwSAfh8O8GU",
        letra: ejer7,
        cursoId: fisioCurso5ID,
        detalles: detalles,
        icon: CardioIcon,
        floatingButton: conocerMiCuerpo,
      },
    ],
  },
];
