export const letraFis1 = "El Big Bang dio lugar a las primeras partículas. Con el tiempo, estas se combinaron y formaron átomos simples, como el hidrógeno y el helio. La gravedad reunió esa materia dando origen a las primeras estrellas. Dentro de las estrellas, a través de la fusión nuclear, se formaron átomos más complejos. Al morir, las estrellas liberaron esos átomos al espacio. Esa materia volvió a unirse para formar planetas, naturaleza… y, por extensión, a nosotros. Estamos formados, literalmente, de polvo de estrellas.";

export const letraFis2 = "El taoísmo tiene relación con ideas de la física moderna. El taoísmo habla de que el vacío no está realmente vacío, sino en continua actividad. En física, sabemos que el vacío tiene fluctuaciones de energía constantes, porque la energía puede transformarse en partículas, y las partículas en energía. Cuando una partícula se encuentra con su antipartícula, pueden aniquilarse y volver a ser energía. Y esa energía, en las condiciones adecuadas, puede convertirse en materia. Como sugiere el taoísmo, el vacío no es ausencia… es potencial. Nada está completamente quieto, nada es totalmente estable.";

export const letraFis3 = "Todo lo que existe es la transformación de materia que ya existía. Como sabemos gracias a Einstein, la energía se transforma en materia y la materia en energía. Nuestro universo es literalmente un milagro, y nuestro cuerpo es un préstamo privilegiado. Porque de la energía se crean las partículas, de las partículas los átomos, y de los átomos, nosotros.";

export const letraFis4 = "Sabemos que los átomos que nos forman no son estables. Aún así, cada segundo de nuestra vida ocurren reacciones metabólicas que tienen como fundamento esos átomos, los cuales nos permiten disfrutar de miles de posibilidades. Si salimos de nuestra mente y de nuestras costumbres, tenemos tantas oportunidades que es hasta abrumador. Este es el porqué empezamos a devaluar la vida: nos quedamos en los patrones que nos permiten sobrevivir y creer que tenemos el control, y desde ahí perdemos de vista lo afortunados que somos de tener un cuerpo solo para nosotros.";

export const letraFis5 = "";
